dbus-keyring.h
typedef struct DBusKeyring DBusKeyring
DBusKeyring* _dbus_keyring_new_for_credentials(DBusCredentials *credentials, const DBusString *context, DBusError *error)
Creates a new keyring that lives in the ~/.dbus-keyrings directory of the user represented by credentials.
If the credentials are NULL or empty, uses those of the current process. credentials a set of credentials representing a user or NULL context which keyring to get error return location for errors the keyring or NULL on error
References _dbus_check_setuid, dbus_set_error_const, DBUS_ERROR_NOT_SUPPORTED, NULL, FALSE, _dbus_string_init, dbus_set_error, DBUS_ERROR_NO_MEMORY, _dbus_credentials_copy, _dbus_credentials_new_from_current_process, _dbus_credentials_are_anonymous, _dbus_credentials_add_from_current_process, _dbus_append_keyring_directory_for_credentials, _dbus_assert, DBusKeyring::credentials, _dbus_keyring_validate_context, TRUE, DBUS_ERROR_FAILED, _dbus_string_copy, DBusKeyring::directory, DBusKeyring::filename, _dbus_concat_dir_and_file, DBusKeyring::filename_lock, _dbus_string_append, dbus_error_init, DBusError::message, dbus_error_free, _dbus_create_directory, _dbus_string_free, _dbus_credentials_unref, _dbus_keyring_unref.
Referenced by _dbus_keyring_get_hex_key.
DBusKeyring* _dbus_keyring_ref(DBusKeyring *keyring)
Increments reference count of the keyring.
keyring the keyring the keyring
References DBusKeyring::refcount.
Referenced by _dbus_keyring_get_hex_key.
void _dbus_keyring_unref(DBusKeyring *keyring)
Decrements refcount and finalizes if it reaches zero.
keyring the keyring
References DBusKeyring::refcount, DBusKeyring::credentials, _dbus_credentials_unref, _dbus_string_free, DBusKeyring::filename, DBusKeyring::filename_lock, DBusKeyring::directory, DBusKeyring::keys, DBusKeyring::n_keys, dbus_free.
Referenced by _dbus_auth_unref, _dbus_keyring_new_for_credentials, _dbus_keyring_get_hex_key.
dbus_bool_t _dbus_keyring_validate_context(const DBusString *context)
Checks whether the context is a valid context.
Contexts that might cause confusion when used in filenames are not allowed (contexts can't start with a dot or contain dir separators).Todothis is the most inefficient implementation imaginable. context the context TRUE if valid
References FALSE, _dbus_string_validate_ascii, _dbus_string_find, NULL, _dbus_string_find_blank, TRUE, _dbus_get_real_time, DBusKeyring::n_keys, DBusKeyring::keys, DBusKey::creation_time, NEW_KEY_TIMEOUT_SECONDS.
Referenced by _dbus_keyring_new_for_credentials, _dbus_keyring_get_hex_key.
int _dbus_keyring_get_best_key(DBusKeyring *keyring, DBusError *error)
Gets a recent key to use for authentication.
If no recent key exists, creates one. Returns the key ID. If a key can't be written to the keyring file so no recent key can be created, returns -1. All valid keys are > 0. keyring the keyring error error on failure key ID to use for auth, or -1 on failure
References DBusKey::id, TRUE, dbus_set_error_const, DBUS_ERROR_FAILED.
Referenced by _dbus_keyring_get_hex_key.
dbus_bool_t _dbus_keyring_is_for_credentials(DBusKeyring *keyring, DBusCredentials *credentials)
Checks whether the keyring is for the same user as the given credentials.
keyring the keyring credentials the credentials to check TRUE if the keyring belongs to the given user
References _dbus_credentials_same_user, DBusKeyring::credentials.
dbus_bool_t _dbus_keyring_get_hex_key(DBusKeyring *keyring, int key_id, DBusString *hex_key)
Gets the hex-encoded secret key for the given ID.
Returns FALSE if not enough memory. Returns TRUE but empty key on any other error such as unknown key ID. keyring the keyring key_id the key ID hex_key string to append hex-encoded key to TRUE if we had enough memory
References DBusKeyring::keys, DBusKeyring::n_keys, NULL, TRUE, _dbus_string_hex_encode, DBusKey::secret, _dbus_string_init_const, _dbus_assert, _dbus_keyring_validate_context, _dbus_string_init, _dbus_assert_not_reached, _dbus_string_append_byte, _dbus_string_free, dbus_error_init, _dbus_keyring_new_for_credentials, DBusError::name, _dbus_keyring_get_best_key, DBusError::message, dbus_error_free, DBusKey::id, DBusKey::creation_time, _dbus_string_equal, _dbus_keyring_ref, _dbus_keyring_unref, FALSE.