dbus-threads.h
DBusThreadFunctionsMask
typedef struct DBusMutex DBusMutex
An opaque mutex type provided by the DBusThreadFunctions implementation installed by dbus_threads_init().
typedef struct DBusCondVar DBusCondVar
An opaque condition variable type provided by the DBusThreadFunctions implementation installed by dbus_threads_init().
typedef DBusMutex*(* DBusMutexNewFunction) (void))(void)
Deprecated, provide DBusRecursiveMutexNewFunction instead.
typedef void(* DBusMutexFreeFunction) (DBusMutex *mutex))(DBusMutex *mutex)
Deprecated, provide DBusRecursiveMutexFreeFunction instead.
typedef dbus_bool_t(* DBusMutexLockFunction) (DBusMutex *mutex))(DBusMutex *mutex)
Deprecated, provide DBusRecursiveMutexLockFunction instead.
Return value is lock success, but gets ignored in practice.
typedef dbus_bool_t(* DBusMutexUnlockFunction) (DBusMutex *mutex))(DBusMutex *mutex)
Deprecated, provide DBusRecursiveMutexUnlockFunction instead.
Return value is unlock success, but gets ignored in practice.
typedef DBusMutex*(* DBusRecursiveMutexNewFunction) (void))(void)
Creates a new recursively-lockable mutex, or returns NULL if not enough memory.
Can only fail due to lack of memory. Found in DBusThreadFunctions. Do not just use PTHREAD_MUTEX_RECURSIVE for this, because it does not save/restore the recursion count when waiting on a condition. libdbus requires the Java-style behavior where the mutex is fully unlocked to wait on a condition.
typedef void(* DBusRecursiveMutexFreeFunction) (DBusMutex *mutex))(DBusMutex *mutex)
Frees a recursively-lockable mutex.
Found in DBusThreadFunctions.
typedef void(* DBusRecursiveMutexLockFunction) (DBusMutex *mutex))(DBusMutex *mutex)
Locks a recursively-lockable mutex.
Found in DBusThreadFunctions. Can only fail due to lack of memory.
typedef void(* DBusRecursiveMutexUnlockFunction) (DBusMutex *mutex))(DBusMutex *mutex)
Unlocks a recursively-lockable mutex.
Found in DBusThreadFunctions. Can only fail due to lack of memory.
typedef DBusCondVar*(* DBusCondVarNewFunction) (void))(void)
Creates a new condition variable.
Found in DBusThreadFunctions. Can only fail (returning NULL) due to lack of memory.
typedef void(* DBusCondVarFreeFunction) (DBusCondVar *cond))(DBusCondVar *cond)
Frees a condition variable.
Found in DBusThreadFunctions.
typedef void(* DBusCondVarWaitFunction) (DBusCondVar *cond, DBusMutex *mutex))(DBusCondVar *cond, DBusMutex *mutex)
Waits on a condition variable.
Found in DBusThreadFunctions. Must work with either a recursive or nonrecursive mutex, whichever the thread implementation provides. Note that PTHREAD_MUTEX_RECURSIVE does not work with condition variables (does not save/restore the recursion count) so don't try using simply pthread_cond_wait() and a PTHREAD_MUTEX_RECURSIVE to implement this, it won't work right.Has no error conditions. Must succeed if it returns.
typedef dbus_bool_t(* DBusCondVarWaitTimeoutFunction) (DBusCondVar *cond, DBusMutex *mutex, int timeout_milliseconds))(DBusCondVar *cond, DBusMutex *mutex, int timeout_milliseconds)
Waits on a condition variable with a timeout.
Found in DBusThreadFunctions. Returns TRUE if the wait did not time out, and FALSE if it did.Has no error conditions. Must succeed if it returns.
typedef void(* DBusCondVarWakeOneFunction) (DBusCondVar *cond))(DBusCondVar *cond)
Wakes one waiting thread on a condition variable.
Found in DBusThreadFunctions.Has no error conditions. Must succeed if it returns.
typedef void(* DBusCondVarWakeAllFunction) (DBusCondVar *cond))(DBusCondVar *cond)
Wakes all waiting threads on a condition variable.
Found in DBusThreadFunctions.Has no error conditions. Must succeed if it returns.
DBUS_EXPORT dbus_bool_t dbus_threads_init(const DBusThreadFunctions *functions)
Initializes threads, like dbus_threads_init_default().
This version previously allowed user-specified threading primitives, but since D-Bus 1.6 it ignores them and behaves exactly like dbus_threads_init_default(). functions ignored, formerly functions for using threads TRUE on success, FALSE if no memory
References _dbus_current_generation, _dbus_threads_init_platform_specific, _dbus_threads_lock_platform_specific, _dbus_threads_unlock_platform_specific, FALSE, TRUE.
Referenced by dbus_threads_init_default.
DBUS_EXPORT dbus_bool_t dbus_threads_init_default(void)
Initializes threads.
If this function is not called, the D-Bus library will not lock any data structures. If it is called, D-Bus will do locking, at some cost in efficiency.Since D-Bus 1.7 it is safe to call this function from any thread, any number of times (but it must be called before any other libdbus API is used).In D-Bus 1.6 or older, this function must be called in the main thread before any other thread starts. As a result, it is not sufficient to call this function in a library or plugin, unless the library or plugin imposes a similar requirement on its callers.dbus_shutdown() reverses the effects of this function when it resets all global state in libdbus.TRUE on success, FALSE if not enough memory
References dbus_threads_init, NULL.
Referenced by _dbus_cmutex_new_at_location, _dbus_condvar_new, _dbus_condvar_wake_one, _dbus_rmutex_new_at_location.