dbus-connection-internal.h
_DBUS_DEFAULT_TIMEOUT_VALUE
default timeout value when waiting for a message reply, 25 seconds
DBusIterationFlags
Write messages out.
typedef void(* DBusPendingFdsChangeFunction) (void *data))(void *data)
void _dbus_connection_lock(DBusConnection *connection)
Acquires the connection lock.
connection the connection.
References CONNECTION_LOCK.
Referenced by _dbus_object_tree_dispatch_and_unlock, _dbus_transport_get_is_connected.
void _dbus_connection_unlock(DBusConnection *connection)
Releases the connection lock.
connection the connection.
References DBusConnection::expired_messages, NULL, _dbus_rmutex_unlock, DBusConnection::mutex, _dbus_list_pop_first_link, DBusList::data, dbus_message_unref, _dbus_list_free_link, DBusConnection::wakeup_main_function, DBusConnection::wakeup_main_data, DBusConnection::dispatch_mutex, DBusConnection::io_path_mutex, DBusConnection::dispatch_cond, DBusConnection::io_path_cond.
Referenced by _dbus_object_tree_unregister_and_unlock, _dbus_object_tree_free_all_unlocked, _dbus_object_tree_dispatch_and_unlock, _dbus_object_tree_list_registered_and_unlock, _dbus_transport_get_is_connected.
DBusConnection* _dbus_connection_ref_unlocked(DBusConnection *connection)
Increments the reference count of a DBusConnection.
Requires that the caller already holds the connection lock. connection the connection. the connection.
References _dbus_assert, NULL, _dbus_current_generation, _dbus_atomic_inc, DBusConnection::refcount.
Referenced by _dbus_connection_toggle_timeout_unlocked, _dbus_connection_remove_pending_call, _dbus_connection_handle_watch, dbus_connection_unref, dbus_connection_send, dbus_connection_pop_message, dbus_connection_dispatch, _dbus_object_tree_unregister_and_unlock, _dbus_pending_call_new_unlocked, _dbus_transport_try_to_authenticate.
void _dbus_connection_unref_unlocked(DBusConnection *connection)
Decrements the reference count of a DBusConnection.
Requires that the caller already holds the connection lock. connection the connection.
References _dbus_assert, NULL, _dbus_atomic_dec, DBusConnection::refcount, DBusConnection::client_serial.
Referenced by _dbus_connection_toggle_timeout_unlocked, _dbus_connection_remove_pending_call, _dbus_connection_handle_watch, dbus_connection_pop_message, _dbus_transport_try_to_authenticate.
void _dbus_connection_queue_received_message_link(DBusConnection *connection, DBusList *link)
Adds a message-containing list link to the incoming message queue, taking ownership of the link and the message's current refcount.
Cannot fail due to lack of memory. connection the connection. link the message link to queue.
References _dbus_assert, _dbus_transport_peek_is_authenticated, DBusConnection::transport, _dbus_list_append_link, DBusConnection::incoming_messages, DBusList::data, dbus_message_get_reply_serial, _dbus_hash_table_lookup_int, DBusConnection::pending_replies, NULL, _dbus_pending_call_is_timeout_added_unlocked, _dbus_connection_remove_timeout_unlocked, _dbus_pending_call_get_timeout_unlocked, _dbus_pending_call_set_timeout_added_unlocked, FALSE, DBusConnection::n_incoming, dbus_message_type_to_string, dbus_message_get_type, dbus_message_get_path, dbus_message_get_interface, dbus_message_get_member, dbus_message_get_signature.
Referenced by _dbus_transport_queue_messages.
dbus_bool_t _dbus_connection_has_messages_to_send_unlocked(DBusConnection *connection)
Checks whether there are messages in the outgoing message queue.
Called with connection lock held. connection the connection. TRUE if the outgoing queue is non-empty.
References DBusConnection::outgoing_messages, NULL.
Referenced by dbus_connection_has_messages_to_send.
DBusMessage* _dbus_connection_get_message_to_send(DBusConnection *connection)
Gets the next outgoing message.
The message remains in the queue, and the caller does not own a reference to it. connection the connection. the message to be sent.
References _dbus_list_get_last, DBusConnection::outgoing_messages.
void _dbus_connection_message_sent_unlocked(DBusConnection *connection, DBusMessage *message)
Notifies the connection that a message has been sent, so the message can be removed from the outgoing queue.
Called with the connection lock held. connection the connection. message the message that was sent.
References _dbus_list_get_last_link, DBusConnection::outgoing_messages, _dbus_assert, NULL, DBusList::data, _dbus_list_unlink, _dbus_list_prepend_link, DBusConnection::expired_messages, DBusConnection::n_outgoing, dbus_message_type_to_string, dbus_message_get_type, dbus_message_get_path, dbus_message_get_interface, dbus_message_get_member, dbus_message_get_signature, _dbus_message_remove_counter, DBusConnection::outgoing_counter.
Referenced by dbus_connection_pop_message.
dbus_bool_t _dbus_connection_add_watch_unlocked(DBusConnection *connection, DBusWatch *watch)
Adds a watch using the connection's DBusAddWatchFunction if available.
Otherwise records the watch to be added when said function is available. Also re-adds the watch if the DBusAddWatchFunction changes. May fail due to lack of memory. Connection lock should be held when calling this. connection the connection. watch the watch to add. TRUE on success.
References _dbus_watch_list_add_watch, NULL, FALSE.
void _dbus_connection_remove_watch_unlocked(DBusConnection *connection, DBusWatch *watch)
Removes a watch using the connection's DBusRemoveWatchFunction if available.
It's an error to call this function on a watch that was not previously added. Connection lock should be held when calling this. connection the connection. watch the watch to remove.
References NULL, _dbus_watch_list_remove_watch, FALSE.
void _dbus_connection_toggle_watch_unlocked(DBusConnection *connection, DBusWatch *watch, dbus_bool_t enabled)
Toggles a watch and notifies app via connection's DBusWatchToggledFunction if available.
It's an error to call this function on a watch that was not previously added. Connection lock should be held when calling this. connection the connection. watch the watch to toggle. enabled whether to enable or disable
References _dbus_assert, NULL, _dbus_watch_list_toggle_watch.
dbus_bool_t _dbus_connection_handle_watch(DBusWatch *watch, unsigned int condition, void *data)
A callback for use with dbus_watch_new() to create a DBusWatch.
TodoThis is basically a hack - we could delete _dbus_transport_handle_watch() and the virtual handle_watch in DBusTransport if we got rid of it. The reason this is some work is threading, see the _dbus_connection_handle_watch() implementation. watch the watch. condition the current condition of the file descriptors being watched. data must be a pointer to a DBusConnection FALSE if the IO condition may not have been fully handled due to lack of memory
References CONNECTION_LOCK, CONNECTION_UNLOCK, TRUE, _dbus_transport_handle_watch, DBusConnection::transport, NULL, dbus_connection_ref, _dbus_connection_close_possibly_shared, dbus_connection_pop_message, dbus_message_unref, dbus_connection_unref, _DBUS_LOCK, _dbus_hash_table_get_n_entries, _dbus_hash_iter_init, _dbus_hash_iter_next, _dbus_hash_iter_get_value, _DBUS_UNLOCK, _dbus_assert_not_reached, _dbus_assert, _dbus_hash_table_unref, _dbus_list_pop_first, FALSE, _dbus_hash_table_new, DBUS_HASH_STRING, dbus_free, _dbus_register_shutdown_func, dbus_address_entry_get_value, _dbus_hash_table_lookup_string, _dbus_connection_ref_unlocked, DBusConnection::server_guid, DBusConnection::shareable, _dbus_list_prepend, _dbus_strdup, _dbus_hash_table_insert_string, _dbus_hash_table_remove_string, _dbus_list_remove, _dbus_connection_unref_unlocked, _dbus_transport_open, _dbus_connection_new_for_transport, _dbus_transport_unref, DBusConnection::have_connection_lock, DBUS_ERROR_INIT, dbus_parse_address, dbus_move_error, dbus_error_free, dbus_address_entries_free.
dbus_bool_t _dbus_connection_add_timeout_unlocked(DBusConnection *connection, DBusTimeout *timeout)
Adds a timeout using the connection's DBusAddTimeoutFunction if available.
Otherwise records the timeout to be added when said function is available. Also re-adds the timeout if the DBusAddTimeoutFunction changes. May fail due to lack of memory. The timeout will fire repeatedly until removed. Connection lock should be held when calling this. connection the connection. timeout the timeout to add. TRUE on success.
References _dbus_timeout_list_add_timeout, NULL, FALSE.
Referenced by _dbus_connection_toggle_timeout_unlocked.
void _dbus_connection_remove_timeout_unlocked(DBusConnection *connection, DBusTimeout *timeout)
Removes a timeout using the connection's DBusRemoveTimeoutFunction if available.
It's an error to call this function on a timeout that was not previously added. Connection lock should be held when calling this. connection the connection. timeout the timeout to remove.
References NULL, _dbus_timeout_list_remove_timeout, FALSE.
Referenced by _dbus_connection_queue_received_message_link, _dbus_connection_toggle_timeout_unlocked, _dbus_connection_close_if_only_one_ref, dbus_connection_send.
void _dbus_connection_toggle_timeout_unlocked(DBusConnection *connection, DBusTimeout *timeout, dbus_bool_t enabled)
Toggles a timeout and notifies app via connection's DBusTimeoutToggledFunction if available.
It's an error to call this function on a timeout that was not previously added. Connection lock should be held when calling this. connection the connection. timeout the timeout to toggle. enabled whether to enable or disable
References NULL, _dbus_timeout_list_toggle_timeout, _dbus_pending_call_get_reply_serial_unlocked, _dbus_assert, _dbus_pending_call_get_timeout_unlocked, _dbus_connection_add_timeout_unlocked, FALSE, _dbus_hash_table_insert_int, DBusConnection::pending_replies, _dbus_connection_remove_timeout_unlocked, _dbus_pending_call_set_timeout_added_unlocked, TRUE, _dbus_pending_call_ref_unlocked, _dbus_pending_call_get_connection_unlocked, _dbus_pending_call_is_timeout_added_unlocked, _dbus_connection_ref_unlocked, _dbus_pending_call_unref_and_unlock, CONNECTION_LOCK, _dbus_connection_unref_unlocked, _dbus_hash_table_remove_int.
DBusConnection* _dbus_connection_new_for_transport(DBusTransport *transport)
Creates a new connection for the given transport.
A transport represents a message stream that uses some concrete mechanism, such as UNIX domain sockets. May return NULL if insufficient memory exists to create the connection. transport the transport. the new connection, or NULL on failure.
References NULL, _dbus_watch_list_new, _dbus_timeout_list_new, _dbus_hash_table_new, DBUS_HASH_INT, dbus_new0, _dbus_rmutex_new_at_location, DBusConnection::mutex, _dbus_cmutex_new_at_location, DBusConnection::io_path_mutex, DBusConnection::dispatch_mutex, _dbus_condvar_new_at_location, DBusConnection::dispatch_cond, DBusConnection::io_path_cond, DBusConnection::slot_mutex, dbus_message_new_signal, DBUS_PATH_LOCAL, DBUS_INTERFACE_LOCAL, _dbus_list_alloc_link, _dbus_counter_new, _dbus_object_tree_new, _dbus_disable_sigpipe, _dbus_atomic_inc, DBusConnection::refcount, DBusConnection::transport, DBusConnection::watches, DBusConnection::timeouts, DBusConnection::pending_replies, DBusConnection::outgoing_counter, DBusConnection::filter_list, DBusConnection::last_dispatch_status, DBUS_DISPATCH_COMPLETE, DBusConnection::objects, DBusConnection::exit_on_disconnect, FALSE, DBusConnection::shareable, DBusConnection::route_peer_messages, DBusConnection::disconnected_message_arrived, DBusConnection::disconnected_message_processed, _dbus_current_generation, _dbus_data_slot_list_init, DBusConnection::slot_list, DBusConnection::client_serial, DBusConnection::disconnect_message_link, CONNECTION_LOCK, _dbus_transport_set_connection, CONNECTION_UNLOCK, _dbus_transport_ref, dbus_message_unref, _dbus_list_free_link, _dbus_condvar_free_at_location, _dbus_rmutex_free_at_location, _dbus_cmutex_free_at_location, dbus_free, _dbus_hash_table_unref, _dbus_watch_list_free, _dbus_timeout_list_free, _dbus_counter_unref, _dbus_object_tree_unref.
Referenced by _dbus_connection_handle_watch.
void _dbus_connection_do_iteration_unlocked(DBusConnection *connection, DBusPendingCall *pending, unsigned int flags, int timeout_milliseconds)
Queues incoming messages and sends outgoing messages for this connection, optionally blocking in the process.
Each call to _dbus_connection_do_iteration_unlocked() will call select() or poll() one time and then read or write data if possible.The purpose of this function is to be able to flush outgoing messages or queue up incoming messages without returning control to the application and causing reentrancy weirdness.The flags parameter allows you to specify whether to read incoming messages, write outgoing messages, or both, and whether to block if no immediate action is possible.The timeout_milliseconds parameter does nothing unless the iteration is blocking.If there are no outgoing messages and DBUS_ITERATION_DO_READING wasn't specified, then it's impossible to block, even if you specify DBUS_ITERATION_BLOCK; in that case the function returns immediately.If pending is not NULL then a check is made if the pending call is completed after the io path has been required. If the call has been completed nothing is done. This must be done since the _dbus_connection_acquire_io_path releases the connection lock for a while.Called with connection lock held. connection the connection. pending the pending call that should be checked or NULL flags iteration flags. timeout_milliseconds maximum blocking time, or -1 for no limit.
References DBusConnection::n_outgoing, NULL, _dbus_pending_call_get_completed_unlocked, _dbus_pending_call_get_reply_serial_unlocked, _dbus_transport_do_iteration, DBusConnection::transport.
Referenced by _dbus_connection_close_possibly_shared, _dbus_connection_block_pending_call, dbus_connection_send_with_reply_and_block, dbus_connection_flush.
void _dbus_connection_close_possibly_shared(DBusConnection *connection)
Closes a shared OR private connection, while dbus_connection_close() can only be used on private connections.
Should only be called by the dbus code that owns the connection - an owner must be known, the open/close state is like malloc/free, not like ref/unref. connection the connection
References _dbus_assert, NULL, _dbus_current_generation, CONNECTION_LOCK, dbus_new, DBusPreallocatedSend::queue_link, _dbus_list_alloc_link, DBusPreallocatedSend::counter_link, DBusConnection::outgoing_counter, _dbus_counter_ref, DBusList::data, DBusPreallocatedSend::connection, _dbus_list_free_link, dbus_free, _dbus_list_prepend_link, DBusConnection::outgoing_messages, _dbus_message_add_counter_link, dbus_message_ref, DBusConnection::n_outgoing, dbus_message_type_to_string, dbus_message_get_type, dbus_message_get_path, dbus_message_get_interface, dbus_message_get_member, dbus_message_get_signature, dbus_message_get_destination, dbus_message_get_serial, dbus_message_set_serial, dbus_message_lock, _dbus_connection_do_iteration_unlocked.
Referenced by _dbus_bus_notify_shared_connection_disconnected_unlocked, _dbus_connection_handle_watch.
void _dbus_connection_close_if_only_one_ref(DBusConnection *connection)
Used internally to handle the semantics of dbus_server_set_new_connection_function().
If the new connection function does not ref the connection, we want to close it.A bit of a hack, probably the new connection function should have returned a value for whether to close, or should have had to close the connection itself if it didn't want it.But, this works OK as long as the new connection function doesn't do anything crazy like keep the connection around without ref'ing it.We have to lock the connection across refcount check and close in case the new connection function spawns a thread that closes and unrefs. In that case, if the app thread closes and unrefs first, we'll harmlessly close again; if the app thread still has the ref, we'll close and then the app will close harmlessly. If the app unrefs without closing, the app is broken since if the app refs from the new connection function it is supposed to also close.If we didn't atomically check the refcount and close with the lock held though, we could screw this up. connection the connection
References DBusMessageFilter::refcount, CONNECTION_LOCK, _dbus_atomic_get, DBusConnection::refcount, _dbus_assert, CONNECTION_UNLOCK, _dbus_sleep_milliseconds, dbus_message_new, DBUS_MESSAGE_TYPE_ERROR, dbus_message_set_error_name, dbus_message_unref, NULL, dbus_message_set_no_reply, TRUE, dbus_message_set_reply_serial, dbus_message_iter_init_append, dbus_message_iter_append_basic, DBUS_TYPE_STRING, _dbus_list_get_first_link, DBusConnection::incoming_messages, DBusList::data, dbus_message_get_reply_serial, _dbus_list_get_next_link, FALSE, _dbus_list_remove_link, DBusConnection::n_incoming, _dbus_hash_table_get_n_entries, DBusConnection::pending_replies, _dbus_hash_iter_init, _dbus_hash_iter_next, _dbus_hash_iter_get_value, _dbus_pending_call_ref_unlocked, _dbus_pending_call_queue_timeout_error_unlocked, _dbus_pending_call_is_timeout_added_unlocked, _dbus_connection_remove_timeout_unlocked, _dbus_pending_call_get_timeout_unlocked, _dbus_pending_call_set_timeout_added_unlocked, _dbus_hash_iter_remove_entry, _dbus_pending_call_unref_and_unlock, _dbus_pending_call_set_reply_unlocked, _dbus_pending_call_complete, dbus_pending_call_unref, _dbus_pending_call_get_reply_serial_unlocked.
DBusPendingCall* _dbus_pending_call_new(DBusConnection *connection, int timeout_milliseconds, DBusTimeoutHandler timeout_handler)
void _dbus_pending_call_notify(DBusPendingCall *pending)
void _dbus_connection_remove_pending_call(DBusConnection *connection, DBusPendingCall *pending)
Removes a pending call from the connection, such that the pending reply will be ignored.
May drop the last reference to the pending call. connection the connection pending the pending call
References CONNECTION_LOCK, _dbus_connection_ref_unlocked, CONNECTION_UNLOCK, _dbus_cmutex_lock, DBusConnection::io_path_mutex, DBusConnection::io_path_acquired, FALSE, _dbus_condvar_wait_timeout, DBusConnection::io_path_cond, _dbus_condvar_wait, TRUE, _dbus_cmutex_unlock, _dbus_connection_unref_unlocked, _dbus_assert, _dbus_condvar_wake_one.
Referenced by dbus_pending_call_cancel.
void _dbus_connection_block_pending_call(DBusPendingCall *pending)
Blocks until a pending call times out or gets a reply.
Does not re-enter the main loop or run filter/path-registered callbacks. The reply to the message will not be seen by filter callbacks.Returns immediately if pending call already got a reply.Todocould use performance improvements (it keeps scanning the whole message queue for example) pending the pending call we block for a reply on
References _dbus_assert, NULL, dbus_pending_call_get_completed, dbus_pending_call_ref, _dbus_pending_call_get_connection_and_lock, _dbus_pending_call_get_reply_serial_unlocked, _dbus_pending_call_get_timeout_unlocked, _dbus_get_monotonic_time, dbus_timeout_get_interval, _dbus_connection_do_iteration_unlocked, _dbus_pending_call_get_completed_unlocked, dbus_pending_call_unref, DBUS_DISPATCH_DATA_REMAINS, DBUS_ERROR_DISCONNECTED, DBusConnection::disconnect_message_link, DBUS_DISPATCH_NEED_MEMORY, CONNECTION_LOCK.
Referenced by dbus_pending_call_block.
void _dbus_pending_call_complete_and_unlock(DBusPendingCall *pending, DBusMessage *message)
dbus_bool_t _dbus_connection_send_and_unlock(DBusConnection *connection, DBusMessage *message, dbus_uint32_t *client_serial)
Like dbus_connection_send(), but assumes the connection is already locked on function entry, and unlocks before returning.
connection the connection message the message to send client_serial return location for client serial of sent message FALSE on out-of-memory
References _dbus_assert, NULL, CONNECTION_UNLOCK, FALSE, TRUE.
Referenced by dbus_connection_send, _dbus_object_tree_free_all_unlocked.
void _dbus_connection_queue_synthesized_message_link(DBusConnection *connection, DBusList *link)
Adds a link + message to the incoming message queue.
Can't fail. Takes ownership of both link and message. connection the connection. link the list node and message to queue.
References _dbus_list_append_link, DBusConnection::incoming_messages, DBusConnection::n_incoming, DBusList::data.
Referenced by dbus_connection_pop_message, _dbus_pending_call_queue_timeout_error_unlocked.
void _dbus_connection_test_get_locks(DBusConnection *conn, DBusMutex **mutex_loc, DBusMutex **dispatch_mutex_loc, DBusMutex **io_path_mutex_loc, DBusCondVar **dispatch_cond_loc, DBusCondVar **io_path_cond_loc)
int _dbus_connection_get_pending_fds_count(DBusConnection *connection)
Return how many file descriptors are pending in the loader.
connection the connection
References _dbus_transport_get_pending_fds_count, DBusConnection::transport.
void _dbus_connection_set_pending_fds_function(DBusConnection *connection, DBusPendingFdsChangeFunction callback, void *data)
Register a function to be called whenever the number of pending file descriptors in the loader change.
connection the connection callback the callback
References _dbus_transport_set_pending_fds_function, DBusConnection::transport.
void _dbus_connection_get_stats(DBusConnection *connection, dbus_uint32_t *in_messages, dbus_uint32_t *in_bytes, dbus_uint32_t *in_fds, dbus_uint32_t *in_peak_bytes, dbus_uint32_t *in_peak_fds, dbus_uint32_t *out_messages, dbus_uint32_t *out_bytes, dbus_uint32_t *out_fds, dbus_uint32_t *out_peak_bytes, dbus_uint32_t *out_peak_fds)
const char* _dbus_connection_get_address(DBusConnection *connection)
void _dbus_bus_notify_shared_connection_disconnected_unlocked(DBusConnection *connection)
Internal function that checks to see if this is a shared connection owned by the bus and if it is unref it.
connection a connection that has been disconnected.
References _dbus_assert, _dbus_assert_not_reached, _dbus_connection_close_possibly_shared, _DBUS_LOCK, _DBUS_UNLOCK, dbus_bus_register, DBUS_BUS_STARTER, dbus_connection_open, dbus_connection_open_private, dbus_connection_ref, dbus_connection_set_exit_on_disconnect, dbus_connection_unref, DBUS_ERROR_FAILED, dbus_set_error, BusData::is_well_known, N_BUS_TYPES, NULL, TRUE.
Referenced by dbus_connection_pop_message.