dbus-userdb-util.c
DBUS_USERDB_INCLUDES_PRIVATE
dbus_bool_t _dbus_is_console_user(dbus_uid_t uid, DBusError *error)
Checks to see if the UID sent in is the console user.
uid UID of person to check error return location for errors TRUE if the UID is the same as the console user and there are no errors
References _dbus_error_from_errno, _dbus_stat, _dbus_string_append, _dbus_string_free, _dbus_string_init, _dbus_user_at_console, _dbus_user_database_get_system, _dbus_user_database_lock_system, _dbus_user_database_lookup, _dbus_user_database_unlock_system, DBUS_ERROR_FAILED, dbus_set_error, DBUS_UID_FORMAT, FALSE, NULL, TRUE, DBusStat::uid, DBusUserInfo::username.
Referenced by _dbus_groups_from_uid, _dbus_unix_user_is_at_console.
dbus_bool_t _dbus_get_user_id(const DBusString *username, dbus_uid_t *uid)
Gets user ID given username.
username the username uid return location for UID TRUE if username existed and we got the UID
References _dbus_get_user_id_and_primary_group, NULL.
Referenced by _dbus_groups_from_uid, _dbus_parse_unix_user_from_config.
dbus_bool_t _dbus_get_group_id(const DBusString *groupname, dbus_gid_t *gid)
Gets group ID given groupname.
groupname the groupname gid return location for GID TRUE if group name existed and we got the GID
References _dbus_user_database_get_groupname, _dbus_user_database_get_system, _dbus_user_database_lock_system, _dbus_user_database_unlock_system, FALSE, DBusGroupInfo::gid, NULL, TRUE.
Referenced by _dbus_parse_unix_group_from_config.
dbus_bool_t _dbus_get_user_id_and_primary_group(const DBusString *username, dbus_uid_t *uid_p, dbus_gid_t *gid_p)
Gets user ID and primary group given username.
username the username uid_p return location for UID gid_p return location for GID TRUE if username existed and we got the UID and GID
References _dbus_user_database_get_system, _dbus_user_database_get_username, _dbus_user_database_lock_system, _dbus_user_database_unlock_system, FALSE, NULL, DBusUserInfo::primary_gid, TRUE, DBusUserInfo::uid.
Referenced by _dbus_change_to_daemon_user, _dbus_get_user_id, _dbus_verify_daemon_user.
DBusGroupInfo* _dbus_user_database_lookup_group(DBusUserDatabase *db, dbus_gid_t gid, const DBusString *groupname, DBusError *error)
Looks up a gid or group name in the user database.
Only one of name or GID can be provided. There are wrapper functions for this that are better to use, this one does no locking or anything on the database and otherwise sort of sucks. db the database gid the group ID or DBUS_GID_UNSET groupname group name or NULL error error to fill in the entry in the database
References _dbus_group_info_fill, _dbus_group_info_fill_gid, _dbus_group_info_free_allocated, _dbus_hash_table_insert_string, _dbus_hash_table_insert_uintptr, _dbus_hash_table_lookup_string, _dbus_hash_table_lookup_uintptr, _dbus_hash_table_remove_uintptr, _dbus_is_a_number, DBUS_ERROR_NO_MEMORY, DBUS_GID_FORMAT, DBUS_GID_UNSET, dbus_new0, dbus_set_error, DBUS_UID_UNSET, DBusGroupInfo::gid, DBusGroupInfo::groupname, NULL.
Referenced by _dbus_user_database_get_gid, _dbus_user_database_get_groupname.
dbus_bool_t _dbus_user_database_get_groupname(DBusUserDatabase *db, const DBusString *groupname, const DBusGroupInfo **info, DBusError *error)
Gets the user information for the given group name, returned group info should not be freed.
db user database groupname the group name info return location for const ref to group info error error location FALSE if error is set
References _dbus_user_database_lookup_group, DBUS_GID_UNSET, NULL.
Referenced by _dbus_get_group_id.
dbus_bool_t _dbus_user_database_get_gid(DBusUserDatabase *db, dbus_gid_t gid, const DBusGroupInfo **info, DBusError *error)
Gets the user information for the given GID, returned group info should not be freed.
db user database gid the group ID info return location for const ref to group info error error location FALSE if error is set
References _dbus_user_database_lookup_group, NULL.
dbus_bool_t _dbus_groups_from_uid(dbus_uid_t uid, dbus_gid_t **group_ids, int *n_group_ids)
Gets all groups corresponding to the given UID.
Returns FALSE if no memory, or user isn't known, but always initializes group_ids to a NULL array. uid the UID group_ids return location for array of group IDs n_group_ids return location for length of returned array TRUE if the UID existed and we got some credentials
References _dbus_assert, _dbus_assert_not_reached, _dbus_get_user_id, _dbus_groups_from_uid, _dbus_homedir_from_current_process, _dbus_is_console_user, _dbus_user_database_get_system, _dbus_user_database_get_uid, _dbus_user_database_lock_system, _dbus_user_database_unlock_system, _dbus_username_from_current_process, dbus_error_free, dbus_error_init, dbus_free, dbus_new, FALSE, DBusUserInfo::group_ids, DBusError::message, DBusUserInfo::n_group_ids, NULL, TRUE, DBusUserInfo::uid.
Referenced by _dbus_groups_from_uid, _dbus_unix_groups_from_uid.