dbus-watch.c
VALID_WATCH_FLAGS
dbus_bool_t _dbus_watch_get_enabled(DBusWatch *watch)
dbus_bool_t _dbus_watch_get_oom_last_time(DBusWatch *watch)
void _dbus_watch_set_oom_last_time(DBusWatch *watch, dbus_bool_t oom)
DBusWatch * _dbus_watch_new(int fd, unsigned int flags, dbus_bool_t enabled, DBusWatchHandler handler, void *data, DBusFreeFunction free_data_function)
Creates a new DBusWatch.
Used to add a file descriptor to be polled by a main loop. fd the file descriptor to be watched. flags the conditions to watch for on the descriptor. enabled the initial enabled state handler the handler function data data for handler function free_data_function function to free the data the new DBusWatch object.
References _dbus_assert, DBusWatch::data, dbus_new0, DBusWatch::enabled, DBusWatch::fd, DBusWatch::flags, DBusWatch::free_data_function, DBusWatch::free_handler_data_function, DBusWatch::handler, DBusWatch::handler_data, NULL, DBusWatch::refcount.
Referenced by _dbus_server_new_for_socket, _dbus_spawn_async_with_babysitter, _dbus_transport_new_for_socket.
DBusWatch * _dbus_watch_ref(DBusWatch *watch)
Increments the reference count of a DBusWatch object.
watch the watch object. the watch object.
References DBusWatch::refcount.
Referenced by _dbus_transport_handle_watch, _dbus_watch_list_add_watch.
void _dbus_watch_unref(DBusWatch *watch)
Decrements the reference count of a DBusWatch object and finalizes the object if the count reaches zero.
watch the watch object.
References _dbus_assert, _dbus_warn, dbus_free, dbus_watch_set_data, DBusWatch::fd, DBusWatch::free_handler_data_function, DBusWatch::handler_data, NULL, DBusWatch::refcount.
Referenced by _dbus_babysitter_ref, _dbus_babysitter_unref, _dbus_server_new_for_socket, _dbus_spawn_async_with_babysitter, _dbus_transport_handle_watch, _dbus_transport_new_for_socket, _dbus_watch_list_add_watch, _dbus_watch_list_free, _dbus_watch_list_remove_watch.
void _dbus_watch_invalidate(DBusWatch *watch)
Clears the file descriptor from a now-invalid watch object so that no one tries to use it.
This is because a watch may stay alive due to reference counts after the file descriptor is closed. Invalidation makes it easier to catch bugs. It also keeps people from doing dorky things like assuming file descriptors are unique (never recycled). watch the watch object.
References DBusWatch::fd, DBusWatch::flags.
Referenced by _dbus_babysitter_ref, _dbus_babysitter_unref, _dbus_spawn_async_with_babysitter, _dbus_transport_new_for_socket.
void _dbus_watch_sanitize_condition(DBusWatch *watch, unsigned int *condition)
Sanitizes the given condition so that it only contains flags that the DBusWatch requested.
e.g. if the watch is a DBUS_WATCH_READABLE watch then DBUS_WATCH_WRITABLE will be stripped from the condition. watch the watch object. condition address of the condition to sanitize.
References DBUS_WATCH_READABLE, DBUS_WATCH_WRITABLE, DBusWatch::flags.
Referenced by _dbus_transport_handle_watch, dbus_watch_handle.
DBusWatchList * _dbus_watch_list_new(void)
Creates a new watch list.
Returns NULL if insufficient memory exists.the new watch list, or NULL on failure.
References dbus_new0, NULL.
Referenced by _dbus_connection_new_for_transport, _dbus_server_init_base.
void _dbus_watch_list_free(DBusWatchList *watch_list)
Frees a DBusWatchList.
watch_list the watch list.
References _dbus_list_clear, _dbus_list_foreach, _dbus_watch_list_set_functions, _dbus_watch_unref, dbus_free, DBUS_WATCH_READABLE, DBUS_WATCH_WRITABLE, DBusWatch::flags, NULL, DBusWatchList::watches.
Referenced by _dbus_babysitter_unref, _dbus_connection_new_for_transport, _dbus_server_finalize_base, _dbus_server_init_base, dbus_connection_ref.
dbus_bool_t _dbus_watch_list_set_functions(DBusWatchList *watch_list, DBusAddWatchFunction add_function, DBusRemoveWatchFunction remove_function, DBusWatchToggledFunction toggled_function, void *data, DBusFreeFunction free_data_function)
Sets the watch functions.
This function is the "backend" for dbus_connection_set_watch_functions() and dbus_server_set_watch_functions(). watch_list the watch list. add_function the add watch function. remove_function the remove watch function. toggled_function function on toggling enabled flag, or NULL data the data for those functions. free_data_function the function to free the data. FALSE if not enough memory
References _dbus_list_foreach, _dbus_list_get_first_link, _dbus_list_get_next_link, DBusWatchList::add_watch_function, DBusList::data, DBusWatch::data, dbus_watch_get_flags, dbus_watch_get_socket, FALSE, DBusWatch::free_data_function, NULL, DBusWatchList::remove_watch_function, TRUE, DBusWatchList::watch_data, DBusWatchList::watch_free_data_function, DBusWatchList::watch_toggled_function, DBusWatchList::watches.
Referenced by _dbus_babysitter_set_watch_functions, _dbus_watch_list_free, dbus_connection_set_watch_functions, dbus_server_set_watch_functions.
dbus_bool_t _dbus_watch_list_add_watch(DBusWatchList *watch_list, DBusWatch *watch)
Adds a new watch to the watch list, invoking the application DBusAddWatchFunction if appropriate.
watch_list the watch list. watch the watch to add. TRUE on success, FALSE if no memory.
References _dbus_list_append, _dbus_list_remove_last, _dbus_watch_ref, _dbus_watch_unref, DBusWatchList::add_watch_function, dbus_watch_get_socket, FALSE, NULL, TRUE, DBusWatchList::watch_data, DBusWatchList::watches.
Referenced by _dbus_connection_add_watch_unlocked, _dbus_server_add_watch, _dbus_spawn_async_with_babysitter.
void _dbus_watch_list_remove_watch(DBusWatchList *watch_list, DBusWatch *watch)
Removes a watch from the watch list, invoking the application's DBusRemoveWatchFunction if appropriate.
watch_list the watch list. watch the watch to remove.
References _dbus_assert_not_reached, _dbus_list_remove, _dbus_watch_unref, dbus_watch_get_socket, NULL, DBusWatchList::remove_watch_function, DBusWatchList::watch_data, DBusWatchList::watches.
Referenced by _dbus_babysitter_ref, _dbus_babysitter_unref, _dbus_connection_remove_watch_unlocked, _dbus_server_remove_watch.
void _dbus_watch_list_toggle_watch(DBusWatchList *watch_list, DBusWatch *watch, dbus_bool_t enabled)
Sets a watch to the given enabled state, invoking the application's DBusWatchToggledFunction if appropriate.
watch_list the watch list. watch the watch to toggle. enabled TRUE to enable
References dbus_watch_get_socket, DBusWatch::enabled, NULL, DBusWatchList::watch_data, DBusWatchList::watch_toggled_function.
Referenced by _dbus_connection_toggle_watch_unlocked, _dbus_watch_list_toggle_all_watches.
void _dbus_watch_list_toggle_all_watches(DBusWatchList *watch_list, dbus_bool_t enabled)
Sets all watches to the given enabled state, invoking the application's DBusWatchToggledFunction if appropriate.
watch_list the watch list. enabled TRUE to enable
References _dbus_list_get_first_link, _dbus_list_get_next_link, _dbus_watch_list_toggle_watch, DBusList::data, NULL, DBusWatchList::watches.
Referenced by _dbus_server_toggle_all_watches.
void _dbus_watch_set_handler(DBusWatch *watch, DBusWatchHandler handler, void *data, DBusFreeFunction free_data_function)
Sets the handler for the watch.
Todothis function only exists because of the weird way connection watches are done, see the note in docs for _dbus_connection_handle_watch(). watch the watch handler the new handler data the data free_data_function free data with this
References DBusWatch::data, DBusWatch::free_data_function, DBusWatch::free_handler_data_function, DBusWatch::handler, DBusWatch::handler_data.
int dbus_watch_get_fd(DBusWatch *watch)
Deprecated former name of dbus_watch_get_unix_fd().
watch the DBusWatch object. the file descriptor to watch.
References dbus_watch_get_unix_fd, NULL.
int dbus_watch_get_unix_fd(DBusWatch *watch)
Returns a UNIX file descriptor to be watched, which may be a pipe, socket, or other type of descriptor.
On UNIX this is preferred to dbus_watch_get_socket() since it works with more kinds of DBusWatch.Always returns -1 on Windows. On Windows you use dbus_watch_get_socket() to get a Winsock socket to watch. watch the DBusWatch object. the file descriptor to watch.
References dbus_watch_get_socket, DBusWatch::fd, NULL.
Referenced by dbus_watch_get_fd.
int dbus_watch_get_socket(DBusWatch *watch)
Returns a socket to be watched, on UNIX this will return -1 if our transport is not socket-based so dbus_watch_get_unix_fd() is preferred.
On Windows, dbus_watch_get_unix_fd() returns -1 but this function returns a Winsock socket (assuming the transport is socket-based, as it always is for now). watch the DBusWatch object. the socket to watch.
References DBusWatch::fd, NULL.
Referenced by _dbus_babysitter_set_watch_functions, _dbus_transport_handle_watch, _dbus_watch_list_add_watch, _dbus_watch_list_remove_watch, _dbus_watch_list_set_functions, _dbus_watch_list_toggle_watch, dbus_watch_get_unix_fd, dbus_watch_set_data.
unsigned int dbus_watch_get_flags(DBusWatch *watch)
Gets flags from DBusWatchFlags indicating what conditions should be monitored on the file descriptor.
The flags returned will only contain DBUS_WATCH_READABLE and DBUS_WATCH_WRITABLE, never DBUS_WATCH_HANGUP or DBUS_WATCH_ERROR; all watches implicitly include a watch for hangups, errors, and other exceptional conditions. watch the DBusWatch object. the conditions to watch.
References _dbus_assert, DBusWatch::flags, NULL.
Referenced by _dbus_watch_list_set_functions.
void * dbus_watch_get_data(DBusWatch *watch)
Gets data previously set with dbus_watch_set_data() or NULL if none.
watch the DBusWatch object. previously-set data.
References DBusWatch::data, NULL.
void dbus_watch_set_data(DBusWatch *watch, void *data, DBusFreeFunction free_data_function)
Sets data which can be retrieved with dbus_watch_get_data().
Intended for use by the DBusAddWatchFunction and DBusRemoveWatchFunction to store their own data. For example with Qt you might store the QSocketNotifier for this watch and with GLib you might store a GSource. watch the DBusWatch object. data the data. free_data_function function to be called to free the data.
References DBusWatch::data, dbus_watch_get_socket, DBusWatch::free_data_function, NULL.
Referenced by _dbus_watch_unref.
dbus_bool_t dbus_watch_get_enabled(DBusWatch *watch)
Returns whether a watch is enabled or not.
If not enabled, it should not be polled by the main loop. watch the DBusWatch object TRUE if the watch is enabled
References DBusWatch::enabled, FALSE, NULL.
dbus_bool_t dbus_watch_handle(DBusWatch *watch, unsigned int flags)
Called to notify the D-Bus library when a previously-added watch is ready for reading or writing, or has an exception such as a hangup.
If this function returns FALSE, then the file descriptor may still be ready for reading or writing, but more memory is needed in order to do the reading or writing. If you ignore the FALSE return, your application may spin in a busy loop on the file descriptor until memory becomes available, but nothing more catastrophic should happen.dbus_watch_handle() cannot be called during the DBusAddWatchFunction, as the connection will not be ready to handle that watch yet.It is not allowed to reference a DBusWatch after it has been passed to remove_function. watch the DBusWatch object. flags the poll condition using DBusWatchFlags values FALSE if there wasn't enough memory
References _dbus_warn_check_failed, _dbus_watch_sanitize_condition, FALSE, DBusWatch::fd, DBusWatch::flags, DBusWatch::handler, DBusWatch::handler_data, NULL, TRUE.