dbus-marshal-basic.c
_DBUS_ASSERT_ALIGNMENT
@0
_DBUS_STATIC_ASSERT(sizeof(char)==1)
_DBUS_ASSERT_ALIGNMENT(char,==, 1)
_DBUS_STATIC_ASSERT(sizeof(dbus_int16_t)==2)
_DBUS_ASSERT_ALIGNMENT(dbus_int16_t,<=, 2)
_DBUS_STATIC_ASSERT(sizeof(dbus_uint16_t)==2)
_DBUS_ASSERT_ALIGNMENT(dbus_uint16_t,<=, 2)
_DBUS_STATIC_ASSERT(sizeof(dbus_int32_t)==4)
_DBUS_ASSERT_ALIGNMENT(dbus_int32_t,<=, 4)
_DBUS_STATIC_ASSERT(sizeof(dbus_uint32_t)==4)
_DBUS_ASSERT_ALIGNMENT(dbus_uint32_t,<=, 4)
_DBUS_STATIC_ASSERT(sizeof(double)==8)
_DBUS_ASSERT_ALIGNMENT(double,<=, 8)
_DBUS_STATIC_ASSERT(sizeof(dbus_int64_t)==8)
_DBUS_ASSERT_ALIGNMENT(dbus_int64_t,<=, 8)
_DBUS_STATIC_ASSERT(sizeof(dbus_uint64_t)==8)
_DBUS_ASSERT_ALIGNMENT(dbus_uint64_t,<=, 8)
_DBUS_STATIC_ASSERT(sizeof(DBusBasicValue) >=8)
_DBUS_STATIC_ASSERT(sizeof(DBus8ByteStruct)==8)
_DBUS_ASSERT_ALIGNMENT(DBus8ByteStruct,<=, 8)
static void pack_2_octets(dbus_uint16_t value, int byte_order, unsigned char *data)
static void pack_4_octets(dbus_uint32_t value, int byte_order, unsigned char *data)
static void pack_8_octets(DBusBasicValue value, int byte_order, unsigned char *data)
void _dbus_pack_uint32(dbus_uint32_t value, int byte_order, unsigned char *data)
Packs a 32 bit unsigned integer into a data pointer.
value the value byte_order the byte order to use data the data pointer
References DBusBasicValue::u64.
Referenced by _dbus_first_type_in_signature_c_str.
static void swap_8_octets(DBusBasicValue *value, int byte_order)
dbus_uint16_t _dbus_unpack_uint16(int byte_order, const unsigned char *data)
Unpacks a 16 bit unsigned integer from a data pointer.
byte_order The byte order to use data the data pointer the integer
References _dbus_assert, DBUS_LITTLE_ENDIAN.
dbus_uint32_t _dbus_unpack_uint32(int byte_order, const unsigned char *data)
Unpacks a 32 bit unsigned integer from a data pointer.
byte_order The byte order to use data the data pointer the integer
References _dbus_assert, _dbus_string_get_data_len, DBUS_BIG_ENDIAN, DBUS_LITTLE_ENDIAN.
Referenced by _dbus_first_type_in_signature_c_str, _dbus_marshal_read_uint32, _dbus_marshal_set_uint32, _dbus_type_writer_init_values_only, _dbus_type_writer_write_fixed_multi, _dbus_validate_signature_with_reason, _dbus_verbose_bytes.
static void set_2_octets(DBusString *str, int offset, dbus_uint16_t value, int byte_order)
static void set_4_octets(DBusString *str, int offset, dbus_uint32_t value, int byte_order)
static void set_8_octets(DBusString *str, int offset, DBusBasicValue value, int byte_order)
void _dbus_marshal_set_uint32(DBusString *str, int pos, dbus_uint32_t value, int byte_order)
Sets the 4 bytes at the given offset to a marshaled unsigned integer, replacing anything found there previously.
str the string to write the marshalled int to pos the byte offset where int should be written value the value byte_order the byte order to use
References _dbus_assert, _dbus_marshal_set_uint32, _dbus_string_init_const, _dbus_string_replace_len, _dbus_unpack_uint32, FALSE, TRUE.
Referenced by _dbus_first_type_in_signature_c_str, _dbus_header_set_serial, _dbus_header_update_lengths, _dbus_marshal_set_uint32, _dbus_type_writer_unrecurse.
static dbus_bool_t set_string(DBusString *str, int pos, const char *value, int byte_order, int *old_end_pos, int *new_end_pos)
Sets the existing marshaled string at the given offset with a new marshaled string.
The given offset must point to an existing string or the wrong length will be deleted and replaced with the new string.Note: no attempt is made by this function to re-align any data which has been already marshalled after this string. Use with caution. str the string to write the marshalled string to pos the position of the marshaled string length value the value byte_order the byte order to use old_end_pos place to store byte after the nul byte of the old value new_end_pos place to store byte after the nul byte of the new value TRUE on success, FALSE if no memory
static dbus_bool_t set_signature(DBusString *str, int pos, const char *value, int byte_order, int *old_end_pos, int *new_end_pos)
Sets the existing marshaled signature at the given offset to a new marshaled signature.
Same basic ideas as set_string(). str the string to write the marshalled signature to pos the position of the marshaled signature length value the value byte_order the byte order to use old_end_pos place to store byte after the nul byte of the old value new_end_pos place to store byte after the nul byte of the new value TRUE on success, FALSE if no memory
dbus_bool_t _dbus_marshal_set_basic(DBusString *str, int pos, int type, const void *value, int byte_order, int *old_end_pos, int *new_end_pos)
Sets an existing basic type value to a new value.
Arguments work the same way as _dbus_marshal_basic_type(). str the string pos location of the current value type the type of the current and new values value the address of the new value byte_order byte order for marshaling old_end_pos location to store end position of the old value, or NULL new_end_pos location to store end position of the new value, or NULL FALSE if no memory
References _dbus_assert, _dbus_assert_not_reached, DBusBasicValue::byt, DBUS_TYPE_BOOLEAN, DBUS_TYPE_BYTE, DBUS_TYPE_DOUBLE, DBUS_TYPE_INT16, DBUS_TYPE_INT32, DBUS_TYPE_INT64, DBUS_TYPE_OBJECT_PATH, DBUS_TYPE_SIGNATURE, DBUS_TYPE_STRING, DBUS_TYPE_UINT16, DBUS_TYPE_UINT32, DBUS_TYPE_UINT64, DBUS_TYPE_UNIX_FD, FALSE, NULL, DBusBasicValue::str, TRUE, DBusBasicValue::u16, DBusBasicValue::u32.
Referenced by _dbus_first_type_in_signature_c_str.
dbus_uint32_t _dbus_marshal_read_uint32(const DBusString *str, int pos, int byte_order, int *new_pos)
Convenience function to demarshal a 32 bit unsigned integer.
str the string containing the data byte_order the byte order pos the position in the string new_pos the new position of the string the demarshaled integer.
References _dbus_assert, _dbus_unpack_uint32.
Referenced by _dbus_header_get_serial, _dbus_header_have_message_untrusted, _dbus_marshal_read_basic, _dbus_marshal_skip_array, _dbus_marshal_skip_basic.
void _dbus_marshal_read_basic(const DBusString *str, int pos, int type, void *value, int byte_order, int *new_pos)
Demarshals a basic-typed value.
The "value" pointer is always the address of a variable of the basic type. So e.g. if the basic type is "double" then the pointer is a double*, and if it's "char*" then the pointer is a "char**".A value of type DBusBasicValue is guaranteed to be large enough to hold any of the types that may be returned, which is handy if you are trying to do things generically. For example you can pass a DBusBasicValue* in to this function, and then pass the same DBusBasicValue* in to _dbus_marshal_basic_type() in order to move a value from one place to another. str the string containing the data pos position in the string type type of value to demarshal value pointer to return value data byte_order the byte order new_pos pointer to update with new position, or NULL
References _dbus_assert, _dbus_assert_not_reached, _dbus_marshal_read_uint32, _dbus_string_copy_len, _dbus_string_delete, _dbus_string_equal_substring, _dbus_string_init_const_len, _dbus_string_insert_2_aligned, _dbus_string_insert_4_aligned, _dbus_string_insert_8_aligned, _dbus_string_insert_byte, _dbus_type_to_string, _dbus_verbose_bytes_of_string, _dbus_warn, _dbus_warn_check_failed, DBUS_BIG_ENDIAN, DBUS_LITTLE_ENDIAN, DBUS_MAXIMUM_SIGNATURE_LENGTH, DBUS_TYPE_BOOLEAN, DBUS_TYPE_BYTE, DBUS_TYPE_DOUBLE, DBUS_TYPE_INT16, DBUS_TYPE_INT32, DBUS_TYPE_INT64, dbus_type_is_basic, DBUS_TYPE_OBJECT_PATH, DBUS_TYPE_SIGNATURE, DBUS_TYPE_STRING, DBUS_TYPE_UINT16, DBUS_TYPE_UINT32, DBUS_TYPE_UINT64, DBUS_TYPE_UNIX_FD, dbus_uint64_t, FALSE, TRUE.
Referenced by _dbus_first_type_in_signature_c_str, _dbus_header_get_field_basic, _dbus_type_reader_read_basic.
static dbus_bool_t marshal_2_octets(DBusString *str, int insert_at, dbus_uint16_t value, int byte_order, int *pos_after)
static dbus_bool_t marshal_4_octets(DBusString *str, int insert_at, dbus_uint32_t value, int byte_order, int *pos_after)
static dbus_bool_t marshal_8_octets(DBusString *str, int insert_at, DBusBasicValue value, int byte_order, int *pos_after)
static dbus_bool_t marshal_len_followed_by_bytes(int marshal_as, DBusString *str, int insert_at, const unsigned char *value, int data_len, int byte_order, int *pos_after)
static dbus_bool_t marshal_string(DBusString *str, int insert_at, const char *value, int byte_order, int *pos_after)
static dbus_bool_t marshal_signature(DBusString *str, int insert_at, const char *value, int *pos_after)
dbus_bool_t _dbus_marshal_write_basic(DBusString *str, int insert_at, int type, const void *value, int byte_order, int *pos_after)
Marshals a basic-typed value.
The "value" pointer is always the address of a variable containing the basic type value. So for example for int32 it will be dbus_int32_t*, and for string it will be const char**. This is for symmetry with _dbus_marshal_read_basic() and to have a simple consistent rule. str string to marshal to insert_at where to insert the value type type of value value pointer to a variable containing the value byte_order byte order pos_after NULL or the position after the type TRUE on success
References _dbus_assert, _dbus_assert_not_reached, _dbus_string_copy_len, _dbus_string_init_const_len, _dbus_string_insert_byte, DBusBasicValue::byt, DBUS_TYPE_BOOLEAN, DBUS_TYPE_BYTE, DBUS_TYPE_DOUBLE, DBUS_TYPE_INT16, DBUS_TYPE_INT32, DBUS_TYPE_INT64, dbus_type_is_basic, DBUS_TYPE_OBJECT_PATH, DBUS_TYPE_SIGNATURE, DBUS_TYPE_STRING, DBUS_TYPE_UINT16, DBUS_TYPE_UINT32, DBUS_TYPE_UINT64, DBUS_TYPE_UNIX_FD, FALSE, NULL, DBusBasicValue::str, TRUE, DBusBasicValue::u16, DBusBasicValue::u32.
Referenced by _dbus_type_writer_init_values_only.
static dbus_bool_t marshal_1_octets_array(DBusString *str, int insert_at, const unsigned char *value, int n_elements, int byte_order, int *pos_after)
void _dbus_swap_array(unsigned char *data, int n_elements, int alignment)
Swaps the elements of an array to the opposite byte order.
data start of array n_elements number of elements alignment size of each element
References _dbus_assert, _dbus_string_copy, _dbus_string_delete, _dbus_string_init_const_len, _dbus_string_insert_alignment, _dbus_swap_array, DBUS_MAXIMUM_ARRAY_LENGTH, dbus_uint64_t, FALSE, TRUE.
Referenced by _dbus_swap_array.
static void swap_array(DBusString *str, int array_start, int n_elements, int byte_order, int alignment)
static dbus_bool_t marshal_fixed_multi(DBusString *str, int insert_at, const DBusBasicValue *value, int n_elements, int byte_order, int alignment, int *pos_after)
dbus_bool_t _dbus_marshal_write_fixed_multi(DBusString *str, int insert_at, int element_type, const void *value, int n_elements, int byte_order, int *pos_after)
Marshals a block of values of fixed-length type all at once, as an optimization.
dbus_type_is_fixed() returns TRUE for fixed-length types, which are the basic types minus the string-like types.The value argument should be the adddress of an array, so e.g. "const dbus_uint32_t**" str string to marshal to insert_at where to insert the value element_type type of array elements value address of an array to marshal n_elements number of elements in the array byte_order byte order pos_after NULL or the position after the type TRUE on success
References _dbus_assert, _dbus_assert_not_reached, _dbus_type_to_string, DBUS_TYPE_BOOLEAN, DBUS_TYPE_BYTE, DBUS_TYPE_DOUBLE, DBUS_TYPE_INT16, DBUS_TYPE_INT32, DBUS_TYPE_INT64, dbus_type_is_fixed, DBUS_TYPE_UINT16, DBUS_TYPE_UINT32, DBUS_TYPE_UINT64, DBUS_TYPE_UNIX_FD, FALSE.
Referenced by _dbus_type_writer_write_fixed_multi.
void _dbus_marshal_skip_basic(const DBusString *str, int type, int byte_order, int *pos)
Skips over a basic-typed value, reporting the following position.
str the string containing the data type type of value to read byte_order the byte order pos pointer to position in the string, updated on return to new position
References _dbus_assert, _dbus_assert_not_reached, _dbus_marshal_read_uint32, _dbus_type_to_string, _dbus_warn, DBUS_BIG_ENDIAN, DBUS_LITTLE_ENDIAN, DBUS_TYPE_BOOLEAN, DBUS_TYPE_BYTE, DBUS_TYPE_DOUBLE, DBUS_TYPE_INT16, DBUS_TYPE_INT32, DBUS_TYPE_INT64, DBUS_TYPE_OBJECT_PATH, DBUS_TYPE_SIGNATURE, DBUS_TYPE_STRING, DBUS_TYPE_UINT16, DBUS_TYPE_UINT32, DBUS_TYPE_UINT64, DBUS_TYPE_UNIX_FD.
Referenced by _dbus_type_signature_next.
void _dbus_marshal_skip_array(const DBusString *str, int element_type, int byte_order, int *pos)
Skips an array, returning the next position.
str the string containing the data element_type the type of array elements byte_order the byte order pos pointer to position in the string, updated on return to new position
References _dbus_marshal_read_uint32, _dbus_type_get_alignment.
Referenced by _dbus_type_signature_next.
int _dbus_type_get_alignment(int typecode)
Gets the alignment requirement for the given type; will be 1, 4, or 8.
typecode the type alignment of 1, 4, or 8
References _dbus_assert_not_reached, DBUS_TYPE_ARRAY, DBUS_TYPE_BOOLEAN, DBUS_TYPE_BYTE, DBUS_TYPE_DICT_ENTRY, DBUS_TYPE_DOUBLE, DBUS_TYPE_INT16, DBUS_TYPE_INT32, DBUS_TYPE_INT64, DBUS_TYPE_OBJECT_PATH, DBUS_TYPE_SIGNATURE, DBUS_TYPE_STRING, DBUS_TYPE_STRUCT, DBUS_TYPE_UINT16, DBUS_TYPE_UINT32, DBUS_TYPE_UINT64, DBUS_TYPE_UNIX_FD, DBUS_TYPE_VARIANT.
Referenced by _dbus_first_type_in_signature_c_str, _dbus_marshal_skip_array, _dbus_type_reader_read_fixed_multi, _dbus_type_writer_init_values_only, _dbus_validate_signature_with_reason, dbus_message_iter_append_fixed_array.
const char* _dbus_type_to_string(int typecode)
Returns a string describing the given type.
typecode the type to describe a constant string describing the type
References DBUS_DICT_ENTRY_BEGIN_CHAR, DBUS_DICT_ENTRY_END_CHAR, DBUS_STRUCT_BEGIN_CHAR, DBUS_STRUCT_END_CHAR, DBUS_TYPE_ARRAY, DBUS_TYPE_BOOLEAN, DBUS_TYPE_BYTE, DBUS_TYPE_DICT_ENTRY, DBUS_TYPE_DOUBLE, DBUS_TYPE_INT16, DBUS_TYPE_INT32, DBUS_TYPE_INT64, DBUS_TYPE_INVALID, DBUS_TYPE_OBJECT_PATH, DBUS_TYPE_SIGNATURE, DBUS_TYPE_STRING, DBUS_TYPE_STRUCT, DBUS_TYPE_UINT16, DBUS_TYPE_UINT32, DBUS_TYPE_UINT64, DBUS_TYPE_UNIX_FD, DBUS_TYPE_VARIANT.
Referenced by _dbus_first_type_in_signature_c_str, _dbus_marshal_read_basic, _dbus_marshal_skip_basic, _dbus_marshal_write_fixed_multi, _dbus_message_iter_get_args_valist, _dbus_type_reader_get_current_type, _dbus_type_reader_next, _dbus_type_reader_recurse, _dbus_type_reader_set_basic, _dbus_type_signature_next, _dbus_type_writer_init_values_only, _dbus_type_writer_unrecurse, _dbus_type_writer_write_fixed_multi, _dbus_validate_signature_with_reason, dbus_message_append_args_valist.
void _dbus_verbose_bytes(const unsigned char *data, int len, int offset)
If in verbose mode, print a block of binary data.
data the data len the length of the data offset where to start counting for byte indexes
References _dbus_assert, _dbus_unpack_uint32, DBUS_BIG_ENDIAN, DBUS_LITTLE_ENDIAN, dbus_uint64_t.
Referenced by _dbus_verbose_bytes_of_string.
void _dbus_verbose_bytes_of_string(const DBusString *str, int start, int len)
Dump the given part of the string to verbose log.
str the string start the start of range to dump len length of range
References _dbus_assert, _dbus_verbose_bytes, DBUS_DICT_ENTRY_BEGIN_CHAR, DBUS_DICT_ENTRY_END_CHAR, DBUS_STRUCT_BEGIN_CHAR, DBUS_STRUCT_END_CHAR, DBUS_TYPE_DICT_ENTRY, DBUS_TYPE_STRUCT.
Referenced by _dbus_marshal_read_basic, _dbus_message_loader_return_unix_fds, _dbus_read, _dbus_read_socket, _dbus_read_socket_with_unix_fds, _dbus_type_reader_set_basic, _dbus_write, _dbus_write_socket.
static int map_type_char_to_type(int t)
int _dbus_first_type_in_signature(const DBusString *str, int pos)
Get the first type in the signature.
The difference between this and just getting the first byte of the signature is that you won't get DBUS_STRUCT_BEGIN_CHAR, you'll get DBUS_TYPE_STRUCT instead. str string containing signature pos where the signature starts the first type in the signature
Referenced by _dbus_type_reader_get_current_type, _dbus_type_reader_get_element_type, _dbus_type_reader_read_fixed_multi, _dbus_type_reader_recurse, _dbus_type_signature_next, _dbus_type_writer_init_values_only, _dbus_validate_signature_with_reason.
int _dbus_first_type_in_signature_c_str(const char *str, int pos)
Similar to _dbus_first_type_in_signature, but operates on a C string buffer.
str a C string buffer pos where the signature starts the first type in the signature
References _dbus_assert, _dbus_assert_not_reached, _DBUS_DOUBLES_BITWISE_EQUAL, _dbus_marshal_read_basic, _dbus_marshal_set_basic, _dbus_marshal_set_uint32, _dbus_pack_uint32, _dbus_string_free, _dbus_string_init, _dbus_string_init_const, _dbus_string_init_const_len, _dbus_string_set_length, _dbus_type_get_alignment, _dbus_type_to_string, _dbus_unpack_uint32, DBUS_BIG_ENDIAN, DBUS_INT64_CONSTANT, dbus_int64_t, DBUS_LITTLE_ENDIAN, dbus_type_is_basic, dbus_type_is_fixed, DBUS_TYPE_STRING, DBUS_UINT64_CONSTANT, dbus_uint64_t, FALSE, NULL, TRUE.
Referenced by dbus_signature_iter_get_current_type, dbus_signature_iter_get_element_type.