dbus-marshal-header.c
FIELDS_ARRAY_SIGNATURE_OFFSET
Offset from start of _dbus_header_signature_str to the signature of the fields array.
Referenced by _dbus_header_get_byte_order, _dbus_header_create, _dbus_header_update_lengths, _dbus_header_set_field_basic.
FIELDS_ARRAY_ELEMENT_SIGNATURE_OFFSET
Offset from start of _dbus_header_signature_str to the signature of an element of the fields array.
Referenced by _dbus_header_set_field_basic.
BYTE_ORDER_OFFSET
Offset to byte order from start of header.
Referenced by _dbus_header_get_byte_order, _dbus_header_have_message_untrusted, _dbus_header_load, _dbus_header_byteswap.
TYPE_OFFSET
Offset to type from start of header.
Referenced by _dbus_header_get_message_type, _dbus_header_load.
FLAGS_OFFSET
Offset to flags from start of header.
Referenced by _dbus_header_load, _dbus_header_toggle_flag, _dbus_header_get_flag.
VERSION_OFFSET
Offset to version from start of header.
Referenced by _dbus_header_load.
BODY_LENGTH_OFFSET
Offset to body length from start of header.
Referenced by _dbus_header_have_message_untrusted, _dbus_header_load, _dbus_header_update_lengths.
SERIAL_OFFSET
Offset to client serial from start of header.
Referenced by _dbus_header_set_serial, _dbus_header_get_serial, _dbus_header_load.
FIELDS_ARRAY_LENGTH_OFFSET
Offset to fields array length from start of header.
Referenced by _dbus_header_get_byte_order, _dbus_header_have_message_untrusted, _dbus_header_load, _dbus_header_update_lengths, _dbus_header_set_field_basic.
FIRST_FIELD_OFFSET
Offset to first field in header.
Referenced by _dbus_header_have_message_untrusted, _dbus_header_load, _dbus_header_set_field_basic.
EXPECTED_TYPE_OF_FIELD
Macro to look up the correct type for a field.
Referenced by _dbus_header_have_message_untrusted, _dbus_header_get_field_basic.
MAX_POSSIBLE_HEADER_PADDING
The most padding we could ever need for a header.
HEADER_END_BEFORE_PADDING
Compute the end of the header, ignoring padding.
Referenced by _dbus_header_create, _dbus_header_set_field_basic.
REQUIRE_FIELD
const HeaderFieldType _dbus_header_field_types[DBUS_HEADER_FIELD_LAST+1][DBUS_HEADER_FIELD_LAST+1]
_DBUS_STRING_DEFINE_STATIC(_dbus_header_signature_str, DBUS_HEADER_SIGNATURE)
Static DBusString containing the signature of a message header.
_DBUS_STRING_DEFINE_STATIC(_dbus_local_interface_str, DBUS_INTERFACE_LOCAL)
Static DBusString containing the local interface.
_DBUS_STRING_DEFINE_STATIC(_dbus_local_path_str, DBUS_PATH_LOCAL)
Static DBusString containing the local path.
static dbus_bool_t reserve_header_padding(DBusHeader *header)
static void correct_header_padding(DBusHeader *header)
static void _dbus_header_cache_invalidate_all(DBusHeader *header)
Invalidates all fields in the cache.
This may be used when the cache is totally uninitialized (contains junk) so should not look at what's in there now. header the header
static void _dbus_header_cache_one(DBusHeader *header, int field_code, DBusTypeReader *variant_reader)
Caches one field.
header the header field_code the field variant_reader the reader for the variant in the field
char _dbus_header_get_byte_order(const DBusHeader *header)
Returns the header's byte order.
header the header the byte order
References _dbus_assert, _dbus_assert_not_reached, _dbus_header_get_byte_order, _dbus_string_delete, _dbus_string_init_const_len, _dbus_type_reader_get_current_type, _dbus_type_reader_init, _dbus_type_reader_next, _dbus_type_reader_read_basic, _dbus_type_reader_recurse, _dbus_type_reader_set_basic, _dbus_type_writer_recurse, _dbus_type_writer_unrecurse, _dbus_type_writer_write_basic, BYTE_ORDER_OFFSET, DBusHeader::data, DBUS_HEADER_FIELD_LAST, DBUS_TYPE_BYTE, DBUS_TYPE_INVALID, DBUS_TYPE_STRUCT, DBUS_TYPE_VARIANT, FALSE, DBusHeader::fields, FIELDS_ARRAY_LENGTH_OFFSET, FIELDS_ARRAY_SIGNATURE_OFFSET, NULL, TRUE, DBusHeaderField::value_pos, DBusTypeWriter::value_pos, DBusTypeWriter::value_str.
Referenced by _dbus_header_byteswap, _dbus_header_get_byte_order, _dbus_header_get_field_basic, _dbus_header_get_serial, _dbus_header_have_message_untrusted, _dbus_header_set_field_basic, _dbus_header_set_serial, _dbus_header_update_lengths, dbus_message_iter_init, dbus_message_iter_init_append.
static void _dbus_header_cache_revalidate(DBusHeader *header)
Revalidates the fields cache.
header the header
static dbus_bool_t _dbus_header_cache_check(DBusHeader *header, int field)
Checks for a field, updating the cache if required.
header the header field the field to check FALSE if the field doesn't exist
static dbus_bool_t _dbus_header_cache_known_nonexistent(DBusHeader *header, int field)
Checks whether a field is known not to exist.
It may exist even if it's not known to exist. header the header field the field to check FALSE if the field definitely doesn't exist
static dbus_bool_t write_basic_field(DBusTypeWriter *writer, int field, int type, const void *value)
Writes a struct of { byte, variant } with the given basic type.
writer the writer (should be ready to write a struct) field the header field type the type of the value value the value as for _dbus_marshal_set_basic() FALSE if no memory
static dbus_bool_t set_basic_field(DBusTypeReader *reader, int field, int type, const void *value, const DBusTypeReader *realign_root)
Sets a struct of { byte, variant } with the given basic type.
reader the reader (should be iterating over the array pointing at the field to set) field the header field type the type of the value value the value as for _dbus_marshal_set_basic() realign_root where to realign from FALSE if no memory
int _dbus_header_get_message_type(DBusHeader *header)
Gets the type of the message.
header the header the type
References _dbus_assert, DBusHeader::data, DBUS_MESSAGE_TYPE_INVALID, TYPE_OFFSET.
Referenced by _dbus_header_have_message_untrusted, dbus_message_get_type.
void _dbus_header_set_serial(DBusHeader *header, dbus_uint32_t serial)
Sets the serial number of a header.
This can only be done once on a header. header the header serial the serial
References _dbus_assert, _dbus_header_get_byte_order, _dbus_header_get_serial, _dbus_marshal_set_uint32, DBusHeader::data, SERIAL_OFFSET.
Referenced by _dbus_header_copy, dbus_message_set_serial.
dbus_uint32_t _dbus_header_get_serial(DBusHeader *header)
See dbus_message_get_serial()
header the header the client serial
References _dbus_header_get_byte_order, _dbus_marshal_read_uint32, DBusHeader::data, NULL, SERIAL_OFFSET.
Referenced by _dbus_header_set_serial, dbus_message_get_serial.
void _dbus_header_reinit(DBusHeader *header)
Re-initializes a header that was previously initialized and never freed.
After this, to make the header valid you have to call _dbus_header_create(). header header to re-initialize
References _dbus_string_set_length, DBusHeader::data, DBusHeader::padding.
Referenced by _dbus_header_init, dbus_message_get_reply_serial.
dbus_bool_t _dbus_header_init(DBusHeader *header)
Initializes a header, but doesn't prepare it for use; to make the header valid, you have to call _dbus_header_create().
header header to initialize FALSE if not enough memory
References _dbus_header_reinit, _dbus_string_init_preallocated, DBusHeader::data, FALSE, TRUE.
Referenced by dbus_message_get_reply_serial.
void _dbus_header_free(DBusHeader *header)
Frees a header.
header the header
References _dbus_string_free, DBusHeader::data.
Referenced by dbus_message_copy, dbus_message_get_reply_serial.
dbus_bool_t _dbus_header_copy(const DBusHeader *header, DBusHeader *dest)
Initializes dest with a copy of the given header.
Resets the message serial to 0 on the copy. header header to copy dest destination for copy FALSE if not enough memory
References _dbus_header_set_serial, _dbus_string_copy, _dbus_string_free, _dbus_string_init_preallocated, DBusHeader::data, FALSE, TRUE.
Referenced by dbus_message_copy.
dbus_bool_t _dbus_header_create(DBusHeader *header, int byte_order, int message_type, const char *destination, const char *path, const char *interface, const char *member, const char *error_name)
Fills in the primary fields of the header, so the header is ready for use.
NULL may be specified for some or all of the fields to avoid adding those fields. Some combinations of fields don't make sense, and passing them in will trigger an assertion failure. header the header byte_order byte order of the header message_type the message type destination destination field or NULL path path field or NULL interface interface field or NULL member member field or NULL error_name error name or NULL FALSE if not enough memory
References _dbus_assert, _dbus_string_delete, _dbus_type_writer_init_values_only, _dbus_type_writer_recurse, _dbus_type_writer_unrecurse, _dbus_type_writer_write_basic, DBusHeader::data, DBUS_BIG_ENDIAN, DBUS_HEADER_FIELD_DESTINATION, DBUS_HEADER_FIELD_ERROR_NAME, DBUS_HEADER_FIELD_INTERFACE, DBUS_HEADER_FIELD_MEMBER, DBUS_HEADER_FIELD_PATH, DBUS_LITTLE_ENDIAN, DBUS_MAJOR_PROTOCOL_VERSION, DBUS_MESSAGE_TYPE_SIGNAL, DBUS_TYPE_ARRAY, DBUS_TYPE_BYTE, DBUS_TYPE_OBJECT_PATH, DBUS_TYPE_STRING, DBUS_TYPE_UINT32, FALSE, FIELDS_ARRAY_SIGNATURE_OFFSET, HEADER_END_BEFORE_PADDING, NULL, DBusHeader::padding, TRUE.
Referenced by dbus_message_new, dbus_message_new_error, dbus_message_new_method_call, dbus_message_new_method_return, dbus_message_new_signal.
dbus_bool_t _dbus_header_have_message_untrusted(int max_message_length, DBusValidity *validity, int *byte_order, int *fields_array_len, int *header_len, int *body_len, const DBusString *str, int start, int len)
Given data long enough to contain the length of the message body and the fields array, check whether the data is long enough to contain the entire message (assuming the claimed lengths are accurate).
Also checks that the lengths are in sanity parameters. max_message_length maximum length of a valid message validity return location for why the data is invalid if it is byte_order return location for byte order fields_array_len return location for claimed fields array length header_len return location for claimed header length body_len return location for claimed body length str the data start start of data, 8-aligned len length of data TRUE if the data is long enough for the claimed length, and the lengths were valid
References _dbus_assert, _dbus_assert_not_reached, _dbus_header_get_byte_order, _dbus_header_get_field_basic, _dbus_header_get_field_raw, _dbus_header_get_message_type, _DBUS_INT32_MAX, _dbus_marshal_read_uint32, _dbus_string_equal_substring, _dbus_type_reader_get_current_type, _dbus_validate_bus_name, _dbus_validate_error_name, _dbus_validate_interface, _dbus_validate_member, BODY_LENGTH_OFFSET, BYTE_ORDER_OFFSET, DBUS_BIG_ENDIAN, DBUS_HEADER_FIELD_DESTINATION, DBUS_HEADER_FIELD_ERROR_NAME, DBUS_HEADER_FIELD_INTERFACE, DBUS_HEADER_FIELD_INVALID, DBUS_HEADER_FIELD_LAST, DBUS_HEADER_FIELD_MEMBER, DBUS_HEADER_FIELD_PATH, DBUS_HEADER_FIELD_REPLY_SERIAL, DBUS_HEADER_FIELD_SENDER, DBUS_HEADER_FIELD_SIGNATURE, DBUS_HEADER_FIELD_UNIX_FDS, DBUS_LITTLE_ENDIAN, DBUS_MESSAGE_TYPE_ERROR, DBUS_MESSAGE_TYPE_METHOD_CALL, DBUS_MESSAGE_TYPE_METHOD_RETURN, DBUS_MESSAGE_TYPE_SIGNAL, DBUS_TYPE_OBJECT_PATH, DBUS_TYPE_SIGNATURE, DBUS_TYPE_STRING, DBUS_TYPE_UINT32, DBUS_VALID, EXPECTED_TYPE_OF_FIELD, FALSE, DBusHeader::fields, FIELDS_ARRAY_LENGTH_OFFSET, FIRST_FIELD_OFFSET, NULL, DBusHeaderField::value_pos.
Referenced by _dbus_message_loader_queue_messages, dbus_message_demarshal_bytes_needed.
static DBusValidity check_mandatory_fields(DBusHeader *header)
static DBusValidity load_and_validate_field(DBusHeader *header, int field, DBusTypeReader *variant_reader)
dbus_bool_t _dbus_header_load(DBusHeader *header, DBusValidationMode mode, DBusValidity *validity, int byte_order, int fields_array_len, int header_len, int body_len, const DBusString *str, int start, int len)
Creates a message header from potentially-untrusted data.
The return value is TRUE if there was enough memory and the data was valid. If it returns TRUE, the header will be created. If it returns FALSE and *validity == DBUS_VALIDITY_UNKNOWN_OOM_ERROR, then there wasn't enough memory. If it returns FALSE and *validity != DBUS_VALIDITY_UNKNOWN_OOM_ERROR then the data was invalid.The byte_order, fields_array_len, and body_len args should be from _dbus_header_have_message_untrusted(). Validation performed in _dbus_header_have_message_untrusted() is assumed to have been already done. header the header (must be initialized) mode whether to do validation validity return location for invalidity reason byte_order byte order from header fields_array_len claimed length of fields array body_len claimed length of body header_len claimed length of header str a string start start of header, 8-aligned len length of string to look at FALSE if no memory or data was invalid, TRUE otherwise
References _dbus_assert, _dbus_string_copy_len, _dbus_string_set_length, _dbus_string_validate_nul, _dbus_type_reader_get_current_type, _dbus_type_reader_get_value_pos, _dbus_type_reader_init, _dbus_type_reader_next, _dbus_type_reader_read_basic, _dbus_type_reader_recurse, _dbus_validate_body_with_reason, BODY_LENGTH_OFFSET, BYTE_ORDER_OFFSET, DBusHeader::data, DBUS_HEADER_FIELD_INVALID, DBUS_HEADER_FIELD_LAST, DBUS_MAJOR_PROTOCOL_VERSION, DBUS_MESSAGE_TYPE_INVALID, DBUS_TYPE_ARRAY, DBUS_TYPE_BYTE, DBUS_TYPE_INVALID, DBUS_TYPE_STRUCT, DBUS_TYPE_UINT32, DBUS_TYPE_VARIANT, DBUS_VALID, DBUS_VALIDITY_UNKNOWN_OOM_ERROR, FALSE, DBusHeader::fields, FIELDS_ARRAY_LENGTH_OFFSET, FIRST_FIELD_OFFSET, FLAGS_OFFSET, DBusHeader::padding, SERIAL_OFFSET, TRUE, TYPE_OFFSET, DBusHeaderField::value_pos, VERSION_OFFSET.
Referenced by _dbus_message_loader_return_unix_fds.
void _dbus_header_update_lengths(DBusHeader *header, int body_len)
Fills in the correct body length.
header the header body_len the length of the body
References _dbus_assert, _dbus_header_get_byte_order, _dbus_marshal_set_uint32, _dbus_type_reader_get_current_type, _dbus_type_reader_init, _dbus_type_reader_next, _dbus_type_reader_read_basic, _dbus_type_reader_recurse, BODY_LENGTH_OFFSET, DBusHeader::data, DBUS_TYPE_BYTE, DBUS_TYPE_INVALID, DBUS_TYPE_STRUCT, FALSE, FIELDS_ARRAY_LENGTH_OFFSET, FIELDS_ARRAY_SIGNATURE_OFFSET, TRUE.
Referenced by dbus_message_lock.
static dbus_bool_t find_field_for_modification(DBusHeader *header, int field, DBusTypeReader *reader, DBusTypeReader *realign_root)
Try to find the given field.
header the header field the field code reader a type reader; on success this is left pointing at the struct (uv) for the field, while on failure it is left pointing into empty space at the end of the header fields realign_root another type reader; on success or failure it is left pointing to the beginning of the array of fields (i.e. the thing that might need realigning) TRUE on success
dbus_bool_t _dbus_header_set_field_basic(DBusHeader *header, int field, int type, const void *value)
Sets the value of a field with basic type.
If the value is a string value, it isn't allowed to be NULL. If the field doesn't exist, it will be created. header the header field the field to set type the type of the value value the value as for _dbus_marshal_set_basic() FALSE if no memory
References _dbus_assert, _dbus_assert_not_reached, _dbus_header_get_byte_order, _dbus_type_writer_append_array, _dbus_type_writer_init_values_only, _dbus_type_writer_unrecurse, DBusHeader::data, DBUS_HEADER_FIELD_LAST, FALSE, FIELDS_ARRAY_ELEMENT_SIGNATURE_OFFSET, FIELDS_ARRAY_LENGTH_OFFSET, FIELDS_ARRAY_SIGNATURE_OFFSET, FIRST_FIELD_OFFSET, HEADER_END_BEFORE_PADDING, TRUE, DBusTypeWriter::u, DBusTypeWriter::value_pos.
Referenced by dbus_message_iter_append_basic, dbus_message_iter_init_append, dbus_message_lock, dbus_message_set_reply_serial.
dbus_bool_t _dbus_header_get_field_basic(DBusHeader *header, int field, int type, void *value)
Gets the value of a field with basic type.
If the field doesn't exist, returns FALSE, otherwise returns TRUE. header the header field the field to get type the type of the value value the value as for _dbus_marshal_read_basic() FALSE if the field doesn't exist
References _dbus_assert, _dbus_header_get_byte_order, _dbus_marshal_read_basic, DBusHeader::data, DBUS_HEADER_FIELD_INVALID, DBUS_HEADER_FIELD_LAST, EXPECTED_TYPE_OF_FIELD, FALSE, DBusHeader::fields, NULL, TRUE, DBusHeaderField::value_pos.
Referenced by _dbus_header_have_message_untrusted, _dbus_message_loader_return_unix_fds, dbus_message_get_destination, dbus_message_get_error_name, dbus_message_get_interface, dbus_message_get_member, dbus_message_get_path, dbus_message_get_reply_serial, dbus_message_get_sender.
dbus_bool_t _dbus_header_get_field_raw(DBusHeader *header, int field, const DBusString **str, int *pos)
Gets the raw marshaled data for a field.
If the field doesn't exist, returns FALSE, otherwise returns TRUE. Returns the start of the marshaled data, i.e. usually the byte where the length starts (for strings and arrays) or for basic types just the value itself. header the header field the field to get str return location for the data string pos return location for start of field value FALSE if the field doesn't exist
References DBusHeader::data, FALSE, DBusHeader::fields, TRUE, DBusHeaderField::value_pos.
Referenced by _dbus_header_have_message_untrusted, dbus_message_iter_init_append.
dbus_bool_t _dbus_header_delete_field(DBusHeader *header, int field)
Deletes a field, if it exists.
header the header field the field to delete FALSE if no memory
References _dbus_assert, _dbus_type_reader_delete, FALSE, TRUE.
Referenced by dbus_message_lock.
void _dbus_header_toggle_flag(DBusHeader *header, dbus_uint32_t flag, dbus_bool_t value)
Toggles a message flag bit, turning on the bit if value = TRUE and flipping it off if value = FALSE.
header the header flag the message flag to toggle value toggle on or off
References _dbus_string_get_data_len, DBusHeader::data, FLAGS_OFFSET.
Referenced by dbus_message_set_allow_interactive_authorization, dbus_message_set_auto_start, dbus_message_set_no_reply.
dbus_bool_t _dbus_header_get_flag(DBusHeader *header, dbus_uint32_t flag)
Gets a message flag bit, returning TRUE if the bit is set.
header the header flag the message flag to get TRUE if the flag is set
References DBusHeader::data, FLAGS_OFFSET.
Referenced by dbus_message_get_allow_interactive_authorization, dbus_message_get_auto_start, dbus_message_get_no_reply.
void _dbus_header_byteswap(DBusHeader *header, int new_order)
Swaps the header into the given order if required.
header the header new_order the new byte order
References _dbus_header_get_byte_order, _dbus_marshal_byteswap, BYTE_ORDER_OFFSET, DBusHeader::data.