dbus-threads.c
int thread_init_generation
DBusRMutex* global_locks[_DBUS_N_GLOBAL_LOCKS][_DBUS_N_GLOBAL_LOCKS]
void _dbus_rmutex_new_at_location(DBusRMutex **location_p)
Creates a new mutex or creates a no-op mutex if threads are not initialized.
May return NULL even if threads are initialized, indicating out-of-memory.If possible, the mutex returned by this function is recursive, to avoid deadlocks. However, that cannot be relied on. location_p the location of the new mutex, can return NULL on OOM
References _dbus_assert, dbus_threads_init_default, NULL.
Referenced by _dbus_connection_new_for_transport, _dbus_server_init_base.
void _dbus_cmutex_new_at_location(DBusCMutex **location_p)
Creates a new mutex or creates a no-op mutex if threads are not initialized.
May return NULL even if threads are initialized, indicating out-of-memory.The returned mutex is suitable for use with condition variables. location_p the location of the new mutex, can return NULL on OOM
References _dbus_assert, dbus_threads_init_default, NULL.
Referenced by _dbus_connection_new_for_transport.
void _dbus_rmutex_free_at_location(DBusRMutex **location_p)
Frees a DBusRMutex; does nothing if passed a NULL pointer.
References NULL.
Referenced by _dbus_connection_new_for_transport, dbus_connection_ref, _dbus_server_init_base, _dbus_server_finalize_base.
void _dbus_cmutex_free_at_location(DBusCMutex **location_p)
Frees a DBusCMutex; does nothing if passed a NULL pointer.
References NULL.
Referenced by _dbus_connection_new_for_transport, dbus_connection_ref.
void _dbus_rmutex_lock(DBusRMutex *mutex)
Locks a mutex.
Does nothing if passed a NULL pointer. Locks may be recursive if threading implementation initialized recursive locks.
References NULL.
void _dbus_cmutex_lock(DBusCMutex *mutex)
Locks a mutex.
Does nothing if passed a NULL pointer. Locks may be recursive if threading implementation initialized recursive locks.
References NULL.
Referenced by _dbus_connection_remove_pending_call, dbus_connection_pop_message.
void _dbus_rmutex_unlock(DBusRMutex *mutex)
Unlocks a mutex.
Does nothing if passed a NULL pointer.TRUE on success
References NULL.
Referenced by _dbus_connection_unlock.
void _dbus_cmutex_unlock(DBusCMutex *mutex)
Unlocks a mutex.
Does nothing if passed a NULL pointer.TRUE on success
References NULL.
Referenced by _dbus_connection_remove_pending_call, dbus_connection_pop_message.
DBusCondVar* _dbus_condvar_new(void)
Creates a new condition variable using the function supplied to dbus_threads_init(), or creates a no-op condition variable if threads are not initialized.
May return NULL even if threads are initialized, indicating out-of-memory.new mutex or NULL
References dbus_threads_init_default, NULL.
Referenced by _dbus_condvar_new_at_location.
void _dbus_condvar_new_at_location(DBusCondVar **location_p)
This does the same thing as _dbus_condvar_new.
It however gives another level of indirection by allocating a pointer to point to the condvar location; this used to be useful.the location of a new condvar or NULL on OOM
References _dbus_assert, _dbus_condvar_new, NULL.
Referenced by _dbus_connection_new_for_transport.
void _dbus_condvar_free(DBusCondVar *cond)
Frees a conditional variable created with dbus_condvar_new(); does nothing if passed a NULL pointer.
References NULL.
void _dbus_condvar_free_at_location(DBusCondVar **location_p)
Frees a condition variable; does nothing if passed a NULL pointer.
References NULL.
Referenced by _dbus_connection_new_for_transport, dbus_connection_ref.
void _dbus_condvar_wait(DBusCondVar *cond, DBusCMutex *mutex)
Atomically unlocks the mutex and waits for the conditions variable to be signalled.
Locks the mutex again before returning. Does nothing if passed a NULL pointer.
References NULL.
Referenced by _dbus_connection_remove_pending_call, dbus_connection_pop_message.
dbus_bool_t _dbus_condvar_wait_timeout(DBusCondVar *cond, DBusCMutex *mutex, int timeout_milliseconds)
Atomically unlocks the mutex and waits for the conditions variable to be signalled, or for a timeout.
Locks the mutex again before returning. Does nothing if passed a NULL pointer. Return value is FALSE if we timed out, TRUE otherwise. cond the condition variable mutex the mutex timeout_milliseconds the maximum time to wait FALSE if the timeout occurred, TRUE if not
References NULL, TRUE.
Referenced by _dbus_connection_remove_pending_call.
void _dbus_condvar_wake_one(DBusCondVar *cond)
If there are threads waiting on the condition variable, wake up exactly one.
Does nothing if passed a NULL pointer.
References _dbus_assert, _dbus_current_generation, dbus_threads_init_default, FALSE, DBusCMutex::lock, NULL, TRUE.
Referenced by _dbus_connection_remove_pending_call, dbus_connection_pop_message.
static void shutdown_global_locks(void *nil)
static dbus_bool_t init_global_locks(void)
dbus_bool_t _dbus_lock(DBusGlobalLock lock)
void _dbus_unlock(DBusGlobalLock lock)
DBUS_EXPORT dbus_bool_t dbus_threads_init(const DBusThreadFunctions *functions)
Initializes threads, like dbus_threads_init_default().
This version previously allowed user-specified threading primitives, but since D-Bus 1.6 it ignores them and behaves exactly like dbus_threads_init_default(). functions ignored, formerly functions for using threads TRUE on success, FALSE if no memory
References _dbus_current_generation, _dbus_threads_init_platform_specific, _dbus_threads_lock_platform_specific, _dbus_threads_unlock_platform_specific, FALSE, TRUE.
Referenced by dbus_threads_init_default.
DBUS_EXPORT dbus_bool_t dbus_threads_init_default(void)
Initializes threads.
If this function is not called, the D-Bus library will not lock any data structures. If it is called, D-Bus will do locking, at some cost in efficiency.Since D-Bus 1.7 it is safe to call this function from any thread, any number of times (but it must be called before any other libdbus API is used).In D-Bus 1.6 or older, this function must be called in the main thread before any other thread starts. As a result, it is not sufficient to call this function in a library or plugin, unless the library or plugin imposes a similar requirement on its callers.dbus_shutdown() reverses the effects of this function when it resets all global state in libdbus.TRUE on success, FALSE if not enough memory
References dbus_threads_init, NULL.
Referenced by _dbus_cmutex_new_at_location, _dbus_condvar_new, _dbus_condvar_wake_one, _dbus_rmutex_new_at_location.