dbus-timeout.c
DBusTimeout * _dbus_timeout_new(int interval, DBusTimeoutHandler handler, void *data, DBusFreeFunction free_data_function)
Creates a new DBusTimeout, enabled by default.
interval the timeout interval in milliseconds. handler function to call when the timeout occurs. data data to pass to the handler free_data_function function to be called to free the data. the new DBusTimeout object,
References DBusTimeout::data, dbus_new0, DBusTimeout::enabled, DBusTimeout::free_data_function, DBusTimeout::free_handler_data_function, DBusTimeout::handler, DBusTimeout::handler_data, DBusTimeout::interval, NULL, DBusTimeout::refcount, TRUE.
Referenced by _dbus_pending_call_new_unlocked.
DBusTimeout * _dbus_timeout_ref(DBusTimeout *timeout)
Increments the reference count of a DBusTimeout object.
timeout the timeout object. the timeout object.
References DBusTimeout::refcount.
Referenced by _dbus_timeout_list_add_timeout.
void _dbus_timeout_unref(DBusTimeout *timeout)
Decrements the reference count of a DBusTimeout object and finalizes the object if the count reaches zero.
timeout the timeout object.
References _dbus_assert, dbus_free, dbus_timeout_set_data, DBusTimeout::free_handler_data_function, DBusTimeout::handler_data, NULL, DBusTimeout::refcount.
Referenced by _dbus_pending_call_ref_unlocked, _dbus_timeout_list_add_timeout, _dbus_timeout_list_free, _dbus_timeout_list_remove_timeout.
void _dbus_timeout_set_interval(DBusTimeout *timeout, int interval)
Changes the timeout interval.
Note that you have to disable and re-enable the timeout using the timeout toggle function (_dbus_connection_toggle_timeout_unlocked() etc.) to notify the application of this change. timeout the timeout interval the new interval
References _dbus_assert, DBusTimeout::interval.
void _dbus_timeout_set_enabled(DBusTimeout *timeout, dbus_bool_t enabled)
Changes the timeout's enabled-ness.
Note that you should use _dbus_connection_toggle_timeout_unlocked() etc. instead, if the timeout is passed out to an application main loop. i.e. you can't use this function in the D-Bus library, it's only used in the message bus daemon implementation. timeout the timeout enabled TRUE if timeout should be enabled.
References DBusTimeout::enabled, FALSE.
DBusTimeoutList * _dbus_timeout_list_new(void)
Creates a new timeout list.
Returns NULL if insufficient memory exists.the new timeout list, or NULL on failure.
References dbus_new0, NULL.
Referenced by _dbus_connection_new_for_transport, _dbus_server_init_base.
void _dbus_timeout_list_free(DBusTimeoutList *timeout_list)
Frees a DBusTimeoutList.
timeout_list the timeout list.
References _dbus_list_clear, _dbus_list_foreach, _dbus_timeout_list_set_functions, _dbus_timeout_unref, dbus_free, NULL, DBusTimeoutList::timeouts.
Referenced by _dbus_connection_new_for_transport, _dbus_server_finalize_base, _dbus_server_init_base, dbus_connection_ref.
dbus_bool_t _dbus_timeout_list_set_functions(DBusTimeoutList *timeout_list, DBusAddTimeoutFunction add_function, DBusRemoveTimeoutFunction remove_function, DBusTimeoutToggledFunction toggled_function, void *data, DBusFreeFunction free_data_function)
Sets the timeout functions.
This function is the "backend" for dbus_connection_set_timeout_functions(). timeout_list the timeout list add_function the add timeout function. remove_function the remove timeout function. toggled_function toggle notify function, or NULL data the data for those functions. free_data_function the function to free the data. FALSE if no memory
References _dbus_list_foreach, _dbus_list_get_first_link, _dbus_list_get_next_link, DBusTimeoutList::add_timeout_function, DBusList::data, DBusTimeout::data, FALSE, DBusTimeout::free_data_function, NULL, DBusTimeoutList::remove_timeout_function, DBusTimeoutList::timeout_data, DBusTimeoutList::timeout_free_data_function, DBusTimeoutList::timeout_toggled_function, DBusTimeoutList::timeouts, TRUE.
Referenced by _dbus_timeout_list_free, dbus_connection_set_timeout_functions, dbus_server_set_timeout_functions.
dbus_bool_t _dbus_timeout_list_add_timeout(DBusTimeoutList *timeout_list, DBusTimeout *timeout)
Adds a new timeout to the timeout list, invoking the application DBusAddTimeoutFunction if appropriate.
timeout_list the timeout list. timeout the timeout to add. TRUE on success, FALSE If no memory.
References _dbus_list_append, _dbus_list_remove_last, _dbus_timeout_ref, _dbus_timeout_unref, DBusTimeoutList::add_timeout_function, FALSE, NULL, DBusTimeoutList::timeout_data, DBusTimeoutList::timeouts, TRUE.
Referenced by _dbus_connection_add_timeout_unlocked, _dbus_server_add_timeout.
void _dbus_timeout_list_remove_timeout(DBusTimeoutList *timeout_list, DBusTimeout *timeout)
Removes a timeout from the timeout list, invoking the application's DBusRemoveTimeoutFunction if appropriate.
timeout_list the timeout list. timeout the timeout to remove.
References _dbus_assert_not_reached, _dbus_list_remove, _dbus_timeout_unref, NULL, DBusTimeoutList::remove_timeout_function, DBusTimeoutList::timeout_data, DBusTimeoutList::timeouts.
Referenced by _dbus_connection_remove_timeout_unlocked, _dbus_server_remove_timeout.
void _dbus_timeout_list_toggle_timeout(DBusTimeoutList *timeout_list, DBusTimeout *timeout, dbus_bool_t enabled)
Sets a timeout to the given enabled state, invoking the application's DBusTimeoutToggledFunction if appropriate.
timeout_list the timeout list. timeout the timeout to toggle. enabled TRUE to enable
References DBusTimeout::enabled, NULL, DBusTimeoutList::timeout_data, DBusTimeoutList::timeout_toggled_function.
Referenced by _dbus_connection_toggle_timeout_unlocked, _dbus_server_toggle_timeout.
int dbus_timeout_get_interval(DBusTimeout *timeout)
Gets the timeout interval.
The dbus_timeout_handle() should be called each time this interval elapses, starting after it elapses once.The interval may change during the life of the timeout; if so, the timeout will be disabled and re-enabled (calling the "timeout toggled function") to notify you of the change. timeout the DBusTimeout object. the interval in milliseconds.
References DBusTimeout::interval.
Referenced by _dbus_connection_block_pending_call.
void * dbus_timeout_get_data(DBusTimeout *timeout)
Gets data previously set with dbus_timeout_set_data() or NULL if none.
timeout the DBusTimeout object. previously-set data.
References DBusTimeout::data.
void dbus_timeout_set_data(DBusTimeout *timeout, void *data, DBusFreeFunction free_data_function)
Sets data which can be retrieved with dbus_timeout_get_data().
Intended for use by the DBusAddTimeoutFunction and DBusRemoveTimeoutFunction to store their own data. For example with Qt you might store the QTimer for this timeout and with GLib you might store a g_timeout_add result id. timeout the DBusTimeout object. data the data. free_data_function function to be called to free the data.
References DBusTimeout::data, DBusTimeout::free_data_function, NULL.
Referenced by _dbus_timeout_unref.
dbus_bool_t dbus_timeout_handle(DBusTimeout *timeout)
Calls the timeout handler for this timeout.
This function should be called when the timeout occurs.If this function returns FALSE, then there wasn't enough memory to handle the timeout. Typically just letting the timeout fire again next time it naturally times out is an adequate response to that problem, but you could try to do more if you wanted. timeout the DBusTimeout object. FALSE if there wasn't enough memory
References DBusTimeout::handler, DBusTimeout::handler_data.
dbus_bool_t dbus_timeout_get_enabled(DBusTimeout *timeout)
Returns whether a timeout is enabled or not.
If not enabled, it should not be polled by the main loop. timeout the DBusTimeout object TRUE if the timeout is enabled
References DBusTimeout::enabled.