dbus-internals.c
const char* _dbus_no_memory_message
Fixed "out of memory" error message, just to avoid making up a different string every time and wasting space.
dbus_bool_t warn_initted
dbus_bool_t fatal_warnings
dbus_bool_t fatal_warnings_on_check_failed
int machine_uuid_initialized_generation
DBusGUID machine_uuid
const char* _dbus_return_if_fail_warning_format
String used in _dbus_return_if_fail macro.
Referenced by dbus_server_ref, dbus_server_unref.
static void init_warnings(void)
void _dbus_warn(const char *format,...)
Prints a warning message to stderr.
Can optionally be made to exit fatally by setting DBUS_FATAL_WARNINGS, but this is rarely used. This function should be considered pretty much equivalent to fprintf(stderr). _dbus_warn_check_failed() on the other hand is suitable for use when a programming mistake has been made. format printf-style format string.
References _dbus_abort.
Referenced by _dbus_append_keyring_directory_for_credentials, _dbus_babysitter_unref, _dbus_change_to_daemon_user, _dbus_check_dir_is_private_to_user, _dbus_decompose_path, _dbus_file_exists, _dbus_full_duplex_pipe, _dbus_get_environment, _dbus_get_tmpdir, _dbus_listen_tcp_socket, _dbus_listen_unix_socket, _dbus_marshal_read_basic, _dbus_marshal_skip_basic, _dbus_message_iter_get_args_valist, _dbus_object_tree_unregister_and_unlock, _dbus_poll, _dbus_real_assert, _dbus_real_assert_not_reached, _dbus_server_new_for_launchd, _dbus_sha_compute, _dbus_spawn_async_with_babysitter, _dbus_user_database_lookup, _dbus_warn_check_failed, _dbus_watch_unref, dbus_address_unescape_value, dbus_connection_register_fallback, dbus_connection_register_object_path, dbus_malloc, dbus_malloc0, dbus_message_append_args_valist, dbus_realloc, dbus_server_get_data.
void _dbus_warn_check_failed(const char *format,...)
Prints a "critical" warning to stderr when an assertion fails; differs from _dbus_warn primarily in that it prefixes the pid and defaults to fatal.
This should be used only when a programming error has been detected. (NOT for unavoidable errors that an app might handle - those should be returned as DBusError.) Calling this means "there is a bug"
References _dbus_abort, _dbus_assert, _dbus_getenv, _dbus_pid_for_log, _dbus_warn, FALSE, NULL, TRUE.
Referenced by _dbus_get_local_machine_uuid_encoded, _dbus_marshal_read_basic, _dbus_transport_handle_watch, _dbus_type_reader_recurse, _dbus_type_writer_init_values_only, dbus_connection_close, dbus_connection_remove_filter, dbus_connection_unref, dbus_message_iter_init_append, dbus_server_ref, dbus_server_set_timeout_functions, dbus_server_set_watch_functions, dbus_server_unref, dbus_watch_handle.
char* _dbus_strdup(const char *str)
Duplicates a string.
Result must be freed with dbus_free(). Returns NULL if memory allocation fails. If the string to be duplicated is NULL, returns NULL. str string to duplicate. newly-allocated copy.
References dbus_malloc, NULL.
Referenced by _dbus_check_dir_is_private_to_user, _dbus_connection_handle_watch, _dbus_credentials_add_windows_sid, _dbus_directory_close, _dbus_dup_string_array, _dbus_get_environment, _dbus_hash_table_get_n_entries, _dbus_message_iter_get_args_valist, _dbus_object_tree_free_all_unlocked, _dbus_server_new_for_domain_socket, _dbus_spawn_async_with_babysitter, _dbus_transport_get_is_connected, _dbus_transport_get_windows_user, _dbus_transport_open, _dbus_transport_open_platform_specific, dbus_bus_get_id, dbus_bus_register, dbus_bus_set_unique_name, dbus_connection_get_server_id, dbus_server_get_address, dbus_set_error.
void* _dbus_memdup(const void *mem, size_t n_bytes)
Duplicates a block of memory.
Returns NULL on failure. mem memory to copy n_bytes number of bytes to copy the copy
References dbus_malloc, NULL.
Referenced by _dbus_credentials_add_adt_audit_data, _dbus_decompose_path, _dbus_message_loader_return_unix_fds.
char** _dbus_dup_string_array(const char **array)
Duplicates a string array.
Result may be freed with dbus_free_string_array(). Returns NULL if memory allocation fails. If the array to be duplicated is NULL, returns NULL. array array to duplicate. newly-allocated copy.
References _dbus_strdup, dbus_free_string_array, dbus_new0, NULL.
Referenced by _dbus_auth_set_mechanisms, dbus_server_set_auth_mechanisms.
dbus_bool_t _dbus_string_array_contains(const char **array, const char *str)
Checks whether a string array contains the given string.
array array to search. str string to look for TRUE if array contains string
References FALSE, NULL, TRUE.
void _dbus_generate_uuid(DBusGUID *uuid)
Generates a new UUID.
If you change how this is done, there's some text about it in the spec that should also change. uuid the uuid to initialize
References _dbus_generate_random_bytes_buffer, _dbus_get_real_time, DBusGUID::as_bytes, DBusGUID::as_uint32s, NULL.
Referenced by _dbus_get_local_machine_uuid_encoded, _dbus_read_local_machine_uuid, _dbus_read_uuid_file, _dbus_server_init_base, dbus_internal_do_not_use_create_uuid.
dbus_bool_t _dbus_uuid_encode(const DBusGUID *uuid, DBusString *encoded)
Hex-encode a UUID.
uuid the uuid encoded string to append hex uuid to FALSE if no memory
References _dbus_file_get_contents, _dbus_string_chop_white, _dbus_string_copy_to_buffer, _dbus_string_free, _dbus_string_hex_decode, _dbus_string_hex_encode, _dbus_string_init, _dbus_string_init_const_len, DBusGUID::as_bytes, DBUS_ERROR_INVALID_FILE_CONTENT, dbus_set_error, FALSE, TRUE.
Referenced by _dbus_get_local_machine_uuid_encoded, _dbus_server_init_base, _dbus_write_uuid_file.
static dbus_bool_t _dbus_read_uuid_file_without_creating(const DBusString *filename, DBusGUID *uuid, DBusError *error)
dbus_bool_t _dbus_write_uuid_file(const DBusString *filename, const DBusGUID *uuid, DBusError *error)
Write the give UUID to a file.
filename the file to write uuid the UUID to save error used to raise an error FALSE on error
References _dbus_string_append_byte, _dbus_string_free, _dbus_string_init, _dbus_string_save_to_file, _dbus_uuid_encode, FALSE, TRUE.
Referenced by _dbus_read_local_machine_uuid, _dbus_read_uuid_file.
dbus_bool_t _dbus_read_uuid_file(const DBusString *filename, DBusGUID *uuid, dbus_bool_t create_if_not_found, DBusError *error)
Reads (and optionally writes) a uuid to a file.
Initializes the uuid unless an error is returned. filename the name of the file uuid uuid to be initialized with the loaded uuid create_if_not_found TRUE to create a new uuid and save it if the file doesn't exist error the error return FALSE if the error is set
References _dbus_generate_uuid, _dbus_write_uuid_file, dbus_error_free, dbus_error_has_name, DBUS_ERROR_INIT, DBUS_ERROR_INVALID_FILE_CONTENT, dbus_move_error, FALSE, TRUE.
Referenced by _dbus_read_local_machine_uuid, dbus_internal_do_not_use_get_uuid.
dbus_bool_t _dbus_get_local_machine_uuid_encoded(DBusString *uuid_str)
Gets the hex-encoded UUID of the machine this function is executed on.
This UUID is guaranteed to be the same for a given machine at least until it next reboots, though it also makes some effort to be the same forever, it may change if the machine is reconfigured or its hardware is modified. uuid_str string to append hex-encoded machine uuid to FALSE if no memory
References _dbus_current_generation, _dbus_generate_uuid, _DBUS_LOCK, _dbus_read_local_machine_uuid, _DBUS_UNLOCK, _dbus_uuid_encode, _dbus_warn_check_failed, dbus_error_free, DBUS_ERROR_INIT, FALSE, DBusError::message.
Referenced by _dbus_get_autolaunch_address, dbus_connection_get_dispatch_status, dbus_get_local_machine_id.
void _dbus_real_assert(dbus_bool_t condition, const char *condition_text, const char *file, int line, const char *func)
Internals of _dbus_assert(); it's a function rather than a macro with the inline code so that the assertion failure blocks don't show up in test suite coverage, and to shrink code size.
condition TRUE if assertion succeeded condition_text condition as a string file file the assertion is in line line the assertion is in func function the assertion is in
References _dbus_abort, _dbus_pid_for_log, _dbus_warn.
void _dbus_real_assert_not_reached(const char *explanation, const char *file, int line)
Internals of _dbus_assert_not_reached(); it's a function rather than a macro with the inline code so that the assertion failure blocks don't show up in test suite coverage, and to shrink code size.
explanation what was reached that shouldn't have been file file the assertion is in line line the assertion is in
References _dbus_abort, _dbus_getenv, _DBUS_INT_MAX, _dbus_pid_for_log, _dbus_string_init_const, _dbus_string_parse_int, _dbus_warn, FALSE, NULL, TRUE.