dbus-sysdeps-win.c
STRSAFE_NO_DEPRECATE
_WIN32_WINNT
O_BINARY
PROCESS_QUERY_LIMITED_INFORMATION
USE_CHRIS_IMPL
DBUS_POLL_CHAR_BUFFER_SIZE
NANOSECONDS_PER_SECOND
nanoseconds in a second
MICROSECONDS_PER_SECOND
microseconds in a second
MILLISECONDS_PER_SECOND
milliseconds in a second
NANOSECONDS_PER_MILLISECOND
nanoseconds in a millisecond
MICROSECONDS_PER_MILLISECOND
microseconds in a millisecond
BACKTRACES
DPRINTF
FUNC
KEYRING_DIR
typedef int socklen_t
typedef MIB_TCPROW_OWNER_PID _MIB_TCPROW_EX
typedef MIB_TCPTABLE_OWNER_PID MIB_TCPTABLE_EX
typedef PMIB_TCPTABLE_OWNER_PID PMIB_TCPTABLE_EX
typedef DWORD(WINAPI * ProcAllocateAndGetTcpExtTableFromStack) (PMIB_TCPTABLE_EX *, BOOL, HANDLE, DWORD, DWORD))(PMIB_TCPTABLE_EX *, BOOL, HANDLE, DWORD, DWORD)
ProcAllocateAndGetTcpExtTableFromStack lpfnAllocateAndGetTcpExTableFromStack
HANDLE hProcess
HANDLE HANDLE hThread
HANDLE HANDLE LPSTACKFRAME StackFrame
HANDLE HANDLE LPSTACKFRAME PVOID ContextRecord
HANDLE HANDLE LPSTACKFRAME PVOID PREAD_PROCESS_MEMORY_ROUTINE ReadMemoryRoutine
HANDLE HANDLE LPSTACKFRAME PVOID PREAD_PROCESS_MEMORY_ROUTINE PFUNCTION_TABLE_ACCESS_ROUTINE FunctionTableAccessRoutine
HANDLE HANDLE LPSTACKFRAME PVOID PREAD_PROCESS_MEMORY_ROUTINE PFUNCTION_TABLE_ACCESS_ROUTINE PGET_MODULE_BASE_ROUTINE GetModuleBaseRoutine
HANDLE HANDLE LPSTACKFRAME PVOID PREAD_PROCESS_MEMORY_ROUTINE PFUNCTION_TABLE_ACCESS_ROUTINE PGET_MODULE_BASE_ROUTINE PTRANSLATE_ADDRESS_ROUTINE TranslateAddress
static DWORD dwAddr
DWORD AddrBase
PSTR UserSearchPath
PSTR BOOL fInvadeProcess
DWORD Address
DWORD PDWORD Displacement
DWORD PDWORD PIMAGEHLP_SYMBOL Symbol
DWORD PIMAGEHLP_MODULE ModuleInfo
HANDLE hDBusDaemonMutex
HANDLE hDBusSharedMem
const char* cUniqueDBusInitMutex
const char* cDBusAutolaunchMutex
const char* cDBusDaemonMutex
const char* cDBusDaemonAddressInfo
BOOL WINAPI ConvertStringSidToSidA(LPCSTR StringSid, PSID *Sid)
BOOL WINAPI ConvertSidToStringSidA(PSID Sid, LPSTR *StringSid)
void _dbus_win_set_errno(int err)
static BOOL is_winxp_sp3_or_lower()
static BOOL load_ex_ip_helper_procedures(void)
AllocateAndGetTcpExTableFromStack() is undocumented and not exported, but is the only way to do this in older XP versions.
true if the procedures could be loaded
static dbus_pid_t get_pid_from_extended_tcp_table(int peer_port)
get pid from localhost tcp connection using peer_port This function is available on WinXP >= SP3
peer_port peers tcp port process id or 0 if connection has not been found
static dbus_pid_t get_pid_from_tcp_ex_table(int peer_port)
get pid from localhost tcp connection using peer_port This function is available on all WinXP versions, but not in wine (at least version <= 1.6.0)
peer_port peers tcp port process id or 0 if connection has not been found
static dbus_pid_t _dbus_get_peer_pid_from_tcp_handle(int handle)
return peer process id from tcp handle for localhost connections
handle tcp socket descriptor process id or 0 in case the process id could not be fetched
const char* _dbus_win_error_from_last_error(void)
char* _dbus_win_error_string(int error_number)
void _dbus_win_free_error_string(char *string)
int _dbus_read_socket(int fd, DBusString *buffer, int count)
Socket interface.
Like _dbus_read(), but only works on sockets so is available on Windows.Thin wrapper around the read() system call that appends the data it reads to the DBusString buffer. It appends up to the given count, and returns the same value and same errno as read(). The only exception is that _dbus_read_socket() handles EINTR for you. _dbus_read_socket() can return ENOMEM, even though regular UNIX read doesn't. fd the file descriptor to read from buffer the buffer to append data to count the amount of data to read the number of bytes read or -1
References _dbus_read, _dbus_assert, _dbus_string_lengthen, _dbus_string_get_data_len, _dbus_string_set_length, _dbus_verbose_bytes_of_string.
Referenced by _dbus_read_credentials_socket.
int _dbus_write_socket(int fd, const DBusString *buffer, int start, int len)
Thin wrapper around the write() system call that writes a part of a DBusString and handles EINTR for you.
Like _dbus_write(), but only supports sockets and is thus available on Windows. fd the file descriptor to write buffer the buffer to write data from start the first byte in the buffer to write len the number of bytes to try to write the number of bytes written or -1 on error
References _dbus_write, _dbus_strerror_from_errno, _dbus_verbose_bytes_of_string.
Referenced by _dbus_send_credentials_socket.
dbus_bool_t _dbus_close_socket(int fd, DBusError *error)
Closes a file descriptor.
Socket interface. fd the file descriptor error error object FALSE if error set
References _dbus_close, dbus_set_error, _dbus_error_from_errno, _dbus_strerror_from_errno, FALSE, TRUE.
static void _dbus_win_handle_set_close_on_exec(HANDLE handle)
Sets the file descriptor to be close on exec.
Should be called for all file descriptors in D-Bus code. handle the Windows HANDLE (a SOCKET is also OK)
dbus_bool_t _dbus_set_fd_nonblocking(int handle, DBusError *error)
Sets a file descriptor to be nonblocking.
handle the file descriptor. error address of error location. TRUE on success.
int _dbus_write_socket_two(int fd, const DBusString *buffer1, int start1, int len1, const DBusString *buffer2, int start2, int len2)
Like _dbus_write() but will use writev() if possible to write both buffers in sequence.
Like _dbus_write_two() but only works on sockets and is thus available on Windows.The return value is the number of bytes written in the first buffer, plus the number written in the second. If the first buffer is written successfully and an error occurs writing the second, the number of bytes in the first is returned (i.e. the error is ignored), on systems that don't have writev. Handles EINTR for you. The second buffer may be NULL. fd the file descriptor buffer1 first buffer start1 first byte to write in first buffer len1 number of bytes to write from first buffer buffer2 second buffer, or NULL start2 first byte to write in second buffer len2 number of bytes to write in second buffer total bytes written from both buffers, or -1 on error
References _dbus_assert, NULL, _DBUS_ZERO, _dbus_write_two, TRUE, FALSE, _dbus_strerror_from_errno, _dbus_assert_not_reached, _DBUS_LOCK, _dbus_abort, _DBUS_UNLOCK.
dbus_bool_t _dbus_socket_is_invalid(int fd)
dbus_bool_t _dbus_win_startup_winsock(void)
FALSE if no memory
int _dbus_printf_string_upper_bound(const char *format, va_list args)
Measure the message length without terminating nul.
Measure the length of the given format string and arguments, not including the terminating nul.
References dbus_malloc, NULL, dbus_free, _dbus_string_init_const, _dbus_string_validate_utf8, dbus_set_error_const, DBUS_ERROR_FAILED, dbus_new, FALSE, TRUE.
wchar_t* _dbus_win_utf8_to_utf16(const char *str, DBusError *error)
Returns the UTF-16 form of a UTF-8 string.
The result should be freed with dbus_free() when no longer needed. str the UTF-8 string error return location for error code
char* _dbus_win_utf16_to_utf8(const wchar_t *str, DBusError *error)
Returns the UTF-8 form of a UTF-16 string.
The result should be freed with dbus_free() when no longer needed. str the UTF-16 string error return location for error code
dbus_bool_t _dbus_win_account_to_sid(const wchar_t *waccount, void **ppsid, DBusError *error)
unsigned long _dbus_pid_for_log(void)
The only reason this is separate from _dbus_getpid() is to allow it on Windows for logging but not for other purposes.
process ID to put in log messages
References _dbus_getpid, NULL, FALSE, TRUE.
static dbus_bool_t _dbus_getsid(char **sid, dbus_pid_t process_id)
Gets our SID.
sid points to sid buffer, need to be freed with LocalFree() process_id the process id for which the sid should be returned process sid
dbus_bool_t _dbus_full_duplex_pipe(int *fd1, int *fd2, dbus_bool_t blocking, DBusError *error)
Creates a full-duplex pipe (as in socketpair()).
Sets both ends of the pipe nonblocking. fd1 return location for one end fd2 return location for the other end blocking TRUE if pipe should be blocking error error return FALSE on failure (if error is set)
References dbus_set_error, _dbus_error_from_errno, FALSE, _dbus_fd_set_close_on_exec, NULL, _dbus_close, TRUE, _dbus_warn, DBUS_ERROR_FAILED, _DBUS_ZERO, _dbus_strerror_from_errno.
int _dbus_poll(DBusPollFD *fds, int n_fds, int timeout_milliseconds)
Wrapper for poll().
fds the file descriptors to poll n_fds number of descriptors in the array timeout_milliseconds timeout or -1 for infinite numbers of fds with revents, or <0 on error
References _DBUS_POLLIN, _DBUS_POLLPRI, _DBUS_POLLOUT, _DBUS_POLLERR, _DBUS_POLLHUP, _DBUS_POLLNVAL, _dbus_warn, DBusPollFD::events, DBusPollFD::fd, NULL, DBusPollFD::revents, _dbus_assert_not_reached, FALSE, _dbus_strerror_from_errno.
void _dbus_exit(int code)
Exit the process, returning the given value.
code the exit code
References NULL.
int _dbus_connect_tcp_socket(const char *host, const char *port, const char *family, DBusError *error)
Creates a socket and connects to a socket at the given host and port.
The connection fd is returned, and is set up as nonblocking. host the host name to connect to port the port to connect to family the address family to listen on, NULL for all error return location for error code connection file descriptor or -1 on error
References NULL, _DBUS_ZERO, dbus_set_error, DBUS_ERROR_BAD_ADDRESS, _dbus_error_from_errno, _dbus_close, _dbus_string_init_const, _dbus_string_free, DBUS_ERROR_INVALID_ARGS, _dbus_strerror_from_errno, _dbus_string_init, _dbus_string_append, DBUS_ERROR_NO_MEMORY.
int _dbus_connect_tcp_socket_with_nonce(const char *host, const char *port, const char *family, const char *noncefile, DBusError *error)
int _dbus_listen_tcp_socket(const char *host, const char *port, const char *family, DBusString *retport, int **fds_p, DBusError *error)
Creates a socket and binds it to the given path, then listens on the socket.
The socket is set to be nonblocking. In case of port=0 a random free port is used and returned in the port parameter. If inaddr_any is specified, the hostname is ignored. host the host name to listen on port the port to listen on, if zero a free port will be used family the address family to listen on, NULL for all retport string to return the actual port listened on fds_p location to store returned file descriptors error return location for errors the number of listening file descriptors or -1 on error
References NULL, _DBUS_ZERO, dbus_set_error, DBUS_ERROR_BAD_ADDRESS, _dbus_error_from_errno, _dbus_warn, _dbus_close, dbus_realloc, _dbus_string_append, DBUS_ERROR_NO_MEMORY, dbus_free, FALSE, DBUS_ERROR_IO_ERROR, _dbus_assert, TRUE, DBUS_ERROR_INVALID_ARGS, _dbus_strerror_from_errno.
int _dbus_accept(int listen_fd)
Accepts a connection on a listening socket.
Handles EINTR for you. listen_fd the listen file descriptor the connection fd of the client, or -1 on error
References _dbus_fd_set_close_on_exec, NULL.
dbus_bool_t _dbus_send_credentials_socket(int handle, DBusError *error)
Sends a single nul byte with our UNIX credentials as ancillary data.
Returns TRUE if the data was successfully written. On systems that don't support sending credentials, just writes a byte, doesn't send any credentials. On some systems, such as Linux, reading/writing the byte isn't actually required, but we do it anyway just to avoid multiple codepaths.Fails if no byte can be written, so you must select() first.The point of the byte is that on some systems we have to use sendmsg()/recvmsg() to transmit credentials. server_fd file descriptor for connection to server error return location for error code TRUE if the byte was sent
References TRUE, FALSE, _dbus_string_init_const_len, _dbus_write_socket, dbus_set_error, _dbus_error_from_errno, _dbus_strerror_from_errno, DBUS_ERROR_IO_ERROR, _dbus_assert.
dbus_bool_t _dbus_read_credentials_socket(int handle, DBusCredentials *credentials, DBusError *error)
Reads a single byte which must be nul (an error occurs otherwise), and reads unix credentials if available.
Fills in pid/uid/gid with -1 if no credentials are available. Return value indicates whether a byte was read, not whether we got valid credentials. On some systems, such as Linux, reading/writing the byte isn't actually required, but we do it anyway just to avoid multiple codepaths.Fails if no byte is available, so you must select() first.The point of the byte is that on some systems we have to use sendmsg()/recvmsg() to transmit credentials. handle the client file descriptor credentials struct to fill with credentials of client error location to store error code TRUE on success
References DBUS_UID_UNSET, DBUS_PID_UNSET, _dbus_credentials_clear, _DBUS_ZERO, dbus_set_error, _dbus_error_from_errno, FALSE, DBUS_ERROR_FAILED, NULL, _dbus_credentials_add_adt_audit_data, DBUS_PID_FORMAT, DBUS_UID_FORMAT, _dbus_credentials_add_pid, _dbus_credentials_add_unix_uid, TRUE, _dbus_string_init, _dbus_read_socket, _dbus_string_free, _dbus_credentials_add_windows_sid.
dbus_bool_t _dbus_check_dir_is_private_to_user(DBusString *dir, DBusError *error)
Checks to make sure the given directory is private to the user.
dir the name of the directory error error return FALSE on failure
References dbus_set_error, _dbus_error_from_errno, FALSE, DBUS_ERROR_FAILED, TRUE, _dbus_assert, NULL, DBusUserInfo::uid, DBusUserInfo::primary_gid, DBusUserInfo::username, _dbus_strdup, DBusUserInfo::homedir, DBUS_ERROR_NO_MEMORY, DBUS_UID_UNSET, DBUS_GID_UNSET, DBusUserInfo::group_ids, DBusUserInfo::n_group_ids, dbus_malloc, dbus_free, dbus_new, dbus_realloc, _dbus_warn, DBUS_GID_FORMAT.
dbus_bool_t _dbus_concat_dir_and_file(DBusString *dir, const DBusString *next_component)
Appends the given filename to the given directory.
Todoit might be cute to collapse multiple '/' such as "foo//" concat "//bar" dir the directory name next_component the filename TRUE on success
References TRUE, _dbus_string_shorten, _dbus_string_append_byte, FALSE, _dbus_string_copy.
Referenced by _dbus_append_keyring_directory_for_credentials.
dbus_bool_t _dbus_credentials_add_from_user(DBusCredentials *credentials, const DBusString *username)
Adds the credentials corresponding to the given username.
credentials credentials to fill in username the username TRUE if the username existed and we got some credentials
dbus_bool_t _dbus_credentials_add_from_current_process(DBusCredentials *credentials)
Adds the credentials of the current process to the passed-in credentials object.
credentials credentials to add to FALSE if no memory; does not properly roll back on failure, so only some credentials may have been added
References _dbus_credentials_add_pid, _dbus_getpid, FALSE, _dbus_credentials_add_unix_uid, _dbus_geteuid, TRUE, NULL, _dbus_credentials_add_windows_sid.
dbus_bool_t _dbus_append_user_from_current_process(DBusString *str)
Append to the string the identity we would like to have when we authenticate, on UNIX this is the current process UID and on Windows something else, probably a Windows SID string.
No escaping is required, that is done in dbus-auth.c. The username here need not be anything human-readable, it can be the machine-readable form i.e. a user id. str the string to append to FALSE on no memory Todoto which class belongs this
References _dbus_string_append_uint, _dbus_geteuid, FALSE, NULL, _dbus_getpid, _dbus_string_append.
Referenced by _dbus_read_local_machine_uuid.
dbus_pid_t _dbus_getpid(void)
Gets our process ID.
process ID
Referenced by _dbus_pid_for_log, _dbus_credentials_add_from_current_process, _dbus_append_user_from_current_process.
void _dbus_sleep_milliseconds(int milliseconds)
Sleeps the given number of milliseconds.
milliseconds number of milliseconds
References _dbus_string_lengthen, FALSE, _dbus_string_get_data_len, _dbus_generate_pseudorandom_bytes_buffer, TRUE.
void _dbus_get_real_time(long *tv_sec, long *tv_usec)
Get current time, as in gettimeofday().
Never uses the monotonic clock. tv_sec return location for number of seconds tv_usec return location for number of microseconds
References NULL, dbus_uint64_t, DBUS_INT64_CONSTANT.
Referenced by _dbus_get_monotonic_time.
void _dbus_get_monotonic_time(long *tv_sec, long *tv_usec)
Get current time, as in gettimeofday().
Use the monotonic clock if available, to avoid problems when the system time changes. tv_sec return location for number of seconds tv_usec return location for number of microseconds
References NULL, _dbus_get_real_time.
void _dbus_disable_sigpipe(void)
signal (SIGPIPE, SIG_IGN);
dbus_bool_t _dbus_create_directory(const DBusString *filename, DBusError *error)
Creates a directory; succeeds if the directory is created or already existed.
directory interface filename directory filename error initialized error object TRUE on success
References TRUE, dbus_set_error, DBUS_ERROR_FAILED, FALSE, NULL, _dbus_strerror_from_errno.
dbus_bool_t _dbus_generate_random_bytes(DBusString *str, int n_bytes)
Generates the given number of random bytes, using the best mechanism we can come up with.
str the string n_bytes the number of random bytes to append to string TRUE on success, FALSE if no memory
References _dbus_read, _dbus_close, NULL, _dbus_string_set_length, TRUE, _dbus_string_lengthen, FALSE, _dbus_string_get_data_len.
const char* _dbus_get_tmpdir(void)
Gets the temporary files directory by inspecting the environment variables TMPDIR, TMP, and TEMP in that order.
If none of those are set "/tmp" is returnedlocation of temp directory, or NULL if no memory for locking
References NULL, _DBUS_LOCK, _DBUS_UNLOCK, _dbus_assert, FALSE, dbus_set_error, _dbus_error_from_errno, READ_END, WRITE_END, _dbus_close_all, _dbus_read, _dbus_string_init, _dbus_string_set_length, DBUS_ERROR_SPAWN_EXEC_FAILED, TRUE, _dbus_warn, _dbus_abort.
dbus_bool_t _dbus_delete_file(const DBusString *filename, DBusError *error)
Deletes the given file.
filename the filename error error location TRUE if unlink() succeeded
References dbus_set_error, DBUS_ERROR_FAILED, FALSE, TRUE, _dbus_strerror_from_errno, NULL, _DBUS_ZERO.
static BOOL(WINAPI *pStackWalk)(DWORD MachineType
static DWORD(WINAPI *pSymGetModuleBase)(HANDLE hProcess
static PVOID(WINAPI *pSymFunctionTableAccess)(HANDLE hProcess
static BOOL init_backtrace()
static void dump_backtrace_for_thread(HANDLE hThread)
static DWORD WINAPI dump_thread_proc(LPVOID lpParameter)
static void dump_backtrace()
void _dbus_print_backtrace(void)
On GNU libc systems, print a crude backtrace to stderr.
On other systems, print "no backtrace support" and block for possible gdb attachment if an appropriate environment variable is set.
static dbus_uint32_t fromAscii(char ascii)
dbus_bool_t _dbus_read_local_machine_uuid(DBusGUID *machine_id, dbus_bool_t create_if_not_found, DBusError *error)
Reads the uuid of the machine we're running on from the dbus configuration.
Optionally try to create it (only root can do this usually).On UNIX, reads a file that gets created by dbus-uuidgen in a post-install script. On Windows, if there's a standard machine uuid we could just use that, but I can't find one with the right properties (the hardware profile guid can change without rebooting I believe). If there's no standard one we might want to use the registry instead of a file for this, and I'm not sure how we'd ensure the uuid gets created. machine_id guid to init with the machine's uuid create_if_not_found try to create the uuid if it doesn't exist error the error return FALSE if the error is set
References _dbus_string_init_const, _dbus_read_uuid_file, FALSE, TRUE, dbus_error_free, _dbus_write_uuid_file, NULL, _dbus_generate_uuid, dbus_set_error, DBUS_ERROR_NO_MEMORY, DBusGUID::as_uint32s, _dbus_string_init, _dbus_string_append, _dbus_string_tolower_ascii, _dbus_sha_compute, _dbus_string_free, _dbus_append_user_from_current_process, _dbus_assert.
static HANDLE _dbus_global_lock(const char *mutexname)
static void _dbus_global_unlock(HANDLE mutex)
static dbus_bool_t _dbus_get_install_root_as_hash(DBusString *out)
static dbus_bool_t _dbus_get_address_string(DBusString *out, const char *basestring, const char *scope)
static dbus_bool_t _dbus_get_shm_name(DBusString *out, const char *scope)
static dbus_bool_t _dbus_get_mutex_name(DBusString *out, const char *scope)
dbus_bool_t _dbus_daemon_is_session_bus_address_published(const char *scope)
dbus_bool_t _dbus_daemon_publish_session_bus_address(const char *address, const char *scope)
void _dbus_daemon_unpublish_session_bus_address(void)
static dbus_bool_t _dbus_get_autolaunch_shm(DBusString *address, DBusString *shm_name)
static dbus_bool_t _dbus_daemon_already_runs(DBusString *address, DBusString *shm_name, const char *scope)
dbus_bool_t _dbus_get_autolaunch_address(const char *scope, DBusString *address, DBusError *error)
Returns the address of a new session bus.
If successful, returns TRUE and appends the address to address. If a failure happens, returns FALSE and sets an error in error. scope scope of autolaunch (Windows only) address a DBusString where the address can be stored error a DBusError to store the error in case of failure TRUE on success, FALSE if an error happened
References _dbus_check_setuid, dbus_set_error_const, DBUS_ERROR_NOT_SUPPORTED, FALSE, _dbus_getenv, NULL, _dbus_string_init, _dbus_get_local_machine_uuid_encoded, _dbus_assert, _DBUS_N_ELEMENTS, TRUE, _dbus_string_free, DBUS_ERROR_FAILED.
dbus_bool_t _dbus_make_file_world_readable(const DBusString *filename, DBusError *error)
Makes the file readable by every user in the system.
filename the filename error error location TRUE if the file's permissions could be changed.
References dbus_set_error, DBUS_ERROR_FAILED, FALSE, TRUE.
dbus_int32_t _dbus_atomic_inc(DBusAtomic *atomic)
Atomically increments an integer.
atomic pointer to the integer to increment the value before incrementing
References DBusAtomic::value.
dbus_int32_t _dbus_atomic_dec(DBusAtomic *atomic)
Atomically decrement an integer.
atomic pointer to the integer to decrement the value before decrementing
References DBusAtomic::value.
dbus_int32_t _dbus_atomic_get(DBusAtomic *atomic)
Atomically get the value of an integer.
It may change at any time thereafter, so this is mostly only useful for assertions. atomic pointer to the integer to get the value at this moment
References DBusAtomic::value.
void _dbus_flush_caches(void)
Called when the bus daemon is signaled to reload its configuration; any caches should be nuked.
Of course any caches that need explicit reload are probably broken, but c'est la vie.
References _dbus_user_database_flush_system.
dbus_bool_t _dbus_get_is_errno_eagain_or_ewouldblock(int e)
See if errno is EAGAIN or EWOULDBLOCK (this has to be done differently for Winsock so is abstracted)
TRUE if e == EAGAIN or e == EWOULDBLOCK
References FALSE, NULL, TRUE, _dbus_file_exists, _dbus_string_append.
dbus_bool_t _dbus_get_install_root(char *prefix, int len)
return the absolute path of the dbus installation
prefix buffer for installation path len length of buffer FALSE on failure
dbus_bool_t _dbus_get_config_file_name(DBusString *config_file, char *s)
find config file either from installation or build root according to the following path layout install-root/ bin/dbus-daemon[d].exe etc/<config-file>.conf or etc/dbus-1/<config-file>.conf (the former above is what dbus4win uses, the latter above is what a "normal" Unix-style "make install" uses)
build-root/ bin/dbus-daemon[d].exe bus/<config-file>.conf
dbus_bool_t _dbus_lookup_session_address(dbus_bool_t *supported, DBusString *address, DBusError *error)
Determines the address of the session bus by querying a platform-specific method.
The first parameter will be a boolean specifying whether or not a dynamic session lookup is supported on this platform.If supported is TRUE and the return value is TRUE, the address will be appended to address. If a failure happens, returns FALSE and sets an error in error.If supported is FALSE, ignore the return value. supported returns whether this method is supported address a DBusString where the address can be stored error a DBusError to store the error in case of failure TRUE on success, FALSE if an error happened
References TRUE, FALSE.
dbus_bool_t _dbus_append_keyring_directory_for_credentials(DBusString *directory, DBusCredentials *credentials)
Appends the directory in which a keyring for the given credentials should be stored.
The credentials should have either a Windows or UNIX user in them. The directory should be an absolute path.On UNIX the directory is ~/.dbus-keyrings while on Windows it should probably be something else, since the dotfile convention is not normal on Windows. directory string to append directory to credentials credentials the directory should be for FALSE on no memory
References _dbus_assert, NULL, _dbus_credentials_are_anonymous, _dbus_string_init, FALSE, _dbus_credentials_get_unix_uid, DBUS_UID_UNSET, _dbus_homedir_from_uid, _dbus_getenv, _dbus_string_set_length, _dbus_string_append, _dbus_warn, TRUE, _dbus_string_init_const, _dbus_concat_dir_and_file, _dbus_string_copy, _dbus_string_free.
dbus_bool_t _dbus_file_exists(const char *file)
Checks if a file exists.
File interface. file full path to the file TRUE if file exists
References TRUE, FALSE, NULL, dbus_malloc, dbus_set_error, dbus_error_init, _dbus_warn, DBusError::message, dbus_error_free.
Referenced by _dbus_get_is_errno_eagain_or_ewouldblock.
const char* _dbus_strerror(int error_number)
A wrapper around strerror() because some platforms may be lame and not have strerror().
error_number errno. error description.
void _dbus_win_set_error_from_win_error(DBusError *error, int code)
Assigns an error name and message corresponding to a Win32 error code to a DBusError.
Does nothing if error is NULL. error the error. code the Win32 error code
void _dbus_win_warn_win_error(const char *message, unsigned long code)
dbus_bool_t _dbus_delete_directory(const DBusString *filename, DBusError *error)
Removes a directory; Directory must be empty.
filename directory filename error initialized error object TRUE on success
References dbus_set_error, DBUS_ERROR_FAILED, FALSE, TRUE.
dbus_bool_t _dbus_path_is_absolute(const DBusString *filename)
Checks whether the filename is an absolute path.
filename the filename TRUE if an absolute path
References FALSE.
dbus_bool_t _dbus_check_setuid(void)
NOTE: If you modify this function, please also consider making the corresponding change in GLib.
See glib/gutils.c:g_check_setuid().Returns TRUE if the current process was executed as setuid (or an equivalent __libc_enable_secure is available). See: http://osdir.com/ml/linux.lfs.hardened/2007-04/msg00032.html
References TRUE, FALSE.
int _dbus_save_socket_errno(void)
void _dbus_restore_socket_errno(int saved_errno)