dbus-marshal-recursive.c
RECURSIVE_MARSHAL_READ_TRACE
turn this on to get deluged in TypeReader verbose spam
RECURSIVE_MARSHAL_WRITE_TRACE
turn this on to get deluged in TypeWriter verbose spam
ARRAY_READER_LEN_POS
compute position of array length given array_len_offset, which is the offset back from start_pos to end of the len
Referenced by _dbus_type_writer_write_fixed_multi.
const DBusTypeReaderClass body_reader_class
const DBusTypeReaderClass body_types_only_reader_class
const DBusTypeReaderClass struct_reader_class
const DBusTypeReaderClass struct_types_only_reader_class
const DBusTypeReaderClass dict_entry_reader_class
const DBusTypeReaderClass dict_entry_types_only_reader_class
const DBusTypeReaderClass array_reader_class
const DBusTypeReaderClass array_types_only_reader_class
const DBusTypeReaderClass variant_reader_class
const DBusTypeReaderClass* const all_reader_classes[][]
static dbus_bool_t _dbus_type_reader_greater_than(const DBusTypeReader *lhs, const DBusTypeReader *rhs)
static void _dbus_type_writer_set_enabled(DBusTypeWriter *writer, dbus_bool_t enabled)
static dbus_bool_t _dbus_type_writer_write_reader_partial(DBusTypeWriter *writer, DBusTypeReader *reader, const DBusTypeReader *start_after, int start_after_new_pos, int start_after_new_len, DBusList **fixups)
static void free_fixups(DBusList **fixups)
static void apply_and_free_fixups(DBusList **fixups, DBusTypeReader *reader)
static int element_type_get_alignment(const DBusString *str, int pos)
static void reader_init(DBusTypeReader *reader, int byte_order, const DBusString *type_str, int type_pos, const DBusString *value_str, int value_pos)
static void base_reader_recurse(DBusTypeReader *sub, DBusTypeReader *parent)
static void struct_or_dict_entry_types_only_reader_recurse(DBusTypeReader *sub, DBusTypeReader *parent)
static void struct_or_dict_entry_reader_recurse(DBusTypeReader *sub, DBusTypeReader *parent)
static void array_types_only_reader_recurse(DBusTypeReader *sub, DBusTypeReader *parent)
static int array_reader_get_array_len(const DBusTypeReader *reader)
static void array_reader_recurse(DBusTypeReader *sub, DBusTypeReader *parent)
static void variant_reader_recurse(DBusTypeReader *sub, DBusTypeReader *parent)
static dbus_bool_t array_reader_check_finished(const DBusTypeReader *reader)
static void skip_one_complete_type(const DBusString *type_str, int *type_pos)
void _dbus_type_signature_next(const char *type_str, int *type_pos)
Skips to the next "complete" type inside a type signature.
The signature is read starting at type_pos, and the next type position is stored in the same variable. type_str a type signature (must be valid) type_pos an integer position in the type signature (in and out)
References _dbus_assert, _dbus_first_type_in_signature, _dbus_marshal_skip_array, _dbus_marshal_skip_basic, _dbus_type_reader_next, _dbus_type_reader_recurse, _dbus_type_to_string, DBusTypeReader::byte_order, DBUS_DICT_ENTRY_BEGIN_CHAR, DBUS_DICT_ENTRY_END_CHAR, DBUS_STRUCT_BEGIN_CHAR, DBUS_STRUCT_END_CHAR, DBUS_TYPE_ARRAY, DBUS_TYPE_DICT_ENTRY, DBUS_TYPE_INVALID, DBUS_TYPE_STRUCT, DBUS_TYPE_VARIANT, FALSE, DBusTypeReader::finished, DBusTypeReader::klass, NULL, TRUE, DBusTypeReader::type_pos, DBusTypeReader::type_str, DBusTypeReaderClass::types_only, DBusTypeReader::u, DBusTypeReader::value_pos, DBusTypeReader::value_str.
Referenced by dbus_signature_iter_get_signature, dbus_signature_iter_next.
static int find_len_of_complete_type(const DBusString *type_str, int type_pos)
static void base_reader_next(DBusTypeReader *reader, int current_type)
static void struct_reader_next(DBusTypeReader *reader, int current_type)
static void dict_entry_reader_next(DBusTypeReader *reader, int current_type)
static void array_types_only_reader_next(DBusTypeReader *reader, int current_type)
static void array_reader_next(DBusTypeReader *reader, int current_type)
void _dbus_type_reader_init(DBusTypeReader *reader, int byte_order, const DBusString *type_str, int type_pos, const DBusString *value_str, int value_pos)
Initializes a type reader.
reader the reader byte_order the byte order of the block to read type_str the signature of the block to read type_pos location of signature value_str the string containing values block value_pos start of values block
References DBusTypeReader::klass, DBusTypeReader::type_pos, DBusTypeReader::type_str, DBusTypeReader::value_pos.
Referenced by _dbus_header_get_byte_order, _dbus_header_load, _dbus_header_update_lengths, dbus_message_iter_init.
void _dbus_type_reader_init_types_only(DBusTypeReader *reader, const DBusString *type_str, int type_pos)
Like _dbus_type_reader_init() but the iteration is over the signature, not over values.
reader the reader type_str the signature string type_pos location in the signature string
References _DBUS_INT_MAX, DBusTypeReader::klass, NULL, DBusTypeReader::type_pos, DBusTypeReader::type_str.
Referenced by _dbus_marshal_byteswap, _dbus_validate_body_with_reason, _dbus_validate_signature_with_reason.
int _dbus_type_reader_get_current_type(const DBusTypeReader *reader)
Gets the type of the value the reader is currently pointing to; or for a types-only reader gets the type it's currently pointing to.
If the reader is at the end of a block or end of a container such as an array, returns DBUS_TYPE_INVALID. reader the reader
References _dbus_assert, _dbus_first_type_in_signature, _dbus_type_to_string, DBusTypeReaderClass::check_finished, DBUS_DICT_ENTRY_BEGIN_CHAR, DBUS_DICT_ENTRY_END_CHAR, DBUS_STRUCT_BEGIN_CHAR, DBUS_STRUCT_END_CHAR, DBUS_TYPE_INVALID, DBusTypeReader::finished, DBusTypeReader::klass, DBusTypeReader::type_pos, DBusTypeReader::type_str.
Referenced by _dbus_header_get_byte_order, _dbus_header_have_message_untrusted, _dbus_header_load, _dbus_header_update_lengths, _dbus_message_iter_get_args_valist, _dbus_type_reader_get_element_type, _dbus_type_reader_next, _dbus_type_reader_read_basic, _dbus_type_reader_set_basic, _dbus_type_writer_write_fixed_multi, _dbus_validate_signature_with_reason, dbus_message_iter_get_arg_type, dbus_message_iter_get_fixed_array, dbus_message_iter_init.
int _dbus_type_reader_get_element_type(const DBusTypeReader *reader)
Gets the type of an element of the array the reader is currently pointing to.
It's an error to call this if _dbus_type_reader_get_current_type() doesn't return DBUS_TYPE_ARRAY for this reader. reader the reader
References _dbus_assert, _dbus_first_type_in_signature, _dbus_type_reader_get_current_type, DBUS_TYPE_ARRAY, DBusTypeReader::type_pos, DBusTypeReader::type_str.
Referenced by _dbus_message_iter_get_args_valist, _dbus_validate_signature_with_reason, dbus_message_iter_get_element_type.
int _dbus_type_reader_get_value_pos(const DBusTypeReader *reader)
Gets the current position in the value block.
reader the reader
References DBusTypeReader::value_pos.
Referenced by _dbus_header_load.
void _dbus_type_reader_read_raw(const DBusTypeReader *reader, const unsigned char **value_location)
Get the address of the marshaled value in the data being read.
The address may not be aligned; you have to align it to the type of the value you want to read. Most of the demarshal routines do this for you. reader the reader value_location the address of the marshaled value
References _dbus_assert, DBusTypeReader::klass, DBusTypeReaderClass::types_only, DBusTypeReader::value_pos, DBusTypeReader::value_str.
void _dbus_type_reader_read_basic(const DBusTypeReader *reader, void *value)
Reads a basic-typed value, as with _dbus_marshal_read_basic().
reader the reader value the address of the value
References _dbus_assert, _dbus_marshal_read_basic, _dbus_type_reader_get_current_type, DBusTypeReader::byte_order, DBusTypeReader::klass, NULL, DBusTypeReader::type_pos, DBusTypeReader::type_str, DBusTypeReaderClass::types_only, DBusTypeReader::value_pos, DBusTypeReader::value_str.
Referenced by _dbus_header_get_byte_order, _dbus_header_load, _dbus_header_update_lengths, _dbus_message_iter_get_args_valist, _dbus_type_writer_write_fixed_multi, dbus_message_iter_get_basic.
int _dbus_type_reader_get_array_length(const DBusTypeReader *reader)
Returns the number of bytes in the array.
reader the reader to read from the number of bytes in the array
References _dbus_assert, DBusTypeReader::klass, DBusTypeReaderClass::types_only.
Referenced by dbus_message_iter_get_array_len.
void _dbus_type_reader_read_fixed_multi(const DBusTypeReader *reader, void *value, int *n_elements)
Reads a block of fixed-length basic values, from the current point in an array to the end of the array.
Does not work for arrays of string or container types.This function returns the array in-place; it does not make a copy, and it does not swap the bytes.If you ask for DBUS_TYPE_DOUBLE you will get a "const double*" back and the "value" argument should be a "const double**" and so on. reader the reader to read from value place to return the array values n_elements place to return number of array elements
References _dbus_assert, _dbus_first_type_in_signature, _dbus_type_get_alignment, DBUS_TYPE_INVALID, dbus_type_is_fixed, DBusTypeReader::klass, NULL, DBusTypeReader::type_pos, DBusTypeReader::type_str, DBusTypeReaderClass::types_only, DBusTypeReader::u, DBusTypeReader::value_pos, DBusTypeReader::value_str.
Referenced by _dbus_message_iter_get_args_valist, dbus_message_iter_get_fixed_array.
void _dbus_type_reader_recurse(DBusTypeReader *reader, DBusTypeReader *sub)
Initialize a new reader pointing to the first type and corresponding value that's a child of the current container.
It's an error to call this if the current type is a non-container.Note that DBusTypeReader traverses values, not types. So if you have an empty array of array of int, you can't recurse into it. You can only recurse into each element. reader the reader sub a reader to init pointing to the first child
References _dbus_assert, _dbus_assert_not_reached, _dbus_first_type_in_signature, _dbus_type_to_string, _dbus_warn_check_failed, DBUS_TYPE_ARRAY, DBUS_TYPE_DICT_ENTRY, DBUS_TYPE_INVALID, DBUS_TYPE_STRUCT, DBUS_TYPE_VARIANT, DBusTypeReaderClass::id, DBusTypeReader::klass, DBusTypeReaderClass::recurse, DBusTypeReader::type_pos, DBusTypeReader::type_str, DBusTypeReaderClass::types_only, DBusTypeReader::value_pos.
Referenced by _dbus_header_get_byte_order, _dbus_header_load, _dbus_header_update_lengths, _dbus_message_iter_get_args_valist, _dbus_type_signature_next, _dbus_type_writer_write_fixed_multi, _dbus_validate_signature_with_reason, dbus_message_iter_recurse.
dbus_bool_t _dbus_type_reader_next(DBusTypeReader *reader)
Skip to the next value on this "level".
e.g. the next field in a struct, the next value in an array. Returns FALSE at the end of the current container. reader the reader FALSE if nothing more to read at or below this level
References _dbus_type_reader_get_current_type, _dbus_type_to_string, DBUS_TYPE_INVALID, FALSE, DBusTypeReader::klass, DBusTypeReaderClass::next, DBusTypeReader::type_pos, DBusTypeReader::type_str, DBusTypeReader::value_pos.
Referenced by _dbus_header_get_byte_order, _dbus_header_load, _dbus_header_update_lengths, _dbus_message_iter_get_args_valist, _dbus_type_reader_has_next, _dbus_type_signature_next, _dbus_type_writer_write_fixed_multi, _dbus_validate_signature_with_reason, dbus_message_iter_next.
dbus_bool_t _dbus_type_reader_has_next(const DBusTypeReader *reader)
Check whether there's another value on this "level".
e.g. the next field in a struct, the next value in an array. Returns FALSE at the end of the current container.You probably don't want to use this; it makes for an awkward for/while loop. A nicer one is "while ((current_type = get_current_type()) != INVALID)" reader the reader FALSE if nothing more to read at or below this level
References _dbus_type_reader_next.
Referenced by dbus_message_iter_has_next.
void _dbus_type_reader_get_signature(const DBusTypeReader *reader, const DBusString **str_p, int *start_p, int *len_p)
Gets the string and range of said string containing the signature of the current value.
Essentially a more complete version of _dbus_type_reader_get_current_type() (returns the full type rather than only the outside of the onion).Note though that the first byte in a struct signature is DBUS_STRUCT_BEGIN_CHAR while the current type will be DBUS_TYPE_STRUCT so it isn't true that the first byte of the signature is always the same as the current type. Another difference is that this function will still return a signature when inside an empty array; say you recurse into empty array of int32, the signature is "i" but the current type will always be DBUS_TYPE_INVALID since there are no elements to be currently pointing to. reader the reader str_p place to return the string with the type in it start_p place to return start of the type len_p place to return the length of the type
References DBusTypeReader::type_pos, DBusTypeReader::type_str.
Referenced by _dbus_type_writer_write_fixed_multi, dbus_message_iter_get_signature.
static dbus_bool_t replacement_block_init(ReplacementBlock *block, DBusTypeReader *reader)
static dbus_bool_t replacement_block_replace(ReplacementBlock *block, DBusTypeReader *reader, const DBusTypeReader *realign_root)
static void replacement_block_free(ReplacementBlock *block)
static dbus_bool_t reader_set_basic_variable_length(DBusTypeReader *reader, int current_type, const void *value, const DBusTypeReader *realign_root)
static void reader_set_basic_fixed_length(DBusTypeReader *reader, int current_type, const void *value)
dbus_bool_t _dbus_type_reader_set_basic(DBusTypeReader *reader, const void *value, const DBusTypeReader *realign_root)
Sets a new value for the basic type value pointed to by the reader, leaving the reader valid to continue reading.
Any other readers will be invalidated if you set a variable-length type such as a string.The provided realign_root is the reader to start from when realigning the data that follows the newly-set value. The reader parameter must point to a value below the realign_root parameter. If the type being set is fixed-length, then realign_root may be NULL. Only values reachable from realign_root will be realigned, so if your string contains other values you will need to deal with those somehow yourself. It is OK if realign_root is the same reader as the reader parameter, though if you aren't setting the root it may not be such a good idea.TodoDBusTypeReader currently takes "const" versions of the type and value strings, and this function modifies those strings by casting away the const, which is of course bad if we want to get picky. (To be truly clean you'd have an object which contained the type and value strings and set_basic would be a method on that object... this would also make DBusTypeReader the same thing as DBusTypeMark. But since DBusMessage is effectively that object for D-Bus it doesn't seem worth creating some random object.)Todooptimize this by only rewriting until the old and new values are at the same alignment. Frequently this should result in only replacing the value that's immediately at hand. reader reader indicating where to set a new value value address of the value to set realign_root realign from here FALSE if not enough memory
References _dbus_assert, _dbus_type_reader_get_current_type, _dbus_type_to_string, _dbus_verbose_bytes_of_string, dbus_type_is_basic, dbus_type_is_fixed, DBusTypeReader::klass, NULL, TRUE, DBusTypeReader::type_pos, DBusTypeReader::type_str, DBusTypeReaderClass::types_only, DBusTypeReader::value_pos, DBusTypeReader::value_str.
Referenced by _dbus_header_get_byte_order.
dbus_bool_t _dbus_type_reader_delete(DBusTypeReader *reader, const DBusTypeReader *realign_root)
Recursively deletes any value pointed to by the reader, leaving the reader valid to continue reading.
Any other readers will be invalidated.The provided realign_root is the reader to start from when realigning the data that follows the newly-set value. See _dbus_type_reader_set_basic() for more details on the realign_root paramter.Todofor now this does not delete the typecodes associated with the value, so this function should only be used for array elements. reader reader indicating where to delete a value realign_root realign from here FALSE if not enough memory
References _dbus_assert, FALSE, DBusTypeReader::klass, NULL, TRUE, DBusTypeReader::value_pos, DBusTypeReader::value_str.
Referenced by _dbus_header_delete_field.
void _dbus_type_writer_init(DBusTypeWriter *writer, int byte_order, DBusString *type_str, int type_pos, DBusString *value_str, int value_pos)
Initialize a write iterator, which is used to write out values in serialized D-Bus format.
The type_pos passed in is expected to be inside an already-valid, though potentially empty, type signature. This means that the byte after type_pos must be either DBUS_TYPE_INVALID (aka nul) or some other valid type. DBusTypeWriter won't enforce that the signature is already valid (you can append the nul byte at the end if you like), but just be aware that you need the nul byte eventually and DBusTypeWriter isn't going to write it for you. writer the writer to init byte_order the byte order to marshal into type_str the string to write typecodes into type_pos where to insert typecodes value_str the string to write values into value_pos where to insert values
References DBusTypeWriter::byte_order, DBusTypeWriter::container_type, DBUS_TYPE_INVALID, DBusTypeWriter::enabled, FALSE, TRUE, DBusTypeWriter::type_pos, DBusTypeWriter::type_pos_is_expectation, DBusTypeWriter::type_str, DBusTypeWriter::value_pos, DBusTypeWriter::value_str.
Referenced by _dbus_type_writer_init_types_delayed, _dbus_type_writer_init_values_only.
void _dbus_type_writer_init_types_delayed(DBusTypeWriter *writer, int byte_order, DBusString *value_str, int value_pos)
Initialize a write iterator, with the signature to be provided later.
writer the writer to init byte_order the byte order to marshal into value_str the string to write values into value_pos where to insert values
References _dbus_type_writer_init, NULL.
Referenced by dbus_message_iter_init_append.
void _dbus_type_writer_add_types(DBusTypeWriter *writer, DBusString *type_str, int type_pos)
Adds type string to the writer, if it had none.
writer the writer to init type_str type string to add type_pos type position
References NULL, DBusTypeWriter::type_pos, DBusTypeWriter::type_str.
Referenced by dbus_message_iter_init_append.
void _dbus_type_writer_remove_types(DBusTypeWriter *writer)
Removes type string from the writer.
writer the writer to remove from
References NULL, DBusTypeWriter::type_pos, DBusTypeWriter::type_str.
Referenced by dbus_message_iter_init_append.
void _dbus_type_writer_init_values_only(DBusTypeWriter *writer, int byte_order, const DBusString *type_str, int type_pos, DBusString *value_str, int value_pos)
Like _dbus_type_writer_init(), except the type string passed in should correspond to an existing signature that matches what you're going to write out.
The writer will check what you write vs. this existing signature. writer the writer to init byte_order the byte order to marshal into type_str the string with signature type_pos start of signature value_str the string to write values into value_pos where to insert values
References _dbus_assert, _dbus_assert_not_reached, _dbus_first_type_in_signature, _dbus_marshal_write_basic, _dbus_string_alloc_space, _dbus_string_copy_len, _dbus_string_equal_substring, _dbus_string_insert_byte, _dbus_string_insert_bytes, _dbus_type_get_alignment, _dbus_type_to_string, _dbus_type_writer_init, _dbus_unpack_uint32, _dbus_warn_check_failed, DBusTypeWriter::byte_order, DBusTypeWriter::container_type, DBUS_DICT_ENTRY_BEGIN_CHAR, DBUS_STRUCT_BEGIN_CHAR, DBUS_TYPE_ARRAY, DBUS_TYPE_DICT_ENTRY, DBUS_TYPE_INVALID, DBUS_TYPE_STRUCT, DBUS_TYPE_UINT32, DBUS_TYPE_VARIANT, DBusTypeWriter::enabled, FALSE, NULL, TRUE, DBusTypeWriter::type_pos, DBusTypeWriter::type_pos_is_expectation, DBusTypeWriter::type_str, DBusTypeWriter::u, DBusTypeWriter::value_pos, DBusTypeWriter::value_str.
Referenced by _dbus_header_create, _dbus_header_set_field_basic.
static dbus_bool_t _dbus_type_writer_write_basic_no_typecode(DBusTypeWriter *writer, int type, const void *value)
static void writer_recurse_init_and_check(DBusTypeWriter *writer, int container_type, DBusTypeWriter *sub)
static dbus_bool_t write_or_verify_typecode(DBusTypeWriter *writer, int typecode)
static dbus_bool_t writer_recurse_struct_or_dict_entry(DBusTypeWriter *writer, int begin_char, const DBusString *contained_type, int contained_type_start, int contained_type_len, DBusTypeWriter *sub)
static dbus_bool_t writer_recurse_array(DBusTypeWriter *writer, const DBusString *contained_type, int contained_type_start, int contained_type_len, DBusTypeWriter *sub, dbus_bool_t is_array_append)
static dbus_bool_t writer_recurse_variant(DBusTypeWriter *writer, const DBusString *contained_type, int contained_type_start, int contained_type_len, DBusTypeWriter *sub)
static dbus_bool_t _dbus_type_writer_recurse_contained_len(DBusTypeWriter *writer, int container_type, const DBusString *contained_type, int contained_type_start, int contained_type_len, DBusTypeWriter *sub, dbus_bool_t is_array_append)
dbus_bool_t _dbus_type_writer_recurse(DBusTypeWriter *writer, int container_type, const DBusString *contained_type, int contained_type_start, DBusTypeWriter *sub)
Opens a new container and writes out the initial information for that container.
writer the writer container_type the type of the container to open contained_type the array element type or variant content type contained_type_start position to look for the type sub the new sub-writer to write container contents FALSE if no memory
References FALSE.
Referenced by _dbus_header_create, _dbus_header_get_byte_order, dbus_message_iter_open_container.
dbus_bool_t _dbus_type_writer_append_array(DBusTypeWriter *writer, const DBusString *contained_type, int contained_type_start, DBusTypeWriter *sub)
Append to an existing array.
Essentially, the writer will read an existing length at the write location; jump over that length; and write new fields. On unrecurse(), the existing length will be updated. writer the writer contained_type element type contained_type_start position of element type sub the subwriter to init FALSE if no memory
References _dbus_assert, DBusTypeWriter::container_type, DBUS_TYPE_ARRAY, TRUE, DBusTypeWriter::u, DBusTypeWriter::value_pos.
Referenced by _dbus_header_set_field_basic.
static int writer_get_array_len(DBusTypeWriter *writer)
dbus_bool_t _dbus_type_writer_unrecurse(DBusTypeWriter *writer, DBusTypeWriter *sub)
Closes a container created by _dbus_type_writer_recurse() and writes any additional information to the values block.
writer the writer sub the sub-writer created by _dbus_type_writer_recurse() FALSE if no memory
References _dbus_assert, _dbus_marshal_set_uint32, _dbus_type_to_string, DBusTypeWriter::byte_order, DBusTypeWriter::container_type, DBUS_DICT_ENTRY_END_CHAR, DBUS_STRUCT_END_CHAR, DBUS_TYPE_ARRAY, DBUS_TYPE_DICT_ENTRY, DBUS_TYPE_INVALID, DBUS_TYPE_STRUCT, FALSE, NULL, TRUE, DBusTypeWriter::type_pos, DBusTypeWriter::type_pos_is_expectation, DBusTypeWriter::type_str, DBusTypeWriter::u, DBusTypeWriter::value_pos, DBusTypeWriter::value_str.
Referenced by _dbus_header_create, _dbus_header_get_byte_order, _dbus_header_set_field_basic, _dbus_type_writer_write_fixed_multi, dbus_message_iter_close_container.
dbus_bool_t _dbus_type_writer_write_basic(DBusTypeWriter *writer, int type, const void *value)
Writes out a basic type.
writer the writer type the type to write value the address of the value to write FALSE if no memory
References _dbus_assert_not_reached, _dbus_string_alloc_space, DBusTypeWriter::enabled, FALSE, NULL, TRUE, DBusTypeWriter::type_pos, DBusTypeWriter::type_pos_is_expectation, DBusTypeWriter::type_str, DBusTypeWriter::value_pos.
Referenced by _dbus_header_create, _dbus_header_get_byte_order, _dbus_type_writer_write_fixed_multi, dbus_message_iter_append_basic.
dbus_bool_t _dbus_type_writer_write_fixed_multi(DBusTypeWriter *writer, int element_type, const void *value, int n_elements)
Writes a block of fixed-length basic values, i.e.
those that are both dbus_type_is_fixed() and _dbus_type_is_basic(). The block must be written inside an array.The value parameter should be the address of said array of values, so e.g. if it's an array of double, pass in "const double**" writer the writer element_type type of stuff in the array value address of the array n_elements number of elements in the array FALSE if no memory
References _dbus_assert, _dbus_assert_not_reached, _dbus_list_append, _dbus_marshal_write_fixed_multi, _dbus_string_delete, _dbus_type_reader_get_current_type, _dbus_type_reader_get_signature, _dbus_type_reader_next, _dbus_type_reader_read_basic, _dbus_type_reader_recurse, _dbus_type_to_string, _dbus_type_writer_unrecurse, _dbus_type_writer_write_basic, _dbus_unpack_uint32, ARRAY_READER_LEN_POS, DBusTypeReader::byte_order, DBusTypeWriter::byte_order, DBusTypeWriter::container_type, dbus_free, dbus_new, DBUS_TYPE_ARRAY, DBUS_TYPE_INVALID, dbus_type_is_basic, dbus_type_is_container, dbus_type_is_fixed, DBusTypeWriter::enabled, FALSE, DBusArrayLenFixup::len_pos_in_reader, DBusArrayLenFixup::new_len, NULL, TRUE, DBusTypeReader::type_pos, DBusTypeWriter::type_pos, DBusTypeWriter::type_pos_is_expectation, DBusTypeReader::type_str, DBusTypeWriter::type_str, DBusTypeReader::u, DBusTypeReader::value_pos, DBusTypeWriter::value_pos, DBusTypeReader::value_str, DBusTypeWriter::value_str.
Referenced by dbus_message_iter_append_fixed_array.
static void enable_if_after(DBusTypeWriter *writer, DBusTypeReader *reader, const DBusTypeReader *start_after)
static dbus_bool_t append_fixup(DBusList **fixups, const DBusArrayLenFixup *fixup)
static dbus_bool_t writer_write_reader_helper(DBusTypeWriter *writer, DBusTypeReader *reader, const DBusTypeReader *start_after, int start_after_new_pos, int start_after_new_len, DBusList **fixups, dbus_bool_t inside_start_after)
dbus_bool_t _dbus_type_writer_write_reader(DBusTypeWriter *writer, DBusTypeReader *reader)
Iterate through all values in the given reader, writing a copy of each value to the writer.
The reader will be moved forward to its end position. writer the writer to copy to reader the reader to copy from FALSE if no memory
References DBusTypeWriter::enabled, FALSE, NULL.