dbus-object-tree.h
typedef struct DBusObjectTree DBusObjectTree
DBusObjectTree* _dbus_object_tree_new(DBusConnection *connection)
Creates a new object tree, representing a mapping from paths to handler vtables.
connection the connection this tree belongs to the new tree or NULL if no memory
References dbus_new0, NULL, DBusObjectTree::refcount, DBusObjectTree::connection, DBusObjectTree::root, DBusObjectSubtree::invoke_as_fallback, TRUE, dbus_free.
Referenced by _dbus_connection_new_for_transport, _dbus_decompose_path.
DBusObjectTree* _dbus_object_tree_ref(DBusObjectTree *tree)
Increment the reference count.
tree the object tree the object tree
References _dbus_assert, DBusObjectTree::refcount.
Referenced by _dbus_decompose_path.
void _dbus_object_tree_unref(DBusObjectTree *tree)
Decrement the reference count.
tree the object tree
References _dbus_assert, DBusObjectTree::refcount, _dbus_object_tree_free_all_unlocked, dbus_free.
Referenced by _dbus_connection_new_for_transport, dbus_connection_ref, _dbus_decompose_path.
dbus_bool_t _dbus_object_tree_register(DBusObjectTree *tree, dbus_bool_t fallback, const char **path, const DBusObjectPathVTable *vtable, void *user_data, DBusError *error)
Registers a new subtree in the global object tree.
tree the global object tree fallback TRUE to handle messages to children of this path path NULL-terminated array of path elements giving path to subtree vtable the vtable used to traverse this subtree user_data user data to pass to methods in the vtable error address where an error can be returned FALSE if an error (DBUS_ERROR_NO_MEMORY or DBUS_ERROR_OBJECT_PATH_IN_USE) is reported
References _dbus_assert, NULL, DBusObjectPathVTable::message_function, FALSE, DBusObjectSubtree::message_function, dbus_set_error, DBUS_ERROR_OBJECT_PATH_IN_USE, dbus_free, DBusObjectSubtree::unregister_function, DBusObjectPathVTable::unregister_function, DBusObjectSubtree::user_data, DBusObjectSubtree::invoke_as_fallback, TRUE, DBusObjectSubtree::parent, DBusObjectSubtree::n_subtrees, DBusObjectSubtree::subtrees, DBusObjectSubtree::name.
Referenced by dbus_connection_remove_filter, _dbus_decompose_path.
void _dbus_object_tree_unregister_and_unlock(DBusObjectTree *tree, const char **path)
Unregisters an object subtree that was registered with the same path.
tree the global object tree path path to the subtree (same as the one passed to _dbus_object_tree_register())
References DBusObjectTree::connection, _dbus_assert, NULL, TRUE, DBusObjectTree::root, FALSE, _dbus_warn, _dbus_connection_ref_unlocked, _dbus_connection_unlock, dbus_connection_unref, DBusObjectSubtree::n_subtrees, DBusObjectSubtree::subtrees, DBusObjectSubtree::parent, DBusObjectSubtree::unregister_function, DBusObjectSubtree::user_data, DBusObjectSubtree::message_function.
Referenced by dbus_connection_unregister_object_path, _dbus_decompose_path.
DBusHandlerResult _dbus_object_tree_dispatch_and_unlock(DBusObjectTree *tree, DBusMessage *message, dbus_bool_t *found_object)
Tries to dispatch a message by directing it to handler for the object path listed in the message header, if any.
Messages are dispatched first to the registered handler that matches the largest number of path elements; that is, message to /foo/bar/baz would go to the handler for /foo/bar before the one for /foo.Todothread problems tree the global object tree message the message to dispatch found_object return location for the object whether message was handled successfully
References NULL, dbus_message_get_path_decomposed, DBusObjectTree::connection, _dbus_connection_unlock, DBUS_HANDLER_RESULT_NEED_MEMORY, DBUS_HANDLER_RESULT_NOT_YET_HANDLED, DBusObjectSubtree::message_function, DBusObjectSubtree::invoke_as_fallback, _dbus_list_append, FALSE, DBusObjectSubtree::parent, _dbus_list_get_length, _dbus_list_get_first_link, _dbus_list_get_next_link, DBusList::data, DBusObjectSubtree::user_data, _dbus_connection_lock, _dbus_list_remove_link, dbus_free_string_array.
Referenced by dbus_connection_dispatch, _dbus_decompose_path.
void* _dbus_object_tree_get_user_data_unlocked(DBusObjectTree *tree, const char **path)
Looks up the data passed to _dbus_object_tree_register() for a handler at the given path.
tree the global object tree path NULL-terminated array of path elements giving path to subtree the object's user_data or NULL if none found
References _dbus_assert, NULL, DBusObjectSubtree::user_data, dbus_malloc0, DBusObjectSubtree::name, DBusObjectSubtree::parent, DBusObjectSubtree::message_function, DBusObjectPathVTable::message_function, DBusObjectSubtree::unregister_function, DBusObjectPathVTable::unregister_function, _dbus_atomic_inc, DBusObjectSubtree::refcount, DBusObjectSubtree::subtrees, DBusObjectSubtree::n_subtrees, DBusObjectSubtree::max_subtrees, DBusObjectSubtree::invoke_as_fallback, FALSE, _dbus_atomic_dec, dbus_free.
Referenced by dbus_connection_get_object_path_data, _dbus_decompose_path.
void _dbus_object_tree_free_all_unlocked(DBusObjectTree *tree)
Free all the handlers in the tree.
Lock on tree's connection must not be held. tree the object tree
References DBusObjectTree::root, DBusObjectTree::connection, NULL, _dbus_assert, dbus_new0, DBusObjectSubtree::n_subtrees, _dbus_strdup, DBusObjectSubtree::subtrees, DBusObjectSubtree::name, dbus_free_string_array, FALSE, dbus_message_is_method_call, DBUS_INTERFACE_INTROSPECTABLE, _dbus_connection_unlock, DBUS_HANDLER_RESULT_NOT_YET_HANDLED, _dbus_string_init, DBUS_HANDLER_RESULT_NEED_MEMORY, _dbus_string_append, DBUS_INTROSPECT_1_0_XML_DOCTYPE_DECL_NODE, _dbus_string_append_printf, dbus_message_new_method_return, dbus_message_iter_init_append, dbus_message_iter_append_basic, DBUS_TYPE_STRING, TRUE, _dbus_connection_send_and_unlock, DBUS_HANDLER_RESULT_HANDLED, _dbus_string_free, dbus_message_unref.
Referenced by dbus_connection_ref, _dbus_object_tree_unref.
dbus_bool_t _dbus_object_tree_list_registered_and_unlock(DBusObjectTree *tree, const char **parent_path, char ***child_entries)
Lists the registered fallback handlers and object path handlers at the given parent_path.
The returned array should be freed with dbus_free_string_array(). tree the object tree parent_path the path to list the child handlers of child_entries returns NULL-terminated array of children FALSE if no memory to allocate the child entries
References DBusObjectTree::connection, _dbus_connection_unlock.
Referenced by dbus_connection_list_registered.
dbus_bool_t _dbus_decompose_path(const char *data, int len, char ***path, int *path_len)
Decompose an object path.
A path of just "/" is represented as an empty vector of strings. The path need not be nul terminated. data the path data len the length of the path string path address to store new object path path_len length of stored path
References _dbus_assert, NULL, dbus_new0, FALSE, _dbus_memdup, dbus_free_string_array, TRUE, _dbus_string_init, _dbus_string_append_byte, _dbus_string_append, _dbus_string_steal_data, _dbus_string_free, DBusObjectSubtree::name, DBusObjectSubtree::n_subtrees, DBusObjectSubtree::subtrees, DBusObjectTree::root, DBUS_HANDLER_RESULT_NOT_YET_HANDLED, _dbus_object_tree_register, _dbus_object_tree_get_user_data_unlocked, dbus_message_new_method_call, dbus_free, _dbus_object_tree_dispatch_and_unlock, DBUS_HANDLER_RESULT_NEED_MEMORY, dbus_message_unref, _DBUS_N_ELEMENTS, _dbus_decompose_path, _dbus_warn, _dbus_assert_not_reached, _dbus_object_tree_new, _dbus_object_tree_unref, _dbus_object_tree_unregister_and_unlock, _dbus_object_tree_ref.
Referenced by dbus_connection_remove_filter, dbus_connection_unregister_object_path, dbus_connection_get_object_path_data, dbus_connection_list_registered, dbus_message_get_path_decomposed, _dbus_decompose_path.