dbus-userdb.h
typedef struct DBusUserDatabase DBusUserDatabase
DBusUserDatabase* _dbus_user_database_get_system(void)
Gets the system global user database; must be called with lock held (_dbus_user_database_lock_system()).
the database or NULL if no memory
References _dbus_assert.
Referenced by _dbus_is_console_user, _dbus_get_group_id, _dbus_get_user_id_and_primary_group, _dbus_groups_from_uid, _dbus_homedir_from_username, _dbus_homedir_from_uid, _dbus_credentials_add_from_user.
dbus_bool_t _dbus_user_database_lock_system(void) _DBUS_GNUC_WARN_UNUSED_RESULT
Locks global system user database.
References _DBUS_LOCK, TRUE, FALSE.
Referenced by _dbus_is_console_user, _dbus_get_group_id, _dbus_get_user_id_and_primary_group, _dbus_groups_from_uid, _dbus_user_database_flush_system, _dbus_username_from_current_process, _dbus_homedir_from_current_process, _dbus_homedir_from_username, _dbus_homedir_from_uid, _dbus_credentials_add_from_user.
void _dbus_user_database_unlock_system(void)
Unlocks global system user database.
References FALSE, _DBUS_UNLOCK.
Referenced by _dbus_is_console_user, _dbus_get_group_id, _dbus_get_user_id_and_primary_group, _dbus_groups_from_uid, _dbus_user_database_flush_system, _dbus_username_from_current_process, _dbus_homedir_from_current_process, _dbus_homedir_from_username, _dbus_homedir_from_uid, _dbus_credentials_add_from_user.
void _dbus_user_database_flush_system(void)
Flushes the system global user database;.
References _dbus_user_database_lock_system, NULL, _dbus_user_database_flush, _dbus_user_database_unlock_system.
Referenced by _dbus_flush_caches.
dbus_bool_t _dbus_get_user_id(const DBusString *username, dbus_uid_t *uid)
Gets user ID given username.
username the username uid return location for UID TRUE if username existed and we got the UID
References _dbus_get_user_id_and_primary_group, NULL.
Referenced by _dbus_parse_unix_user_from_config, _dbus_groups_from_uid.
dbus_bool_t _dbus_get_group_id(const DBusString *group_name, dbus_gid_t *gid)
Gets group ID given groupname.
groupname the groupname gid return location for GID TRUE if group name existed and we got the GID
References _dbus_user_database_lock_system, FALSE, _dbus_user_database_get_system, NULL, _dbus_user_database_unlock_system, _dbus_user_database_get_groupname, DBusGroupInfo::gid, TRUE.
Referenced by _dbus_parse_unix_group_from_config.
dbus_bool_t _dbus_get_user_id_and_primary_group(const DBusString *username, dbus_uid_t *uid_p, dbus_gid_t *gid_p)
Gets user ID and primary group given username.
username the username uid_p return location for UID gid_p return location for GID TRUE if username existed and we got the UID and GID
References _dbus_user_database_lock_system, FALSE, _dbus_user_database_get_system, NULL, _dbus_user_database_unlock_system, _dbus_user_database_get_username, DBusUserInfo::uid, DBusUserInfo::primary_gid, TRUE.
Referenced by _dbus_verify_daemon_user, _dbus_change_to_daemon_user, _dbus_get_user_id.
dbus_bool_t _dbus_credentials_from_uid(dbus_uid_t user_id, DBusCredentials *credentials)
dbus_bool_t _dbus_groups_from_uid(dbus_uid_t uid, dbus_gid_t **group_ids, int *n_group_ids)
Gets all groups corresponding to the given UID.
Returns FALSE if no memory, or user isn't known, but always initializes group_ids to a NULL array. uid the UID group_ids return location for array of group IDs n_group_ids return location for length of returned array TRUE if the UID existed and we got some credentials
References NULL, _dbus_user_database_lock_system, FALSE, _dbus_user_database_get_system, _dbus_user_database_unlock_system, _dbus_user_database_get_uid, _dbus_assert, DBusUserInfo::uid, DBusUserInfo::n_group_ids, dbus_new, DBusUserInfo::group_ids, TRUE, _dbus_username_from_current_process, _dbus_assert_not_reached, _dbus_homedir_from_current_process, _dbus_get_user_id, _dbus_groups_from_uid, dbus_error_init, _dbus_is_console_user, DBusError::message, dbus_error_free, dbus_free.
Referenced by _dbus_unix_groups_from_uid, _dbus_groups_from_uid.
dbus_bool_t _dbus_is_console_user(dbus_uid_t uid, DBusError *error)
Checks to see if the UID sent in is the console user.
uid UID of person to check error return location for errors TRUE if the UID is the same as the console user and there are no errors
References FALSE, NULL, dbus_set_error, _dbus_error_from_errno, DBUS_UID_FORMAT, _dbus_string_init, _dbus_string_append, _dbus_string_free, _dbus_stat, DBusStat::uid, TRUE, _dbus_user_database_lock_system, _dbus_user_database_get_system, DBUS_ERROR_FAILED, _dbus_user_database_unlock_system, _dbus_user_database_lookup, _dbus_user_at_console, DBusUserInfo::username.
Referenced by _dbus_unix_user_is_at_console, _dbus_groups_from_uid.
dbus_bool_t _dbus_is_a_number(const DBusString *str, unsigned long *num)
Checks if a given string is actually a number and converts it if it is.
str the string to check num the memory location of the unsigned long to fill in TRUE if str is a number and num is filled in
References _dbus_string_parse_uint, TRUE, FALSE.
Referenced by _dbus_user_database_lookup_group, _dbus_user_database_lookup.
dbus_bool_t _dbus_username_from_current_process(const DBusString **username)
Gets username of user owning current process.
The returned string is valid until dbus_shutdown() is called. username place to store pointer to username FALSE if no memory
References _dbus_user_database_lock_system, FALSE, _dbus_user_database_unlock_system, TRUE.
Referenced by _dbus_groups_from_uid.
dbus_bool_t _dbus_homedir_from_current_process(const DBusString **homedir)
Gets homedir of user owning current process.
The returned string is valid until dbus_shutdown() is called. homedir place to store pointer to homedir FALSE if no memory
References _dbus_user_database_lock_system, FALSE, _dbus_user_database_unlock_system, TRUE.
Referenced by _dbus_get_standard_session_servicedirs, _dbus_groups_from_uid.
dbus_bool_t _dbus_homedir_from_username(const DBusString *username, DBusString *homedir)
Gets the home directory for the given user.
username the username homedir string to append home directory to TRUE if user existed and we appended their homedir
References _dbus_user_database_lock_system, FALSE, _dbus_user_database_get_system, NULL, _dbus_user_database_unlock_system, _dbus_user_database_get_username, _dbus_string_append, DBusUserInfo::homedir, TRUE.
dbus_bool_t _dbus_homedir_from_uid(dbus_uid_t uid, DBusString *homedir)
Gets the home directory for the given user.
uid the uid homedir string to append home directory to TRUE if user existed and we appended their homedir
References _dbus_user_database_lock_system, FALSE, _dbus_user_database_get_system, NULL, _dbus_user_database_unlock_system, _dbus_user_database_get_uid, _dbus_string_append, DBusUserInfo::homedir, TRUE.
Referenced by _dbus_append_keyring_directory_for_credentials.