dbus-spawn.c
LIVE_CHILDREN
Macro returns TRUE if the babysitter still has live sockets open to the babysitter child or the grandchild.
Referenced by _dbus_babysitter_kill_child, _dbus_babysitter_get_child_exited, _dbus_babysitter_set_watch_functions, _dbus_spawn_async_with_babysitter.
READ_END
Helps remember which end of the pipe is which.
Referenced by _dbus_spawn_async_with_babysitter, _dbus_get_tmpdir.
WRITE_END
Helps remember which end of the pipe is which.
Referenced by _dbus_spawn_async_with_babysitter, _dbus_get_tmpdir.
ReadStatus
Read succeeded.
@8
char** environ
int babysit_sigchld_pipe
static ReadStatus read_ints(int fd, int *buf, int n_ints_in_buf, int *n_ints_read, DBusError *error)
static ReadStatus read_pid(int fd, pid_t *buf, DBusError *error)
static DBusBabysitter* _dbus_babysitter_new(void)
DBusBabysitter* _dbus_babysitter_ref(DBusBabysitter *sitter)
Increment the reference count on the babysitter object.
sitter the babysitter the babysitter
References _dbus_assert, _dbus_close_socket, _dbus_watch_invalidate, _dbus_watch_list_remove_watch, _dbus_watch_unref, NULL, DBusBabysitter::refcount, DBusBabysitter::sitter_watch, DBusBabysitter::socket_to_babysitter, DBusBabysitter::watches.
Referenced by _dbus_babysitter_set_watch_functions.
static void close_socket_to_babysitter(DBusBabysitter *sitter)
static void close_error_pipe_from_child(DBusBabysitter *sitter)
void _dbus_babysitter_unref(DBusBabysitter *sitter)
Decrement the reference count on the babysitter object.
When the reference count of the babysitter object reaches zero, the babysitter is killed and the child that was being babysat gets emancipated. sitter the babysitter
References _dbus_assert, _dbus_close_socket, _dbus_poll, _DBUS_POLLERR, _DBUS_POLLHUP, _DBUS_POLLIN, _dbus_warn, _dbus_watch_invalidate, _dbus_watch_list_free, _dbus_watch_list_remove_watch, _dbus_watch_unref, dbus_error_free, DBUS_ERROR_INIT, dbus_free, DBusBabysitter::errnum, DBusBabysitter::error_pipe_from_child, DBusBabysitter::error_watch, DBusPollFD::events, FALSE, DBusPollFD::fd, DBusBabysitter::grandchild_pid, DBusBabysitter::have_exec_errnum, DBusBabysitter::have_fork_errnum, DBusBabysitter::log_name, DBusError::message, NULL, READ_STATUS_EOF, READ_STATUS_ERROR, READ_STATUS_OK, DBusBabysitter::refcount, DBusPollFD::revents, DBusBabysitter::sitter_pid, DBusBabysitter::sitter_watch, DBusBabysitter::socket_to_babysitter, DBusBabysitter::status, TRUE, DBusBabysitter::watches.
Referenced by _dbus_babysitter_set_watch_functions, _dbus_spawn_async_with_babysitter.
static ReadStatus read_data(DBusBabysitter *sitter, int fd)
static void handle_babysitter_socket(DBusBabysitter *sitter, int revents)
static void handle_error_pipe(DBusBabysitter *sitter, int revents)
static dbus_bool_t babysitter_iteration(DBusBabysitter *sitter, dbus_bool_t block)
void _dbus_babysitter_kill_child(DBusBabysitter *sitter)
Blocks until the babysitter process gives us the PID of the spawned grandchild, then kills the spawned grandchild.
sitter the babysitter object
References DBusBabysitter::grandchild_pid, LIVE_CHILDREN, NULL, TRUE.
Referenced by _dbus_spawn_async_with_babysitter.
dbus_bool_t _dbus_babysitter_get_child_exited(DBusBabysitter *sitter)
Checks whether the child has exited, without blocking.
sitter the babysitter
References FALSE, LIVE_CHILDREN, NULL, DBusBabysitter::socket_to_babysitter.
Referenced by _dbus_babysitter_get_child_exit_status, _dbus_babysitter_set_child_exit_error, _dbus_babysitter_set_watch_functions.
dbus_bool_t _dbus_babysitter_get_child_exit_status(DBusBabysitter *sitter, int *status)
Gets the exit status of the child.
We do this so implementation specific detail is not cluttering up dbus, for example the system launcher code. This can only be called if the child has exited, i.e. call _dbus_babysitter_get_child_exited(). It returns FALSE if the child did not return a status code, e.g. because the child was signaled or we failed to ever launch the child in the first place. sitter the babysitter status the returned status code FALSE on failure
References _dbus_assert_not_reached, _dbus_babysitter_get_child_exited, FALSE, DBusBabysitter::status, TRUE.
void _dbus_babysitter_set_child_exit_error(DBusBabysitter *sitter, DBusError *error)
Sets the DBusError with an explanation of why the spawned child process exited (on a signal, or whatever).
If the child process has not exited, does nothing (error will remain unset). sitter the babysitter error an error to fill in
References _dbus_babysitter_get_child_exited, DBUS_ERROR_FAILED, DBUS_ERROR_NO_MEMORY, DBUS_ERROR_SPAWN_CHILD_EXITED, DBUS_ERROR_SPAWN_CHILD_SIGNALED, DBUS_ERROR_SPAWN_EXEC_FAILED, dbus_set_error, DBusBabysitter::errnum, DBusBabysitter::have_exec_errnum, DBusBabysitter::have_fork_errnum, DBusBabysitter::log_name, DBusBabysitter::status.
Referenced by _dbus_spawn_async_with_babysitter.
dbus_bool_t _dbus_babysitter_set_watch_functions(DBusBabysitter *sitter, DBusAddWatchFunction add_function, DBusRemoveWatchFunction remove_function, DBusWatchToggledFunction toggled_function, void *data, DBusFreeFunction free_data_function)
Sets watch functions to notify us when the babysitter object needs to read/write file descriptors.
sitter the babysitter add_function function to begin monitoring a new descriptor. remove_function function to stop monitoring a descriptor. toggled_function function to notify when the watch is enabled/disabled data data to pass to add_function and remove_function. free_data_function function to be called to free the data. FALSE on failure (no memory)
References _dbus_assert, _dbus_babysitter_get_child_exited, _dbus_babysitter_ref, _dbus_babysitter_unref, _DBUS_POLLERR, _DBUS_POLLHUP, _DBUS_POLLIN, _dbus_watch_list_set_functions, dbus_malloc, DBUS_WATCH_ERROR, dbus_watch_get_socket, DBUS_WATCH_HANGUP, DBUS_WATCH_READABLE, DBusBabysitter::error_pipe_from_child, DBusBabysitter::error_watch, FALSE, LIVE_CHILDREN, DBusBabysitter::log_name, NULL, DBusBabysitter::sitter_watch, DBusBabysitter::socket_to_babysitter, DBusBabysitter::status, TRUE, DBusBabysitter::watches.
static dbus_bool_t handle_watch(DBusWatch *watch, unsigned int condition, void *data)
static int close_and_invalidate(int *fd)
static dbus_bool_t make_pipe(int p[2], DBusError *error)
static void do_write(int fd, const void *buf, size_t count)
static void write_err_and_exit(int fd, int msg)
static void write_pid(int fd, pid_t pid)
static void write_status_and_exit(int fd, int status)
static void do_exec(int child_err_report_fd, char **argv, char **envp, DBusSpawnChildSetupFunc child_setup, void *user_data)
static void check_babysit_events(pid_t grandchild_pid, int parent_pipe, int revents)
static void babysit_signal_handler(int signo)
static void babysit(pid_t grandchild_pid, int parent_pipe)
dbus_bool_t _dbus_spawn_async_with_babysitter(DBusBabysitter **sitter_p, const char *log_name, char **argv, char **env, DBusSpawnChildSetupFunc child_setup, void *user_data, DBusError *error)
Spawns a new process.
The child_setup function is passed the given user_data and is run in the child just before calling exec().Also creates a "babysitter" which tracks the status of the child process, advising the parent if the child exits. If the spawn fails, no babysitter is created. If sitter_p is NULL, no babysitter is kept. sitter_p return location for babysitter or NULL log_name the name under which to log messages about this process being spawned argv the executable and arguments env the environment, or NULL to copy the parent's child_setup function to call in child pre-exec() user_data user data for setup function error error object to be filled in if function fails TRUE on success, FALSE if error is filled in
References _dbus_assert, _dbus_assert_not_reached, _dbus_babysitter_kill_child, _dbus_babysitter_set_child_exit_error, _dbus_babysitter_unref, _dbus_full_duplex_pipe, _dbus_getenv, _dbus_spawn_async_with_babysitter, _dbus_strdup, _dbus_string_append_printf, _dbus_string_free, _dbus_string_init, _dbus_warn, _dbus_watch_invalidate, _dbus_watch_list_add_watch, _dbus_watch_new, _dbus_watch_unref, dbus_error_free, dbus_error_has_name, DBUS_ERROR_INIT, dbus_error_init, dbus_error_is_set, DBUS_ERROR_NO_MEMORY, DBUS_ERROR_SPAWN_CHILD_EXITED, DBUS_ERROR_SPAWN_CHILD_SIGNALED, DBUS_ERROR_SPAWN_EXEC_FAILED, DBUS_ERROR_SPAWN_FORK_FAILED, dbus_free_string_array, dbus_set_error, dbus_set_error_const, DBUS_WATCH_READABLE, DBusBabysitter::error_pipe_from_child, DBusBabysitter::error_watch, FALSE, DBusBabysitter::grandchild_pid, LIVE_CHILDREN, DBusBabysitter::log_name, DBusError::message, DBusError::name, NULL, READ_END, DBusBabysitter::sitter_pid, DBusBabysitter::sitter_watch, DBusBabysitter::socket_to_babysitter, TRUE, DBusBabysitter::watches, WRITE_END.
Referenced by _dbus_spawn_async_with_babysitter.
void _dbus_babysitter_set_result_function(DBusBabysitter *sitter, DBusBabysitterFinishedFunc finished, void *user_data)