dbus-string.h
_DBUS_STRING_ALLOCATION_PADDING
We allocate 1 byte for nul termination, plus 7 bytes for possible align_offset, so we always need 8 bytes on top of the string's length to be in the allocated block.
_DBUS_STRING_DEFINE_STATIC
Defines a static const variable with type DBusString called "name" containing the given string literal.
name the name of the variable str the string value
typedef struct DBusString DBusString
DBusString object.
dbus_bool_t _dbus_string_init(DBusString *str)
Initializes a string.
The string starts life with zero length. The string must eventually be freed with _dbus_string_free(). str memory to hold the string TRUE on success, FALSE if no memory
References _dbus_string_init_preallocated.
Referenced by dbus_address_entries_free, dbus_parse_address, dbus_address_escape_value, dbus_address_unescape_value, _dbus_auth_server_new, _dbus_auth_client_new, dbus_connection_get_dispatch_status, dbus_connection_dispatch, dbus_set_error, _dbus_string_save_to_file, _dbus_uuid_encode, _dbus_write_uuid_file, _dbus_keyring_new_for_credentials, _dbus_keyring_get_hex_key, _dbus_first_type_in_signature_c_str, dbus_message_new_error_printf, dbus_message_iter_get_signature, _dbus_message_loader_new, dbus_message_marshal, dbus_get_local_machine_id, dbus_get_version, _dbus_object_tree_free_all_unlocked, _dbus_decompose_path, _dbus_server_new_for_launchd, _dbus_server_new_for_tcp_socket, _dbus_server_listen_platform_specific, _dbus_server_new_for_domain_socket, _dbus_server_init_base, _dbus_sha_compute, dbus_signature_iter_get_signature, _dbus_spawn_async_with_babysitter, _dbus_string_find_byte_backward, _dbus_string_init_from_string, _dbus_string_steal_data, _dbus_string_hex_encode, _dbus_string_hex_decode, _dbus_get_tmpdir, _dbus_get_autolaunch_address, _dbus_lookup_launchd_socket, _dbus_append_keyring_directory_for_credentials, _dbus_write_pid_to_file_and_pipe, _dbus_user_at_console, _dbus_command_for_pid, _dbus_get_standard_session_servicedirs, _dbus_get_environment, _dbus_connect_tcp_socket, _dbus_read_credentials_socket, _dbus_read_local_machine_uuid, _dbus_split_paths_and_append, _dbus_generate_random_bytes_buffer, _dbus_transport_new_for_socket, _dbus_transport_new_for_tcp_socket, _dbus_transport_new_for_domain_socket, _dbus_transport_open_platform_specific, _dbus_transport_finalize_base, _dbus_transport_do_iteration, _dbus_is_console_user, _dbus_user_database_lookup.
void _dbus_string_init_const(DBusString *str, const char *value)
Initializes a constant string.
The value parameter is not copied (should be static), and the string may never be modified. It is safe but not necessary to call _dbus_string_free() on a const string. The string has a length limit of MAXINT - 8. str memory to use for the string value a string to be stored in str (not copied!!!)
References _dbus_assert, NULL, _dbus_string_init_const_len.
Referenced by dbus_address_entry_get_value, dbus_parse_address, dbus_address_escape_value, dbus_address_unescape_value, dbus_error_has_name, _dbus_real_assert_not_reached, _dbus_keyring_get_hex_key, _dbus_marshal_set_uint32, _dbus_first_type_in_signature_c_str, dbus_message_iter_open_container, _dbus_server_new_for_tcp_socket, _dbus_server_new_for_domain_socket, _dbus_sha_compute, dbus_signature_validate, _dbus_string_find_byte_backward, dbus_validate_path, dbus_validate_interface, dbus_validate_member, dbus_validate_error_name, dbus_validate_bus_name, dbus_validate_utf8, _dbus_connect_tcp_socket, _dbus_read_local_machine_uuid, _dbus_append_keyring_directory_for_credentials, _dbus_append_address_from_socket, _dbus_verify_daemon_user, _dbus_change_to_daemon_user, _dbus_user_at_console, _dbus_get_standard_session_servicedirs, _dbus_get_standard_system_servicedirs, _dbus_get_environment, _dbus_printf_string_upper_bound, _dbus_split_paths_and_append, dbus_internal_do_not_use_get_uuid.
void _dbus_string_init_const_len(DBusString *str, const char *value, int len)
Initializes a constant string with a length.
The value parameter is not copied (should be static), and the string may never be modified. It is safe but not necessary to call _dbus_string_free() on a const string. str memory to use for the string value a string to be stored in str (not copied!!!) len the length to use
References _dbus_assert, NULL, _DBUS_STRING_MAX_LENGTH, DBusRealString::str, DBusRealString::len, DBusRealString::allocated, DBusRealString::constant, TRUE, DBusRealString::locked, DBusRealString::invalid, FALSE, DBusRealString::align_offset.
Referenced by _dbus_uuid_encode, _dbus_marshal_read_basic, _dbus_marshal_write_basic, _dbus_swap_array, _dbus_first_type_in_signature_c_str, _dbus_header_get_byte_order, _dbus_validate_signature_with_reason, dbus_message_demarshal_bytes_needed, _dbus_sha_compute, _dbus_string_init_const, _dbus_send_credentials_socket.
dbus_bool_t _dbus_string_init_preallocated(DBusString *str, int allocate_size)
Initializes a string that can be up to the given allocation size before it has to realloc.
The string starts life with zero length. The string must eventually be freed with _dbus_string_free(). str memory to hold the string allocate_size amount to preallocate TRUE on success, FALSE if no memory
References _dbus_assert, NULL, DBusRealString::str, dbus_malloc, FALSE, DBusRealString::allocated, DBusRealString::len, DBusRealString::constant, DBusRealString::locked, DBusRealString::invalid, DBusRealString::align_offset, TRUE.
Referenced by _dbus_header_init, _dbus_header_copy, dbus_message_get_reply_serial, dbus_message_copy, dbus_message_iter_init_append, _dbus_string_init.
dbus_bool_t _dbus_string_init_from_string(DBusString *str, const DBusString *from)
Initializes a string from another string.
The string must eventually be freed with _dbus_string_free(). str memory to hold the string from instance from which the string is initialized TRUE on success, FALSE if no memory
References _dbus_string_init, FALSE, _dbus_string_append.
Referenced by _dbus_directory_open.
void _dbus_string_free(DBusString *str)
Frees a string created by _dbus_string_init().
str memory where the string is stored.
References DBUS_GENERIC_STRING_PREAMBLE, DBusRealString::constant, DBusRealString::str, NULL, dbus_free, DBusRealString::align_offset, DBusRealString::invalid, TRUE, DBusRealString::allocated, DBusRealString::len, dbus_realloc, FALSE, DBUS_LOCKED_STRING_PREAMBLE, DBusRealString::locked, _DBUS_STRING_MAX_LENGTH, _dbus_assert.
Referenced by _dbus_address_append_escaped, dbus_parse_address, dbus_address_escape_value, dbus_address_unescape_value, _dbus_auth_server_new, _dbus_auth_client_new, _dbus_auth_unref, dbus_connection_get_dispatch_status, dbus_connection_dispatch, dbus_set_error, _dbus_string_save_to_file, _dbus_uuid_encode, _dbus_write_uuid_file, _dbus_keyring_unref, _dbus_keyring_new_for_credentials, _dbus_keyring_get_hex_key, _dbus_first_type_in_signature_c_str, _dbus_header_free, _dbus_header_copy, dbus_message_get_reply_serial, dbus_message_new_error_printf, dbus_message_copy, dbus_message_iter_get_signature, dbus_message_iter_init_append, _dbus_message_loader_unref, dbus_message_marshal, dbus_message_demarshal_bytes_needed, dbus_get_local_machine_id, dbus_get_version, _dbus_object_tree_free_all_unlocked, _dbus_decompose_path, _dbus_server_new_for_launchd, _dbus_server_new_for_tcp_socket, _dbus_server_listen_platform_specific, _dbus_server_new_for_domain_socket, _dbus_server_init_base, _dbus_server_finalize_base, _dbus_sha_compute, dbus_signature_iter_get_signature, _dbus_spawn_async_with_babysitter, _dbus_string_find_byte_backward, _dbus_string_hex_encode, _dbus_string_hex_decode, _dbus_connect_tcp_socket, _dbus_get_autolaunch_address, _dbus_lookup_launchd_socket, _dbus_append_keyring_directory_for_credentials, _dbus_write_pid_to_file_and_pipe, _dbus_user_at_console, _dbus_command_for_pid, _dbus_get_standard_session_servicedirs, _dbus_directory_open, _dbus_get_environment, _dbus_read_credentials_socket, _dbus_read_local_machine_uuid, _dbus_split_paths_and_append, _dbus_generate_random_bytes_buffer, _dbus_transport_new_for_socket, _dbus_transport_new_for_tcp_socket, _dbus_transport_new_for_domain_socket, _dbus_transport_open_platform_specific, _dbus_transport_finalize_base, _dbus_transport_do_iteration, _dbus_is_console_user, _dbus_user_database_lookup.
void _dbus_string_lock(DBusString *str)
dbus_bool_t _dbus_string_compact(DBusString *str, int max_waste)
Compacts the string to avoid wasted memory.
Wasted memory is memory that is allocated but not actually required to store the current length of the string. The compact is only done if more than the given amount of memory is being wasted (otherwise the waste is ignored and the call does nothing). str the string max_waste the maximum amount of waste to ignore FALSE if the compact failed due to realloc failure
References DBUS_STRING_PREAMBLE, _DBUS_STRING_MAX_LENGTH, FALSE, DBusRealString::allocated, DBusRealString::len, DBusRealString::str, TRUE, DBUS_CONST_STRING_PREAMBLE.
Referenced by _dbus_message_loader_return_unix_fds, _dbus_string_find_byte_backward.
char* _dbus_string_get_data(DBusString *str)
const char* _dbus_string_get_const_data(const DBusString *str)
char* _dbus_string_get_data_len(DBusString *str, int start, int len)
Gets a sub-portion of the raw character buffer from the string.
The "len" field is required simply for error checking, to be sure you don't try to use more string than exists. The nul termination of the returned buffer remains at the end of the entire string, not at start + len. str the string start byte offset to return len length of segment to return the string data
References DBUS_STRING_PREAMBLE, _dbus_assert, DBusRealString::str, DBUS_CONST_STRING_PREAMBLE.
Referenced by _dbus_unpack_uint32, _dbus_marshal_byteswap, _dbus_header_toggle_flag, _dbus_read_socket_with_unix_fds, _dbus_read, _dbus_sleep_milliseconds, _dbus_read_socket, _dbus_generate_random_bytes, _dbus_string_append_int, _dbus_string_append_uint.
const char* _dbus_string_get_const_data_len(const DBusString *str, int start, int len)
void _dbus_string_set_byte(DBusString *str, int i, unsigned char byte)
unsigned char _dbus_string_get_byte(const DBusString *str, int start)
dbus_bool_t _dbus_string_insert_bytes(DBusString *str, int i, int n_bytes, unsigned char byte)
Inserts a number of bytes of a given value at the given position.
str the string i the position n_bytes number of bytes byte the value to insert TRUE on success
References DBUS_STRING_PREAMBLE, _dbus_assert, TRUE, FALSE, DBusRealString::str.
Referenced by _dbus_type_writer_init_values_only, _dbus_string_find_byte_backward.
dbus_bool_t _dbus_string_insert_byte(DBusString *str, int i, unsigned char byte)
Inserts a single byte at the given position.
str the string i the position byte the value to insert TRUE on success
References DBUS_STRING_PREAMBLE, _dbus_assert, FALSE, DBusRealString::str, TRUE.
Referenced by _dbus_marshal_read_basic, _dbus_marshal_write_basic, _dbus_type_writer_init_values_only.
dbus_bool_t _dbus_string_steal_data(DBusString *str, char **data_return)
Like _dbus_string_get_data(), but removes the gotten data from the original string.
The caller must free the data returned. This function may fail due to lack of memory, and return FALSE. str the string data_return location to return the buffer TRUE on success
References DBUS_STRING_PREAMBLE, _dbus_assert, NULL, DBusRealString::str, _dbus_string_init, FALSE, TRUE.
Referenced by dbus_address_escape_value, dbus_address_unescape_value, dbus_set_error, dbus_message_iter_get_signature, dbus_message_marshal, dbus_get_local_machine_id, _dbus_decompose_path, dbus_signature_iter_get_signature, _dbus_string_find_byte_backward.
dbus_bool_t _dbus_string_steal_data_len(DBusString *str, char **data_return, int start, int len)
dbus_bool_t _dbus_string_copy_data(const DBusString *str, char **data_return)
Copies the data from the string into a char*.
str the string data_return place to return the data TRUE on success, FALSE on no memory
References DBUS_CONST_STRING_PREAMBLE, _dbus_assert, NULL, dbus_malloc, DBusRealString::len, FALSE, DBusRealString::str, TRUE.
Referenced by dbus_server_get_id, _dbus_split_paths_and_append, _dbus_transport_init_base.
dbus_bool_t _dbus_string_copy_data_len(const DBusString *str, char **data_return, int start, int len)
void _dbus_string_copy_to_buffer(const DBusString *str, char *buffer, int len)
Copies the contents of a DBusString into a different buffer.
It is a bug if avail_len is too short to hold the string contents. nul termination is not copied, just the supplied bytes. str a string buffer a C buffer to copy data to avail_len maximum length of C buffer
References DBUS_CONST_STRING_PREAMBLE, _dbus_assert, DBusRealString::len, DBusRealString::str.
Referenced by _dbus_uuid_encode, _dbus_generate_random_bytes_buffer.
void _dbus_string_copy_to_buffer_with_nul(const DBusString *str, char *buffer, int avail_len)
Copies the contents of a DBusString into a different buffer.
It is a bug if avail_len is too short to hold the string contents plus a nul byte. str a string buffer a C buffer to copy data to avail_len maximum length of C buffer
References DBUS_CONST_STRING_PREAMBLE, _dbus_assert, DBusRealString::len, DBusRealString::str.
int _dbus_string_get_length(const DBusString *str)
dbus_bool_t _dbus_string_lengthen(DBusString *str, int additional_length)
Makes a string longer by the given number of bytes.
Checks whether adding additional_length to the current length would overflow an integer, and checks for exceeding a string's max length. The new bytes are not initialized, other than nul-terminating the end of the string. The uninitialized bytes may contain nul bytes or other junk. str a string additional_length length to add to the string. TRUE on success.
References DBUS_STRING_PREAMBLE, _dbus_assert, _DBUS_STRING_MAX_LENGTH, DBusRealString::len, FALSE.
Referenced by _dbus_string_alloc_space, _dbus_string_append_printf_valist, _dbus_read_socket_with_unix_fds, _dbus_read, _dbus_sleep_milliseconds, _dbus_read_socket, _dbus_generate_random_bytes, _dbus_string_append_int, _dbus_string_append_uint.
void _dbus_string_shorten(DBusString *str, int length_to_remove)
Makes a string shorter by the given number of bytes.
str a string length_to_remove length to remove from the string.
References DBUS_STRING_PREAMBLE, _dbus_assert, DBusRealString::len.
Referenced by _dbus_string_find_byte_backward, _dbus_string_alloc_space, _dbus_concat_dir_and_file, _dbus_lookup_launchd_socket, _dbus_string_append_int, _dbus_string_append_uint.
dbus_bool_t _dbus_string_set_length(DBusString *str, int length)
Sets the length of a string.
Can be used to truncate or lengthen the string. If the string is lengthened, the function may fail and return FALSE. Newly-added bytes are not initialized, as with _dbus_string_lengthen(). str a string length new length of the string. FALSE on failure.
References DBUS_STRING_PREAMBLE, _dbus_assert, DBusRealString::len, _DBUS_STRING_MAX_LENGTH, FALSE, TRUE, DBusRealString::str.
Referenced by _dbus_address_append_escaped, _dbus_auth_delete_unused_bytes, _dbus_file_get_contents, _dbus_first_type_in_signature_c_str, _dbus_header_reinit, _dbus_header_load, dbus_message_get_reply_serial, _dbus_message_loader_new, _dbus_sha_compute, _dbus_string_find_byte_backward, _dbus_string_split_on_byte, _dbus_string_pop_line, _dbus_string_chop_white, _dbus_string_append_byte_as_hex, _dbus_read_socket_with_unix_fds, _dbus_read, _dbus_generate_random_bytes, _dbus_get_tmpdir, _dbus_append_keyring_directory_for_credentials, _dbus_directory_get_next_file, _dbus_read_socket.
dbus_bool_t _dbus_string_align_length(DBusString *str, int alignment)
Align the length of a string to a specific alignment (typically 4 or 8) by appending nul bytes to the string.
str a string alignment the alignment FALSE if no memory
dbus_bool_t _dbus_string_alloc_space(DBusString *str, int extra_bytes)
Preallocate extra_bytes such that a future lengthening of the string by extra_bytes is guaranteed to succeed without an out of memory error.
str a string extra_bytes bytes to alloc FALSE if no memory
References _dbus_string_lengthen, FALSE, _dbus_string_shorten, TRUE, DBusRealString::str, DBusRealString::len.
Referenced by _dbus_type_writer_init_values_only, _dbus_type_writer_write_basic.
dbus_bool_t _dbus_string_append(DBusString *str, const char *buffer)
Appends a nul-terminated C-style string to a DBusString.
str the DBusString buffer the nul-terminated characters to append FALSE if not enough memory.
References DBUS_STRING_PREAMBLE, _dbus_assert, NULL, _DBUS_STRING_MAX_LENGTH, FALSE.
Referenced by dbus_set_error, _dbus_string_save_to_file, _dbus_keyring_new_for_credentials, _dbus_object_tree_free_all_unlocked, _dbus_decompose_path, _dbus_server_new_for_launchd, _dbus_server_new_for_tcp_socket, _dbus_server_listen_platform_specific, _dbus_server_new_for_domain_socket, _dbus_sha_compute, _dbus_string_find_byte_backward, _dbus_string_init_from_string, _dbus_listen_tcp_socket, _dbus_lookup_launchd_socket, _dbus_append_keyring_directory_for_credentials, _dbus_append_address_from_socket, _dbus_write_pid_to_file_and_pipe, _dbus_user_at_console, _dbus_directory_get_next_file, _dbus_string_get_dirname, _dbus_get_standard_session_servicedirs, _dbus_append_system_config_file, _dbus_append_session_config_file, _dbus_directory_open, _dbus_directory_close, _dbus_connect_tcp_socket, _dbus_append_user_from_current_process, _dbus_read_local_machine_uuid, _dbus_get_is_errno_eagain_or_ewouldblock, _dbus_transport_new_for_tcp_socket, _dbus_transport_new_for_domain_socket, _dbus_is_console_user, _dbus_user_database_lookup, _dbus_homedir_from_username, _dbus_homedir_from_uid.
dbus_bool_t _dbus_string_append_len(DBusString *str, const char *buffer, int len)
Appends block of bytes with the given length to a DBusString.
str the DBusString buffer the bytes to append len the number of bytes to append FALSE if not enough memory.
References DBUS_STRING_PREAMBLE, _dbus_assert, NULL.
Referenced by dbus_message_iter_get_signature, dbus_message_demarshal, _dbus_sha_final, dbus_signature_iter_get_signature, _dbus_string_find_byte_backward.
dbus_bool_t _dbus_string_append_int(DBusString *str, long value)
Appends an integer to a DBusString.
str the string value the integer value FALSE if not enough memory or other failure.
References _dbus_string_lengthen, FALSE, _dbus_string_get_data_len, _dbus_string_shorten, TRUE.
Referenced by dbus_get_version, _dbus_string_find_byte_backward, _dbus_write_pid_to_file_and_pipe.
dbus_bool_t _dbus_string_append_uint(DBusString *str, unsigned long value)
Appends an unsigned integer to a DBusString.
str the string value the integer value FALSE if not enough memory or other failure.
References _dbus_string_lengthen, FALSE, _dbus_string_get_data_len, _dbus_string_shorten, TRUE.
Referenced by _dbus_append_user_from_current_process.
dbus_bool_t _dbus_string_append_byte(DBusString *str, unsigned char byte)
Appends a single byte to the string, returning FALSE if not enough memory.
str the string byte the byte to append TRUE on success
References DBUS_STRING_PREAMBLE, DBusRealString::len, FALSE, DBusRealString::str, TRUE.
Referenced by _dbus_address_append_escaped, dbus_address_entry_get_value, _dbus_write_uuid_file, _dbus_keyring_get_hex_key, dbus_get_version, _dbus_decompose_path, _dbus_sha_compute, _dbus_string_find_byte_backward, _dbus_string_append_byte_as_hex, _dbus_string_hex_decode, _dbus_concat_dir_and_file.
dbus_bool_t _dbus_string_append_printf(DBusString *str, const char *format,...)
Appends a printf-style formatted string to the DBusString.
str the string format printf format FALSE if no memory
References _dbus_string_append_printf_valist.
Referenced by dbus_connection_dispatch, _dbus_credentials_to_string_append, _dbus_object_tree_free_all_unlocked, _dbus_spawn_async_with_babysitter, _dbus_append_address_from_socket, _dbus_command_for_pid, _dbus_transport_new_for_domain_socket.
dbus_bool_t _dbus_string_append_printf_valist(DBusString *str, const char *format, va_list args)
Appends a printf-style formatted string to the DBusString.
str the string format printf format args variable argument list FALSE if no memory
References DBUS_STRING_PREAMBLE, _dbus_printf_string_upper_bound, FALSE, _dbus_string_lengthen, DBusRealString::str, DBusRealString::len, TRUE.
Referenced by dbus_set_error, dbus_message_new_error_printf, _dbus_string_append_printf.
dbus_bool_t _dbus_string_insert_2_aligned(DBusString *str, int insert_at, const unsigned char octets[2])
Inserts 2 bytes aligned on a 2 byte boundary with any alignment padding initialized to 0.
str the DBusString insert_at where to insert octets 2 bytes to insert FALSE if not enough memory.
References DBUS_STRING_PREAMBLE, FALSE, ASSIGN_2_OCTETS, DBusRealString::str, TRUE.
Referenced by _dbus_marshal_read_basic.
dbus_bool_t _dbus_string_insert_4_aligned(DBusString *str, int insert_at, const unsigned char octets[4])
Inserts 4 bytes aligned on a 4 byte boundary with any alignment padding initialized to 0.
str the DBusString insert_at where to insert octets 4 bytes to insert FALSE if not enough memory.
References DBUS_STRING_PREAMBLE, FALSE, ASSIGN_4_OCTETS, DBusRealString::str, TRUE.
Referenced by _dbus_marshal_read_basic.
dbus_bool_t _dbus_string_insert_8_aligned(DBusString *str, int insert_at, const unsigned char octets[8])
Inserts 8 bytes aligned on an 8 byte boundary with any alignment padding initialized to 0.
str the DBusString insert_at where to insert octets 8 bytes to insert FALSE if not enough memory.
References DBUS_STRING_PREAMBLE, FALSE, _dbus_assert, ASSIGN_8_OCTETS, DBusRealString::str, TRUE.
Referenced by _dbus_marshal_read_basic.
dbus_bool_t _dbus_string_insert_alignment(DBusString *str, int *insert_at, int alignment)
Inserts padding at *insert_at such to align it to the given boundary.
Initializes the padding to nul bytes. Sets *insert_at to the aligned position. str the DBusString insert_at location to be aligned alignment alignment boundary (1, 2, 4, or 8) FALSE if not enough memory.
References DBUS_STRING_PREAMBLE, FALSE, _dbus_assert, TRUE.
Referenced by _dbus_swap_array.
void _dbus_string_delete(DBusString *str, int start, int len)
Deletes a segment of a DBusString with length len starting at start.
(Hint: to clear an entire string, setting length to 0 with _dbus_string_set_length() is easier.) str the DBusString start where to start deleting len the number of bytes to delete
References DBUS_STRING_PREAMBLE, _dbus_assert, TRUE, FALSE, DBusRealString::str.
Referenced by _dbus_auth_bytes_sent, _dbus_marshal_read_basic, _dbus_swap_array, _dbus_header_get_byte_order, _dbus_header_create, _dbus_type_writer_write_fixed_multi, _dbus_message_loader_return_unix_fds, _dbus_sha_compute, _dbus_string_pop_line, _dbus_string_chop_white.
dbus_bool_t _dbus_string_move(DBusString *source, int start, DBusString *dest, int insert_at)
Moves the end of one string into another string.
Both strings must be initialized, valid strings. source the source string start where to chop off the source string dest the destination string insert_at where to move the chopped-off part of source string FALSE if not enough memory
References _dbus_assert, _dbus_string_move_len, DBusRealString::len.
Referenced by _dbus_sha_compute, _dbus_string_find_byte_backward, _dbus_string_hex_encode, _dbus_string_hex_decode, _dbus_transport_do_iteration.
dbus_bool_t _dbus_string_copy(const DBusString *source, int start, DBusString *dest, int insert_at)
Like _dbus_string_move(), but does not delete the section of the source string that's copied to the dest string.
source the source string start where to start copying the source string dest the destination string insert_at where to place the copied part of source string FALSE if not enough memory
References DBUS_STRING_COPY_PREAMBLE.
Referenced by _dbus_auth_server_new, _dbus_auth_encode_data, _dbus_auth_decode_data, _dbus_string_save_to_file, _dbus_keyring_new_for_credentials, _dbus_swap_array, _dbus_header_copy, dbus_message_copy, dbus_message_marshal, _dbus_string_find_byte_backward, _dbus_concat_dir_and_file, _dbus_lookup_launchd_socket, _dbus_append_keyring_directory_for_credentials, _dbus_command_for_pid, _dbus_transport_do_iteration.
dbus_bool_t _dbus_string_move_len(DBusString *source, int start, int len, DBusString *dest, int insert_at)
Like _dbus_string_move(), but can move a segment from the middle of the source string.
source the source string start first byte of source string to move len length of segment to move dest the destination string insert_at where to move the bytes from the source string FALSE if not enough memory
References DBUS_STRING_COPY_PREAMBLE, _dbus_assert, TRUE, FALSE.
Referenced by _dbus_string_move, _dbus_string_split_on_byte, _dbus_string_pop_line.
dbus_bool_t _dbus_string_copy_len(const DBusString *source, int start, int len, DBusString *dest, int insert_at)
Like _dbus_string_copy(), but can copy a segment from the middle of the source string.
source the source string start where to start copying the source string len length of segment to copy dest the destination string insert_at where to place the copied segment of source string FALSE if not enough memory
References DBUS_STRING_COPY_PREAMBLE, _dbus_assert.
Referenced by dbus_parse_address, _dbus_marshal_read_basic, _dbus_marshal_write_basic, _dbus_header_load, _dbus_type_writer_init_values_only, dbus_message_iter_init_append, _dbus_message_loader_return_unix_fds, _dbus_string_get_dirname, _dbus_directory_close, _dbus_split_paths_and_append.
dbus_bool_t _dbus_string_replace_len(const DBusString *source, int start, int len, DBusString *dest, int replace_at, int replace_len)
Replaces a segment of dest string with a segment of source string.
source the source string start where to start copying the source string len length of segment to copy dest the destination string replace_at start of segment of dest string to replace replace_len length of segment of dest string to replace FALSE if not enough memory
References DBUS_STRING_COPY_PREAMBLE, _dbus_assert, FALSE, TRUE.
Referenced by _dbus_auth_set_context, _dbus_marshal_set_uint32, _dbus_string_find_byte_backward.
dbus_bool_t _dbus_string_split_on_byte(DBusString *source, unsigned char byte, DBusString *tail)
Looks for the first occurance of a byte, deletes that byte, and moves everything after the byte to the beginning of a separate string.
Both strings must be initialized, valid strings. source the source string byte the byte to remove and split the string at tail the split off string FALSE if not enough memory or if byte could not be found
References _dbus_string_find, FALSE, _dbus_string_move_len, _dbus_string_set_length, TRUE.
Referenced by _dbus_string_find_byte_backward.
dbus_bool_t _dbus_string_parse_int(const DBusString *str, int start, long *value_return, int *end_return)
Parses an integer contained in a DBusString.
Either return parameter may be NULL if you aren't interested in it. The integer is parsed and stored in value_return. Return parameters are not initialized if the function returns FALSE. str the string start the byte index of the start of the integer value_return return location of the integer value or NULL end_return return location of the end of the integer, or NULL TRUE on success
References NULL, _dbus_set_errno_to_zero, FALSE, TRUE.
Referenced by _dbus_real_assert_not_reached, _dbus_sha_compute, _dbus_string_find_byte_backward, _dbus_parse_uid.
dbus_bool_t _dbus_string_parse_uint(const DBusString *str, int start, unsigned long *value_return, int *end_return)
Parses an unsigned integer contained in a DBusString.
Either return parameter may be NULL if you aren't interested in it. The integer is parsed and stored in value_return. Return parameters are not initialized if the function returns FALSE. str the string start the byte index of the start of the integer value_return return location of the integer value or NULL end_return return location of the end of the integer, or NULL TRUE on success
References NULL, _dbus_set_errno_to_zero, FALSE, TRUE.
Referenced by _dbus_is_a_number.
dbus_bool_t _dbus_string_find(const DBusString *str, int start, const char *substr, int *found)
Finds the given substring in the string, returning TRUE and filling in the byte index where the substring was found, if it was found.
Returns FALSE if the substring wasn't found. Sets *start to the length of the string if the substring is not found. str the string start where to start looking substr the substring found return location for where it was found, or NULL TRUE if found
References _dbus_string_find_to.
Referenced by dbus_parse_address, _dbus_keyring_validate_context, _dbus_sha_compute, _dbus_string_find_byte_backward, _dbus_string_split_on_byte, _dbus_split_paths_and_append.
dbus_bool_t _dbus_string_find_eol(const DBusString *str, int start, int *found, int *found_len)
Finds end of line ("\r\n" or "\n") in the string, returning TRUE and filling in the byte index where the eol string was found, if it was found.
Returns FALSE if eol wasn't found. str the string start where to start looking found return location for where eol was found or string length otherwise found_len return length of found eol string or zero otherwise TRUE if found
References DBUS_CONST_STRING_PREAMBLE, _dbus_assert, DBusRealString::str, DBusRealString::len, TRUE, FALSE.
Referenced by _dbus_string_find_byte_backward, _dbus_string_pop_line.
dbus_bool_t _dbus_string_find_to(const DBusString *str, int start, int end, const char *substr, int *found)
Finds the given substring in the string, up to a certain position, returning TRUE and filling in the byte index where the substring was found, if it was found.
Returns FALSE if the substring wasn't found. Sets *start to the length of the string if the substring is not found. str the string start where to start looking end where to stop looking substr the substring found return location for where it was found, or NULL TRUE if found
References DBUS_CONST_STRING_PREAMBLE, _dbus_assert, NULL, TRUE, DBusRealString::str, FALSE.
Referenced by dbus_parse_address, _dbus_string_find_byte_backward, _dbus_string_find.
dbus_bool_t _dbus_string_find_byte_backward(const DBusString *str, int start, unsigned char byte, int *found)
Find the given byte scanning backward from the given start.
Sets *found to -1 if the byte is not found. str the string start the place to start scanning (will not find the byte at this point) byte the byte to find found return location for where it was found TRUE if found
References DBUS_CONST_STRING_PREAMBLE, _dbus_assert, NULL, _dbus_string_init, _dbus_assert_not_reached, _dbus_string_append_len, _dbus_string_hex_encode, _dbus_string_hex_decode, _dbus_string_equal, _dbus_string_free, _DBUS_N_ELEMENTS, _dbus_string_set_length, _dbus_string_shorten, _dbus_string_append, _dbus_string_init_const, _dbus_string_equal_substring, _dbus_string_append_byte, _dbus_string_steal_data, dbus_free, _dbus_string_move, _dbus_string_copy, _dbus_string_equal_c_str, _dbus_string_replace_len, _dbus_string_insert_bytes, _dbus_string_append_int, _dbus_string_parse_int, _dbus_string_find, _dbus_string_find_to, _dbus_string_find_byte_backward, _dbus_string_find_eol, _dbus_string_pop_line, _dbus_string_compact, _dbus_string_split_on_byte, _dbus_string_tolower_ascii, _dbus_string_toupper_ascii, TRUE.
Referenced by _dbus_string_find_byte_backward, _dbus_string_get_dirname, _dbus_directory_close.
dbus_bool_t _dbus_string_find_blank(const DBusString *str, int start, int *found)
Finds a blank (space or tab) in the string.
Returns TRUE if found, FALSE otherwise. If a blank is not found sets *found to the length of the string. str the string start byte index to start looking found place to store the location of the first blank TRUE if a blank was found
References DBUS_CONST_STRING_PREAMBLE, _dbus_assert, DBusRealString::str, TRUE, DBusRealString::len, FALSE.
Referenced by _dbus_keyring_validate_context, _dbus_string_pop_line.
void _dbus_string_skip_blank(const DBusString *str, int start, int *end)
Skips blanks from start, storing the first non-blank in *end (blank is space or tab).
str the string start where to start end where to store the first non-blank byte index
References DBUS_CONST_STRING_PREAMBLE, _dbus_assert, DBUS_IS_ASCII_BLANK, DBusRealString::str, DBusRealString::len, DBUS_IS_ASCII_WHITE.
Referenced by _dbus_sha_compute, _dbus_string_pop_line.
void _dbus_string_skip_white(const DBusString *str, int start, int *end)
Skips whitespace from start, storing the first non-whitespace in *end.
(whitespace is space, tab, newline, CR). str the string start where to start end where to store the first non-whitespace byte index
References DBUS_CONST_STRING_PREAMBLE, _dbus_assert, DBUS_IS_ASCII_WHITE, DBusRealString::str, DBusRealString::len.
Referenced by _dbus_string_chop_white.
void _dbus_string_skip_white_reverse(const DBusString *str, int end, int *start)
Skips whitespace from end, storing the start index of the trailing whitespace in *start.
(whitespace is space, tab, newline, CR). str the string end where to start scanning backward start where to store the start of whitespace chars
References DBUS_CONST_STRING_PREAMBLE, _dbus_assert, DBUS_IS_ASCII_WHITE, DBusRealString::str.
Referenced by _dbus_string_chop_white.
dbus_bool_t _dbus_string_equal(const DBusString *a, const DBusString *b)
Tests two DBusString for equality.
Todomemcmp is probably faster a first string b second string TRUE if equal
References DBUS_GENERIC_STRING_PREAMBLE, DBusRealString::len, FALSE, DBusRealString::str, TRUE.
Referenced by dbus_error_has_name, _dbus_keyring_get_hex_key, _dbus_sha_compute, _dbus_string_find_byte_backward.
dbus_bool_t _dbus_string_equal_c_str(const DBusString *a, const char *c_str)
Checks whether a string is equal to a C string.
a the string c_str the C string TRUE if equal
References DBUS_GENERIC_STRING_PREAMBLE, _dbus_assert, NULL, DBusRealString::str, DBusRealString::len, FALSE, TRUE.
Referenced by dbus_address_entry_get_value, dbus_get_version, _dbus_string_find_byte_backward, _dbus_get_environment.
dbus_bool_t _dbus_string_equal_len(const DBusString *a, const DBusString *b, int len)
Tests two DBusString for equality up to the given length.
The strings may be shorter than the given length.Todowrite a unit testTodomemcmp is probably faster a first string b second string len the maximum length to look at TRUE if equal for the given number of bytes
References DBUS_GENERIC_STRING_PREAMBLE, DBusRealString::len, FALSE, DBusRealString::str, TRUE.
dbus_bool_t _dbus_string_equal_substring(const DBusString *a, int a_start, int a_len, const DBusString *b, int b_start)
Tests two sub-parts of two DBusString for equality.
The specified range of the first string must exist; the specified start position of the second string must exist.Todowrite a unit testTodomemcmp is probably faster a first string a_start where to start substring in first string a_len length of substring in first string b second string b_start where to start substring in second string TRUE if the two substrings are equal
References DBUS_GENERIC_STRING_PREAMBLE, _dbus_assert, DBusRealString::len, FALSE, DBusRealString::str, TRUE.
Referenced by _dbus_marshal_read_basic, _dbus_header_have_message_untrusted, _dbus_type_writer_init_values_only, _dbus_string_find_byte_backward.
dbus_bool_t _dbus_string_starts_with_c_str(const DBusString *a, const char *c_str)
Checks whether a string starts with the given C string.
a the string c_str the C string TRUE if string starts with it
References DBUS_GENERIC_STRING_PREAMBLE, _dbus_assert, NULL, DBusRealString::str, DBusRealString::len, FALSE, TRUE.
Referenced by _dbus_sha_compute.
dbus_bool_t _dbus_string_ends_with_c_str(const DBusString *a, const char *c_str)
Returns whether a string ends with the given suffix.
Todomemcmp might make this faster. a the string c_str the C-style string TRUE if the string ends with the suffix
References DBUS_GENERIC_STRING_PREAMBLE, _dbus_assert, NULL, DBusRealString::len, FALSE, DBusRealString::str, TRUE.
Referenced by _dbus_directory_open.
dbus_bool_t _dbus_string_pop_line(DBusString *source, DBusString *dest)
Assigns a newline-terminated or \r\n-terminated line from the front of the string to the given dest string.
The dest string's previous contents are deleted. If the source string contains no newline, moves the entire source string to the dest string.Todoowen correctly notes that this is a stupid function (it was written purely for test code, e.g. dbus-message-builder.c). Probably should be enforced as test code only with ifdef DBUS_ENABLE_EMBEDDED_TESTS source the source string dest the destination string (contents are replaced) FALSE if no memory, or source has length 0
References _dbus_string_set_length, _dbus_string_find_eol, _dbus_assert, FALSE, _dbus_string_move_len, _dbus_assert_not_reached, TRUE, _dbus_string_find_blank, _dbus_string_skip_blank, _dbus_string_delete.
Referenced by _dbus_sha_compute, _dbus_string_find_byte_backward.
void _dbus_string_delete_first_word(DBusString *str)
void _dbus_string_delete_leading_blanks(DBusString *str)
void _dbus_string_chop_white(DBusString *str)
Deletes leading and trailing whitespace.
str the string
References _dbus_string_skip_white, _dbus_string_delete, _dbus_string_skip_white_reverse, _dbus_string_set_length.
Referenced by _dbus_uuid_encode, _dbus_split_paths_and_append.
dbus_bool_t _dbus_string_append_byte_as_hex(DBusString *str, unsigned char byte)
Appends a two-character hex digit to a string, where the hex digit has the value of the given byte.
str the string byte the byte FALSE if no memory
References _dbus_string_append_byte, FALSE, _dbus_string_set_length, TRUE.
Referenced by _dbus_address_append_escaped, _dbus_string_hex_encode.
dbus_bool_t _dbus_string_hex_encode(const DBusString *source, int start, DBusString *dest, int insert_at)
Encodes a string in hex, the way MD5 and SHA-1 are usually encoded.
(Each byte is two hex digits.) source the string to encode start byte index to start encoding dest string where encoded data should be placed insert_at where to place encoded data TRUE if encoding was successful, FALSE if no memory etc.
References _dbus_assert, _dbus_string_init, FALSE, _dbus_string_append_byte_as_hex, _dbus_string_move, TRUE, _dbus_string_free.
Referenced by _dbus_uuid_encode, _dbus_keyring_get_hex_key, _dbus_sha_compute, _dbus_string_find_byte_backward.
dbus_bool_t _dbus_string_hex_decode(const DBusString *source, int start, int *end_return, DBusString *dest, int insert_at)
Decodes a string from hex encoding.
source the string to decode start byte index to start decode end_return return location of the end of the hex data, or NULL dest string where decoded data should be placed insert_at where to place decoded data TRUE if decoding was successful, FALSE if no memory.
References _dbus_assert, _dbus_string_init, FALSE, TRUE, _dbus_string_append_byte, _dbus_string_move, _dbus_string_free.
Referenced by dbus_address_entry_get_value, _dbus_uuid_encode, _dbus_string_find_byte_backward.
void _dbus_string_tolower_ascii(const DBusString *str, int start, int len)
Converts the given range of the string to lower case.
str the string start first byte index to convert len number of bytes to convert
References DBUS_STRING_PREAMBLE, _dbus_assert, DBusRealString::str.
Referenced by _dbus_string_find_byte_backward, _dbus_read_local_machine_uuid.
void _dbus_string_toupper_ascii(const DBusString *str, int start, int len)
Converts the given range of the string to upper case.
str the string start first byte index to convert len number of bytes to convert
References DBUS_STRING_PREAMBLE, _dbus_assert, DBusRealString::str.
Referenced by _dbus_string_find_byte_backward.
dbus_bool_t _dbus_string_validate_ascii(const DBusString *str, int start, int len)
Checks that the given range of the string is valid ASCII with no nul bytes.
If the given range is not entirely contained in the string, returns FALSE.Todothis is inconsistent with most of DBusString in that it allows a start,len range that extends past the string end. str the string start first byte index to check len number of bytes to check TRUE if the byte range exists and is all valid ASCII
References DBUS_CONST_STRING_PREAMBLE, _dbus_assert, DBusRealString::len, FALSE, DBusRealString::str, TRUE.
Referenced by _dbus_keyring_validate_context, _dbus_generate_random_ascii.
dbus_bool_t _dbus_string_validate_utf8(const DBusString *str, int start, int len)
Checks that the given range of the string is valid UTF-8.
If the given range is not entirely contained in the string, returns FALSE. If the string contains any nul bytes in the given range, returns FALSE. If the start and start+len are not on character boundaries, returns FALSE.Todothis is inconsistent with most of DBusString in that it allows a start,len range that extends past the string end. str the string start first byte index to check len number of bytes to check TRUE if the byte range exists and is all valid UTF-8
References DBUS_CONST_STRING_PREAMBLE, _dbus_assert, DBusRealString::len, FALSE, DBusRealString::str, UTF8_COMPUTE, UTF8_GET, UTF8_LENGTH, UNICODE_VALID, TRUE.
Referenced by _dbus_validate_signature_with_reason, dbus_validate_path, dbus_validate_interface, dbus_validate_member, dbus_validate_error_name, dbus_validate_bus_name, dbus_validate_utf8, _dbus_printf_string_upper_bound.
dbus_bool_t _dbus_string_validate_nul(const DBusString *str, int start, int len)
Checks that the given range of the string is all nul bytes.
If the given range is not entirely contained in the string, returns FALSE.Todothis is inconsistent with most of DBusString in that it allows a start,len range that extends past the string end. str the string start first byte index to check len number of bytes to check TRUE if the byte range exists and is all nul bytes
References DBUS_CONST_STRING_PREAMBLE, _dbus_assert, DBusRealString::len, FALSE, DBusRealString::str, TRUE.
Referenced by _dbus_header_load.
void _dbus_string_zero(DBusString *str)
Clears all allocated bytes in the string to zero.
str the string
References DBUS_STRING_PREAMBLE, DBusRealString::str, DBusRealString::align_offset, DBusRealString::allocated.