dbus-timeout.h
DBusTimeoutList
Opaque data type representing a list of timeouts and a set of DBusAddTimeoutFunction/DBusRemoveTimeoutFunction.
Automatically handles removing/re-adding timeouts when the DBusAddTimeoutFunction is updated or changed. Holds a reference count to each timeout.
typedef dbus_bool_t(* DBusTimeoutHandler) (void *data))(void *data)
function to run when the timeout is handled
DBusTimeout * _dbus_timeout_new(int interval, DBusTimeoutHandler handler, void *data, DBusFreeFunction free_data_function)
Creates a new DBusTimeout, enabled by default.
interval the timeout interval in milliseconds. handler function to call when the timeout occurs. data data to pass to the handler free_data_function function to be called to free the data. the new DBusTimeout object,
References DBusTimeout::data, dbus_new0, DBusTimeout::enabled, DBusTimeout::free_data_function, DBusTimeout::free_handler_data_function, DBusTimeout::handler, DBusTimeout::handler_data, DBusTimeout::interval, NULL, DBusTimeout::refcount, TRUE.
Referenced by _dbus_pending_call_new_unlocked.
DBusTimeout * _dbus_timeout_ref(DBusTimeout *timeout)
Increments the reference count of a DBusTimeout object.
timeout the timeout object. the timeout object.
References DBusTimeout::refcount.
Referenced by _dbus_timeout_list_add_timeout.
void _dbus_timeout_unref(DBusTimeout *timeout)
Decrements the reference count of a DBusTimeout object and finalizes the object if the count reaches zero.
timeout the timeout object.
References _dbus_assert, dbus_free, dbus_timeout_set_data, DBusTimeout::free_handler_data_function, DBusTimeout::handler_data, NULL, DBusTimeout::refcount.
Referenced by _dbus_pending_call_ref_unlocked, _dbus_timeout_list_add_timeout, _dbus_timeout_list_free, _dbus_timeout_list_remove_timeout.
void _dbus_timeout_set_interval(DBusTimeout *timeout, int interval)
Changes the timeout interval.
Note that you have to disable and re-enable the timeout using the timeout toggle function (_dbus_connection_toggle_timeout_unlocked() etc.) to notify the application of this change. timeout the timeout interval the new interval
References _dbus_assert, DBusTimeout::interval.
void _dbus_timeout_set_enabled(DBusTimeout *timeout, dbus_bool_t enabled)
Changes the timeout's enabled-ness.
Note that you should use _dbus_connection_toggle_timeout_unlocked() etc. instead, if the timeout is passed out to an application main loop. i.e. you can't use this function in the D-Bus library, it's only used in the message bus daemon implementation. timeout the timeout enabled TRUE if timeout should be enabled.
References DBusTimeout::enabled, FALSE.
DBusTimeoutList * _dbus_timeout_list_new(void)
Creates a new timeout list.
Returns NULL if insufficient memory exists.the new timeout list, or NULL on failure.
References dbus_new0, NULL.
Referenced by _dbus_connection_new_for_transport, _dbus_server_init_base.
void _dbus_timeout_list_free(DBusTimeoutList *timeout_list)
Frees a DBusTimeoutList.
timeout_list the timeout list.
References _dbus_list_clear, _dbus_list_foreach, _dbus_timeout_list_set_functions, _dbus_timeout_unref, dbus_free, NULL, DBusTimeoutList::timeouts.
Referenced by _dbus_connection_new_for_transport, _dbus_server_finalize_base, _dbus_server_init_base, dbus_connection_ref.
dbus_bool_t _dbus_timeout_list_set_functions(DBusTimeoutList *timeout_list, DBusAddTimeoutFunction add_function, DBusRemoveTimeoutFunction remove_function, DBusTimeoutToggledFunction toggled_function, void *data, DBusFreeFunction free_data_function)
Sets the timeout functions.
This function is the "backend" for dbus_connection_set_timeout_functions(). timeout_list the timeout list add_function the add timeout function. remove_function the remove timeout function. toggled_function toggle notify function, or NULL data the data for those functions. free_data_function the function to free the data. FALSE if no memory
References _dbus_list_foreach, _dbus_list_get_first_link, _dbus_list_get_next_link, DBusTimeoutList::add_timeout_function, DBusList::data, DBusTimeout::data, FALSE, DBusTimeout::free_data_function, NULL, DBusTimeoutList::remove_timeout_function, DBusTimeoutList::timeout_data, DBusTimeoutList::timeout_free_data_function, DBusTimeoutList::timeout_toggled_function, DBusTimeoutList::timeouts, TRUE.
Referenced by _dbus_timeout_list_free, dbus_connection_set_timeout_functions, dbus_server_set_timeout_functions.
dbus_bool_t _dbus_timeout_list_add_timeout(DBusTimeoutList *timeout_list, DBusTimeout *timeout)
Adds a new timeout to the timeout list, invoking the application DBusAddTimeoutFunction if appropriate.
timeout_list the timeout list. timeout the timeout to add. TRUE on success, FALSE If no memory.
References _dbus_list_append, _dbus_list_remove_last, _dbus_timeout_ref, _dbus_timeout_unref, DBusTimeoutList::add_timeout_function, FALSE, NULL, DBusTimeoutList::timeout_data, DBusTimeoutList::timeouts, TRUE.
Referenced by _dbus_connection_add_timeout_unlocked, _dbus_server_add_timeout.
void _dbus_timeout_list_remove_timeout(DBusTimeoutList *timeout_list, DBusTimeout *timeout)
Removes a timeout from the timeout list, invoking the application's DBusRemoveTimeoutFunction if appropriate.
timeout_list the timeout list. timeout the timeout to remove.
References _dbus_assert_not_reached, _dbus_list_remove, _dbus_timeout_unref, NULL, DBusTimeoutList::remove_timeout_function, DBusTimeoutList::timeout_data, DBusTimeoutList::timeouts.
Referenced by _dbus_connection_remove_timeout_unlocked, _dbus_server_remove_timeout.
void _dbus_timeout_list_toggle_timeout(DBusTimeoutList *timeout_list, DBusTimeout *timeout, dbus_bool_t enabled)
Sets a timeout to the given enabled state, invoking the application's DBusTimeoutToggledFunction if appropriate.
timeout_list the timeout list. timeout the timeout to toggle. enabled TRUE to enable
References DBusTimeout::enabled, NULL, DBusTimeoutList::timeout_data, DBusTimeoutList::timeout_toggled_function.
Referenced by _dbus_connection_toggle_timeout_unlocked, _dbus_server_toggle_timeout.