dbus-file-unix.c
O_BINARY
N_TMP_FILENAME_RANDOM_BYTES
dbus_bool_t _dbus_file_get_contents(DBusString *str, const DBusString *filename, DBusError *error)
Appends the contents of the given file to the string, returning error code.
At the moment, won't open a file more than a megabyte in size. str the string to append to filename filename to load error place to set an error FALSE if error was set
Referenced by _dbus_uuid_encode, _dbus_sha_compute.
dbus_bool_t _dbus_string_save_to_file(const DBusString *str, const DBusString *filename, dbus_bool_t world_readable, DBusError *error)
Writes a string out to a file.
If the file exists, it will be atomically overwritten by the new data. str the string to write out filename the file to save string to world_readable If set, ensure the file is world readable error error to be filled in on failure FALSE on failure
Referenced by _dbus_write_uuid_file.
dbus_bool_t _dbus_make_file_world_readable(const DBusString *filename, DBusError *error)
Makes the file readable by every user in the system.
filename the filename error error location TRUE if the file's permissions could be changed.
Referenced by _dbus_string_save_to_file.
dbus_bool_t _dbus_create_file_exclusively(const DBusString *filename, DBusError *error)
Creates the given file, failing if the file already exists.
filename the filename error error location TRUE if we created the file and it didn't exist
dbus_bool_t _dbus_delete_file(const DBusString *filename, DBusError *error)
Deletes the given file.
filename the filename error error location TRUE if unlink() succeeded