dbus-userdb.c
DBUS_USERDB_INCLUDES_PRIVATE
dbus_bool_t database_locked
DBusUserDatabase* system_db
DBusString process_username
DBusString process_homedir
void _dbus_user_info_free_allocated(DBusUserInfo *info)
Frees the given DBusUserInfo's members with _dbus_user_info_free() and also calls dbus_free() on the block itself.
info the info
References _dbus_user_info_free, dbus_free, NULL.
Referenced by _dbus_user_database_lookup, _dbus_user_database_new.
void _dbus_group_info_free_allocated(DBusGroupInfo *info)
Frees the given DBusGroupInfo's members with _dbus_group_info_free() and also calls dbus_free() on the block itself.
info the info
References _dbus_group_info_free, dbus_free, NULL.
Referenced by _dbus_user_database_lookup_group, _dbus_user_database_new.
void _dbus_user_info_free(DBusUserInfo *info)
Frees the members of info (but not info itself)
info the user info struct
References dbus_free, DBusUserInfo::group_ids, DBusUserInfo::homedir, DBusUserInfo::username.
Referenced by _dbus_user_info_free_allocated.
void _dbus_group_info_free(DBusGroupInfo *info)
Frees the members of info (but not info itself).
info the group info
References dbus_free, DBusGroupInfo::groupname.
Referenced by _dbus_group_info_free_allocated.
dbus_bool_t _dbus_is_a_number(const DBusString *str, unsigned long *num)
Checks if a given string is actually a number and converts it if it is.
str the string to check num the memory location of the unsigned long to fill in TRUE if str is a number and num is filled in
References _dbus_string_parse_uint, FALSE, TRUE.
Referenced by _dbus_user_database_lookup, _dbus_user_database_lookup_group.
DBusUserInfo* _dbus_user_database_lookup(DBusUserDatabase *db, dbus_uid_t uid, const DBusString *username, DBusError *error)
Looks up a uid or username in the user database.
Only one of name or UID can be provided. There are wrapper functions for this that are better to use, this one does no locking or anything on the database and otherwise sort of sucks. db the database uid the user ID or DBUS_UID_UNSET username username or NULL error error to fill in the entry in the database
References _dbus_assert, _dbus_getuid, _dbus_hash_table_insert_string, _dbus_hash_table_insert_uintptr, _dbus_hash_table_lookup_string, _dbus_hash_table_lookup_uintptr, _dbus_hash_table_remove_uintptr, _dbus_is_a_number, _dbus_register_shutdown_func, _dbus_string_append, _dbus_string_free, _dbus_string_init, _dbus_user_database_get_uid, _dbus_user_database_new, _dbus_user_database_unref, _dbus_user_info_fill, _dbus_user_info_fill_uid, _dbus_user_info_free_allocated, _dbus_warn, dbus_error_free, dbus_error_has_name, DBUS_ERROR_INIT, DBUS_ERROR_NO_MEMORY, dbus_new0, dbus_set_error, DBUS_UID_FORMAT, DBUS_UID_UNSET, FALSE, DBusUserInfo::homedir, DBusError::message, NULL, TRUE, DBusUserInfo::uid, DBusUserInfo::username.
Referenced by _dbus_is_console_user, _dbus_user_database_get_uid, _dbus_user_database_get_username.
static void shutdown_system_db(void *data)
static dbus_bool_t init_system_db(void)
dbus_bool_t _dbus_user_database_lock_system(void)
Locks global system user database.
References _DBUS_LOCK, TRUE, FALSE.
Referenced by _dbus_is_console_user, _dbus_get_group_id, _dbus_get_user_id_and_primary_group, _dbus_groups_from_uid, _dbus_user_database_flush_system, _dbus_username_from_current_process, _dbus_homedir_from_current_process, _dbus_homedir_from_username, _dbus_homedir_from_uid, _dbus_credentials_add_from_user.
void _dbus_user_database_unlock_system(void)
Unlocks global system user database.
References FALSE, _DBUS_UNLOCK.
Referenced by _dbus_is_console_user, _dbus_get_group_id, _dbus_get_user_id_and_primary_group, _dbus_groups_from_uid, _dbus_user_database_flush_system, _dbus_username_from_current_process, _dbus_homedir_from_current_process, _dbus_homedir_from_username, _dbus_homedir_from_uid, _dbus_credentials_add_from_user.
DBusUserDatabase* _dbus_user_database_get_system(void)
Gets the system global user database; must be called with lock held (_dbus_user_database_lock_system()).
the database or NULL if no memory
References _dbus_assert.
Referenced by _dbus_credentials_add_from_user, _dbus_get_group_id, _dbus_get_user_id_and_primary_group, _dbus_groups_from_uid, _dbus_homedir_from_uid, _dbus_homedir_from_username, _dbus_is_console_user.
void _dbus_user_database_flush_system(void)
Flushes the system global user database;.
References _dbus_user_database_lock_system, NULL, _dbus_user_database_flush, _dbus_user_database_unlock_system.
Referenced by _dbus_flush_caches.
dbus_bool_t _dbus_username_from_current_process(const DBusString **username)
Gets username of user owning current process.
The returned string is valid until dbus_shutdown() is called. username place to store pointer to username FALSE if no memory
References _dbus_user_database_lock_system, _dbus_user_database_unlock_system, FALSE, TRUE.
Referenced by _dbus_groups_from_uid.
dbus_bool_t _dbus_homedir_from_current_process(const DBusString **homedir)
Gets homedir of user owning current process.
The returned string is valid until dbus_shutdown() is called. homedir place to store pointer to homedir FALSE if no memory
References _dbus_user_database_lock_system, _dbus_user_database_unlock_system, FALSE, TRUE.
Referenced by _dbus_get_standard_session_servicedirs, _dbus_groups_from_uid.
dbus_bool_t _dbus_homedir_from_username(const DBusString *username, DBusString *homedir)
Gets the home directory for the given user.
username the username homedir string to append home directory to TRUE if user existed and we appended their homedir
References _dbus_string_append, _dbus_user_database_get_system, _dbus_user_database_get_username, _dbus_user_database_lock_system, _dbus_user_database_unlock_system, FALSE, DBusUserInfo::homedir, NULL, TRUE.
dbus_bool_t _dbus_homedir_from_uid(dbus_uid_t uid, DBusString *homedir)
Gets the home directory for the given user.
uid the uid homedir string to append home directory to TRUE if user existed and we appended their homedir
References _dbus_string_append, _dbus_user_database_get_system, _dbus_user_database_get_uid, _dbus_user_database_lock_system, _dbus_user_database_unlock_system, FALSE, DBusUserInfo::homedir, NULL, TRUE.
Referenced by _dbus_append_keyring_directory_for_credentials.
dbus_bool_t _dbus_credentials_add_from_user(DBusCredentials *credentials, const DBusString *username)
Adds the credentials corresponding to the given username.
Used among other purposes to parses a desired identity provided from a client in the auth protocol. On UNIX this means parsing a UID, on Windows probably parsing an SID string.Todothis is broken because it treats OOM and parse error the same way. Needs a DBusError. credentials credentials to fill in username the username TRUE if the username existed and we got some credentials
References _dbus_credentials_add_unix_uid, _dbus_credentials_add_windows_sid, _dbus_user_database_get_system, _dbus_user_database_get_username, _dbus_user_database_lock_system, _dbus_user_database_unlock_system, FALSE, NULL, TRUE, DBusUserInfo::uid.
DBusUserDatabase* _dbus_user_database_new(void)
Creates a new user database object used to look up and cache user information.
new database, or NULL on out of memory
References _dbus_group_info_free_allocated, _dbus_hash_table_new, _dbus_user_database_unref, _dbus_user_info_free_allocated, DBUS_HASH_STRING, DBUS_HASH_UINTPTR, dbus_new0, NULL.
Referenced by _dbus_user_database_lookup.
void _dbus_user_database_flush(DBusUserDatabase *db)
Flush all information out of the user database.
References _dbus_hash_table_remove_all, _dbus_assert.
Referenced by _dbus_user_database_flush_system.
void _dbus_user_database_unref(DBusUserDatabase *db)
Decrements refcount of user database.
db the database
References _dbus_assert, _dbus_hash_table_unref, dbus_free.
Referenced by _dbus_user_database_lookup, _dbus_user_database_new.
dbus_bool_t _dbus_user_database_get_uid(DBusUserDatabase *db, dbus_uid_t uid, const DBusUserInfo **info, DBusError *error)
Gets the user information for the given UID, returned user info should not be freed.
db user database uid the user ID info return location for const ref to user info error error location FALSE if error is set
References _dbus_user_database_lookup, NULL.
Referenced by _dbus_groups_from_uid, _dbus_homedir_from_uid, _dbus_user_database_lookup.
dbus_bool_t _dbus_user_database_get_username(DBusUserDatabase *db, const DBusString *username, const DBusUserInfo **info, DBusError *error)
Gets the user information for the given username.
db user database username the user name info return location for const ref to user info error error location FALSE if error is set
References _dbus_user_database_lookup, DBUS_UID_UNSET, NULL.
Referenced by _dbus_credentials_add_from_user, _dbus_get_user_id_and_primary_group, _dbus_homedir_from_username.