dbus-marshal-header.h
_DBUS_HEADER_FIELD_VALUE_UNKNOWN
_DBUS_HEADER_FIELD_VALUE_NONEXISTENT
typedef struct DBusHeader DBusHeader
typedef struct DBusHeaderField DBusHeaderField
dbus_bool_t _dbus_header_init(DBusHeader *header)
Initializes a header, but doesn't prepare it for use; to make the header valid, you have to call _dbus_header_create().
header header to initialize FALSE if not enough memory
References _dbus_string_init_preallocated, DBusHeader::data, FALSE, _dbus_header_reinit, TRUE.
Referenced by dbus_message_get_reply_serial.
void _dbus_header_free(DBusHeader *header)
Frees a header.
header the header
References _dbus_string_free, DBusHeader::data.
Referenced by dbus_message_get_reply_serial, dbus_message_copy.
void _dbus_header_reinit(DBusHeader *header)
Re-initializes a header that was previously initialized and never freed.
After this, to make the header valid you have to call _dbus_header_create(). header header to re-initialize
References _dbus_string_set_length, DBusHeader::data, DBusHeader::padding.
Referenced by _dbus_header_init, dbus_message_get_reply_serial.
dbus_bool_t _dbus_header_create(DBusHeader *header, int byte_order, int type, const char *destination, const char *path, const char *interface, const char *member, const char *error_name)
Fills in the primary fields of the header, so the header is ready for use.
NULL may be specified for some or all of the fields to avoid adding those fields. Some combinations of fields don't make sense, and passing them in will trigger an assertion failure. header the header byte_order byte order of the header message_type the message type destination destination field or NULL path path field or NULL interface interface field or NULL member member field or NULL error_name error name or NULL FALSE if not enough memory
References _dbus_assert, DBUS_LITTLE_ENDIAN, DBUS_BIG_ENDIAN, DBUS_MESSAGE_TYPE_SIGNAL, DBusHeader::data, FALSE, _dbus_type_writer_init_values_only, HEADER_END_BEFORE_PADDING, _dbus_type_writer_write_basic, DBUS_TYPE_BYTE, DBUS_MAJOR_PROTOCOL_VERSION, DBUS_TYPE_UINT32, _dbus_type_writer_recurse, DBUS_TYPE_ARRAY, FIELDS_ARRAY_SIGNATURE_OFFSET, NULL, DBUS_HEADER_FIELD_PATH, DBUS_TYPE_OBJECT_PATH, DBUS_HEADER_FIELD_DESTINATION, DBUS_TYPE_STRING, DBUS_HEADER_FIELD_INTERFACE, DBUS_HEADER_FIELD_MEMBER, DBUS_HEADER_FIELD_ERROR_NAME, _dbus_type_writer_unrecurse, TRUE, _dbus_string_delete, DBusHeader::padding.
Referenced by dbus_message_new, dbus_message_new_method_call, dbus_message_new_method_return, dbus_message_new_signal, dbus_message_new_error.
dbus_bool_t _dbus_header_copy(const DBusHeader *header, DBusHeader *dest)
Initializes dest with a copy of the given header.
Resets the message serial to 0 on the copy. header header to copy dest destination for copy FALSE if not enough memory
References _dbus_string_init_preallocated, DBusHeader::data, FALSE, _dbus_string_copy, _dbus_string_free, _dbus_header_set_serial, TRUE.
Referenced by dbus_message_copy.
int _dbus_header_get_message_type(DBusHeader *header)
Gets the type of the message.
header the header the type
References DBusHeader::data, TYPE_OFFSET, _dbus_assert, DBUS_MESSAGE_TYPE_INVALID.
Referenced by _dbus_header_have_message_untrusted, dbus_message_get_type.
void _dbus_header_set_serial(DBusHeader *header, dbus_uint32_t serial)
Sets the serial number of a header.
This can only be done once on a header. header the header serial the serial
References _dbus_assert, _dbus_header_get_serial, _dbus_marshal_set_uint32, DBusHeader::data, SERIAL_OFFSET, _dbus_header_get_byte_order.
Referenced by _dbus_header_copy, dbus_message_set_serial.
dbus_uint32_t _dbus_header_get_serial(DBusHeader *header)
See dbus_message_get_serial()
header the header the client serial
References _dbus_marshal_read_uint32, DBusHeader::data, SERIAL_OFFSET, _dbus_header_get_byte_order, NULL.
Referenced by _dbus_header_set_serial, dbus_message_get_serial.
void _dbus_header_update_lengths(DBusHeader *header, int body_len)
Fills in the correct body length.
header the header body_len the length of the body
References _dbus_marshal_set_uint32, DBusHeader::data, BODY_LENGTH_OFFSET, _dbus_header_get_byte_order, FALSE, _dbus_type_reader_init, FIELDS_ARRAY_SIGNATURE_OFFSET, FIELDS_ARRAY_LENGTH_OFFSET, _dbus_type_reader_recurse, _dbus_type_reader_get_current_type, DBUS_TYPE_INVALID, _dbus_assert, DBUS_TYPE_BYTE, _dbus_type_reader_read_basic, DBUS_TYPE_STRUCT, TRUE, _dbus_type_reader_next.
Referenced by dbus_message_lock.
dbus_bool_t _dbus_header_set_field_basic(DBusHeader *header, int field, int type, const void *value)
Sets the value of a field with basic type.
If the value is a string value, it isn't allowed to be NULL. If the field doesn't exist, it will be created. header the header field the field to set type the type of the value value the value as for _dbus_marshal_set_basic() FALSE if no memory
References _dbus_assert, DBUS_HEADER_FIELD_LAST, FALSE, _dbus_assert_not_reached, _dbus_type_writer_init_values_only, _dbus_header_get_byte_order, FIELDS_ARRAY_SIGNATURE_OFFSET, DBusHeader::data, FIELDS_ARRAY_LENGTH_OFFSET, _dbus_type_writer_append_array, FIELDS_ARRAY_ELEMENT_SIGNATURE_OFFSET, DBusTypeWriter::u, FIRST_FIELD_OFFSET, DBusTypeWriter::value_pos, HEADER_END_BEFORE_PADDING, _dbus_type_writer_unrecurse, TRUE.
Referenced by dbus_message_lock, dbus_message_set_reply_serial, dbus_message_iter_init_append, dbus_message_iter_append_basic.
dbus_bool_t _dbus_header_get_field_basic(DBusHeader *header, int field, int type, void *value)
Gets the value of a field with basic type.
If the field doesn't exist, returns FALSE, otherwise returns TRUE. header the header field the field to get type the type of the value value the value as for _dbus_marshal_read_basic() FALSE if the field doesn't exist
References _dbus_assert, DBUS_HEADER_FIELD_INVALID, DBUS_HEADER_FIELD_LAST, EXPECTED_TYPE_OF_FIELD, FALSE, DBusHeader::fields, DBusHeaderField::value_pos, _dbus_marshal_read_basic, DBusHeader::data, _dbus_header_get_byte_order, NULL, TRUE.
Referenced by _dbus_header_have_message_untrusted, dbus_message_get_reply_serial, dbus_message_get_path, dbus_message_get_interface, dbus_message_get_member, dbus_message_get_error_name, dbus_message_get_destination, dbus_message_get_sender, _dbus_message_loader_return_unix_fds.
dbus_bool_t _dbus_header_get_field_raw(DBusHeader *header, int field, const DBusString **str, int *pos)
Gets the raw marshaled data for a field.
If the field doesn't exist, returns FALSE, otherwise returns TRUE. Returns the start of the marshaled data, i.e. usually the byte where the length starts (for strings and arrays) or for basic types just the value itself. header the header field the field to get str return location for the data string pos return location for start of field value FALSE if the field doesn't exist
References FALSE, DBusHeader::data, DBusHeader::fields, DBusHeaderField::value_pos, TRUE.
Referenced by _dbus_header_have_message_untrusted, dbus_message_iter_init_append.
dbus_bool_t _dbus_header_delete_field(DBusHeader *header, int field)
Deletes a field, if it exists.
header the header field the field to delete FALSE if no memory
References TRUE, FALSE, _dbus_type_reader_delete, _dbus_assert.
Referenced by dbus_message_lock.
void _dbus_header_toggle_flag(DBusHeader *header, dbus_uint32_t flag, dbus_bool_t value)
Toggles a message flag bit, turning on the bit if value = TRUE and flipping it off if value = FALSE.
header the header flag the message flag to toggle value toggle on or off
References _dbus_string_get_data_len, DBusHeader::data, FLAGS_OFFSET.
Referenced by dbus_message_set_no_reply, dbus_message_set_auto_start, dbus_message_set_allow_interactive_authorization.
dbus_bool_t _dbus_header_get_flag(DBusHeader *header, dbus_uint32_t flag)
Gets a message flag bit, returning TRUE if the bit is set.
header the header flag the message flag to get TRUE if the flag is set
References DBusHeader::data, FLAGS_OFFSET.
Referenced by dbus_message_get_no_reply, dbus_message_get_auto_start, dbus_message_get_allow_interactive_authorization.
dbus_bool_t _dbus_header_ensure_signature(DBusHeader *header, DBusString **type_str, int *type_pos)
dbus_bool_t _dbus_header_have_message_untrusted(int max_message_length, DBusValidity *validity, int *byte_order, int *fields_array_len, int *header_len, int *body_len, const DBusString *str, int start, int len)
Given data long enough to contain the length of the message body and the fields array, check whether the data is long enough to contain the entire message (assuming the claimed lengths are accurate).
Also checks that the lengths are in sanity parameters. max_message_length maximum length of a valid message validity return location for why the data is invalid if it is byte_order return location for byte order fields_array_len return location for claimed fields array length header_len return location for claimed header length body_len return location for claimed body length str the data start start of data, 8-aligned len length of data TRUE if the data is long enough for the claimed length, and the lengths were valid
References _dbus_assert, _DBUS_INT32_MAX, BYTE_ORDER_OFFSET, DBUS_LITTLE_ENDIAN, DBUS_BIG_ENDIAN, FALSE, FIELDS_ARRAY_LENGTH_OFFSET, _dbus_marshal_read_uint32, NULL, BODY_LENGTH_OFFSET, FIRST_FIELD_OFFSET, DBUS_VALID, _dbus_header_get_message_type, DBUS_MESSAGE_TYPE_SIGNAL, DBUS_MESSAGE_TYPE_METHOD_CALL, DBUS_MESSAGE_TYPE_ERROR, DBUS_MESSAGE_TYPE_METHOD_RETURN, DBUS_HEADER_FIELD_LAST, DBUS_HEADER_FIELD_INVALID, _dbus_type_reader_get_current_type, EXPECTED_TYPE_OF_FIELD, DBusHeader::fields, DBusHeaderField::value_pos, DBUS_TYPE_UINT32, _dbus_header_get_field_basic, DBUS_TYPE_STRING, DBUS_TYPE_OBJECT_PATH, DBUS_TYPE_SIGNATURE, _dbus_header_get_field_raw, _dbus_assert_not_reached, DBUS_HEADER_FIELD_DESTINATION, _dbus_validate_bus_name, DBUS_HEADER_FIELD_INTERFACE, _dbus_validate_interface, _dbus_string_equal_substring, DBUS_HEADER_FIELD_MEMBER, _dbus_validate_member, DBUS_HEADER_FIELD_ERROR_NAME, _dbus_validate_error_name, DBUS_HEADER_FIELD_SENDER, DBUS_HEADER_FIELD_PATH, DBUS_HEADER_FIELD_REPLY_SERIAL, DBUS_HEADER_FIELD_UNIX_FDS, DBUS_HEADER_FIELD_SIGNATURE, _dbus_header_get_byte_order.
Referenced by _dbus_message_loader_queue_messages, dbus_message_demarshal_bytes_needed.
dbus_bool_t _dbus_header_load(DBusHeader *header, DBusValidationMode mode, DBusValidity *validity, int byte_order, int fields_array_len, int header_len, int body_len, const DBusString *str, int start, int len)
Creates a message header from potentially-untrusted data.
The return value is TRUE if there was enough memory and the data was valid. If it returns TRUE, the header will be created. If it returns FALSE and *validity == DBUS_VALIDITY_UNKNOWN_OOM_ERROR, then there wasn't enough memory. If it returns FALSE and *validity != DBUS_VALIDITY_UNKNOWN_OOM_ERROR then the data was invalid.The byte_order, fields_array_len, and body_len args should be from _dbus_header_have_message_untrusted(). Validation performed in _dbus_header_have_message_untrusted() is assumed to have been already done. header the header (must be initialized) mode whether to do validation validity return location for invalidity reason byte_order byte order from header fields_array_len claimed length of fields array body_len claimed length of body header_len claimed length of header str a string start start of header, 8-aligned len length of string to look at FALSE if no memory or data was invalid, TRUE otherwise
References _dbus_assert, DBusHeader::data, _dbus_string_copy_len, DBUS_VALIDITY_UNKNOWN_OOM_ERROR, FALSE, _dbus_validate_body_with_reason, DBUS_VALID, FIRST_FIELD_OFFSET, _dbus_string_validate_nul, DBusHeader::padding, TRUE, _dbus_type_reader_init, _dbus_type_reader_get_current_type, DBUS_TYPE_BYTE, _dbus_type_reader_get_value_pos, BYTE_ORDER_OFFSET, _dbus_type_reader_read_basic, _dbus_type_reader_next, TYPE_OFFSET, DBUS_MESSAGE_TYPE_INVALID, FLAGS_OFFSET, VERSION_OFFSET, DBUS_MAJOR_PROTOCOL_VERSION, DBUS_TYPE_UINT32, BODY_LENGTH_OFFSET, SERIAL_OFFSET, DBUS_TYPE_ARRAY, FIELDS_ARRAY_LENGTH_OFFSET, _dbus_type_reader_recurse, DBUS_TYPE_INVALID, DBUS_TYPE_STRUCT, DBUS_HEADER_FIELD_INVALID, DBUS_HEADER_FIELD_LAST, DBUS_TYPE_VARIANT, DBusHeader::fields, DBusHeaderField::value_pos, _dbus_string_set_length.
Referenced by _dbus_message_loader_return_unix_fds.
void _dbus_header_byteswap(DBusHeader *header, int new_order)
Swaps the header into the given order if required.
header the header new_order the new byte order
References _dbus_header_get_byte_order, _dbus_marshal_byteswap, DBusHeader::data, BYTE_ORDER_OFFSET.
char _dbus_header_get_byte_order(const DBusHeader *header)
Returns the header's byte order.
header the header the byte order
References _dbus_assert, DBusHeader::data, BYTE_ORDER_OFFSET, DBUS_HEADER_FIELD_LAST, DBusHeader::fields, DBusHeaderField::value_pos, _dbus_type_reader_init, _dbus_header_get_byte_order, FIELDS_ARRAY_SIGNATURE_OFFSET, FIELDS_ARRAY_LENGTH_OFFSET, _dbus_type_reader_recurse, _dbus_type_reader_get_current_type, DBUS_TYPE_INVALID, DBUS_TYPE_BYTE, _dbus_type_reader_read_basic, _dbus_type_reader_next, DBUS_TYPE_VARIANT, FALSE, TRUE, DBusTypeWriter::value_pos, DBusTypeWriter::value_str, _dbus_type_writer_recurse, DBUS_TYPE_STRUCT, NULL, _dbus_type_writer_write_basic, _dbus_string_init_const_len, _dbus_type_writer_unrecurse, _dbus_string_delete, _dbus_assert_not_reached, _dbus_type_reader_set_basic.
Referenced by _dbus_header_get_byte_order, _dbus_header_set_serial, _dbus_header_get_serial, _dbus_header_have_message_untrusted, _dbus_header_update_lengths, _dbus_header_set_field_basic, _dbus_header_get_field_basic, _dbus_header_byteswap, dbus_message_iter_init, dbus_message_iter_init_append.