dbus-sysdeps-pthread.c
DBUS_MUTEX
DBUS_MUTEX_PTHREAD
DBUS_COND_VAR
DBUS_COND_VAR_PTHREAD
PTHREAD_CHECK
pthread_mutex_t init_mutex
DBusCMutex* _dbus_platform_cmutex_new(void)
DBusRMutex* _dbus_platform_rmutex_new(void)
void _dbus_platform_cmutex_free(DBusCMutex *mutex)
void _dbus_platform_rmutex_free(DBusRMutex *mutex)
void _dbus_platform_cmutex_lock(DBusCMutex *mutex)
void _dbus_platform_rmutex_lock(DBusRMutex *mutex)
void _dbus_platform_cmutex_unlock(DBusCMutex *mutex)
void _dbus_platform_rmutex_unlock(DBusRMutex *mutex)
DBusCondVar* _dbus_platform_condvar_new(void)
void _dbus_platform_condvar_free(DBusCondVar *cond)
void _dbus_platform_condvar_wait(DBusCondVar *cond, DBusCMutex *mutex)
dbus_bool_t _dbus_platform_condvar_wait_timeout(DBusCondVar *cond, DBusCMutex *mutex, int timeout_milliseconds)
void _dbus_platform_condvar_wake_one(DBusCondVar *cond)
static void check_monotonic_clock(void)
dbus_bool_t _dbus_threads_init_platform_specific(void)
Initialize threads as in dbus_threads_init_default(), appropriately for the platform.
FALSE if no memory
Referenced by dbus_threads_init.
void _dbus_threads_lock_platform_specific(void)
Lock a static mutex used to protect _dbus_threads_init_platform_specific().
Referenced by dbus_shutdown, dbus_threads_init.
void _dbus_threads_unlock_platform_specific(void)
Undo _dbus_threads_lock_platform_specific().
Referenced by dbus_shutdown, dbus_threads_init.