dbus-auth.c
DBUS_AUTH_IS_SERVER
auth the auth conversation TRUE if the conversation is the server side
Referenced by _dbus_auth_unref.
DBUS_AUTH_IS_CLIENT
auth the auth conversation TRUE if the conversation is the client side
Referenced by _dbus_auth_decode_data, _dbus_auth_encode_data, _dbus_auth_get_guid_from_server, _dbus_auth_needs_decoding, _dbus_auth_needs_encoding, _dbus_auth_unref.
DBUS_AUTH_CLIENT
auth the auth conversation auth cast to DBusAuthClient
Referenced by _dbus_auth_client_new, _dbus_auth_get_guid_from_server, _dbus_auth_unref.
DBUS_AUTH_SERVER
auth the auth conversation auth cast to DBusAuthServer
Referenced by _dbus_auth_server_new, _dbus_auth_unref.
DBUS_AUTH_NAME
The name of the auth ("client" or "server")
auth the auth conversation a string
Referenced by _dbus_auth_bytes_sent, _dbus_auth_do_work.
N_CHALLENGE_BYTES
http://www.ietf.org/rfc/rfc2831.txt suggests at least 64 bits of entropy, we use 128.
This is the number of bytes in the random challenge.
DBUS_AUTH_IN_END_STATE
auth the auth conversation object TRUE if we're in a final state
Referenced by _dbus_auth_delete_unused_bytes, _dbus_auth_do_work, _dbus_auth_get_unused_bytes.
MAX_BUFFER
DBusAuthCommand
typedef dbus_bool_t(* DBusInitialResponseFunction) (DBusAuth *auth, DBusString *response))(DBusAuth *auth, DBusString *response)
This function appends an initial client response to the given string.
typedef dbus_bool_t(* DBusAuthDataFunction) (DBusAuth *auth, const DBusString *data))(DBusAuth *auth, const DBusString *data)
This function processes a block of data received from the peer.
i.e. handles a DATA command.
typedef dbus_bool_t(* DBusAuthEncodeFunction) (DBusAuth *auth, const DBusString *data, DBusString *encoded))(DBusAuth *auth, const DBusString *data, DBusString *encoded)
This function encodes a block of data from the peer.
typedef dbus_bool_t(* DBusAuthDecodeFunction) (DBusAuth *auth, const DBusString *data, DBusString *decoded))(DBusAuth *auth, const DBusString *data, DBusString *decoded)
This function decodes a block of data from the peer.
typedef void(* DBusAuthShutdownFunction) (DBusAuth *auth))(DBusAuth *auth)
This function is called when the mechanism is abandoned.
typedef dbus_bool_t(* DBusAuthStateFunction) (DBusAuth *auth, DBusAuthCommand command, const DBusString *args))(DBusAuth *auth, DBusAuthCommand command, const DBusString *args)
Auth state function, determines the reaction to incoming events for a particular state.
Returns whether we had enough memory to complete the operation.
const DBusAuthStateData server_state_waiting_for_auth
const DBusAuthStateData server_state_waiting_for_data
const DBusAuthStateData server_state_waiting_for_begin
const DBusAuthStateData client_state_need_send_auth
const DBusAuthStateData client_state_waiting_for_data
const DBusAuthStateData client_state_waiting_for_ok
const DBusAuthStateData client_state_waiting_for_reject
const DBusAuthStateData client_state_waiting_for_agree_unix_fd
const DBusAuthStateData common_state_authenticated
Common terminal states.
Terminal states have handler == NULL.
const DBusAuthStateData common_state_need_disconnect
const char auth_side_client[][]
const char auth_side_server[][]
const DBusAuthMechanismHandler all_mechanisms[][]
const DBusAuthCommandName auth_command_names[][]
static void goto_state(DBusAuth *auth, const DBusAuthStateData *new_state)
static dbus_bool_t send_auth(DBusAuth *auth, const DBusAuthMechanismHandler *mech)
static dbus_bool_t send_data(DBusAuth *auth, DBusString *data)
static dbus_bool_t send_rejected(DBusAuth *auth)
static dbus_bool_t send_error(DBusAuth *auth, const char *message)
static dbus_bool_t send_ok(DBusAuth *auth)
static dbus_bool_t send_begin(DBusAuth *auth)
static dbus_bool_t send_cancel(DBusAuth *auth)
static dbus_bool_t send_negotiate_unix_fd(DBusAuth *auth)
static dbus_bool_t send_agree_unix_fd(DBusAuth *auth)
static dbus_bool_t handle_server_state_waiting_for_auth(DBusAuth *auth, DBusAuthCommand command, const DBusString *args)
Client states.
static dbus_bool_t handle_server_state_waiting_for_data(DBusAuth *auth, DBusAuthCommand command, const DBusString *args)
static dbus_bool_t handle_server_state_waiting_for_begin(DBusAuth *auth, DBusAuthCommand command, const DBusString *args)
static dbus_bool_t handle_client_state_waiting_for_data(DBusAuth *auth, DBusAuthCommand command, const DBusString *args)
Client states.
static dbus_bool_t handle_client_state_waiting_for_ok(DBusAuth *auth, DBusAuthCommand command, const DBusString *args)
static dbus_bool_t handle_client_state_waiting_for_reject(DBusAuth *auth, DBusAuthCommand command, const DBusString *args)
static dbus_bool_t handle_client_state_waiting_for_agree_unix_fd(DBusAuth *auth, DBusAuthCommand command, const DBusString *args)
static DBusAuth* _dbus_auth_new(int size)
static void shutdown_mech(DBusAuth *auth)
static dbus_bool_t sha1_compute_hash(DBusAuth *auth, int cookie_id, const DBusString *server_challenge, const DBusString *client_challenge, DBusString *hash)
static dbus_bool_t sha1_handle_first_client_response(DBusAuth *auth, const DBusString *data)
static dbus_bool_t sha1_handle_second_client_response(DBusAuth *auth, const DBusString *data)
static dbus_bool_t handle_server_data_cookie_sha1_mech(DBusAuth *auth, const DBusString *data)
static void handle_server_shutdown_cookie_sha1_mech(DBusAuth *auth)
static dbus_bool_t handle_client_initial_response_cookie_sha1_mech(DBusAuth *auth, DBusString *response)
static dbus_bool_t handle_client_data_cookie_sha1_mech(DBusAuth *auth, const DBusString *data)
static void handle_client_shutdown_cookie_sha1_mech(DBusAuth *auth)
static dbus_bool_t handle_server_data_external_mech(DBusAuth *auth, const DBusString *data)
static void handle_server_shutdown_external_mech(DBusAuth *auth)
static dbus_bool_t handle_client_initial_response_external_mech(DBusAuth *auth, DBusString *response)
static dbus_bool_t handle_client_data_external_mech(DBusAuth *auth, const DBusString *data)
static void handle_client_shutdown_external_mech(DBusAuth *auth)
static dbus_bool_t handle_server_data_anonymous_mech(DBusAuth *auth, const DBusString *data)
static void handle_server_shutdown_anonymous_mech(DBusAuth *auth)
static dbus_bool_t handle_client_initial_response_anonymous_mech(DBusAuth *auth, DBusString *response)
static dbus_bool_t handle_client_data_anonymous_mech(DBusAuth *auth, const DBusString *data)
static void handle_client_shutdown_anonymous_mech(DBusAuth *auth)
static const DBusAuthMechanismHandler* find_mech(const DBusString *name, char **allowed_mechs)
static dbus_bool_t process_ok(DBusAuth *auth, const DBusString *args_from_ok)
static dbus_bool_t process_data(DBusAuth *auth, const DBusString *args, DBusAuthDataFunction data_func)
static dbus_bool_t handle_auth(DBusAuth *auth, const DBusString *args)
static dbus_bool_t get_word(const DBusString *str, int *start, DBusString *word)
static dbus_bool_t record_mechanisms(DBusAuth *auth, const DBusString *args)
static dbus_bool_t process_rejected(DBusAuth *auth, const DBusString *args)
static DBusAuthCommand lookup_command_from_name(DBusString *command)
static dbus_bool_t process_command(DBusAuth *auth)
DBusAuth* _dbus_auth_server_new(const DBusString *guid)
Creates a new auth conversation object for the server side.
See http://dbus.freedesktop.org/doc/dbus-specification.html#auth-protocol for full details on what this object does.the new object or NULL if no memory
References _dbus_string_copy, _dbus_string_free, _dbus_string_init, DBUS_AUTH_SERVER, DBusAuthServer::failures, DBusAuthServer::guid, DBusAuthServer::max_failures, NULL, DBusAuth::side, DBusAuth::state.
Referenced by _dbus_transport_init_base.
DBusAuth* _dbus_auth_client_new(void)
Creates a new auth conversation object for the client side.
See http://dbus.freedesktop.org/doc/dbus-specification.html#auth-protocol for full details on what this object does.the new object or NULL if no memory
References _dbus_auth_unref, _dbus_string_free, _dbus_string_init, DBUS_AUTH_CLIENT, NULL, DBusAuth::side, DBusAuth::state.
Referenced by _dbus_transport_init_base.
DBusAuth* _dbus_auth_ref(DBusAuth *auth)
Increments the refcount of an auth object.
auth the auth conversation the auth conversation
References _dbus_assert, NULL, DBusAuth::refcount.
void _dbus_auth_unref(DBusAuth *auth)
Decrements the refcount of an auth object.
auth the auth conversation
References _dbus_assert, _dbus_credentials_unref, _dbus_keyring_unref, _dbus_list_clear, _dbus_string_free, DBusAuth::allowed_mechs, DBusAuth::authorized_identity, DBusAuth::challenge, DBusAuth::context, DBusAuth::credentials, DBUS_AUTH_CLIENT, DBUS_AUTH_IS_CLIENT, DBUS_AUTH_IS_SERVER, DBUS_AUTH_SERVER, dbus_free, dbus_free_string_array, DBusAuth::desired_identity, DBusAuth::identity, DBusAuth::incoming, DBusAuth::keyring, NULL, DBusAuth::outgoing, DBusAuth::refcount.
Referenced by _dbus_auth_client_new, _dbus_transport_finalize_base, _dbus_transport_init_base.
dbus_bool_t _dbus_auth_set_mechanisms(DBusAuth *auth, const char **mechanisms)
Sets an array of authentication mechanism names that we are willing to use.
auth the auth conversation mechanisms NULL-terminated array of mechanism names FALSE if no memory
References _dbus_dup_string_array, DBusAuth::allowed_mechs, dbus_free_string_array, FALSE, NULL, TRUE.
Referenced by _dbus_transport_set_auth_mechanisms.
DBusAuthState _dbus_auth_do_work(DBusAuth *auth)
Analyzes buffered input and moves the auth conversation forward, returning the new state of the auth conversation.
auth the auth conversation the new state
References DBUS_AUTH_IN_END_STATE, DBUS_AUTH_NAME, FALSE, DBusAuth::incoming, DBusAuth::needed_memory, DBusAuth::outgoing, DBusAuth::state.
Referenced by _dbus_transport_get_dispatch_status, _dbus_transport_try_to_authenticate.
dbus_bool_t _dbus_auth_get_bytes_to_send(DBusAuth *auth, const DBusString **str)
Gets bytes that need to be sent to the peer we're conversing with.
After writing some bytes, _dbus_auth_bytes_sent() must be called to notify the auth object that they were written. auth the auth conversation str return location for a ref to the buffer to send FALSE if nothing to send
References _dbus_assert, FALSE, NULL, DBusAuth::outgoing, TRUE.
void _dbus_auth_bytes_sent(DBusAuth *auth, int bytes_sent)
Notifies the auth conversation object that the given number of bytes of the outgoing buffer have been written out.
auth the auth conversation bytes_sent number of bytes written out
References _dbus_string_delete, DBUS_AUTH_NAME, DBusAuth::outgoing.
void _dbus_auth_get_buffer(DBusAuth *auth, DBusString **buffer)
Get a buffer to be used for reading bytes from the peer we're conversing with.
Bytes should be appended to this buffer. auth the auth conversation buffer return location for buffer to append bytes to
References _dbus_assert, DBusAuth::buffer_outstanding, DBusAuth::incoming, NULL, TRUE.
void _dbus_auth_return_buffer(DBusAuth *auth, DBusString *buffer)
Returns a buffer with new data read into it.
auth the auth conversation buffer the buffer being returned
References _dbus_assert, DBusAuth::buffer_outstanding, FALSE, DBusAuth::incoming.
void _dbus_auth_get_unused_bytes(DBusAuth *auth, const DBusString **str)
Returns leftover bytes that were not used as part of the auth conversation.
These bytes will be part of the message stream instead. This function may not be called until authentication has succeeded. auth the auth conversation str return location for pointer to string of unused bytes
References DBUS_AUTH_IN_END_STATE, DBusAuth::incoming.
Referenced by _dbus_transport_do_iteration.
void _dbus_auth_delete_unused_bytes(DBusAuth *auth)
Gets rid of unused bytes returned by _dbus_auth_get_unused_bytes() after we've gotten them and successfully moved them elsewhere.
auth the auth conversation
References _dbus_string_set_length, DBUS_AUTH_IN_END_STATE, DBusAuth::incoming.
Referenced by _dbus_transport_do_iteration.
dbus_bool_t _dbus_auth_needs_encoding(DBusAuth *auth)
Called post-authentication, indicates whether we need to encode the message stream with _dbus_auth_encode_data() prior to sending it to the peer.
auth the auth conversation TRUE if we need to encode the stream
References DBusAuthMechanismHandler::client_encode_func, DBUS_AUTH_IS_CLIENT, FALSE, DBusAuth::mech, NULL, DBusAuthMechanismHandler::server_encode_func, DBusAuth::state.
Referenced by _dbus_auth_encode_data.
dbus_bool_t _dbus_auth_encode_data(DBusAuth *auth, const DBusString *plaintext, DBusString *encoded)
Called post-authentication, encodes a block of bytes for sending to the peer.
If no encoding was negotiated, just copies the bytes (you can avoid this by checking _dbus_auth_needs_encoding()). auth the auth conversation plaintext the plain text data encoded initialized string to where encoded data is appended TRUE if we had enough memory and successfully encoded
References _dbus_assert, _dbus_auth_needs_encoding, _dbus_string_copy, DBusAuthMechanismHandler::client_encode_func, DBUS_AUTH_IS_CLIENT, FALSE, DBusAuth::mech, DBusAuthMechanismHandler::server_encode_func, DBusAuth::state.
dbus_bool_t _dbus_auth_needs_decoding(DBusAuth *auth)
Called post-authentication, indicates whether we need to decode the message stream with _dbus_auth_decode_data() after receiving it from the peer.
auth the auth conversation TRUE if we need to encode the stream
References DBusAuthMechanismHandler::client_decode_func, DBUS_AUTH_IS_CLIENT, FALSE, DBusAuth::mech, NULL, DBusAuthMechanismHandler::server_decode_func, DBusAuth::state.
Referenced by _dbus_auth_decode_data, _dbus_transport_do_iteration.
dbus_bool_t _dbus_auth_decode_data(DBusAuth *auth, const DBusString *encoded, DBusString *plaintext)
Called post-authentication, decodes a block of bytes received from the peer.
If no encoding was negotiated, just copies the bytes (you can avoid this by checking _dbus_auth_needs_decoding()).Todo1.0? We need to be able to distinguish "out of memory" error from "the data is hosed" error. auth the auth conversation encoded the encoded data plaintext initialized string where decoded data is appended TRUE if we had enough memory and successfully decoded
References _dbus_assert, _dbus_auth_needs_decoding, _dbus_string_copy, DBusAuthMechanismHandler::client_decode_func, DBUS_AUTH_IS_CLIENT, FALSE, DBusAuth::mech, DBusAuthMechanismHandler::server_decode_func, DBusAuth::state.
Referenced by _dbus_transport_do_iteration.
dbus_bool_t _dbus_auth_set_credentials(DBusAuth *auth, DBusCredentials *credentials)
Sets credentials received via reliable means from the operating system.
auth the auth conversation credentials the credentials received FALSE on OOM
References _dbus_credentials_add_credentials, _dbus_credentials_clear, DBusAuth::credentials.
DBusCredentials* _dbus_auth_get_identity(DBusAuth *auth)
Gets the identity we authorized the client as.
Apps may have different policies as to what identities they allow.Returned credentials are not a copy and should not be modified auth the auth conversation the credentials we've authorized BY REFERENCE do not modify
References _dbus_assert, _dbus_credentials_are_empty, DBusAuth::authorized_identity, DBusAuth::state.
Referenced by _dbus_transport_get_adt_audit_session_data, _dbus_transport_get_is_anonymous, _dbus_transport_get_is_connected, _dbus_transport_get_unix_process_id, _dbus_transport_get_unix_user, _dbus_transport_get_windows_user, _dbus_transport_try_to_authenticate.
const char* _dbus_auth_get_guid_from_server(DBusAuth *auth)
Gets the GUID from the server if we've authenticated; gets NULL otherwise.
auth the auth object the GUID in ASCII hex format
References _dbus_assert, DBUS_AUTH_CLIENT, DBUS_AUTH_IS_CLIENT, NULL, DBusAuth::state.
Referenced by _dbus_transport_get_server_id, _dbus_transport_try_to_authenticate.
dbus_bool_t _dbus_auth_set_context(DBusAuth *auth, const DBusString *context)
Sets the "authentication context" which scopes cookies with the DBUS_COOKIE_SHA1 auth mechanism for example.
auth the auth conversation context the context FALSE if no memory
References _dbus_string_replace_len, DBusAuth::context.
void _dbus_auth_set_unix_fd_possible(DBusAuth *auth, dbus_bool_t b)
Sets whether unix fd passing is potentially on the transport and hence shall be negotiated.
auth the auth conversation b TRUE when unix fd passing shall be negotiated, otherwise FALSE
References DBusAuth::unix_fd_possible.
Referenced by _dbus_transport_new_for_socket.
dbus_bool_t _dbus_auth_get_unix_fd_negotiated(DBusAuth *auth)
Queries whether unix fd passing was successfully negotiated.
auth the auth conversion TRUE when unix fd passing was negotiated.
References DBusAuth::unix_fd_negotiated.