dbus-sysdeps.c
MAX_LONG_LEN
MAX_ULONG_LEN
char** environ
void _dbus_abort(void)
Aborts the program with SIGABRT (dumping core).
References _dbus_print_backtrace, _dbus_getenv, _dbus_pid_for_log, _dbus_sleep_milliseconds, _dbus_exit.
Referenced by _dbus_warn, _dbus_warn_check_failed, _dbus_real_assert, _dbus_real_assert_not_reached, dbus_malloc, dbus_malloc0, dbus_realloc, _dbus_write_socket_two, _dbus_get_tmpdir.
dbus_bool_t dbus_setenv(const char *varname, const char *value)
Wrapper for setenv().
If the value is NULL, unsets the environment variable.There is an unfixable memleak in that it is unsafe to free memory malloced for use with setenv. This is because we can not rely on internal implementation details of the underlying libc library.This function is not thread-safe, because altering the environment in Unix is not thread-safe in general. varname name of environment variable value value of environment variable, or NULL to unset TRUE on success, FALSE if not enough memory.
References _dbus_assert, NULL, TRUE, FALSE.
Referenced by _dbus_server_new_for_launchd.
const char * _dbus_getenv(const char *varname)
Wrapper for getenv().
varname name of environment variable value of environment variable or NULL if unset
References _dbus_check_setuid, NULL.
Referenced by _dbus_abort, _dbus_append_keyring_directory_for_credentials, _dbus_become_daemon, _dbus_get_autolaunch_address, _dbus_get_standard_session_servicedirs, _dbus_real_assert_not_reached, _dbus_server_new_for_launchd, _dbus_spawn_async_with_babysitter, _dbus_warn_check_failed.
dbus_bool_t _dbus_clearenv(void)
Wrapper for clearenv().
TRUE on success.
References FALSE, NULL, TRUE.
dbus_bool_t _dbus_split_paths_and_append(DBusString *dirs, const char *suffix, DBusList **dir_list)
Split paths into a list of char strings.
dirs string with pathes suffix string concated to each path in dirs dir_list contains a list of splitted pathes return TRUE is pathes could be splittes,FALSE in oom case
References _dbus_concat_dir_and_file, _dbus_list_append, _dbus_list_clear, _dbus_list_foreach, _dbus_string_chop_white, _dbus_string_copy_data, _dbus_string_copy_len, _dbus_string_find, _dbus_string_free, _dbus_string_init, _dbus_string_init_const, dbus_free, FALSE, NULL, TRUE.
Referenced by _dbus_get_standard_session_servicedirs, _dbus_get_standard_system_servicedirs.
dbus_bool_t _dbus_string_append_int(DBusString *str, long value)
Appends an integer to a DBusString.
str the string value the integer value FALSE if not enough memory or other failure.
References _dbus_string_get_data_len, _dbus_string_lengthen, _dbus_string_shorten, FALSE, TRUE.
Referenced by _dbus_string_find_byte_backward, _dbus_write_pid_to_file_and_pipe, dbus_get_version.
dbus_bool_t _dbus_string_append_uint(DBusString *str, unsigned long value)
Appends an unsigned integer to a DBusString.
str the string value the integer value FALSE if not enough memory or other failure.
References _dbus_string_get_data_len, _dbus_string_lengthen, _dbus_string_shorten, FALSE, TRUE.
Referenced by _dbus_append_user_from_current_process.
dbus_bool_t _dbus_string_parse_int(const DBusString *str, int start, long *value_return, int *end_return)
Parses an integer contained in a DBusString.
Either return parameter may be NULL if you aren't interested in it. The integer is parsed and stored in value_return. Return parameters are not initialized if the function returns FALSE. str the string start the byte index of the start of the integer value_return return location of the integer value or NULL end_return return location of the end of the integer, or NULL TRUE on success
References _dbus_set_errno_to_zero, FALSE, NULL, TRUE.
Referenced by _dbus_parse_uid, _dbus_real_assert_not_reached, _dbus_sha_compute, _dbus_string_find_byte_backward.
dbus_bool_t _dbus_string_parse_uint(const DBusString *str, int start, unsigned long *value_return, int *end_return)
Parses an unsigned integer contained in a DBusString.
Either return parameter may be NULL if you aren't interested in it. The integer is parsed and stored in value_return. Return parameters are not initialized if the function returns FALSE. str the string start the byte index of the start of the integer value_return return location of the integer value or NULL end_return return location of the end of the integer, or NULL TRUE on success
References _dbus_set_errno_to_zero, FALSE, NULL, TRUE.
Referenced by _dbus_is_a_number.
void _dbus_generate_pseudorandom_bytes_buffer(char *buffer, int n_bytes)
Random numbers.
References _dbus_get_real_time, NULL.
Referenced by _dbus_sleep_milliseconds, _dbus_generate_random_bytes_buffer.
void _dbus_generate_random_bytes_buffer(char *buffer, int n_bytes)
Fills n_bytes of the given buffer with random bytes.
buffer an allocated buffer n_bytes the number of bytes in buffer to write to
References _dbus_generate_pseudorandom_bytes_buffer, _dbus_generate_random_bytes, _dbus_string_copy_to_buffer, _dbus_string_free, _dbus_string_init.
Referenced by _dbus_generate_uuid.
dbus_bool_t _dbus_generate_random_ascii(DBusString *str, int n_bytes)
Generates the given number of random bytes, where the bytes are chosen from the alphanumeric ASCII subset.
str the string n_bytes the number of random ASCII bytes to append to string TRUE on success, FALSE if no memory or other failure
References _dbus_assert, _dbus_generate_random_bytes, _dbus_string_validate_ascii, FALSE, TRUE.
Referenced by _dbus_server_listen_platform_specific, _dbus_string_save_to_file.
const char* _dbus_error_from_errno(int error_number)
Converts a UNIX errno, or Windows errno or WinSock error value into a DBusError name.
Todoshould cover more errnos, specifically those from open(). error_number the errno. an error name
References DBUS_ERROR_ACCESS_DENIED, DBUS_ERROR_ADDRESS_IN_USE, DBUS_ERROR_FAILED, DBUS_ERROR_FILE_EXISTS, DBUS_ERROR_FILE_NOT_FOUND, DBUS_ERROR_LIMITS_EXCEEDED, DBUS_ERROR_NO_MEMORY, DBUS_ERROR_NO_NETWORK, DBUS_ERROR_NO_SERVER, DBUS_ERROR_NOT_SUPPORTED, DBUS_ERROR_TIMEOUT.
Referenced by _dbus_append_address_from_socket, _dbus_become_daemon, _dbus_change_to_daemon_user, _dbus_check_dir_is_private_to_user, _dbus_close, _dbus_close_socket, _dbus_command_for_pid, _dbus_connect_exec, _dbus_connect_tcp_socket, _dbus_connect_unix_socket, _dbus_directory_close, _dbus_directory_get_next_file, _dbus_directory_open, _dbus_dup, _dbus_error_from_system_errno, _dbus_file_get_contents, _dbus_full_duplex_pipe, _dbus_get_tmpdir, _dbus_is_console_user, _dbus_listen_systemd_sockets, _dbus_listen_tcp_socket, _dbus_listen_unix_socket, _dbus_read_credentials_socket, _dbus_send_credentials_socket, _dbus_stat, _dbus_string_save_to_file.
const char* _dbus_error_from_system_errno(void)
Converts the current system errno value into a DBusError name.
an error name
References _dbus_error_from_errno.
Referenced by _dbus_become_daemon.
void _dbus_set_errno_to_zero(void)
Assign 0 to the global errno variable.
Referenced by _dbus_string_parse_int, _dbus_string_parse_uint.
dbus_bool_t _dbus_get_is_errno_enomem(int e)
See if errno is ENOMEM.
TRUE if e == ENOMEM
dbus_bool_t _dbus_get_is_errno_eintr(int e)
See if errno is EINTR.
TRUE if e == EINTR
dbus_bool_t _dbus_get_is_errno_epipe(int e)
See if errno is EPIPE.
TRUE if errno == EPIPE
dbus_bool_t _dbus_get_is_errno_etoomanyrefs(int e)
See if errno is ETOOMANYREFS.
TRUE if errno == ETOOMANYREFS
References FALSE.
const char* _dbus_strerror_from_errno(void)
Get error message from errno.
_dbus_strerror(errno)
Referenced by _dbus_become_daemon, _dbus_close_socket, _dbus_connect_tcp_socket, _dbus_create_directory, _dbus_delete_file, _dbus_full_duplex_pipe, _dbus_listen_tcp_socket, _dbus_poll, _dbus_send_credentials_socket, _dbus_write_socket, _dbus_write_socket_two.