dbus-pending-call.c
CONNECTION_LOCK
Internals of DBusPendingCall.
Opaque object representing a reply message that we're waiting for. shorter and more visible way to write _dbus_connection_lock()
Referenced by _dbus_connection_block_pending_call, _dbus_connection_close_if_only_one_ref, _dbus_connection_close_possibly_shared, _dbus_connection_handle_watch, _dbus_connection_lock, _dbus_connection_new_for_transport, _dbus_connection_remove_pending_call, _dbus_connection_toggle_timeout_unlocked, _dbus_pending_call_get_connection_and_lock, _dbus_pending_call_set_data_unlocked, dbus_connection_add_filter, dbus_connection_borrow_message, dbus_connection_can_send_type, dbus_connection_close, dbus_connection_dispatch, dbus_connection_flush, dbus_connection_get_adt_audit_session_data, dbus_connection_get_dispatch_status, dbus_connection_get_is_anonymous, dbus_connection_get_is_authenticated, dbus_connection_get_is_connected, dbus_connection_get_max_message_size, dbus_connection_get_max_message_unix_fds, dbus_connection_get_max_received_size, dbus_connection_get_max_received_unix_fds, dbus_connection_get_object_path_data, dbus_connection_get_outgoing_size, dbus_connection_get_outgoing_unix_fds, dbus_connection_get_server_id, dbus_connection_get_socket, dbus_connection_get_unix_process_id, dbus_connection_get_unix_user, dbus_connection_get_windows_user, dbus_connection_has_messages_to_send, dbus_connection_list_registered, dbus_connection_pop_message, dbus_connection_preallocate_send, dbus_connection_remove_filter, dbus_connection_return_message, dbus_connection_send, dbus_connection_send_preallocated, dbus_connection_send_with_reply, dbus_connection_send_with_reply_and_block, dbus_connection_set_allow_anonymous, dbus_connection_set_dispatch_status_function, dbus_connection_set_exit_on_disconnect, dbus_connection_set_max_message_size, dbus_connection_set_max_message_unix_fds, dbus_connection_set_max_received_size, dbus_connection_set_max_received_unix_fds, dbus_connection_set_route_peer_messages, dbus_connection_set_timeout_functions, dbus_connection_set_unix_user_function, dbus_connection_set_wakeup_main_function, dbus_connection_set_watch_functions, dbus_connection_set_windows_user_function, dbus_connection_steal_borrowed_message, dbus_connection_unregister_object_path, dbus_pending_call_get_completed, dbus_pending_call_get_data, dbus_pending_call_set_data, dbus_pending_call_set_notify, dbus_pending_call_steal_reply.
CONNECTION_UNLOCK
shorter and more visible way to write _dbus_connection_unlock()
Referenced by dbus_connection_has_messages_to_send, _dbus_connection_remove_pending_call, _dbus_connection_new_for_transport, _dbus_connection_handle_watch, _dbus_connection_send_and_unlock, _dbus_connection_close_if_only_one_ref, dbus_connection_close, dbus_connection_get_is_connected, dbus_connection_get_is_authenticated, dbus_connection_get_is_anonymous, dbus_connection_get_server_id, dbus_connection_can_send_type, dbus_connection_set_exit_on_disconnect, dbus_connection_preallocate_send, dbus_connection_send_preallocated, dbus_connection_send, dbus_connection_send_with_reply, dbus_connection_send_with_reply_and_block, dbus_connection_flush, dbus_connection_borrow_message, dbus_connection_pop_message, dbus_connection_get_dispatch_status, dbus_connection_dispatch, dbus_connection_set_watch_functions, dbus_connection_set_timeout_functions, dbus_connection_set_wakeup_main_function, dbus_connection_set_dispatch_status_function, dbus_connection_get_socket, dbus_connection_get_unix_user, dbus_connection_get_unix_process_id, dbus_connection_get_adt_audit_session_data, dbus_connection_set_unix_user_function, dbus_connection_get_windows_user, dbus_connection_set_windows_user_function, dbus_connection_set_allow_anonymous, dbus_connection_set_route_peer_messages, dbus_connection_add_filter, dbus_connection_remove_filter, dbus_connection_get_object_path_data, dbus_connection_set_max_message_size, dbus_connection_get_max_message_size, dbus_connection_set_max_message_unix_fds, dbus_connection_get_max_message_unix_fds, dbus_connection_set_max_received_size, dbus_connection_get_max_received_size, dbus_connection_set_max_received_unix_fds, dbus_connection_get_max_received_unix_fds, dbus_connection_get_outgoing_size, dbus_connection_get_outgoing_unix_fds, _dbus_pending_call_unref_and_unlock, _dbus_pending_call_set_data_unlocked, dbus_pending_call_set_notify, dbus_pending_call_get_completed, dbus_pending_call_steal_reply, dbus_pending_call_set_data, dbus_pending_call_get_data.
dbus_int32_t notify_user_data_slot
DBusDataSlotAllocator slot_allocator
static void _dbus_pending_call_trace_ref(DBusPendingCall *pending_call, int old_refcount, int new_refcount, const char *why)
DBusPendingCall* _dbus_pending_call_new_unlocked(DBusConnection *connection, int timeout_milliseconds, DBusTimeoutHandler timeout_handler)
Creates a new pending reply object.
connection connection where reply will arrive timeout_milliseconds length of timeout, -1 (or DBUS_TIMEOUT_USE_DEFAULT) for default, DBUS_TIMEOUT_INFINITE for no timeout timeout_handler timeout handler, takes pending call as data a new DBusPendingCall or NULL if no memory.
References _dbus_assert, _dbus_atomic_inc, _dbus_connection_ref_unlocked, _dbus_data_slot_list_init, _dbus_timeout_new, DBusPendingCall::connection, dbus_free, dbus_new0, dbus_pending_call_allocate_data_slot, dbus_pending_call_free_data_slot, DBUS_TIMEOUT_INFINITE, NULL, DBusPendingCall::refcount, DBusPendingCall::slot_list, DBusPendingCall::timeout.
Referenced by dbus_connection_send_with_reply.
void _dbus_pending_call_set_reply_unlocked(DBusPendingCall *pending, DBusMessage *message)
Sets the reply of a pending call with the given message, or if the message is NULL, by timing out the pending call.
pending the pending call message the message to complete the call with, or NULL to time out the call
References _dbus_assert, _dbus_list_clear, DBusList::data, dbus_message_get_reply_serial, dbus_message_get_type, dbus_message_ref, DBUS_MESSAGE_TYPE_ERROR, DBUS_MESSAGE_TYPE_METHOD_RETURN, NULL, DBusPendingCall::reply, DBusPendingCall::reply_serial, DBusPendingCall::timeout_link.
Referenced by _dbus_connection_close_if_only_one_ref.
void _dbus_pending_call_complete(DBusPendingCall *pending)
Calls notifier function for the pending call and sets the call to completed.
pending the pending call
References _dbus_assert, DBusPendingCall::completed, dbus_pending_call_get_data, DBusPendingCall::function, TRUE.
Referenced by _dbus_connection_close_if_only_one_ref.
void _dbus_pending_call_queue_timeout_error_unlocked(DBusPendingCall *pending, DBusConnection *connection)
If the pending call hasn't been timed out, add its timeout error reply to the connection's incoming message queue.
pending the pending call connection the connection the call was sent to
References _dbus_assert, _dbus_connection_queue_synthesized_message_link, DBusPendingCall::connection, NULL, DBusPendingCall::timeout_link.
Referenced by _dbus_connection_close_if_only_one_ref, dbus_connection_send.
dbus_bool_t _dbus_pending_call_is_timeout_added_unlocked(DBusPendingCall *pending)
Checks to see if a timeout has been added.
pending the pending_call TRUE if there is a timeout or FALSE if not
References _dbus_assert, NULL, DBusPendingCall::timeout_added.
Referenced by _dbus_connection_close_if_only_one_ref, _dbus_connection_queue_received_message_link, _dbus_connection_toggle_timeout_unlocked.
void _dbus_pending_call_set_timeout_added_unlocked(DBusPendingCall *pending, dbus_bool_t is_added)
Sets wether the timeout has been added.
pending the pending_call is_added whether or not a timeout is added
References _dbus_assert, NULL, DBusPendingCall::timeout_added.
Referenced by _dbus_connection_close_if_only_one_ref, _dbus_connection_queue_received_message_link, _dbus_connection_toggle_timeout_unlocked, dbus_connection_send.
DBusTimeout* _dbus_pending_call_get_timeout_unlocked(DBusPendingCall *pending)
Retrives the timeout.
pending the pending_call a timeout object or NULL if call has no timeout
References _dbus_assert, NULL, DBusPendingCall::timeout.
Referenced by _dbus_connection_block_pending_call, _dbus_connection_close_if_only_one_ref, _dbus_connection_queue_received_message_link, _dbus_connection_toggle_timeout_unlocked, dbus_connection_send.
dbus_uint32_t _dbus_pending_call_get_reply_serial_unlocked(DBusPendingCall *pending)
Gets the reply's serial number.
pending the pending_call a serial number for the reply or 0
References _dbus_assert, NULL, DBusPendingCall::reply_serial.
Referenced by _dbus_connection_block_pending_call, _dbus_connection_close_if_only_one_ref, _dbus_connection_do_iteration_unlocked, _dbus_connection_toggle_timeout_unlocked.
void _dbus_pending_call_set_reply_serial_unlocked(DBusPendingCall *pending, dbus_uint32_t serial)
Sets the reply's serial number.
pending the pending_call serial the serial number
References _dbus_assert, NULL, DBusPendingCall::reply_serial.
Referenced by _dbus_pending_call_set_timeout_error_unlocked.
DBusConnection* _dbus_pending_call_get_connection_and_lock(DBusPendingCall *pending)
Gets the connection associated with this pending call.
pending the pending_call the connection associated with the pending call
References _dbus_assert, DBusPendingCall::connection, CONNECTION_LOCK, NULL.
Referenced by _dbus_connection_block_pending_call, dbus_connection_send.
DBusConnection* _dbus_pending_call_get_connection_unlocked(DBusPendingCall *pending)
Gets the connection associated with this pending call.
pending the pending_call the connection associated with the pending call
References _dbus_assert, DBusPendingCall::connection, NULL.
Referenced by _dbus_connection_toggle_timeout_unlocked.
dbus_bool_t _dbus_pending_call_set_timeout_error_unlocked(DBusPendingCall *pending, DBusMessage *message, dbus_uint32_t serial)
Sets the reply message associated with the pending call to a timeout error.
pending the pending_call message the message we are sending the error reply to serial serial number for the reply FALSE on OOM
References _dbus_list_alloc_link, _dbus_pending_call_set_reply_serial_unlocked, DBUS_ERROR_NO_REPLY, dbus_message_new_error, dbus_message_unref, FALSE, NULL, DBusPendingCall::reply, DBusPendingCall::timeout_link, TRUE.
Referenced by dbus_connection_send_with_reply.
DBusPendingCall* _dbus_pending_call_ref_unlocked(DBusPendingCall *pending)
Increments the reference count on a pending call, while the lock on its connection is already held.
pending the pending call object the pending call object
References _dbus_assert, _dbus_atomic_inc, _dbus_data_slot_list_free, _dbus_list_free_link, _dbus_timeout_unref, DBusPendingCall::connection, DBusList::data, dbus_connection_unref, dbus_free, dbus_message_unref, dbus_pending_call_free_data_slot, NULL, DBusPendingCall::refcount, DBusPendingCall::reply, DBusPendingCall::slot_list, DBusPendingCall::timeout, DBusPendingCall::timeout_added, DBusPendingCall::timeout_link.
Referenced by _dbus_connection_close_if_only_one_ref, _dbus_connection_toggle_timeout_unlocked.
static void _dbus_pending_call_last_unref(DBusPendingCall *pending)
void _dbus_pending_call_unref_and_unlock(DBusPendingCall *pending)
Decrements the reference count on a pending call, freeing it if the count reaches 0.
Assumes connection lock is already held. pending the pending call object
References _dbus_assert, _dbus_atomic_dec, DBusPendingCall::connection, CONNECTION_UNLOCK, DBusPendingCall::refcount.
Referenced by _dbus_connection_close_if_only_one_ref, _dbus_connection_toggle_timeout_unlocked.
dbus_bool_t _dbus_pending_call_get_completed_unlocked(DBusPendingCall *pending)
Checks whether the pending call has received a reply yet, or not.
Assumes connection lock is held. pending the pending call TRUE if a reply has been received
References _DBUS_LOCK_NAME, DBusPendingCall::completed.
Referenced by _dbus_connection_block_pending_call, _dbus_connection_do_iteration_unlocked.
dbus_bool_t _dbus_pending_call_set_data_unlocked(DBusPendingCall *pending, dbus_int32_t slot, void *data, DBusFreeFunction free_data_func)
Stores a pointer on a DBusPendingCall, along with an optional function to be used for freeing the data when the data is set again, or when the pending call is finalized.
The slot number must have been allocated with dbus_pending_call_allocate_data_slot(). pending the pending_call slot the slot number data the data to store free_data_func finalizer function for the data TRUE if there was enough memory to store the data
References _dbus_data_slot_list_set, DBusPendingCall::connection, CONNECTION_LOCK, CONNECTION_UNLOCK, DBusPendingCall::slot_list.
Referenced by dbus_pending_call_set_data, dbus_pending_call_set_notify.
DBUS_EXPORT DBusPendingCall * dbus_pending_call_ref(DBusPendingCall *pending)
Increments the reference count on a pending call.
pending the pending call object the pending call object
References _dbus_atomic_inc, NULL, DBusPendingCall::refcount.
Referenced by _dbus_connection_block_pending_call.
DBUS_EXPORT void dbus_pending_call_unref(DBusPendingCall *pending)
Decrements the reference count on a pending call, freeing it if the count reaches 0.
pending the pending call object
References _dbus_atomic_dec, NULL, DBusPendingCall::refcount.
Referenced by _dbus_connection_block_pending_call, _dbus_connection_close_if_only_one_ref, dbus_connection_send_with_reply, dbus_connection_send_with_reply_and_block.
DBUS_EXPORT dbus_bool_t dbus_pending_call_set_notify(DBusPendingCall *pending, DBusPendingCallNotifyFunction function, void *user_data, DBusFreeFunction free_user_data)
Sets a notification function to be called when the reply is received or the pending call times out.
pending the pending call function notifier function user_data data to pass to notifier function free_user_data function to free the user data FALSE if not enough memory
References _dbus_pending_call_set_data_unlocked, DBusPendingCall::connection, CONNECTION_LOCK, CONNECTION_UNLOCK, FALSE, DBusPendingCall::function, NULL, TRUE.
DBUS_EXPORT void dbus_pending_call_cancel(DBusPendingCall *pending)
Cancels the pending call, such that any reply or error received will just be ignored.
Drops the dbus library's internal reference to the DBusPendingCall so will free the call if nobody else is holding a reference. However you usually get a reference from dbus_connection_send_with_reply() so probably your app owns a ref also.Note that canceling a pending call will not simulate a timed-out call; if a call times out, then a timeout error reply is received. If you cancel the call, no reply is received unless the the reply was already received before you canceled. pending the pending call
References _dbus_connection_remove_pending_call, DBusPendingCall::connection, NULL.
DBUS_EXPORT dbus_bool_t dbus_pending_call_get_completed(DBusPendingCall *pending)
Checks whether the pending call has received a reply yet, or not.
pending the pending call TRUE if a reply has been received
References DBusPendingCall::completed, DBusPendingCall::connection, CONNECTION_LOCK, CONNECTION_UNLOCK, FALSE, NULL.
Referenced by _dbus_connection_block_pending_call.
DBUS_EXPORT DBusMessage * dbus_pending_call_steal_reply(DBusPendingCall *pending)
Gets the reply, or returns NULL if none has been received yet.
Ownership of the reply message passes to the caller. This function can only be called once per pending call, since the reply message is tranferred to the caller. pending the pending call the reply message or NULL.
References DBusPendingCall::completed, DBusPendingCall::connection, CONNECTION_LOCK, CONNECTION_UNLOCK, NULL, DBusPendingCall::reply.
Referenced by dbus_connection_send_with_reply_and_block.
DBUS_EXPORT void dbus_pending_call_block(DBusPendingCall *pending)
Block until the pending call is completed.
The blocking is as with dbus_connection_send_with_reply_and_block(); it does not enter the main loop or process other messages, it simply waits for the reply in question.If the pending call is already completed, this function returns immediately.Todowhen you start blocking, the timeout is reset, but it should really only use time remaining since the pending call was created. This requires storing timestamps instead of intervals in the timeout pending the pending call
References _dbus_connection_block_pending_call, NULL.
Referenced by dbus_connection_send_with_reply_and_block.
DBUS_EXPORT dbus_bool_t dbus_pending_call_allocate_data_slot(dbus_int32_t *slot_p)
Allocates an integer ID to be used for storing application-specific data on any DBusPendingCall.
The allocated ID may then be used with dbus_pending_call_set_data() and dbus_pending_call_get_data(). The passed-in slot must be initialized to -1, and is filled in with the slot ID. If the passed-in slot is not -1, it's assumed to be already allocated, and its refcount is incremented.The allocated slot is global, i.e. all DBusPendingCall objects will have a slot with the given integer ID reserved. slot_p address of a global variable storing the slot FALSE on failure (no memory)
References _dbus_data_slot_allocator_alloc, FALSE, NULL.
Referenced by _dbus_pending_call_new_unlocked.
DBUS_EXPORT void dbus_pending_call_free_data_slot(dbus_int32_t *slot_p)
Deallocates a global ID for DBusPendingCall data slots.
dbus_pending_call_get_data() and dbus_pending_call_set_data() may no longer be used with this slot. Existing data stored on existing DBusPendingCall objects will be freed when the DBusPendingCall is finalized, but may not be retrieved (and may only be replaced if someone else reallocates the slot). When the refcount on the passed-in slot reaches 0, it is set to -1. slot_p address storing the slot to deallocate
References _dbus_data_slot_allocator_free, NULL.
Referenced by _dbus_pending_call_new_unlocked, _dbus_pending_call_ref_unlocked.
DBUS_EXPORT dbus_bool_t dbus_pending_call_set_data(DBusPendingCall *pending, dbus_int32_t slot, void *data, DBusFreeFunction free_data_func)
Stores a pointer on a DBusPendingCall, along with an optional function to be used for freeing the data when the data is set again, or when the pending call is finalized.
The slot number must have been allocated with dbus_pending_call_allocate_data_slot(). pending the pending_call slot the slot number data the data to store free_data_func finalizer function for the data TRUE if there was enough memory to store the data
References _dbus_pending_call_set_data_unlocked, DBusPendingCall::connection, CONNECTION_LOCK, CONNECTION_UNLOCK, FALSE, NULL.
DBUS_EXPORT void * dbus_pending_call_get_data(DBusPendingCall *pending, dbus_int32_t slot)
Retrieves data previously set with dbus_pending_call_set_data().
The slot must still be allocated (must not have been freed). pending the pending_call slot the slot to get data from the data, or NULL if not found
References _dbus_data_slot_list_get, DBusPendingCall::connection, CONNECTION_LOCK, CONNECTION_UNLOCK, NULL, DBusPendingCall::slot_list.
Referenced by _dbus_pending_call_complete.