dbus-transport-socket.h
DBusTransport* _dbus_transport_new_for_socket(int fd, const DBusString *server_guid, const DBusString *address)
Creates a new transport for the given socket file descriptor.
The file descriptor must be nonblocking (use _dbus_set_fd_nonblocking() to make it so). This function is shared by various transports that boil down to a full duplex file descriptor. fd the file descriptor. server_guid non-NULL if this transport is on the server side of a connection address the transport's address the new transport, or NULL if no memory.
References dbus_new0, NULL, _dbus_string_init, DBusTransportSocket::encoded_outgoing, DBusTransportSocket::encoded_incoming, DBusTransportSocket::write_watch, _dbus_watch_new, DBUS_WATCH_WRITABLE, FALSE, DBusTransportSocket::read_watch, DBUS_WATCH_READABLE, _dbus_transport_init_base, DBusTransportSocket::base, _dbus_auth_set_unix_fd_possible, DBusTransport::auth, _dbus_socket_can_pass_unix_fd, DBusTransportSocket::fd, DBusTransportSocket::message_bytes_written, DBusTransportSocket::max_bytes_read_per_iteration, DBusTransportSocket::max_bytes_written_per_iteration, _dbus_watch_invalidate, _dbus_watch_unref, _dbus_string_free, dbus_free.
Referenced by _dbus_transport_new_for_tcp_socket, _dbus_transport_new_for_domain_socket.
DBusTransport* _dbus_transport_new_for_tcp_socket(const char *host, const char *port, const char *family, const char *noncefile, DBusError *error)
Creates a new transport for the given hostname and port.
If host is NULL, it will default to localhost host the host to connect to port the port to connect to family the address family to connect to noncefile path to nonce file error location to store reason for failure. a new transport, or NULL on failure.
References DBusTransportSocket::fd, _dbus_string_init, dbus_set_error, DBUS_ERROR_NO_MEMORY, NULL, _dbus_string_append, _dbus_string_free, _dbus_transport_new_for_socket, _dbus_close_socket.
Referenced by _dbus_transport_open_socket.
DBusTransportOpenResult _dbus_transport_open_socket(DBusAddressEntry *entry, DBusTransport **transport_p, DBusError *error)
Opens a TCP socket transport.
entry the address entry to try opening as a tcp transport. transport_p return location for the opened transport error error to be set result of the attempt
References dbus_address_entry_get_method, _dbus_assert, NULL, dbus_address_entry_get_value, TRUE, _dbus_set_bad_address, _dbus_transport_new_for_tcp_socket.
Referenced by _dbus_transport_finalize_base.