dbus-sysdeps-util-unix.c
DBUS_USERDB_INCLUDES_PRIVATE
O_BINARY
DBUS_UNIX_STANDARD_SESSION_SERVICEDIR
DBUS_UNIX_STANDARD_SYSTEM_SERVICEDIR
dbus_bool_t _dbus_become_daemon(const DBusString *pidfile, DBusPipe *print_pid_pipe, DBusError *error, dbus_bool_t keep_umask)
Does the chdir, fork, setsid, etc.
to become a daemon process. pidfile NULL, or pidfile to create print_pid_pipe pipe to print daemon's pid to, or -1 for none error return location for errors keep_umask TRUE to keep the original umask FALSE on failure
static dbus_bool_t _dbus_write_pid_file(const DBusString *filename, unsigned long pid, DBusError *error)
Creates a file containing the process ID.
filename the filename to write to pid our process ID error return location for errors FALSE on failure
dbus_bool_t _dbus_write_pid_to_file_and_pipe(const DBusString *pidfile, DBusPipe *print_pid_pipe, dbus_pid_t pid_to_write, DBusError *error)
Writes the given pid_to_write to a pidfile (if non-NULL) and/or to a pipe (if non-NULL).
Does nothing if pidfile and print_pid_pipe are both NULL. pidfile the file to write to or NULL print_pid_pipe the pipe to write to or NULL pid_to_write the pid to write out error error on failure FALSE if error is set
Referenced by _dbus_become_daemon.
dbus_bool_t _dbus_verify_daemon_user(const char *user)
Verify that after the fork we can successfully change to this user.
user the username given in the daemon configuration TRUE if username is valid
dbus_bool_t _dbus_change_to_daemon_user(const char *user, DBusError *error)
Changes the user and group the bus is running as.
user the user to become error return location for errors FALSE on failure
static void fd_limit_not_supported(DBusError *error)
DBusRLimit* _dbus_rlimit_save_fd_limit(DBusError *error)
dbus_bool_t _dbus_rlimit_raise_fd_limit_if_privileged(unsigned int desired, DBusError *error)
dbus_bool_t _dbus_rlimit_restore_fd_limit(DBusRLimit *saved, DBusError *error)
void _dbus_rlimit_free(DBusRLimit *lim)
void _dbus_init_system_log(dbus_bool_t is_daemon)
void _dbus_system_log(DBusSystemLogSeverity severity, const char *msg,...)
Log a message to the system log file (e.g.
syslog on Unix). severity a severity value msg a printf-style format string
void _dbus_system_logv(DBusSystemLogSeverity severity, const char *msg, va_list args)
Log a message to the system log file (e.g.
syslog on Unix). severity a severity value msg a printf-style format string args arguments for the format string If the FATAL severity is given, this function will terminate the program with an error code.
Referenced by _dbus_system_log.
void _dbus_set_signal_handler(int sig, DBusSignalHandler handler)
Installs a UNIX signal handler.
sig the signal to handle handler the handler
dbus_bool_t _dbus_file_exists(const char *file)
Checks if a file exists.
File interface. file full path to the file TRUE if file exists
Referenced by _dbus_user_at_console.
dbus_bool_t _dbus_user_at_console(const char *username, DBusError *error)
Checks if user is at the console.
username user to check error return location for errors TRUE is the user is at the consolei and there are no errors
References _dbus_concat_dir_and_file, _dbus_file_exists, _dbus_string_append, _dbus_string_free, _dbus_string_init, _dbus_string_init_const, FALSE.
Referenced by _dbus_is_console_user.
dbus_bool_t _dbus_path_is_absolute(const DBusString *filename)
Checks whether the filename is an absolute path.
filename the filename TRUE if an absolute path
Referenced by _dbus_get_environment, _dbus_get_standard_session_servicedirs.
dbus_bool_t _dbus_stat(const DBusString *filename, DBusStat *statbuf, DBusError *error)
stat() wrapper.
filename the filename to stat statbuf the stat info to fill in error return location for error FALSE if error was set
Referenced by _dbus_is_console_user.
DBusDirIter* _dbus_directory_open(const DBusString *filename, DBusError *error)
Open a directory to iterate over.
filename the directory name error exception return object or NULL new iterator, or NULL on error
dbus_bool_t _dbus_directory_get_next_file(DBusDirIter *iter, DBusString *filename, DBusError *error)
Get next file in the directory.
Will not return "." or ".." on UNIX. If an error occurs, the contents of "filename" are undefined. The error is never set if the function succeeds.This function is not re-entrant, and not necessarily thread-safe. Only use it for test code or single-threaded utilities. iter the iterator filename string to be set to the next file in the dir error return location for error TRUE if filename was filled in with a new filename
void _dbus_directory_close(DBusDirIter *iter)
Closes a directory iteration.
static dbus_bool_t fill_user_info_from_group(struct group *g, DBusGroupInfo *info, DBusError *error)
static dbus_bool_t fill_group_info(DBusGroupInfo *info, dbus_gid_t gid, const DBusString *groupname, DBusError *error)
dbus_bool_t _dbus_group_info_fill(DBusGroupInfo *info, const DBusString *groupname, DBusError *error)
Initializes the given DBusGroupInfo struct with information about the given group name.
info the group info struct groupname name of group error the error return FALSE if error is set
References DBUS_GID_UNSET.
Referenced by _dbus_user_database_lookup_group.
dbus_bool_t _dbus_group_info_fill_gid(DBusGroupInfo *info, dbus_gid_t gid, DBusError *error)
Initializes the given DBusGroupInfo struct with information about the given group ID.
info the group info struct gid group ID error the error return FALSE if error is set
References NULL.
Referenced by _dbus_user_database_lookup_group.
dbus_bool_t _dbus_parse_unix_user_from_config(const DBusString *username, dbus_uid_t *uid_p)
Parse a UNIX user from the bus config file.
On Windows, this should simply always fail (just return FALSE). username the username text uid_p place to return the uid TRUE on success
dbus_bool_t _dbus_parse_unix_group_from_config(const DBusString *groupname, dbus_gid_t *gid_p)
Parse a UNIX group from the bus config file.
On Windows, this should simply always fail (just return FALSE). groupname the groupname text gid_p place to return the gid TRUE on success
dbus_bool_t _dbus_unix_groups_from_uid(dbus_uid_t uid, dbus_gid_t **group_ids, int *n_group_ids)
Gets all groups corresponding to the given UNIX user ID.
On UNIX, just calls _dbus_groups_from_uid(). On Windows, should always fail since we don't know any UNIX groups. uid the UID group_ids return location for array of group IDs n_group_ids return location for length of returned array TRUE if the UID existed and we got some credentials
dbus_bool_t _dbus_unix_user_is_at_console(dbus_uid_t uid, DBusError *error)
Checks to see if the UNIX user ID is at the console.
Should always fail on Windows (set the error to DBUS_ERROR_NOT_SUPPORTED). uid UID of person to check error return location for errors TRUE if the UID is the same as the console user and there are no errors
dbus_bool_t _dbus_unix_user_is_process_owner(dbus_uid_t uid)
Checks to see if the UNIX user ID matches the UID of the process.
Should always return FALSE on Windows. uid the UNIX user ID TRUE if this uid owns the process.
dbus_bool_t _dbus_windows_user_is_process_owner(const char *windows_sid)
Checks to see if the Windows user SID matches the owner of the process.
Should always return FALSE on UNIX. windows_sid the Windows user SID TRUE if this user owns the process.
dbus_bool_t _dbus_string_get_dirname(const DBusString *filename, DBusString *dirname)
Get the directory name from a complete filename.
filename the filename dirname string to append directory name to FALSE if no memory
References _dbus_assert, _dbus_string_append, _dbus_string_copy_len, _dbus_string_find_byte_backward, NULL.
Referenced by _dbus_directory_close, _dbus_get_environment.
static void string_squash_nonprintable(DBusString *str)
dbus_bool_t _dbus_command_for_pid(unsigned long pid, DBusString *str, int max_len, DBusError *error)
Get a printable string describing the command used to execute the process with pid.
This string should only be used for informative purposes such as logging; it may not be trusted.The command is guaranteed to be printable ASCII and no longer than max_len. pid Process id str Append command to this string max_len Maximum length of returned command error return location for errors FALSE on error
const char* _dbus_replace_install_prefix(const char *configure_time_path)
dbus_bool_t _dbus_get_standard_session_servicedirs(DBusList **dirs)
Returns the standard directories for a session bus to look for service activation files.
On UNIX this should be the standard xdg freedesktop.org data directories:XDG_DATA_HOME=${XDG_DATA_HOME-$HOME/.local/share} XDG_DATA_DIRS=${XDG_DATA_DIRS-/usr/local/share:/usr/share}andDBUS_DATADIR dirs the directory list we are returning FALSE on OOM
dbus_bool_t _dbus_get_standard_system_servicedirs(DBusList **dirs)
Returns the standard directories for a system bus to look for service activation files.
On UNIX this should be the standard xdg freedesktop.org data directories:XDG_DATA_DIRS=${XDG_DATA_DIRS-/usr/local/share:/usr/share}andDBUS_DATADIROn Windows there is no system bus and this function can return nothing. dirs the directory list we are returning FALSE on OOM
dbus_bool_t _dbus_append_system_config_file(DBusString *str)
Append the absolute path of the system.conf file (there is no system bus on Windows so this can just return FALSE and print a warning or something)
str the string to append to FALSE if no memory
dbus_bool_t _dbus_append_session_config_file(DBusString *str)
Append the absolute path of the session.conf file.
str the string to append to FALSE if no memory