dbus-spawn.h
typedef void(* DBusSpawnChildSetupFunc) (void *user_data))(void *user_data)
typedef struct DBusBabysitter DBusBabysitter
typedef void(* DBusBabysitterFinishedFunc) (DBusBabysitter *sitter, void *user_data))(DBusBabysitter *sitter, void *user_data)
dbus_bool_t _dbus_spawn_async_with_babysitter(DBusBabysitter **sitter_p, const char *log_name, char **argv, char **env, DBusSpawnChildSetupFunc child_setup, void *user_data, DBusError *error)
Spawns a new process.
The child_setup function is passed the given user_data and is run in the child just before calling exec().Also creates a "babysitter" which tracks the status of the child process, advising the parent if the child exits. If the spawn fails, no babysitter is created. If sitter_p is NULL, no babysitter is kept. sitter_p return location for babysitter or NULL log_name the name under which to log messages about this process being spawned argv the executable and arguments env the environment, or NULL to copy the parent's child_setup function to call in child pre-exec() user_data user data for setup function error error object to be filled in if function fails TRUE on success, FALSE if error is filled in
References _dbus_assert, NULL, FALSE, DBusBabysitter::log_name, _dbus_strdup, _dbus_full_duplex_pipe, DBusBabysitter::socket_to_babysitter, DBusBabysitter::sitter_watch, _dbus_watch_new, DBUS_WATCH_READABLE, TRUE, _dbus_watch_list_add_watch, DBusBabysitter::watches, _dbus_watch_invalidate, _dbus_watch_unref, dbus_set_error_const, DBUS_ERROR_SPAWN_FORK_FAILED, _dbus_babysitter_unref, _dbus_getenv, _dbus_string_init, _dbus_string_append_printf, _dbus_string_free, dbus_error_init, _dbus_spawn_async_with_babysitter, _dbus_babysitter_set_child_exit_error, dbus_error_is_set, _dbus_warn, dbus_error_has_name, DBUS_ERROR_NO_MEMORY, DBUS_ERROR_SPAWN_EXEC_FAILED, DBusError::name, DBusError::message, dbus_error_free, DBUS_ERROR_SPAWN_CHILD_EXITED, _dbus_babysitter_kill_child, dbus_set_error, DBusBabysitter::error_watch, READ_END, DBusBabysitter::grandchild_pid, _dbus_assert_not_reached, WRITE_END, DBusBabysitter::error_pipe_from_child, DBusBabysitter::sitter_pid, dbus_free_string_array, LIVE_CHILDREN, DBUS_ERROR_INIT, DBUS_ERROR_SPAWN_CHILD_SIGNALED.
Referenced by _dbus_spawn_async_with_babysitter.
void _dbus_babysitter_set_result_function(DBusBabysitter *sitter, DBusBabysitterFinishedFunc finished, void *user_data)
DBusBabysitter* _dbus_babysitter_ref(DBusBabysitter *sitter)
Increment the reference count on the babysitter object.
sitter the babysitter the babysitter
References _dbus_assert, NULL, DBusBabysitter::refcount, DBusBabysitter::sitter_watch, DBusBabysitter::watches, _dbus_watch_list_remove_watch, _dbus_watch_invalidate, _dbus_watch_unref, DBusBabysitter::socket_to_babysitter, _dbus_close_socket.
Referenced by _dbus_babysitter_set_watch_functions.
void _dbus_babysitter_unref(DBusBabysitter *sitter)
Decrement the reference count on the babysitter object.
sitter the babysitter When the reference count of the babysitter object reaches zero, the babysitter is killed and the child that was being babysat gets emancipated. sitter the babysitter
References _dbus_assert, NULL, DBusBabysitter::refcount, _dbus_close_socket, dbus_free, DBusBabysitter::sitter_watch, _dbus_watch_invalidate, _dbus_watch_unref, DBusBabysitter::watches, _dbus_watch_list_free, DBusBabysitter::log_name, DBusBabysitter::sitter_pid, DBusBabysitter::status, _dbus_warn, DBUS_ERROR_INIT, READ_STATUS_ERROR, DBusError::message, dbus_error_free, READ_STATUS_EOF, READ_STATUS_OK, TRUE, DBusBabysitter::have_fork_errnum, DBusBabysitter::errnum, DBusBabysitter::have_exec_errnum, DBusBabysitter::grandchild_pid, _dbus_watch_list_remove_watch, DBusBabysitter::socket_to_babysitter, DBusBabysitter::error_watch, DBusBabysitter::error_pipe_from_child, _DBUS_POLLIN, _DBUS_POLLERR, _DBUS_POLLHUP, FALSE, DBusPollFD::fd, DBusPollFD::events, DBusPollFD::revents, _dbus_poll.
Referenced by _dbus_babysitter_set_watch_functions, _dbus_spawn_async_with_babysitter.
void _dbus_babysitter_kill_child(DBusBabysitter *sitter)
Blocks until the babysitter process gives us the PID of the spawned grandchild, then kills the spawned grandchild.
sitter the babysitter object
References NULL, LIVE_CHILDREN, DBusBabysitter::grandchild_pid, TRUE.
Referenced by _dbus_spawn_async_with_babysitter.
dbus_bool_t _dbus_babysitter_get_child_exited(DBusBabysitter *sitter)
Checks whether the child has exited, without blocking.
sitter the babysitter
References NULL, LIVE_CHILDREN, FALSE, DBusBabysitter::socket_to_babysitter.
Referenced by _dbus_babysitter_get_child_exit_status, _dbus_babysitter_set_child_exit_error, _dbus_babysitter_set_watch_functions.
void _dbus_babysitter_set_child_exit_error(DBusBabysitter *sitter, DBusError *error)
Sets the DBusError with an explanation of why the spawned child process exited (on a signal, or whatever).
If the child process has not exited, does nothing (error will remain unset). sitter the babysitter error an error to fill in
References _dbus_babysitter_get_child_exited, dbus_set_error, DBUS_ERROR_SPAWN_EXEC_FAILED, DBusBabysitter::log_name, DBUS_ERROR_SPAWN_CHILD_EXITED, DBUS_ERROR_FAILED, DBusBabysitter::have_exec_errnum, DBusBabysitter::errnum, DBusBabysitter::have_fork_errnum, DBUS_ERROR_NO_MEMORY, DBusBabysitter::status, DBUS_ERROR_SPAWN_CHILD_SIGNALED.
Referenced by _dbus_spawn_async_with_babysitter.
dbus_bool_t _dbus_babysitter_get_child_exit_status(DBusBabysitter *sitter, int *status)
Gets the exit status of the child.
We do this so implementation specific detail is not cluttering up dbus, for example the system launcher code. This can only be called if the child has exited, i.e. call _dbus_babysitter_get_child_exited(). It returns FALSE if the child did not return a status code, e.g. because the child was signaled or we failed to ever launch the child in the first place. sitter the babysitter status the returned status code FALSE on failure
References _dbus_babysitter_get_child_exited, _dbus_assert_not_reached, FALSE, TRUE, DBusBabysitter::status.
dbus_bool_t _dbus_babysitter_set_watch_functions(DBusBabysitter *sitter, DBusAddWatchFunction add_function, DBusRemoveWatchFunction remove_function, DBusWatchToggledFunction toggled_function, void *data, DBusFreeFunction free_data_function)
Sets watch functions to notify us when the babysitter object needs to read/write file descriptors.
sitter the babysitter add_function function to begin monitoring a new descriptor. remove_function function to stop monitoring a descriptor. toggled_function function to notify when the watch is enabled/disabled data data to pass to add_function and remove_function. free_data_function function to be called to free the data. FALSE on failure (no memory)
References _dbus_watch_list_set_functions, DBusBabysitter::watches, _dbus_babysitter_get_child_exited, NULL, TRUE, dbus_malloc, FALSE, _dbus_babysitter_ref, DBusBabysitter::log_name, DBusBabysitter::status, _dbus_babysitter_unref, DBUS_WATCH_READABLE, _DBUS_POLLIN, DBUS_WATCH_ERROR, _DBUS_POLLERR, DBUS_WATCH_HANGUP, _DBUS_POLLHUP, dbus_watch_get_socket, DBusBabysitter::error_pipe_from_child, DBusBabysitter::socket_to_babysitter, LIVE_CHILDREN, _dbus_assert, DBusBabysitter::sitter_watch, DBusBabysitter::error_watch.