dbus-mempool.c
ELEMENT_PADDING
The dummy size of the variable-length "elements" field in DBusMemBlock.
Referenced by _dbus_mem_pool_alloc.
typedef struct DBusFreedElement DBusFreedElement
typedef so DBusFreedElement struct can refer to itself.
typedef struct DBusMemBlock DBusMemBlock
Typedef for DBusMemBlock so the struct can recursively point to itself.
DBusMemPool* _dbus_mem_pool_new(int element_size, dbus_bool_t zero_elements)
Creates a new memory pool, or returns NULL on failure.
Objects in the pool must be at least sizeof(void*) bytes each, due to the way memory pools work. To avoid creating 64 bit problems, this means at least 8 bytes on all platforms, unless you are 4 bytes on 32-bit and 8 bytes on 64-bit. element_size size of an element allocated from the pool. zero_elements whether to zero-initialize elements the new pool or NULL
References _dbus_assert, DBusMemPool::allocated_elements, DBusMemPool::block_size, dbus_new0, DBusMemPool::element_size, FALSE, NULL, DBusMemPool::zero_elements.
Referenced by _dbus_hash_table_new, _dbus_mem_pool_dealloc.
void _dbus_mem_pool_free(DBusMemPool *pool)
Frees a memory pool (and all elements allocated from it).
pool the memory pool.
References DBusMemPool::blocks, dbus_free, DBusFreedElement::next, DBusMemBlock::next, NULL.
Referenced by _dbus_hash_table_unref, _dbus_mem_pool_dealloc.
void* _dbus_mem_pool_alloc(DBusMemPool *pool)
Allocates an object from the memory pool.
The object must be freed with _dbus_mem_pool_dealloc(). pool the memory pool the allocated object or NULL if no memory.
References _dbus_assert, _DBUS_INT_MAX, DBusMemPool::allocated_elements, DBusMemPool::block_size, DBusMemPool::blocks, dbus_malloc, dbus_malloc0, ELEMENT_PADDING, DBusMemPool::element_size, DBusMemBlock::elements, DBusMemPool::free_elements, DBusFreedElement::next, DBusMemBlock::next, NULL, DBusMemBlock::used_so_far, DBusMemPool::zero_elements.
Referenced by _dbus_hash_table_remove_all, _dbus_mem_pool_dealloc.
dbus_bool_t _dbus_mem_pool_dealloc(DBusMemPool *pool, void *element)
Deallocates an object previously created with _dbus_mem_pool_alloc().
The previous object must have come from this same pool. pool the memory pool element the element earlier allocated. TRUE if there are no remaining allocated elements
References _dbus_assert, _dbus_assert_not_reached, _dbus_mem_pool_alloc, _dbus_mem_pool_dealloc, _dbus_mem_pool_free, _dbus_mem_pool_new, _DBUS_N_ELEMENTS, DBusMemPool::allocated_elements, DBusMemPool::block_size, DBusMemPool::blocks, dbus_free, dbus_malloc, dbus_malloc0, DBusMemPool::element_size, DBusMemBlock::elements, FALSE, DBusMemPool::free_elements, DBusFreedElement::next, DBusMemBlock::next, NULL, TRUE, DBusMemBlock::used_so_far.
Referenced by _dbus_hash_table_free_preallocated_entry, _dbus_hash_table_remove_all, _dbus_mem_pool_dealloc.