dbus-internals.h
DBUS_INTERNALS_H
_DBUS_FUNCTION_NAME
_DBUS_LIKELY
_DBUS_UNLIKELY
_dbus_verbose_reset
_dbus_is_verbose
_dbus_assert
Aborts with an error message if the condition is false.
condition condition which must be true.
Referenced by _dbus_append_keyring_directory_for_credentials, _dbus_auth_decode_data, _dbus_auth_encode_data, _dbus_auth_get_buffer, _dbus_auth_get_bytes_to_send, _dbus_auth_get_guid_from_server, _dbus_auth_get_identity, _dbus_auth_ref, _dbus_auth_return_buffer, _dbus_auth_unref, _dbus_babysitter_ref, _dbus_babysitter_set_watch_functions, _dbus_babysitter_unref, _dbus_bus_notify_shared_connection_disconnected_unlocked, _dbus_change_to_daemon_user, _dbus_check_dir_is_private_to_user, _dbus_cmutex_new_at_location, _dbus_condvar_new_at_location, _dbus_condvar_wake_one, _dbus_connection_block_pending_call, _dbus_connection_close_if_only_one_ref, _dbus_connection_close_possibly_shared, _dbus_connection_handle_watch, _dbus_connection_message_sent_unlocked, _dbus_connection_queue_received_message_link, _dbus_connection_ref_unlocked, _dbus_connection_remove_pending_call, _dbus_connection_send_and_unlock, _dbus_connection_toggle_timeout_unlocked, _dbus_connection_toggle_watch_unlocked, _dbus_connection_unref_unlocked, _dbus_counter_ref, _dbus_counter_unref, _dbus_credentials_ref, _dbus_credentials_unref, _dbus_data_slot_allocator_alloc, _dbus_data_slot_allocator_free, _dbus_data_slot_list_free, _dbus_data_slot_list_get, _dbus_data_slot_list_set, _dbus_decompose_path, _dbus_directory_close, _dbus_first_type_in_signature_c_str, _dbus_generate_random_ascii, _dbus_get_autolaunch_address, _dbus_get_environment, _dbus_get_tmpdir, _dbus_groups_from_uid, _dbus_hash_iter_get_int_key, _dbus_hash_iter_get_string_key, _dbus_hash_iter_get_uintptr_key, _dbus_hash_iter_get_value, _dbus_hash_iter_lookup, _dbus_hash_iter_next, _dbus_hash_iter_remove_entry, _dbus_hash_iter_set_value, _dbus_hash_table_free_preallocated_entry, _dbus_hash_table_get_n_entries, _dbus_hash_table_insert_int, _dbus_hash_table_insert_string, _dbus_hash_table_insert_string_preallocated, _dbus_hash_table_insert_uintptr, _dbus_hash_table_lookup_int, _dbus_hash_table_lookup_string, _dbus_hash_table_lookup_uintptr, _dbus_hash_table_new, _dbus_hash_table_remove_all, _dbus_hash_table_remove_int, _dbus_hash_table_remove_string, _dbus_hash_table_remove_uintptr, _dbus_header_create, _dbus_header_delete_field, _dbus_header_get_byte_order, _dbus_header_get_field_basic, _dbus_header_get_message_type, _dbus_header_have_message_untrusted, _dbus_header_load, _dbus_header_set_field_basic, _dbus_header_set_serial, _dbus_header_update_lengths, _dbus_keyring_get_hex_key, _dbus_keyring_new_for_credentials, _dbus_list_copy, _dbus_list_length_is_one, _dbus_listen_tcp_socket, _dbus_lookup_launchd_socket, _dbus_marshal_byteswap, _dbus_marshal_read_basic, _dbus_marshal_read_uint32, _dbus_marshal_set_basic, _dbus_marshal_set_uint32, _dbus_marshal_skip_basic, _dbus_marshal_write_basic, _dbus_marshal_write_fixed_multi, _dbus_mem_pool_alloc, _dbus_mem_pool_dealloc, _dbus_mem_pool_new, _dbus_message_get_network_data, _dbus_message_get_unix_fds, _dbus_message_iter_get_args_valist, _dbus_message_loader_get_buffer, _dbus_message_loader_get_corruption_reason, _dbus_message_loader_get_is_corrupted, _dbus_message_loader_get_unix_fds, _dbus_message_loader_queue_messages, _dbus_message_loader_return_buffer, _dbus_message_loader_return_unix_fds, _dbus_message_remove_counter, _dbus_object_tree_free_all_unlocked, _dbus_object_tree_get_user_data_unlocked, _dbus_object_tree_ref, _dbus_object_tree_register, _dbus_object_tree_unref, _dbus_object_tree_unregister_and_unlock, _dbus_pending_call_complete, _dbus_pending_call_get_connection_and_lock, _dbus_pending_call_get_connection_unlocked, _dbus_pending_call_get_reply_serial_unlocked, _dbus_pending_call_get_timeout_unlocked, _dbus_pending_call_is_timeout_added_unlocked, _dbus_pending_call_new_unlocked, _dbus_pending_call_queue_timeout_error_unlocked, _dbus_pending_call_ref_unlocked, _dbus_pending_call_set_reply_serial_unlocked, _dbus_pending_call_set_reply_unlocked, _dbus_pending_call_set_timeout_added_unlocked, _dbus_pending_call_unref_and_unlock, _dbus_read, _dbus_read_local_machine_uuid, _dbus_read_socket, _dbus_read_socket_with_unix_fds, _dbus_rmutex_new_at_location, _dbus_send_credentials_socket, _dbus_server_finalize_base, _dbus_server_init_base, _dbus_server_ref_unlocked, _dbus_server_unref_unlocked, _dbus_spawn_async_with_babysitter, _dbus_string_append, _dbus_string_append_len, _dbus_string_copy_data, _dbus_string_copy_len, _dbus_string_copy_to_buffer, _dbus_string_copy_to_buffer_with_nul, _dbus_string_delete, _dbus_string_ends_with_c_str, _dbus_string_equal_c_str, _dbus_string_equal_substring, _dbus_string_find_blank, _dbus_string_find_byte_backward, _dbus_string_find_eol, _dbus_string_find_to, _dbus_string_free, _dbus_string_get_data_len, _dbus_string_get_dirname, _dbus_string_hex_decode, _dbus_string_hex_encode, _dbus_string_init_const, _dbus_string_init_const_len, _dbus_string_init_preallocated, _dbus_string_insert_8_aligned, _dbus_string_insert_alignment, _dbus_string_insert_byte, _dbus_string_insert_bytes, _dbus_string_lengthen, _dbus_string_move, _dbus_string_move_len, _dbus_string_pop_line, _dbus_string_replace_len, _dbus_string_set_length, _dbus_string_shorten, _dbus_string_skip_blank, _dbus_string_skip_white, _dbus_string_skip_white_reverse, _dbus_string_starts_with_c_str, _dbus_string_steal_data, _dbus_string_tolower_ascii, _dbus_string_toupper_ascii, _dbus_string_validate_ascii, _dbus_string_validate_nul, _dbus_string_validate_utf8, _dbus_swap_array, _dbus_threads_lock_platform_specific, _dbus_threads_unlock_platform_specific, _dbus_timeout_set_interval, _dbus_timeout_unref, _dbus_transport_disconnect, _dbus_transport_do_iteration, _dbus_transport_finalize_base, _dbus_transport_get_is_connected, _dbus_transport_handle_watch, _dbus_transport_init_base, _dbus_transport_open_platform_specific, _dbus_transport_open_socket, _dbus_transport_queue_messages, _dbus_transport_ref, _dbus_transport_set_connection, _dbus_transport_try_to_authenticate, _dbus_transport_unref, _dbus_type_reader_delete, _dbus_type_reader_get_array_length, _dbus_type_reader_get_current_type, _dbus_type_reader_get_element_type, _dbus_type_reader_read_basic, _dbus_type_reader_read_fixed_multi, _dbus_type_reader_read_raw, _dbus_type_reader_recurse, _dbus_type_reader_set_basic, _dbus_type_signature_next, _dbus_type_writer_append_array, _dbus_type_writer_init_values_only, _dbus_type_writer_unrecurse, _dbus_type_writer_write_fixed_multi, _dbus_unpack_uint16, _dbus_unpack_uint32, _dbus_user_database_flush, _dbus_user_database_get_system, _dbus_user_database_lookup, _dbus_user_database_unref, _dbus_validate_body_with_reason, _dbus_validate_interface, _dbus_validate_member, _dbus_validate_path, _dbus_validate_signature, _dbus_validate_signature_with_reason, _dbus_verbose_bytes, _dbus_verbose_bytes_of_string, _dbus_warn_check_failed, _dbus_watch_new, _dbus_watch_unref, _dbus_write_socket_two, _dbus_write_two, dbus_address_entry_get_value, dbus_address_unescape_value, dbus_bus_set_unique_name, dbus_connection_borrow_message, dbus_connection_get_unix_user, dbus_connection_get_windows_user, dbus_connection_pop_message, dbus_connection_ref, dbus_connection_return_message, dbus_connection_send_preallocated, dbus_connection_send_with_reply_and_block, dbus_connection_steal_borrowed_message, dbus_error_has_name, dbus_error_is_set, dbus_free, dbus_get_version, dbus_message_contains_unix_fds, dbus_message_demarshal_bytes_needed, dbus_message_get_reply_serial, dbus_message_get_signature, dbus_message_iter_init_append, dbus_message_lock, dbus_message_ref, dbus_message_unref, dbus_parse_address, dbus_server_disconnect, dbus_server_get_data, dbus_server_listen, dbus_server_unref, dbus_set_error, dbus_set_error_const, dbus_setenv, dbus_type_is_valid, dbus_watch_get_flags.
_dbus_assert_not_reached
Aborts with an error message if called.
The given explanation will be printed. explanation explanation of what happened if the code was reached.
Referenced by _dbus_babysitter_get_child_exit_status, _dbus_become_daemon, _dbus_bus_notify_shared_connection_disconnected_unlocked, _dbus_connection_handle_watch, _dbus_credentials_include, _dbus_data_slot_allocator_free, _dbus_data_slot_list_free, _dbus_data_slot_list_get, _dbus_data_slot_list_set, _dbus_decompose_path, _dbus_first_type_in_signature_c_str, _dbus_get_environment, _dbus_groups_from_uid, _dbus_hash_table_get_n_entries, _dbus_hash_table_new, _dbus_header_get_byte_order, _dbus_header_have_message_untrusted, _dbus_header_set_field_basic, _dbus_keyring_get_hex_key, _dbus_list_length_is_one, _dbus_marshal_read_basic, _dbus_marshal_set_basic, _dbus_marshal_skip_basic, _dbus_marshal_write_basic, _dbus_marshal_write_fixed_multi, _dbus_mem_pool_dealloc, _dbus_message_loader_get_unix_fds, _dbus_message_loader_return_unix_fds, _dbus_poll, _dbus_sha_compute, _dbus_spawn_async_with_babysitter, _dbus_string_find_byte_backward, _dbus_string_pop_line, _dbus_timeout_list_remove_timeout, _dbus_type_get_alignment, _dbus_type_reader_recurse, _dbus_type_writer_init_values_only, _dbus_type_writer_write_basic, _dbus_type_writer_write_fixed_multi, _dbus_validate_signature_with_reason, _dbus_watch_list_remove_watch, _dbus_write_socket_two, dbus_address_unescape_value, dbus_connection_pop_message, dbus_get_version, dbus_server_get_data, dbus_shutdown, dbus_type_is_valid.
_dbus_return_if_fail
_dbus_return_val_if_fail
_DBUS_N_ELEMENTS
Computes the number of elements in a fixed-size array using sizeof().
array the array to count elements in.
Referenced by _dbus_decompose_path, _dbus_get_autolaunch_address, _dbus_hash_table_new, _dbus_lookup_launchd_socket, _dbus_mem_pool_dealloc, _dbus_string_find_byte_backward, _dbus_transport_open, dbus_address_unescape_value, dbus_server_get_data, dbus_server_listen.
_DBUS_POINTER_TO_INT
Safely casts a void* to an integer; should only be used on void* that actually contain integers, for example one created with _DBUS_INT_TO_POINTER.
Only guaranteed to preserve 32 bits. (i.e. it's used to store 32-bit ints in pointers, but can't be used to store 64-bit pointers in ints.) pointer pointer to extract an integer from.
Referenced by _dbus_data_slot_list_free, _dbus_hash_iter_get_int_key, _dbus_list_length_is_one, _dbus_validate_signature_with_reason.
_DBUS_INT_TO_POINTER
Safely stuffs an integer into a pointer, to be extracted later with _DBUS_POINTER_TO_INT.
Only guaranteed to preserve 32 bits. integer the integer to stuff into a pointer.
Referenced by _dbus_data_slot_list_free, _dbus_hash_table_get_n_entries, _dbus_hash_table_insert_int, _dbus_hash_table_lookup_int, _dbus_hash_table_remove_int, _dbus_list_length_is_one, _dbus_validate_signature_with_reason.
_DBUS_ZERO
Sets all bits in an object to zero.
object the object to be zeroed.
Referenced by _dbus_connect_tcp_socket, _dbus_connect_unix_socket, _dbus_delete_file, _dbus_full_duplex_pipe, _dbus_listen_tcp_socket, _dbus_listen_unix_socket, _dbus_read_credentials_socket, _dbus_read_socket_with_unix_fds, _dbus_sha_final, _dbus_socket_can_pass_unix_fd, _dbus_write_socket_two.
_DBUS_STRUCT_OFFSET
_DBUS_ASSERT_ERROR_IS_SET
_DBUS_ASSERT_ERROR_IS_CLEAR
_dbus_return_if_error_is_set
_dbus_return_val_if_error_is_set
_DBUS_ALIGN_VALUE
_DBUS_ALIGN_ADDRESS
_DBUS_INT16_MIN
Minimum value of type "int16".
_DBUS_INT16_MAX
Maximum value of type "int16".
_DBUS_UINT16_MAX
Maximum value of type "uint16".
_DBUS_INT32_MIN
Minimum value of type "int32".
_DBUS_INT32_MAX
Maximum value of type "int32".
Referenced by _dbus_header_have_message_untrusted, _dbus_validate_signature_with_reason, _dbus_transport_get_unix_user.
_DBUS_UINT32_MAX
Maximum value of type "uint32".
_DBUS_INT_MIN
Minimum value of type "int".
Referenced by _dbus_list_length_is_one.
_DBUS_INT_MAX
Maximum value of type "int".
Referenced by _dbus_real_assert_not_reached, _dbus_list_length_is_one, _dbus_type_reader_init_types_only, _dbus_mem_pool_alloc.
_DBUS_UINT_MAX
Maximum value of type "uint".
_DBUS_INT64_MAX
_DBUS_UINT64_MAX
_DBUS_ONE_KILOBYTE
_DBUS_ONE_MEGABYTE
_DBUS_ONE_HOUR_IN_MILLISECONDS
_DBUS_USEC_PER_SECOND
MAX
MIN
ABS
_DBUS_ISASCII
_DBUS_SET_OOM
_dbus_set_fail_alloc_counter
_dbus_get_fail_alloc_counter
_dbus_decrement_fail_alloc_counter
_dbus_disable_mem_pools
_dbus_get_malloc_blocks_outstanding
_DBUS_LOCK_NAME
Expands to name of a global lock variable.
Referenced by dbus_connection_list_registered, _dbus_message_loader_set_pending_fds_function, _dbus_pending_call_get_completed_unlocked, dbus_server_set_auth_mechanisms.
_DBUS_LOCK
Locks a global lock, initializing it first if necessary.
FALSE if not enough memory
Referenced by _dbus_bus_notify_shared_connection_disconnected_unlocked, _dbus_connection_handle_watch, _dbus_get_local_machine_uuid_encoded, _dbus_get_tmpdir, _dbus_register_shutdown_func, _dbus_user_database_lock_system, _dbus_write_socket_two, dbus_bus_get_unique_name, dbus_bus_register, dbus_bus_set_unique_name.
_DBUS_UNLOCK
Unlocks a global lock.
Referenced by _dbus_bus_notify_shared_connection_disconnected_unlocked, dbus_bus_register, dbus_bus_set_unique_name, dbus_bus_get_unique_name, _dbus_connection_handle_watch, _dbus_get_local_machine_uuid_encoded, _dbus_register_shutdown_func, _dbus_get_tmpdir, _dbus_write_socket_two, _dbus_user_database_unlock_system.
DBUS_UUID_LENGTH_BYTES
DBUS_UUID_LENGTH_WORDS
DBUS_UUID_LENGTH_HEX
_DBUS_PASTE2
_DBUS_PASTE
_DBUS_STATIC_ASSERT
DBusGlobalLock
DBusForeachFunction)(void *element, void *data)
Used to iterate over each item in a collection, such as a DBusList.
typedef void(* DBusShutdownFunction) (void *data))(void *data)
const char* _dbus_return_if_fail_warning_format
String used in _dbus_return_if_fail macro.
Referenced by dbus_server_ref, dbus_server_unref.
const char* _dbus_no_memory_message
Fixed "out of memory" error message, just to avoid making up a different string every time and wasting space.
int _dbus_current_generation
_dbus_current_generation is used to track each time that dbus_shutdown() is called, so we can reinit things after it's been called.
It is simply incremented each time we shut down.
Referenced by _dbus_connection_new_for_transport, _dbus_connection_ref_unlocked, _dbus_connection_close_possibly_shared, dbus_connection_ref, dbus_connection_unref, dbus_connection_close, _dbus_get_local_machine_uuid_encoded, dbus_message_get_reply_serial, dbus_message_ref, dbus_message_unref, _dbus_condvar_wake_one, dbus_threads_init.
void _dbus_warn(const char *format,...)
Prints a warning message to stderr.
Can optionally be made to exit fatally by setting DBUS_FATAL_WARNINGS, but this is rarely used. This function should be considered pretty much equivalent to fprintf(stderr). _dbus_warn_check_failed() on the other hand is suitable for use when a programming mistake has been made. format printf-style format string.
References _dbus_abort.
Referenced by dbus_address_unescape_value, dbus_connection_register_object_path, dbus_connection_register_fallback, _dbus_warn_check_failed, _dbus_real_assert, _dbus_real_assert_not_reached, _dbus_marshal_read_basic, _dbus_marshal_skip_basic, dbus_malloc, dbus_malloc0, dbus_realloc, _dbus_message_iter_get_args_valist, dbus_message_append_args_valist, _dbus_object_tree_unregister_and_unlock, _dbus_decompose_path, _dbus_server_new_for_launchd, dbus_server_get_data, _dbus_sha_compute, _dbus_spawn_async_with_babysitter, _dbus_babysitter_unref, _dbus_listen_unix_socket, _dbus_listen_tcp_socket, _dbus_check_dir_is_private_to_user, _dbus_poll, _dbus_full_duplex_pipe, _dbus_append_keyring_directory_for_credentials, _dbus_change_to_daemon_user, _dbus_get_environment, _dbus_get_tmpdir, _dbus_file_exists, _dbus_user_database_lookup, _dbus_watch_unref.
void _dbus_warn_check_failed(const char *format,...)
Prints a "critical" warning to stderr when an assertion fails; differs from _dbus_warn primarily in that it prefixes the pid and defaults to fatal.
This should be used only when a programming error has been detected. (NOT for unavoidable errors that an app might handle - those should be returned as DBusError.) Calling this means "there is a bug"
References _dbus_pid_for_log, _dbus_abort, FALSE, TRUE, _dbus_getenv, NULL, _dbus_assert, _dbus_warn.
Referenced by dbus_connection_unref, dbus_connection_close, dbus_connection_remove_filter, _dbus_get_local_machine_uuid_encoded, _dbus_marshal_read_basic, _dbus_type_reader_recurse, _dbus_type_writer_init_values_only, dbus_message_iter_init_append, dbus_server_ref, dbus_server_unref, dbus_server_set_watch_functions, dbus_server_set_timeout_functions, _dbus_transport_handle_watch, dbus_watch_handle.
static void _dbus_verbose(const char *x,...)
void _dbus_trace_ref(const char *obj_name, void *obj, int old_refcount, int new_refcount, const char *why, const char *env_var, int *enabled)
const char* _dbus_strerror(int error_number)
A wrapper around strerror() because some platforms may be lame and not have strerror().
Also, never returns NULL. error_number errno. error description. error_number errno. error description.
void _dbus_real_assert(dbus_bool_t condition, const char *condition_text, const char *file, int line, const char *func)
Internals of _dbus_assert(); it's a function rather than a macro with the inline code so that the assertion failure blocks don't show up in test suite coverage, and to shrink code size.
condition TRUE if assertion succeeded condition_text condition as a string file file the assertion is in line line the assertion is in func function the assertion is in
References _dbus_warn, _dbus_pid_for_log, _dbus_abort.
void _dbus_real_assert_not_reached(const char *explanation, const char *file, int line) _DBUS_GNUC_NORETURN
Internals of _dbus_assert_not_reached(); it's a function rather than a macro with the inline code so that the assertion failure blocks don't show up in test suite coverage, and to shrink code size.
explanation what was reached that shouldn't have been file file the assertion is in line line the assertion is in
References _dbus_warn, _dbus_pid_for_log, _dbus_abort, FALSE, _DBUS_INT_MAX, TRUE, _dbus_getenv, NULL, _dbus_string_init_const, _dbus_string_parse_int.
char* _dbus_strdup(const char *str)
Duplicates a string.
Result must be freed with dbus_free(). Returns NULL if memory allocation fails. If the string to be duplicated is NULL, returns NULL. str string to duplicate. newly-allocated copy.
References NULL, dbus_malloc.
Referenced by dbus_bus_register, dbus_bus_set_unique_name, dbus_bus_get_id, _dbus_connection_handle_watch, dbus_connection_get_server_id, _dbus_credentials_add_windows_sid, dbus_set_error, _dbus_hash_table_get_n_entries, _dbus_dup_string_array, _dbus_message_iter_get_args_valist, _dbus_object_tree_free_all_unlocked, _dbus_server_new_for_domain_socket, dbus_server_get_address, _dbus_spawn_async_with_babysitter, _dbus_check_dir_is_private_to_user, _dbus_directory_close, _dbus_get_environment, _dbus_transport_open_platform_specific, _dbus_transport_open, _dbus_transport_get_is_connected, _dbus_transport_get_windows_user.
void* _dbus_memdup(const void *mem, size_t n_bytes)
Duplicates a block of memory.
Returns NULL on failure. mem memory to copy n_bytes number of bytes to copy the copy
References dbus_malloc, NULL.
Referenced by _dbus_credentials_add_adt_audit_data, _dbus_message_loader_return_unix_fds, _dbus_decompose_path.
dbus_bool_t _dbus_string_array_contains(const char **array, const char *str)
Checks whether a string array contains the given string.
array array to search. str string to look for TRUE if array contains string
References NULL, TRUE, FALSE.
char** _dbus_dup_string_array(const char **array)
Duplicates a string array.
Result may be freed with dbus_free_string_array(). Returns NULL if memory allocation fails. If the array to be duplicated is NULL, returns NULL. array array to duplicate. newly-allocated copy.
References NULL, dbus_new0, _dbus_strdup, dbus_free_string_array.
Referenced by _dbus_auth_set_mechanisms, dbus_server_set_auth_mechanisms.
dbus_bool_t _dbus_set_fd_nonblocking(int fd, DBusError *error)
Sets a file descriptor to be nonblocking.
fd the file descriptor. error address of error location. TRUE on success. handle the file descriptor. error address of error location. TRUE on success.
void _dbus_verbose_bytes(const unsigned char *data, int len, int offset)
If in verbose mode, print a block of binary data.
data the data len the length of the data offset where to start counting for byte indexes
References _dbus_assert, _dbus_unpack_uint32, DBUS_BIG_ENDIAN, DBUS_LITTLE_ENDIAN, dbus_uint64_t.
Referenced by _dbus_verbose_bytes_of_string.
void _dbus_verbose_bytes_of_string(const DBusString *str, int start, int len)
Dump the given part of the string to verbose log.
str the string start the start of range to dump len length of range
References _dbus_assert, _dbus_verbose_bytes, DBUS_STRUCT_BEGIN_CHAR, DBUS_TYPE_STRUCT, DBUS_DICT_ENTRY_BEGIN_CHAR, DBUS_TYPE_DICT_ENTRY, DBUS_STRUCT_END_CHAR, DBUS_DICT_ENTRY_END_CHAR.
Referenced by _dbus_marshal_read_basic, _dbus_type_reader_set_basic, _dbus_message_loader_return_unix_fds, _dbus_read_socket_with_unix_fds, _dbus_read, _dbus_write, _dbus_read_socket, _dbus_write_socket.
dbus_bool_t _dbus_register_shutdown_func(DBusShutdownFunction function, void *data)
Register a cleanup function to be called exactly once the next time dbus_shutdown() is called.
func the function data data to pass to the function FALSE on not enough memory
References _DBUS_LOCK, FALSE, _DBUS_UNLOCK, ShutdownClosure::func, ShutdownClosure::data, dbus_new, NULL, ShutdownClosure::next, TRUE.
Referenced by _dbus_connection_handle_watch, _dbus_user_database_lookup.
dbus_bool_t _dbus_register_shutdown_func_unlocked(DBusShutdownFunction function, void *data)
dbus_bool_t _dbus_lock(DBusGlobalLock lock) _DBUS_GNUC_WARN_UNUSED_RESULT
void _dbus_unlock(DBusGlobalLock lock)
dbus_bool_t _dbus_threads_init_debug(void)
dbus_bool_t _dbus_address_append_escaped(DBusString *escaped, const DBusString *unescaped)
Appends an escaped version of one string to another string, using the D-Bus address escaping mechanism.
escaped the string to append to unescaped the string to escape FALSE if no memory
References FALSE, _DBUS_ADDRESS_OPTIONALLY_ESCAPED_BYTE, _dbus_string_append_byte, _dbus_string_append_byte_as_hex, TRUE, _dbus_string_set_length, _dbus_string_free, DBusAddressEntry::method, _dbus_list_get_first_link, DBusAddressEntry::keys, NULL, DBusList::data, dbus_free, _dbus_list_get_next_link, _dbus_list_clear, DBusAddressEntry::values.
Referenced by dbus_address_escape_value, _dbus_server_new_for_tcp_socket, _dbus_server_new_for_domain_socket, _dbus_append_address_from_socket.
void _dbus_set_bad_address(DBusError *error, const char *address_problem_type, const char *address_problem_field, const char *address_problem_other)
Sets DBUS_ERROR_BAD_ADDRESS.
If address_problem_type and address_problem_field are not NULL, sets an error message about how the field is no good. Otherwise, sets address_problem_other as the error message. error the error to set address_problem_type the address type of the bad address or NULL address_problem_field the missing field of the bad address or NULL address_problem_other any other error message or NULL
References NULL, dbus_set_error, DBUS_ERROR_BAD_ADDRESS.
Referenced by _dbus_server_listen_platform_specific, _dbus_transport_open_socket, _dbus_transport_open_platform_specific, _dbus_transport_open.
void _dbus_generate_uuid(DBusGUID *uuid)
Generates a new UUID.
If you change how this is done, there's some text about it in the spec that should also change. uuid the uuid to initialize
References _dbus_get_real_time, NULL, DBusGUID::as_uint32s, _dbus_generate_random_bytes_buffer, DBusGUID::as_bytes.
Referenced by _dbus_read_uuid_file, _dbus_get_local_machine_uuid_encoded, _dbus_server_init_base, _dbus_read_local_machine_uuid, dbus_internal_do_not_use_create_uuid.
dbus_bool_t _dbus_uuid_encode(const DBusGUID *uuid, DBusString *encoded)
Hex-encode a UUID.
uuid the uuid encoded string to append hex uuid to FALSE if no memory
References _dbus_string_init_const_len, DBusGUID::as_bytes, _dbus_string_hex_encode, _dbus_string_init, FALSE, _dbus_string_free, _dbus_file_get_contents, _dbus_string_chop_white, dbus_set_error, DBUS_ERROR_INVALID_FILE_CONTENT, _dbus_string_hex_decode, _dbus_string_copy_to_buffer, TRUE.
Referenced by _dbus_write_uuid_file, _dbus_get_local_machine_uuid_encoded, _dbus_server_init_base.
dbus_bool_t _dbus_read_uuid_file(const DBusString *filename, DBusGUID *uuid, dbus_bool_t create_if_not_found, DBusError *error)
Reads (and optionally writes) a uuid to a file.
Initializes the uuid unless an error is returned. filename the name of the file uuid uuid to be initialized with the loaded uuid create_if_not_found TRUE to create a new uuid and save it if the file doesn't exist error the error return FALSE if the error is set
References DBUS_ERROR_INIT, TRUE, dbus_move_error, FALSE, dbus_error_has_name, DBUS_ERROR_INVALID_FILE_CONTENT, dbus_error_free, _dbus_generate_uuid, _dbus_write_uuid_file.
Referenced by _dbus_read_local_machine_uuid, dbus_internal_do_not_use_get_uuid.
dbus_bool_t _dbus_write_uuid_file(const DBusString *filename, const DBusGUID *uuid, DBusError *error)
Write the give UUID to a file.
filename the file to write uuid the UUID to save error used to raise an error FALSE on error
References _dbus_string_init, FALSE, _dbus_uuid_encode, _dbus_string_append_byte, _dbus_string_save_to_file, TRUE, _dbus_string_free.
Referenced by _dbus_read_uuid_file, _dbus_read_local_machine_uuid.
dbus_bool_t _dbus_get_local_machine_uuid_encoded(DBusString *uuid_str)
Gets the hex-encoded UUID of the machine this function is executed on.
This UUID is guaranteed to be the same for a given machine at least until it next reboots, though it also makes some effort to be the same forever, it may change if the machine is reconfigured or its hardware is modified. uuid_str string to append hex-encoded machine uuid to FALSE if no memory
References _DBUS_LOCK, FALSE, _dbus_current_generation, DBUS_ERROR_INIT, _dbus_read_local_machine_uuid, _dbus_warn_check_failed, DBusError::message, dbus_error_free, _dbus_generate_uuid, _dbus_uuid_encode, _DBUS_UNLOCK.
Referenced by dbus_connection_get_dispatch_status, dbus_get_local_machine_id, _dbus_get_autolaunch_address.