dbus-keyring.c
NEW_KEY_TIMEOUT_SECONDS
The maximum age of a key before we create a new key to use in challenges.
This isn't super-reliably enforced, since system clocks can change or be wrong, but we make a best effort to only use keys for a short time.
Referenced by _dbus_keyring_validate_context.
EXPIRE_KEYS_TIMEOUT_SECONDS
The time after which we drop a key from the secrets file.
The EXPIRE_KEYS_TIMEOUT_SECONDS - NEW_KEY_TIMEOUT_SECONDS is the minimum time window a client has to complete authentication.
MAX_TIME_TRAVEL_SECONDS
The maximum amount of time a key can be in the future.
MAX_KEYS_IN_FILE
Maximum number of keys in the keyring before we just ignore the rest.
MAX_LOCK_TIMEOUTS
Maximum number of timeouts waiting for lock before we decide it's stale.
LOCK_TIMEOUT_MILLISECONDS
Length of each timeout while waiting for a lock.
KEY_LENGTH_BYTES
static DBusKeyring* _dbus_keyring_new(void)
static void free_keys(DBusKey *keys, int n_keys)
static dbus_bool_t _dbus_keyring_lock(DBusKeyring *keyring)
static void _dbus_keyring_unlock(DBusKeyring *keyring)
static DBusKey* find_key_by_id(DBusKey *keys, int n_keys, int id)
static dbus_bool_t add_new_key(DBusKey **keys_p, int *n_keys_p, DBusError *error)
static dbus_bool_t _dbus_keyring_reload(DBusKeyring *keyring, dbus_bool_t add_new, DBusError *error)
Reloads the keyring file, optionally adds one new key to the file, removes all expired keys from the file iff a key was added, then resaves the file.
Stores the keys from the file in keyring->keys. Note that the file is only resaved (written to) if a key is added, this means that only servers ever write to the file and need to lock it, which avoids a lot of lock contention at login time and such. keyring the keyring add_new TRUE to add a new key to the file, expire keys, and resave error return location for errors FALSE on failure
DBusKeyring* _dbus_keyring_ref(DBusKeyring *keyring)
Increments reference count of the keyring.
keyring the keyring the keyring
References DBusKeyring::refcount.
Referenced by _dbus_keyring_get_hex_key.
void _dbus_keyring_unref(DBusKeyring *keyring)
Decrements refcount and finalizes if it reaches zero.
keyring the keyring
References _dbus_credentials_unref, _dbus_string_free, DBusKeyring::credentials, dbus_free, DBusKeyring::directory, DBusKeyring::filename, DBusKeyring::filename_lock, DBusKeyring::keys, DBusKeyring::n_keys, DBusKeyring::refcount.
Referenced by _dbus_auth_unref, _dbus_keyring_get_hex_key, _dbus_keyring_new_for_credentials.
DBusKeyring* _dbus_keyring_new_for_credentials(DBusCredentials *credentials, const DBusString *context, DBusError *error)
Creates a new keyring that lives in the ~/.dbus-keyrings directory of the user represented by credentials.
If the credentials are NULL or empty, uses those of the current process. credentials a set of credentials representing a user or NULL context which keyring to get error return location for errors the keyring or NULL on error
References _dbus_append_keyring_directory_for_credentials, _dbus_assert, _dbus_check_setuid, _dbus_concat_dir_and_file, _dbus_create_directory, _dbus_credentials_add_from_current_process, _dbus_credentials_are_anonymous, _dbus_credentials_copy, _dbus_credentials_new_from_current_process, _dbus_credentials_unref, _dbus_keyring_unref, _dbus_keyring_validate_context, _dbus_string_append, _dbus_string_copy, _dbus_string_free, _dbus_string_init, DBusKeyring::credentials, DBUS_ERROR_FAILED, dbus_error_free, dbus_error_init, DBUS_ERROR_NO_MEMORY, DBUS_ERROR_NOT_SUPPORTED, dbus_set_error, dbus_set_error_const, DBusKeyring::directory, FALSE, DBusKeyring::filename, DBusKeyring::filename_lock, DBusError::message, NULL, TRUE.
Referenced by _dbus_keyring_get_hex_key.
dbus_bool_t _dbus_keyring_validate_context(const DBusString *context)
Checks whether the context is a valid context.
Contexts that might cause confusion when used in filenames are not allowed (contexts can't start with a dot or contain dir separators).Todothis is the most inefficient implementation imaginable. context the context TRUE if valid
References _dbus_get_real_time, _dbus_string_find, _dbus_string_find_blank, _dbus_string_validate_ascii, DBusKey::creation_time, FALSE, DBusKeyring::keys, DBusKeyring::n_keys, NEW_KEY_TIMEOUT_SECONDS, NULL, TRUE.
Referenced by _dbus_keyring_get_hex_key, _dbus_keyring_new_for_credentials.
static DBusKey* find_recent_key(DBusKeyring *keyring)
int _dbus_keyring_get_best_key(DBusKeyring *keyring, DBusError *error)
Gets a recent key to use for authentication.
If no recent key exists, creates one. Returns the key ID. If a key can't be written to the keyring file so no recent key can be created, returns -1. All valid keys are > 0. keyring the keyring error error on failure key ID to use for auth, or -1 on failure
References DBUS_ERROR_FAILED, dbus_set_error_const, DBusKey::id, TRUE.
Referenced by _dbus_keyring_get_hex_key.
dbus_bool_t _dbus_keyring_is_for_credentials(DBusKeyring *keyring, DBusCredentials *credentials)
Checks whether the keyring is for the same user as the given credentials.
keyring the keyring credentials the credentials to check TRUE if the keyring belongs to the given user
References _dbus_credentials_same_user, DBusKeyring::credentials.
dbus_bool_t _dbus_keyring_get_hex_key(DBusKeyring *keyring, int key_id, DBusString *hex_key)
Gets the hex-encoded secret key for the given ID.
Returns FALSE if not enough memory. Returns TRUE but empty key on any other error such as unknown key ID. keyring the keyring key_id the key ID hex_key string to append hex-encoded key to TRUE if we had enough memory
References _dbus_assert, _dbus_assert_not_reached, _dbus_keyring_get_best_key, _dbus_keyring_new_for_credentials, _dbus_keyring_ref, _dbus_keyring_unref, _dbus_keyring_validate_context, _dbus_string_append_byte, _dbus_string_equal, _dbus_string_free, _dbus_string_hex_encode, _dbus_string_init, _dbus_string_init_const, DBusKey::creation_time, dbus_error_free, dbus_error_init, FALSE, DBusKey::id, DBusKeyring::keys, DBusError::message, DBusKeyring::n_keys, DBusError::name, NULL, DBusKey::secret, TRUE.