dbus-message-internal.h
_dbus_message_trace_ref
DBusMessageLoader
The DBusMessageLoader object encapsulates the process of converting a byte stream into a series of DBusMessage.
It buffers the incoming bytes as efficiently as possible, and generates a queue of messages. DBusMessageLoader is typically used as part of a DBusTransport implementation. The DBusTransport then hands off the loaded messages to a DBusConnection, making the messages visible to the application.Todowrite tests for break-loader that a) randomly delete header fields and b) set string fields to zero-length and other funky values.
typedef struct DBusInitialFDs DBusInitialFDs
void _dbus_message_get_network_data(DBusMessage *message, const DBusString **header, const DBusString **body)
Gets the data to be sent over the network for this message.
The header and then the body should be written out. This function is guaranteed to always return the same data once a message is locked (with dbus_message_lock()). message the message. header return location for message header data. body return location for message body data.
References _dbus_assert, DBusMessage::locked, DBusMessage::header, DBusHeader::data, DBusMessage::body.
void _dbus_message_get_unix_fds(DBusMessage *message, const int **fds, unsigned *n_fds)
Gets the unix fds to be sent over the network for this message.
This function is guaranteed to always return the same data once a message is locked (with dbus_message_lock()). message the message. fds return location of unix fd array n_fds return number of entries in array
References _dbus_assert, DBusMessage::locked, NULL.
void _dbus_message_lock(DBusMessage *message)
void _dbus_message_unlock(DBusMessage *message)
dbus_bool_t _dbus_message_add_counter(DBusMessage *message, DBusCounter *counter)
Adds a counter to be incremented immediately with the size/unix fds of this message, and decremented by the size/unix fds of this message when this message if finalized.
This function may be called with locks held. As a result, the counter's notify function is not called; the caller is expected to either call _dbus_counter_notify() on the counter when they are no longer holding locks, or take the same action that would be taken by the notify function. message the message counter the counter FALSE if no memory
References _dbus_list_alloc_link, NULL, FALSE, _dbus_counter_ref, _dbus_message_add_counter_link, TRUE.
Referenced by _dbus_transport_queue_messages.
void _dbus_message_add_counter_link(DBusMessage *message, DBusList *link)
Adds a counter to be incremented immediately with the size/unix fds of this message, and decremented by the size/unix fds of this message when this message if finalized.
The link contains a counter with its refcount already incremented, but the counter itself not incremented. Ownership of link and counter refcount is passed to the message.This function may be called with locks held. As a result, the counter's notify function is not called; the caller is expected to either call _dbus_counter_notify() on the counter when they are no longer holding locks, or take the same action that would be taken by the notify function. message the message link link with counter as data
References DBusMessage::counters, NULL, DBusMessage::size_counter_delta, DBusMessage::header, DBusHeader::data, DBusMessage::body, _dbus_list_append_link, _dbus_counter_adjust_size, DBusList::data, _dbus_counter_adjust_unix_fd.
Referenced by _dbus_connection_close_possibly_shared, _dbus_message_add_counter.
void _dbus_message_remove_counter(DBusMessage *message, DBusCounter *counter)
Removes a counter tracking the size/unix fds of this message, and decrements the counter by the size/unix fds of this message.
message the message counter the counter
References _dbus_list_find_last, DBusMessage::counters, _dbus_assert, NULL, _dbus_list_remove_link, _dbus_counter_adjust_size, DBusMessage::size_counter_delta, _dbus_counter_adjust_unix_fd, _dbus_counter_notify, _dbus_counter_unref.
Referenced by _dbus_connection_message_sent_unlocked, dbus_connection_ref.
DBusMessageLoader* _dbus_message_loader_new(void)
Creates a new message loader.
Returns NULL if memory can't be allocated.new loader, or NULL.
References dbus_new0, NULL, DBusMessageLoader::refcount, DBusMessageLoader::corrupted, FALSE, DBusMessageLoader::corruption_reason, DBUS_VALID, DBusMessageLoader::max_message_size, DBUS_MAXIMUM_MESSAGE_LENGTH, DBusMessageLoader::max_message_unix_fds, _dbus_string_init, DBusMessageLoader::data, dbus_free, _dbus_string_set_length, INITIAL_LOADER_DATA_LEN.
Referenced by dbus_message_demarshal, _dbus_transport_init_base.
DBusMessageLoader* _dbus_message_loader_ref(DBusMessageLoader *loader)
Increments the reference count of the loader.
loader the loader. the loader
References DBusMessageLoader::refcount.
void _dbus_message_loader_unref(DBusMessageLoader *loader)
Decrements the reference count of the loader and finalizes the loader when the count reaches zero.
loader the loader.
References DBusMessageLoader::refcount, dbus_free, _dbus_list_foreach, DBusMessageLoader::messages, dbus_message_unref, NULL, _dbus_list_clear, _dbus_string_free, DBusMessageLoader::data.
Referenced by dbus_message_demarshal, _dbus_transport_init_base, _dbus_transport_finalize_base.
void _dbus_message_loader_get_buffer(DBusMessageLoader *loader, DBusString **buffer)
Gets the buffer to use for reading data from the network.
Network data is read directly into an allocated buffer, which is then used in the DBusMessage, to avoid as many extra memcpy's as possible. The buffer must always be returned immediately using _dbus_message_loader_return_buffer(), even if no bytes are successfully read.Todothis function can be a lot more clever. For example it can probably always return a buffer size to read exactly the body of the next message, thus avoiding any memory wastage or reallocs.Todowe need to enforce a max length on strings in header fields. loader the message loader. buffer the buffer
References _dbus_assert, DBusMessageLoader::buffer_outstanding, DBusMessageLoader::data, TRUE.
Referenced by dbus_message_demarshal, _dbus_transport_do_iteration.
void _dbus_message_loader_return_buffer(DBusMessageLoader *loader, DBusString *buffer)
Returns a buffer obtained from _dbus_message_loader_get_buffer(), indicating to the loader how many bytes of the buffer were filled in.
This function must always be called, even if no bytes were successfully read. loader the loader. buffer the buffer.
References _dbus_assert, DBusMessageLoader::buffer_outstanding, DBusMessageLoader::data, FALSE.
Referenced by dbus_message_demarshal, _dbus_transport_do_iteration.
dbus_bool_t _dbus_message_loader_get_unix_fds(DBusMessageLoader *loader, int **fds, unsigned *max_n_fds)
Gets the buffer to use for reading unix fds from the network.
This works similar to _dbus_message_loader_get_buffer() loader the message loader. fds the array to read fds into max_n_fds how many fds to read at most TRUE on success, FALSE on OOM
References _dbus_assert, DBusMessageLoader::max_message_unix_fds, dbus_realloc, FALSE, TRUE, _dbus_assert_not_reached.
void _dbus_message_loader_return_unix_fds(DBusMessageLoader *loader, int *fds, unsigned n_fds)
Returns a buffer obtained from _dbus_message_loader_get_unix_fds().
This works similar to _dbus_message_loader_return_buffer() loader the message loader. fds the array fds were read into n_fds how many fds were read
References _dbus_assert, FALSE, _dbus_assert_not_reached, _dbus_verbose_bytes_of_string, DBusMessageLoader::data, DBusMessage::header, DBusHeader::data, _dbus_header_load, DBUS_VALID, DBUS_VALIDITY_UNKNOWN_OOM_ERROR, TRUE, DBusMessageLoader::corrupted, DBusMessageLoader::corruption_reason, _dbus_validate_body_with_reason, NULL, _dbus_header_get_field_basic, DBUS_HEADER_FIELD_UNIX_FDS, DBUS_TYPE_UINT32, dbus_free, _dbus_memdup, _dbus_list_append, DBusMessageLoader::messages, DBusMessage::body, _dbus_string_copy_len, _dbus_string_delete, _dbus_string_compact, _dbus_list_find_last, _dbus_list_remove_last.
dbus_bool_t _dbus_message_loader_queue_messages(DBusMessageLoader *loader)
Converts buffered data into messages, if we have enough data.
If we don't have enough data, does nothing.Todowe need to check that the proper named header fields exist for each message type.TodoIf a message has unknown type, we should probably eat it right here rather than passing it out to applications. However it's not an error to see messages of unknown type. loader the loader. TRUE if we had enough memory to finish.
References DBusMessageLoader::corrupted, DBusMessageLoader::data, DBUS_MINIMUM_HEADER_SIZE, _dbus_header_have_message_untrusted, DBusMessageLoader::max_message_size, DBusMessageRealIter::message, _dbus_assert, DBUS_VALID, NULL, FALSE, dbus_message_unref, DBusMessageLoader::messages, _dbus_list_find_last, TRUE, DBusMessageLoader::corruption_reason.
Referenced by dbus_message_demarshal, _dbus_transport_get_dispatch_status.
DBusMessage* _dbus_message_loader_peek_message(DBusMessageLoader *loader)
Peeks at first loaded message, returns NULL if no messages have been queued.
loader the loader. the next message, or NULL if none.
References DBusMessageLoader::messages, DBusList::data, NULL.
Referenced by _dbus_transport_get_dispatch_status.
DBusMessage* _dbus_message_loader_pop_message(DBusMessageLoader *loader)
Pops a loaded message (passing ownership of the message to the caller).
Returns NULL if no messages have been queued. loader the loader. the next message, or NULL if none.
References _dbus_list_pop_first, DBusMessageLoader::messages.
Referenced by dbus_message_demarshal.
DBusList* _dbus_message_loader_pop_message_link(DBusMessageLoader *loader)
Pops a loaded message inside a list link (passing ownership of the message and link to the caller).
Returns NULL if no messages have been loaded. loader the loader. the next message link, or NULL if none.
References _dbus_list_pop_first_link, DBusMessageLoader::messages.
Referenced by _dbus_transport_queue_messages.
void _dbus_message_loader_putback_message_link(DBusMessageLoader *loader, DBusList *link)
Returns a popped message link, used to undo a pop.
loader the loader link the link with a message in it
References _dbus_list_prepend_link, DBusMessageLoader::messages.
Referenced by _dbus_transport_queue_messages.
dbus_bool_t _dbus_message_loader_get_is_corrupted(DBusMessageLoader *loader)
Checks whether the loader is confused due to bad data.
If messages are received that are invalid, the loader gets confused and gives up permanently. This state is called "corrupted." loader the loader TRUE if the loader is hosed.
References _dbus_assert, DBusMessageLoader::corrupted, DBusMessageLoader::corruption_reason, DBUS_VALID.
Referenced by dbus_message_demarshal, _dbus_transport_queue_messages.
DBusValidity _dbus_message_loader_get_corruption_reason(DBusMessageLoader *loader)
Checks what kind of bad data confused the loader.
loader the loader why the loader is hosed, or DBUS_VALID if it isn't.
References _dbus_assert, DBusMessageLoader::corrupted, DBusMessageLoader::corruption_reason, DBUS_VALID.
void _dbus_message_loader_set_max_message_size(DBusMessageLoader *loader, long size)
Sets the maximum size message we allow.
loader the loader size the max message size in bytes
References DBUS_MAXIMUM_MESSAGE_LENGTH, DBusMessageLoader::max_message_size.
Referenced by _dbus_transport_set_max_message_size.
long _dbus_message_loader_get_max_message_size(DBusMessageLoader *loader)
Gets the maximum allowed message size in bytes.
loader the loader max size in bytes
References DBusMessageLoader::max_message_size.
Referenced by _dbus_transport_get_max_message_size.
void _dbus_message_loader_set_max_message_unix_fds(DBusMessageLoader *loader, long n)
Sets the maximum unix fds per message we allow.
loader the loader n the max number of unix fds in a message
References DBUS_MAXIMUM_MESSAGE_UNIX_FDS, DBusMessageLoader::max_message_unix_fds.
Referenced by _dbus_transport_set_max_message_unix_fds.
long _dbus_message_loader_get_max_message_unix_fds(DBusMessageLoader *loader)
Gets the maximum allowed number of unix fds per message.
loader the loader max unix fds
References DBusMessageLoader::max_message_unix_fds.
Referenced by _dbus_transport_get_max_message_unix_fds.
int _dbus_message_loader_get_pending_fds_count(DBusMessageLoader *loader)
Return how many file descriptors are pending in the loader.
loader the loader
Referenced by _dbus_transport_get_pending_fds_count.
void _dbus_message_loader_set_pending_fds_function(DBusMessageLoader *loader, void(*callback)(void *), void *data)
Register a function to be called whenever the number of pending file descriptors in the loader change.
loader the loader callback the callback data the data for the callback
References _DBUS_LOCK_NAME.
Referenced by _dbus_transport_set_pending_fds_function.
DBusInitialFDs* _dbus_check_fdleaks_enter(void)
void _dbus_check_fdleaks_leave(DBusInitialFDs *fds)