dbus-message.c
_DBUS_TYPE_IS_STRINGLIKE
_dbus_enable_message_cache
ensure_byte_order
byte-swap the message if it doesn't match our byte order.
Called only when we need the message in our own byte order, normally when reading arrays of integers or doubles. Otherwise should not be called since it would do needless work.
Referenced by dbus_message_get_args_valist.
MAX_MESSAGE_SIZE_TO_CACHE
Avoid caching huge messages.
MAX_MESSAGE_CACHE_SIZE
Avoid caching too many messages.
INITIAL_LOADER_DATA_LEN
The initial buffer size of the message loader.
Todothis should be based on min header size plus some average body size, or something. Or rather, the min header size only, if we want to try to read only the header, store that in a DBusMessage, then read only the body and store that, etc., depends on how we optimize _dbus_message_loader_get_buffer() and what the exact message format is.
Referenced by _dbus_message_loader_new.
@5
typedef struct DBusMessageRealIter DBusMessageRealIter
typedef for internals of message iterator
DBusMessage* message_cache[MAX_MESSAGE_CACHE_SIZE][MAX_MESSAGE_CACHE_SIZE]
int message_cache_count
dbus_bool_t message_cache_shutdown_registered
DBusDataSlotAllocator slot_allocator
static void dbus_message_finalize(DBusMessage *message)
void _dbus_message_trace_ref(DBusMessage *message, int old_refcount, int new_refcount, const char *why)
_DBUS_STRING_DEFINE_STATIC(_dbus_empty_signature_str,"")
An static string representing an empty signature.
static void get_const_signature(DBusHeader *header, const DBusString **type_str_p, int *type_pos_p)
static void _dbus_message_byteswap(DBusMessage *message)
Swaps the message to compiler byte order if required.
message the message
void _dbus_message_get_network_data(DBusMessage *message, const DBusString **header, const DBusString **body)
Gets the data to be sent over the network for this message.
The header and then the body should be written out. This function is guaranteed to always return the same data once a message is locked (with dbus_message_lock()). message the message. header return location for message header data. body return location for message body data.
References _dbus_assert, DBusMessage::body, DBusHeader::data, DBusMessage::header, DBusMessage::locked.
void _dbus_message_get_unix_fds(DBusMessage *message, const int **fds, unsigned *n_fds)
Gets the unix fds to be sent over the network for this message.
This function is guaranteed to always return the same data once a message is locked (with dbus_message_lock()). message the message. fds return location of unix fd array n_fds return number of entries in array
References _dbus_assert, DBusMessage::locked, NULL.
void dbus_message_set_serial(DBusMessage *message, dbus_uint32_t serial)
Sets the serial number of a message.
This can only be done once on a message.DBusConnection will automatically set the serial to an appropriate value when the message is sent; this function is only needed when encapsulating messages in another protocol, or otherwise bypassing DBusConnection. message the message serial the serial
References _dbus_header_set_serial, DBusMessage::header, DBusMessage::locked, NULL.
Referenced by _dbus_connection_close_possibly_shared, dbus_connection_send_with_reply.
void _dbus_message_add_counter_link(DBusMessage *message, DBusList *link)
Adds a counter to be incremented immediately with the size/unix fds of this message, and decremented by the size/unix fds of this message when this message if finalized.
The link contains a counter with its refcount already incremented, but the counter itself not incremented. Ownership of link and counter refcount is passed to the message.This function may be called with locks held. As a result, the counter's notify function is not called; the caller is expected to either call _dbus_counter_notify() on the counter when they are no longer holding locks, or take the same action that would be taken by the notify function. message the message link link with counter as data
References _dbus_counter_adjust_size, _dbus_counter_adjust_unix_fd, _dbus_list_append_link, DBusMessage::body, DBusMessage::counters, DBusList::data, DBusHeader::data, DBusMessage::header, NULL, DBusMessage::size_counter_delta.
Referenced by _dbus_connection_close_possibly_shared, _dbus_message_add_counter.
dbus_bool_t _dbus_message_add_counter(DBusMessage *message, DBusCounter *counter)
Adds a counter to be incremented immediately with the size/unix fds of this message, and decremented by the size/unix fds of this message when this message if finalized.
This function may be called with locks held. As a result, the counter's notify function is not called; the caller is expected to either call _dbus_counter_notify() on the counter when they are no longer holding locks, or take the same action that would be taken by the notify function. message the message counter the counter FALSE if no memory
References _dbus_counter_ref, _dbus_list_alloc_link, _dbus_message_add_counter_link, FALSE, NULL, TRUE.
Referenced by _dbus_transport_queue_messages.
void _dbus_message_remove_counter(DBusMessage *message, DBusCounter *counter)
Removes a counter tracking the size/unix fds of this message, and decrements the counter by the size/unix fds of this message.
message the message counter the counter
References _dbus_assert, _dbus_counter_adjust_size, _dbus_counter_adjust_unix_fd, _dbus_counter_notify, _dbus_counter_unref, _dbus_list_find_last, _dbus_list_remove_link, DBusMessage::counters, NULL, DBusMessage::size_counter_delta.
Referenced by _dbus_connection_message_sent_unlocked, dbus_connection_ref.
void dbus_message_lock(DBusMessage *message)
Locks a message.
Allows checking that applications don't keep a reference to a message in the outgoing queue and change it underneath us. Messages are locked when they enter the outgoing queue (dbus_connection_send_message()), and the library complains if the message is modified while locked. This function may also called externally, for applications wrapping D-Bus in another protocol. message the message to lock.
References _dbus_assert, _dbus_header_delete_field, _dbus_header_set_field_basic, _dbus_header_update_lengths, DBusMessage::body, DBUS_HEADER_FIELD_SIGNATURE, dbus_message_get_signature, DBUS_TYPE_SIGNATURE, FALSE, DBusMessage::header, DBusMessage::locked, NULL, TRUE.
Referenced by _dbus_connection_close_possibly_shared, dbus_message_marshal.
static dbus_bool_t set_or_delete_string_field(DBusMessage *message, int field, int typecode, const char *value)
static void dbus_message_cache_shutdown(void *data)
static DBusMessage* dbus_message_get_cached(void)
Tries to get a message from the message cache.
The retrieved message will have junk in it, so it still needs to be cleared out in dbus_message_new_empty_header()the message, or NULL if none cached
static void free_counter(void *element, void *data)
static void dbus_message_cache_or_finalize(DBusMessage *message)
Tries to cache a message, otherwise finalize it.
message the message
dbus_bool_t _dbus_message_iter_get_args_valist(DBusMessageIter *iter, DBusError *error, int first_arg_type, va_list var_args)
Implementation of the varargs arg-getting functions.
dbus_message_get_args() is the place to go for complete documentation.dbus_message_get_args iter the message iter error error to be filled in first_arg_type type of the first argument var_args return location for first argument, followed by list of type/location pairs FALSE if error was set
References _dbus_assert, _dbus_close, _dbus_dup, _dbus_strdup, _dbus_type_reader_get_current_type, _dbus_type_reader_get_element_type, _dbus_type_reader_next, _dbus_type_reader_read_basic, _dbus_type_reader_read_fixed_multi, _dbus_type_reader_recurse, _dbus_type_to_string, _dbus_warn, DBUS_ERROR_INCONSISTENT_MESSAGE, DBUS_ERROR_INVALID_ARGS, DBUS_ERROR_NOT_SUPPORTED, dbus_free_string_array, dbus_message_iter_get_arg_type, dbus_new0, dbus_set_error, DBUS_TYPE_ARRAY, DBUS_TYPE_INVALID, dbus_type_is_basic, dbus_type_is_fixed, DBUS_TYPE_UNIX_FD, FALSE, DBusMessageRealIter::message, NULL, DBusMessageRealIter::reader, TRUE, DBusMessageRealIter::u, DBusBasicValue::u32.
Referenced by dbus_message_get_args_valist.
DBUS_EXPORT dbus_uint32_t dbus_message_get_serial(DBusMessage *message)
Returns the serial of a message or 0 if none has been specified.
The message's serial number is provided by the application sending the message and is used to identify replies to this message.All messages received on a connection will have a serial provided by the remote application.For messages you're sending, dbus_connection_send() will assign a serial and return it to you. message the message the serial
References _dbus_header_get_serial, DBusMessage::header, NULL.
Referenced by _dbus_connection_close_possibly_shared, dbus_connection_send_with_reply, dbus_connection_steal_borrowed_message, dbus_message_new_error, dbus_message_new_method_return.
DBUS_EXPORT dbus_bool_t dbus_message_set_reply_serial(DBusMessage *message, dbus_uint32_t reply_serial)
Sets the reply serial of a message (the serial of the message this is a reply to).
message the message reply_serial the serial we're replying to FALSE if not enough memory
References _dbus_header_set_field_basic, DBUS_HEADER_FIELD_REPLY_SERIAL, DBUS_TYPE_UINT32, FALSE, DBusMessage::header, DBusMessage::locked, NULL.
Referenced by _dbus_connection_close_if_only_one_ref, dbus_message_new_error, dbus_message_new_method_return.
DBUS_EXPORT dbus_uint32_t dbus_message_get_reply_serial(DBusMessage *message)
Returns the serial that the message is a reply to or 0 if none.
message the message the reply serial
References _dbus_assert, _dbus_atomic_get, _dbus_atomic_inc, _dbus_current_generation, _dbus_data_slot_list_free, _dbus_data_slot_list_init, _dbus_header_free, _dbus_header_get_field_basic, _dbus_header_init, _dbus_header_reinit, _dbus_list_clear, _dbus_list_foreach, _dbus_string_free, _dbus_string_init_preallocated, _dbus_string_set_length, DBusMessage::body, DBusMessage::changed_stamp, DBusMessage::counters, dbus_free, DBUS_HEADER_FIELD_REPLY_SERIAL, dbus_new0, DBUS_TYPE_UINT32, FALSE, DBusMessage::generation, DBusMessage::header, DBusMessage::in_cache, DBusMessage::locked, DBusMessageRealIter::message, NULL, DBusMessage::refcount, DBusMessage::size_counter_delta, DBusMessage::slot_list, TRUE.
Referenced by _dbus_connection_close_if_only_one_ref, _dbus_connection_queue_received_message_link, _dbus_pending_call_set_reply_unlocked, dbus_connection_dispatch.
static DBusMessage* dbus_message_new_empty_header(void)
DBUS_EXPORT DBusMessage * dbus_message_new(int message_type)
Constructs a new message of the given message type.
Types include DBUS_MESSAGE_TYPE_METHOD_CALL, DBUS_MESSAGE_TYPE_SIGNAL, and so forth.Usually you want to use dbus_message_new_method_call(), dbus_message_new_method_return(), dbus_message_new_signal(), or dbus_message_new_error() instead. message_type type of message new message or NULL if no memory
References _dbus_header_create, DBUS_MESSAGE_TYPE_INVALID, dbus_message_unref, DBusMessage::header, DBusMessageRealIter::message, NULL.
Referenced by _dbus_connection_close_if_only_one_ref.
DBUS_EXPORT DBusMessage * dbus_message_new_method_call(const char *destination, const char *path, const char *iface, const char *method)
Constructs a new message to invoke a method on a remote object.
Returns NULL if memory can't be allocated for the message. The destination may be NULL in which case no destination is set; this is appropriate when using D-Bus in a peer-to-peer context (no message bus). The interface may be NULL, which means that if multiple methods with the given name exist it is undefined which one will be invoked.The path and method names may not be NULL.Destination, path, interface, and method name can't contain any invalid characters (see the D-Bus specification). destination name that the message should be sent to or NULL path object path the message should be sent to iface interface to invoke method on, or NULL method method to invoke a new DBusMessage, free with dbus_message_unref()
References _dbus_header_create, DBUS_MESSAGE_TYPE_METHOD_CALL, dbus_message_unref, DBusMessage::header, DBusMessageRealIter::message, NULL.
Referenced by _dbus_decompose_path, dbus_bus_add_match, dbus_bus_get_id, dbus_bus_get_unix_user, dbus_bus_name_has_owner, dbus_bus_register, dbus_bus_release_name, dbus_bus_remove_match, dbus_bus_request_name, dbus_bus_start_service_by_name.
DBUS_EXPORT DBusMessage * dbus_message_new_method_return(DBusMessage *method_call)
Constructs a message that is a reply to a method call.
Returns NULL if memory can't be allocated for the message. method_call the message being replied to a new DBusMessage, free with dbus_message_unref()
References _dbus_header_create, dbus_message_get_sender, dbus_message_get_serial, dbus_message_set_no_reply, dbus_message_set_reply_serial, DBUS_MESSAGE_TYPE_METHOD_RETURN, dbus_message_unref, DBusMessage::header, DBusMessageRealIter::message, NULL, TRUE.
Referenced by _dbus_object_tree_free_all_unlocked, dbus_connection_get_dispatch_status.
DBUS_EXPORT DBusMessage * dbus_message_new_signal(const char *path, const char *iface, const char *name)
Constructs a new message representing a signal emission.
Returns NULL if memory can't be allocated for the message. A signal is identified by its originating object path, interface, and the name of the signal.Path, interface, and signal name must all be valid (the D-Bus specification defines the syntax of these fields). path the path to the object emitting the signal iface the interface the signal is emitted from name name of the signal a new DBusMessage, free with dbus_message_unref()
References _dbus_header_create, dbus_message_set_no_reply, DBUS_MESSAGE_TYPE_SIGNAL, dbus_message_unref, DBusMessage::header, DBusMessageRealIter::message, NULL, TRUE.
Referenced by _dbus_connection_new_for_transport.
DBUS_EXPORT DBusMessage * dbus_message_new_error(DBusMessage *reply_to, const char *error_name, const char *error_message)
Creates a new message that is an error reply to another message.
Error replies are most common in response to method calls, but can be returned in reply to any message.The error name must be a valid error name according to the syntax given in the D-Bus specification. If you don't want to make up an error name just use DBUS_ERROR_FAILED. reply_to the message we're replying to error_name the error name error_message the error message string (or NULL for none, but please give a message) a new error message object, free with dbus_message_unref()
References _dbus_header_create, dbus_message_get_sender, dbus_message_get_serial, dbus_message_iter_append_basic, dbus_message_iter_init_append, dbus_message_set_no_reply, dbus_message_set_reply_serial, DBUS_MESSAGE_TYPE_ERROR, dbus_message_unref, DBUS_TYPE_STRING, DBusMessage::header, DBusMessageRealIter::message, NULL, TRUE.
Referenced by _dbus_pending_call_set_timeout_error_unlocked, dbus_connection_dispatch, dbus_connection_get_dispatch_status, dbus_message_new_error_printf.
DBUS_EXPORT DBusMessage * dbus_message_new_error_printf(DBusMessage *reply_to, const char *error_name, const char *error_format,...)
Creates a new message that is an error reply to another message, allowing you to use printf formatting.
See dbus_message_new_error() for details - this function is the same aside from the printf formatting.Todoadd _DBUS_GNUC_PRINTF to this (requires moving _DBUS_GNUC_PRINTF to public header, see DBUS_DEPRECATED for an example) reply_to the original message error_name the error name error_format the error message format as with printf ... format string arguments a new error message
References _dbus_string_append_printf_valist, _dbus_string_free, _dbus_string_init, dbus_message_new_error, DBusMessageRealIter::message, NULL.
DBUS_EXPORT DBusMessage * dbus_message_copy(const DBusMessage *message)
Creates a new message that is an exact replica of the message specified, except that its refcount is set to 1, its message serial is reset to 0, and if the original message was "locked" (in the outgoing message queue and thus not modifiable) the new message will not be locked.
TodoThis function can't be used in programs that try to recover from OOM errors. message the message the new message.or NULL if not enough memory or Unix file descriptors (in case the message to copy includes Unix file descriptors) can be allocated.
References _dbus_atomic_inc, _dbus_dup, _dbus_header_copy, _dbus_header_free, _dbus_string_copy, _dbus_string_free, _dbus_string_init_preallocated, DBusMessage::body, dbus_free, dbus_new, dbus_new0, FALSE, DBusMessage::generation, DBusMessage::header, DBusMessage::locked, NULL, DBusMessage::refcount.
DBUS_EXPORT DBusMessage * dbus_message_ref(DBusMessage *message)
Increments the reference count of a DBusMessage.
message the message the message dbus_message_unref
References _dbus_assert, _dbus_atomic_inc, _dbus_current_generation, DBusMessage::generation, DBusMessage::in_cache, DBusMessageRealIter::message, NULL, DBusMessage::refcount.
Referenced by _dbus_connection_close_possibly_shared, _dbus_pending_call_set_reply_unlocked.
DBUS_EXPORT void dbus_message_unref(DBusMessage *message)
Decrements the reference count of a DBusMessage, freeing the message if the count reaches 0.
message the message dbus_message_ref
References _dbus_assert, _dbus_atomic_dec, _dbus_current_generation, DBusMessage::generation, DBusMessage::in_cache, NULL, DBusMessage::refcount.
Referenced by _dbus_connection_close_if_only_one_ref, _dbus_connection_handle_watch, _dbus_connection_new_for_transport, _dbus_connection_unlock, _dbus_decompose_path, _dbus_message_loader_queue_messages, _dbus_message_loader_unref, _dbus_object_tree_free_all_unlocked, _dbus_pending_call_ref_unlocked, _dbus_pending_call_set_timeout_error_unlocked, dbus_bus_add_match, dbus_bus_get_id, dbus_bus_get_unix_user, dbus_bus_name_has_owner, dbus_bus_register, dbus_bus_release_name, dbus_bus_remove_match, dbus_bus_request_name, dbus_bus_start_service_by_name, dbus_connection_dispatch, dbus_connection_ref, dbus_connection_send_with_reply_and_block, dbus_message_new, dbus_message_new_error, dbus_message_new_method_call, dbus_message_new_method_return, dbus_message_new_signal.
DBUS_EXPORT int dbus_message_get_type(DBusMessage *message)
Gets the type of a message.
Types include DBUS_MESSAGE_TYPE_METHOD_CALL, DBUS_MESSAGE_TYPE_METHOD_RETURN, DBUS_MESSAGE_TYPE_ERROR, DBUS_MESSAGE_TYPE_SIGNAL, but other types are allowed and all code must silently ignore messages of unknown type. DBUS_MESSAGE_TYPE_INVALID will never be returned. message the message the type of the message
References _dbus_header_get_message_type, DBUS_MESSAGE_TYPE_INVALID, DBusMessage::header, NULL.
Referenced by _dbus_connection_close_possibly_shared, _dbus_connection_message_sent_unlocked, _dbus_connection_queue_received_message_link, _dbus_pending_call_set_reply_unlocked, dbus_connection_dispatch, dbus_connection_send_preallocated, dbus_connection_steal_borrowed_message, dbus_message_get_signature, dbus_message_is_error, dbus_set_error_from_message.
DBUS_EXPORT dbus_bool_t dbus_message_append_args(DBusMessage *message, int first_arg_type,...)
Appends fields to a message given a variable argument list.
The variable argument list should contain the type of each argument followed by the value to append. Appendable types are basic types, and arrays of fixed-length basic types (except arrays of Unix file descriptors). To append variable-length basic types, or any more complex value, you have to use an iterator rather than this function.To append a basic type, specify its type code followed by the address of the value. For example:dbus_int32_tv_INT32=42; constchar*v_STRING="HelloWorld"; dbus_message_append_args(message, DBUS_TYPE_INT32,&v_INT32, DBUS_TYPE_STRING,&v_STRING, DBUS_TYPE_INVALID); To append an array of fixed-length basic types (except Unix file descriptors), pass in the DBUS_TYPE_ARRAY typecode, the element typecode, the address of the array pointer, and a 32-bit integer giving the number of elements in the array. So for example:constdbus_int32_tarray[]={1,2,3};constdbus_int32_t *v_ARRAY=array;dbus_message_append_args(message, DBUS_TYPE_ARRAY,DBUS_TYPE_INT32,&v_ARRAY,3,DBUS_TYPE_INVALID); This function does not support arrays of Unix file descriptors. If you need those you need to manually recurse into the array.For Unix file descriptors this function will internally duplicate the descriptor you passed in. Hence you may close the descriptor immediately after this call.in C, given "int array[]", "&array == array" (the comp.lang.c FAQ says otherwise, but gcc and the FAQ don't agree). So if you're using an array instead of a pointer you have to create a pointer variable, assign the array to it, then take the address of the pointer variable. For strings it works to write const char *array = "Hello" and then use &array though. The last argument to this function must be DBUS_TYPE_INVALID, marking the end of the argument list. If you don't do this then libdbus won't know to stop and will read invalid memory.String/signature/path arrays should be passed in as "const char*** address_of_array" and "int n_elements"Todosupport DBUS_TYPE_STRUCT and DBUS_TYPE_VARIANT and complex arraysTodoIf this fails due to lack of memory, the message is hosed and you have to start over building the whole message. message the message first_arg_type type of the first argument ... value of first argument, list of additional type-value pairs TRUE on success
References dbus_message_append_args_valist, FALSE, NULL.
Referenced by dbus_bus_add_match, dbus_bus_get_unix_user, dbus_bus_name_has_owner, dbus_bus_release_name, dbus_bus_remove_match, dbus_bus_request_name, dbus_bus_start_service_by_name, dbus_connection_get_dispatch_status.
DBUS_EXPORT dbus_bool_t dbus_message_append_args_valist(DBusMessage *message, int first_arg_type, va_list var_args)
Like dbus_message_append_args() but takes a va_list for use by language bindings.
Todofor now, if this function fails due to OOM it will leave the message half-written and you have to discard the message and start over.dbus_message_append_args. message the message first_arg_type type of first argument var_args value of first argument, then list of type/value pairs TRUE on success
References _dbus_type_to_string, _dbus_warn, dbus_message_iter_abandon_container, dbus_message_iter_append_basic, dbus_message_iter_append_fixed_array, dbus_message_iter_close_container, dbus_message_iter_init_append, dbus_message_iter_open_container, DBUS_TYPE_ARRAY, DBUS_TYPE_INVALID, dbus_type_is_basic, dbus_type_is_fixed, DBUS_TYPE_UNIX_FD, FALSE, NULL, TRUE.
Referenced by dbus_message_append_args.
DBUS_EXPORT dbus_bool_t dbus_message_get_args(DBusMessage *message, DBusError *error, int first_arg_type,...)
Gets arguments from a message given a variable argument list.
The supported types include those supported by dbus_message_append_args(); that is, basic types and arrays of fixed-length basic types. The arguments are the same as they would be for dbus_message_iter_get_basic() or dbus_message_iter_get_fixed_array().In addition to those types, arrays of string, object path, and signature are supported; but these are returned as allocated memory and must be freed with dbus_free_string_array(), while the other types are returned as const references. To get a string array pass in "char ***array_location" and "int *n_elements".Similar to dbus_message_get_fixed_array() this function does not support arrays of type DBUS_TYPE_UNIX_FD. If you need to parse messages with arrays of Unix file descriptors you need to recurse into the array manually.Unix file descriptors that are read with this function will have the FD_CLOEXEC flag set. If you need them without this flag set, make sure to unset it with fcntl().The variable argument list should contain the type of the argument followed by a pointer to where the value should be stored. The list is terminated with DBUS_TYPE_INVALID.Except for string arrays, the returned values are constant; do not free them. They point into the DBusMessage.If the requested arguments are not present, or do not have the requested types, then an error will be set.If more arguments than requested are present, the requested arguments are returned and the extra arguments are ignored.Todosupport DBUS_TYPE_STRUCT and DBUS_TYPE_VARIANT and complex arrays message the message error error to be filled in on failure first_arg_type the first argument type ... location for first argument value, then list of type-location pairs FALSE if the error was set
References dbus_message_get_args_valist, FALSE, NULL.
Referenced by dbus_bus_get_id, dbus_bus_get_unix_user, dbus_bus_name_has_owner, dbus_bus_register, dbus_bus_release_name, dbus_bus_request_name, dbus_bus_start_service_by_name, dbus_set_error_from_message.
DBUS_EXPORT dbus_bool_t dbus_message_get_args_valist(DBusMessage *message, DBusError *error, int first_arg_type, va_list var_args)
Like dbus_message_get_args but takes a va_list for use by language bindings.
dbus_message_get_args message the message error error to be filled in first_arg_type type of the first argument var_args return location for first argument, followed by list of type/location pairs FALSE if error was set
References _dbus_message_iter_get_args_valist, DBusMessage::changed_stamp, DBusMessageRealIter::changed_stamp, dbus_message_iter_init, ensure_byte_order, FALSE, DBusMessageRealIter::iter_type, DBusMessageRealIter::message, NULL, DBusMessageRealIter::sig_refcount.
Referenced by dbus_message_get_args.
static void _dbus_message_iter_init_common(DBusMessage *message, DBusMessageRealIter *real, int iter_type)
DBUS_EXPORT dbus_bool_t dbus_message_iter_init(DBusMessage *message, DBusMessageIter *iter)
Initializes a DBusMessageIter for reading the arguments of the message passed in.
When possible, dbus_message_get_args() is much more convenient. Some types of argument can only be read with DBusMessageIter however.The easiest way to iterate is like this: dbus_message_iter_init(message,&iter); while((current_type=dbus_message_iter_get_arg_type(&iter))!=DBUS_TYPE_INVALID) dbus_message_iter_next(&iter); DBusMessageIter contains no allocated memory; it need not be freed, and can be copied by assignment or memcpy(). message the message iter pointer to an iterator to initialize FALSE if the message has no arguments
References _dbus_header_get_byte_order, _dbus_type_reader_get_current_type, _dbus_type_reader_init, DBusMessage::body, DBUS_TYPE_INVALID, FALSE, DBusMessage::header, NULL, DBusMessageRealIter::reader, DBusMessageRealIter::u.
Referenced by dbus_message_get_args_valist.
DBUS_EXPORT dbus_bool_t dbus_message_iter_has_next(DBusMessageIter *iter)
Checks if an iterator has any more fields.
iter the message iter TRUE if there are more fields following
References _dbus_type_reader_has_next, FALSE, DBusMessageRealIter::iter_type, DBusMessageRealIter::reader, DBusMessageRealIter::u.
DBUS_EXPORT dbus_bool_t dbus_message_iter_next(DBusMessageIter *iter)
Moves the iterator to the next field, if any.
If there's no next field, returns FALSE. If the iterator moves forward, returns TRUE. iter the message iter TRUE if the iterator was moved to the next field
References _dbus_type_reader_next, FALSE, DBusMessageRealIter::iter_type, DBusMessageRealIter::reader, DBusMessageRealIter::u.
DBUS_EXPORT int dbus_message_iter_get_arg_type(DBusMessageIter *iter)
Returns the argument type of the argument that the message iterator points to.
If the iterator is at the end of the message, returns DBUS_TYPE_INVALID. You can thus write a loop as follows:dbus_message_iter_init(message,&iter); while((current_type=dbus_message_iter_get_arg_type(&iter))!=DBUS_TYPE_INVALID) dbus_message_iter_next(&iter); iter the message iter the argument type
References _dbus_type_reader_get_current_type, DBUS_TYPE_INVALID, FALSE, DBusMessageRealIter::iter_type, DBusMessageRealIter::reader, DBusMessageRealIter::u.
Referenced by _dbus_message_iter_get_args_valist, dbus_message_iter_get_basic, dbus_message_iter_get_element_type.
DBUS_EXPORT int dbus_message_iter_get_element_type(DBusMessageIter *iter)
Returns the element type of the array that the message iterator points to.
Note that you need to check that the iterator points to an array prior to using this function. iter the message iter the array element type
References _dbus_type_reader_get_element_type, dbus_message_iter_get_arg_type, DBUS_TYPE_ARRAY, DBUS_TYPE_INVALID, DBusMessageRealIter::iter_type, DBusMessageRealIter::reader, DBusMessageRealIter::u.
DBUS_EXPORT void dbus_message_iter_recurse(DBusMessageIter *iter, DBusMessageIter *sub)
Recurses into a container value when reading values from a message, initializing a sub-iterator to use for traversing the child values of the container.
Note that this recurses into a value, not a type, so you can only recurse if the value exists. The main implication of this is that if you have for example an empty array of array of int32, you can recurse into the outermost array, but it will have no values, so you won't be able to recurse further. There's no array of int32 to recurse into.If a container is an array of fixed-length types (except Unix file descriptors), it is much more efficient to use dbus_message_iter_get_fixed_array() to get the whole array in one shot, rather than individually walking over the array elements.Be sure you have somehow checked that dbus_message_iter_get_arg_type() matches the type you are expecting to recurse into. Results of this function are undefined if there is no container to recurse into at the current iterator position. iter the message iterator sub the sub-iterator to initialize
References _dbus_type_reader_recurse, NULL, DBusMessageRealIter::reader, DBusMessageRealIter::u.
DBUS_EXPORT char * dbus_message_iter_get_signature(DBusMessageIter *iter)
Returns the current signature of a message iterator.
This is useful primarily for dealing with variants; one can recurse into a variant and determine the signature of the variant's value.The returned string must be freed with dbus_free(). iter the message iterator the contained signature, or NULL if out of memory
References _dbus_string_append_len, _dbus_string_free, _dbus_string_init, _dbus_string_steal_data, _dbus_type_reader_get_signature, NULL, DBusMessageRealIter::reader, DBusMessageRealIter::u.
DBUS_EXPORT void dbus_message_iter_get_basic(DBusMessageIter *iter, void *value)
Reads a basic-typed value from the message iterator.
Basic types are the non-containers such as integer and string.The value argument should be the address of a location to store the returned value. So for int32 it should be a "dbus_int32_t*" and for string a "const char**". The returned value is by reference and should not be freed.This call duplicates Unix file descriptors when reading them. It is your job to close them when you don't need them anymore.Unix file descriptors that are read with this function will have the FD_CLOEXEC flag set. If you need them without this flag set, make sure to unset it with fcntl().Be sure you have somehow checked that dbus_message_iter_get_arg_type() matches the type you are expecting, or you'll crash when you try to use an integer as a string or something.To read any container type (array, struct, dict) you will need to recurse into the container with dbus_message_iter_recurse(). If the container is an array of fixed-length values (except Unix file descriptors), you can get all the array elements at once with dbus_message_iter_get_fixed_array(). Otherwise, you have to iterate over the container's contents one value at a time.All basic-typed values are guaranteed to fit in a DBusBasicValue, so in versions of libdbus that have that type, you can write code like this:DBusBasicValuevalue; inttype; dbus_message_iter_get_basic(&read_iter,&value); type=dbus_message_iter_get_arg_type(&read_iter); dbus_message_iter_append_basic(&write_iter,type,&value); (All D-Bus basic types are either numeric and 8 bytes or smaller, or behave like a string; so in older versions of libdbus, DBusBasicValue can be replaced with union { char *string; unsigned char bytes[8]; }, for instance.) iter the iterator value location to store the value
References _dbus_dup, _dbus_type_reader_read_basic, dbus_message_iter_get_arg_type, DBUS_TYPE_UNIX_FD, DBusMessageRealIter::message, NULL, DBusMessageRealIter::reader, DBusMessageRealIter::u, DBusBasicValue::u32.
DBUS_EXPORT DBUS_DEPRECATED int dbus_message_iter_get_array_len(DBusMessageIter *iter)
Returns the number of bytes in the array as marshaled in the wire protocol.
The iterator must currently be inside an array-typed value.This function is deprecated on the grounds that it is stupid. Why would you want to know how many bytes are in the array as marshaled in the wire protocol? For now, use the n_elements returned from dbus_message_iter_get_fixed_array() instead, or iterate over the array values and count them.Todointroduce a variant of this get_n_elements that returns the number of elements, though with a non-fixed array it will not be very efficient, so maybe it's not good. iter the iterator the number of bytes in the array
References _dbus_type_reader_get_array_length, DBusMessageRealIter::reader, DBusMessageRealIter::u.
DBUS_EXPORT void dbus_message_iter_get_fixed_array(DBusMessageIter *iter, void *value, int *n_elements)
Reads a block of fixed-length values from the message iterator.
Fixed-length values are those basic types that are not string-like, such as integers, bool, double. The returned block will be from the current position in the array until the end of the array.There is one exception here: although DBUS_TYPE_UNIX_FD is considered a 'fixed' type arrays of this type may not be read with this function.The message iter should be "in" the array (that is, you recurse into the array, and then you call dbus_message_iter_get_fixed_array() on the "sub-iterator" created by dbus_message_iter_recurse()).The value argument should be the address of a location to store the returned array. So for int32 it should be a "const dbus_int32_t**" The returned value is by reference and should not be freed.This function should only be used if dbus_type_is_fixed() returns TRUE for the element type.If an array's elements are not fixed in size, you have to recurse into the array with dbus_message_iter_recurse() and read the elements one by one.Because the array is not copied, this function runs in constant time and is fast; it's much preferred over walking the entire array with an iterator. (However, you can always use dbus_message_iter_recurse(), even for fixed-length types; dbus_message_iter_get_fixed_array() is just an optimization.) iter the iterator value location to store the block n_elements number of elements in the block
References _dbus_type_reader_get_current_type, _dbus_type_reader_read_fixed_multi, DBUS_TYPE_INVALID, dbus_type_is_fixed, DBUS_TYPE_UNIX_FD, NULL, DBusMessageRealIter::reader, DBusMessageRealIter::u.
DBUS_EXPORT void dbus_message_iter_init_append(DBusMessage *message, DBusMessageIter *iter)
Initializes a DBusMessageIter for appending arguments to the end of a message.
TodoIf appending any of the arguments fails due to lack of memory, the message is hosed and you have to start over building the whole message. message the message iter pointer to an iterator to initialize
References _dbus_assert, _dbus_header_get_byte_order, _dbus_header_get_field_raw, _dbus_header_set_field_basic, _dbus_string_copy_len, _dbus_string_free, _dbus_string_init_preallocated, _dbus_type_writer_add_types, _dbus_type_writer_init_types_delayed, _dbus_type_writer_remove_types, _dbus_warn_check_failed, DBusMessage::body, dbus_free, DBUS_HEADER_FIELD_SIGNATURE, dbus_new, dbus_realloc, DBUS_TYPE_SIGNATURE, FALSE, DBusMessage::header, DBusMessageRealIter::iter_type, DBusMessage::locked, DBusMessageRealIter::message, NULL, DBusMessageRealIter::sig_refcount, TRUE, DBusTypeWriter::type_str, DBusMessageRealIter::u, DBusMessageRealIter::writer.
Referenced by _dbus_connection_close_if_only_one_ref, _dbus_object_tree_free_all_unlocked, dbus_message_append_args_valist, dbus_message_new_error.
static dbus_bool_t _dbus_message_iter_open_signature(DBusMessageRealIter *real)
Creates a temporary signature string containing the current signature, stores it in the iterator, and points the iterator to the end of it.
Used any time we write to the message. real an iterator without a type_str FALSE if no memory
static dbus_bool_t _dbus_message_iter_close_signature(DBusMessageRealIter *real)
Sets the new signature as the message signature, frees the signature string, and marks the iterator as not having a type_str anymore.
Frees the signature even if it fails, so you can't really recover from failure. Kinda busted. real an iterator without a type_str FALSE if no memory
static void _dbus_message_iter_abandon_signature(DBusMessageRealIter *real)
Frees the signature string and marks the iterator as not having a type_str anymore.
Since the new signature is not set, the message will generally be hosed after this is called. real an iterator without a type_str
static dbus_bool_t _dbus_message_iter_append_check(DBusMessageRealIter *iter)
DBUS_EXPORT dbus_bool_t dbus_message_iter_append_basic(DBusMessageIter *iter, int type, const void *value)
Appends a basic-typed value to the message.
The basic types are the non-container types such as integer and string.The "value" argument should be the address of a basic-typed value. So for string, const char**. For integer, dbus_int32_t*.For Unix file descriptors this function will internally duplicate the descriptor you passed in. Hence you may close the descriptor immediately after this call.TodoIf this fails due to lack of memory, the message is hosed and you have to start over building the whole message. iter the append iterator type the type of the value value the address of the value FALSE if not enough memory
References _dbus_close, _dbus_dup, _dbus_header_set_field_basic, _dbus_type_writer_write_basic, DBUS_HEADER_FIELD_UNIX_FDS, DBUS_TYPE_BOOLEAN, dbus_type_is_basic, DBUS_TYPE_OBJECT_PATH, DBUS_TYPE_SIGNATURE, DBUS_TYPE_STRING, DBUS_TYPE_UINT32, DBUS_TYPE_UNIX_FD, FALSE, DBusMessage::header, DBusMessageRealIter::iter_type, DBusMessageRealIter::message, NULL, DBusMessageRealIter::u, DBusMessageRealIter::writer.
Referenced by _dbus_connection_close_if_only_one_ref, _dbus_object_tree_free_all_unlocked, dbus_message_append_args_valist, dbus_message_new_error.
DBUS_EXPORT dbus_bool_t dbus_message_iter_append_fixed_array(DBusMessageIter *iter, int element_type, const void *value, int n_elements)
Appends a block of fixed-length values to an array.
The fixed-length types are all basic types that are not string-like. So int32, double, bool, etc. (Unix file descriptors however are not supported.) You must call dbus_message_iter_open_container() to open an array of values before calling this function. You may call this function multiple times (and intermixed with calls to dbus_message_iter_append_basic()) for the same array.The "value" argument should be the address of the array. So for integer, "dbus_int32_t**" is expected for example.in C, given "int array[]", "&array == array" (the comp.lang.c FAQ says otherwise, but gcc and the FAQ don't agree). So if you're using an array instead of a pointer you have to create a pointer variable, assign the array to it, then take the address of the pointer variable. constdbus_int32_tarray[]={1,2,3}; constdbus_int32_t*v_ARRAY=array; if(!dbus_message_iter_append_fixed_array(&iter,DBUS_TYPE_INT32,&v_ARRAY,3)) fprintf(stderr,"Nomemory!\n"); For strings it works to write const char *array = "Hello" and then use &array though. TodoIf this fails due to lack of memory, the message is hosed and you have to start over building the whole message. iter the append iterator element_type the type of the array elements value the address of the array n_elements the number of elements to append FALSE if not enough memory
References _dbus_type_get_alignment, _dbus_type_writer_write_fixed_multi, DBusTypeWriter::container_type, DBUS_MAXIMUM_ARRAY_LENGTH, DBUS_TYPE_ARRAY, DBUS_TYPE_BOOLEAN, dbus_type_is_fixed, DBUS_TYPE_UNIX_FD, FALSE, DBusMessageRealIter::iter_type, NULL, DBusMessageRealIter::u, DBusMessageRealIter::writer.
Referenced by dbus_message_append_args_valist.
DBUS_EXPORT dbus_bool_t dbus_message_iter_open_container(DBusMessageIter *iter, int type, const char *contained_signature, DBusMessageIter *sub)
Appends a container-typed value to the message; you are required to append the contents of the container using the returned sub-iterator, and then call dbus_message_iter_close_container().
Container types are for example struct, variant, and array. For variants, the contained_signature should be the type of the single value inside the variant. For structs and dict entries, contained_signature should be NULL; it will be set to whatever types you write into the struct. For arrays, contained_signature should be the type of the array elements.TodoIf this fails due to lack of memory, the message is hosed and you have to start over building the whole message. iter the append iterator type the type of the value contained_signature the type of container contents sub sub-iterator to initialize FALSE if not enough memory
References _dbus_string_init_const, _dbus_type_writer_recurse, DBUS_DICT_ENTRY_BEGIN_CHAR, DBUS_TYPE_ARRAY, DBUS_TYPE_DICT_ENTRY, dbus_type_is_container, DBUS_TYPE_STRUCT, DBUS_TYPE_VARIANT, FALSE, DBusMessageRealIter::iter_type, NULL, DBusMessageRealIter::u, DBusMessageRealIter::writer.
Referenced by dbus_message_append_args_valist.
DBUS_EXPORT dbus_bool_t dbus_message_iter_close_container(DBusMessageIter *iter, DBusMessageIter *sub)
Closes a container-typed value appended to the message; may write out more information to the message known only after the entire container is written, and may free resources created by dbus_message_iter_open_container().
TodoIf this fails due to lack of memory, the message is hosed and you have to start over building the whole message. iter the append iterator sub sub-iterator to close FALSE if not enough memory
References _dbus_type_writer_unrecurse, FALSE, DBusMessageRealIter::iter_type, DBusMessageRealIter::u, DBusMessageRealIter::writer.
Referenced by dbus_message_append_args_valist.
DBUS_EXPORT void dbus_message_iter_abandon_container(DBusMessageIter *iter, DBusMessageIter *sub)
Abandons creation of a contained-typed value and frees resources created by dbus_message_iter_open_container().
Once this returns, the message is hosed and you have to start over building the whole message.This should only be used to abandon creation of a message when you have open containers. iter the append iterator sub sub-iterator to close
References DBusMessageRealIter::iter_type.
Referenced by dbus_message_append_args_valist.
DBUS_EXPORT void dbus_message_set_no_reply(DBusMessage *message, dbus_bool_t no_reply)
Sets a flag indicating that the message does not want a reply; if this flag is set, the other end of the connection may (but is not required to) optimize by not sending method return or error replies.
If this flag is set, there is no way to know whether the message successfully arrived at the remote end. Normally you know a message was received when you receive the reply to it.The flag is FALSE by default, that is by default the other end is required to reply.On the protocol level this toggles DBUS_HEADER_FLAG_NO_REPLY_EXPECTED message the message no_reply TRUE if no reply is desired
References _dbus_header_toggle_flag, DBUS_HEADER_FLAG_NO_REPLY_EXPECTED, DBusMessage::header, DBusMessage::locked, NULL.
Referenced by _dbus_connection_close_if_only_one_ref, dbus_bus_start_service_by_name, dbus_message_new_error, dbus_message_new_method_return, dbus_message_new_signal.
DBUS_EXPORT dbus_bool_t dbus_message_get_no_reply(DBusMessage *message)
Returns TRUE if the message does not expect a reply.
message the message TRUE if the message sender isn't waiting for a reply
References _dbus_header_get_flag, DBUS_HEADER_FLAG_NO_REPLY_EXPECTED, FALSE, DBusMessage::header, NULL.
DBUS_EXPORT void dbus_message_set_auto_start(DBusMessage *message, dbus_bool_t auto_start)
Sets a flag indicating that an owner for the destination name will be automatically started before the message is delivered.
When this flag is set, the message is held until a name owner finishes starting up, or fails to start up. In case of failure, the reply will be an error.The flag is set to TRUE by default, i.e. auto starting is the default.On the protocol level this toggles DBUS_HEADER_FLAG_NO_AUTO_START message the message auto_start TRUE if auto-starting is desired
References _dbus_header_toggle_flag, DBUS_HEADER_FLAG_NO_AUTO_START, DBusMessage::header, DBusMessage::locked, NULL.
DBUS_EXPORT dbus_bool_t dbus_message_get_auto_start(DBusMessage *message)
Returns TRUE if the message will cause an owner for destination name to be auto-started.
message the message TRUE if the message will use auto-start
References _dbus_header_get_flag, DBUS_HEADER_FLAG_NO_AUTO_START, FALSE, DBusMessage::header, NULL.
DBUS_EXPORT dbus_bool_t dbus_message_set_path(DBusMessage *message, const char *object_path)
Sets the object path this message is being sent to (for DBUS_MESSAGE_TYPE_METHOD_CALL) or the one a signal is being emitted from (for DBUS_MESSAGE_TYPE_SIGNAL).
The path must contain only valid characters as defined in the D-Bus specification. message the message object_path the path or NULL to unset FALSE if not enough memory
References DBUS_HEADER_FIELD_PATH, DBUS_TYPE_OBJECT_PATH, FALSE, DBusMessage::locked, NULL.
DBUS_EXPORT const char * dbus_message_get_path(DBusMessage *message)
Gets the object path this message is being sent to (for DBUS_MESSAGE_TYPE_METHOD_CALL) or being emitted from (for DBUS_MESSAGE_TYPE_SIGNAL).
Returns NULL if none.See also dbus_message_get_path_decomposed().The returned string becomes invalid if the message is modified, since it points into the wire-marshaled message data. message the message the path (should not be freed) or NULL
References _dbus_header_get_field_basic, DBUS_HEADER_FIELD_PATH, DBUS_TYPE_OBJECT_PATH, DBusMessage::header, NULL.
Referenced by _dbus_connection_close_possibly_shared, _dbus_connection_message_sent_unlocked, _dbus_connection_queue_received_message_link, dbus_connection_steal_borrowed_message, dbus_message_get_path_decomposed, dbus_message_has_path.
DBUS_EXPORT dbus_bool_t dbus_message_has_path(DBusMessage *message, const char *path)
Checks if the message has a particular object path.
The object path is the destination object for a method call or the emitting object for a signal. message the message path the path name TRUE if there is a path field in the header
References dbus_message_get_path, FALSE, NULL, TRUE.
DBUS_EXPORT dbus_bool_t dbus_message_get_path_decomposed(DBusMessage *message, char ***path)
Gets the object path this message is being sent to (for DBUS_MESSAGE_TYPE_METHOD_CALL) or being emitted from (for DBUS_MESSAGE_TYPE_SIGNAL) in a decomposed format (one array element per path component).
Free the returned array with dbus_free_string_array().An empty but non-NULL path array means the path "/". So the path "/foo/bar" becomes { "foo", "bar", NULL } and the path "/" becomes { NULL }.See also dbus_message_get_path().Todothis could be optimized by using the len from the message instead of calling strlen() again message the message path place to store allocated array of path components; NULL set here if no path field exists FALSE if no memory to allocate the array
References _dbus_decompose_path, dbus_message_get_path, FALSE, NULL, TRUE.
Referenced by _dbus_object_tree_dispatch_and_unlock.
DBUS_EXPORT dbus_bool_t dbus_message_set_interface(DBusMessage *message, const char *iface)
Sets the interface this message is being sent to (for DBUS_MESSAGE_TYPE_METHOD_CALL) or the interface a signal is being emitted from (for DBUS_MESSAGE_TYPE_SIGNAL).
The interface name must contain only valid characters as defined in the D-Bus specification. message the message iface the interface or NULL to unset FALSE if not enough memory
References DBUS_HEADER_FIELD_INTERFACE, DBUS_TYPE_STRING, FALSE, DBusMessage::locked, NULL.
DBUS_EXPORT const char * dbus_message_get_interface(DBusMessage *message)
Gets the interface this message is being sent to (for DBUS_MESSAGE_TYPE_METHOD_CALL) or being emitted from (for DBUS_MESSAGE_TYPE_SIGNAL).
The interface name is fully-qualified (namespaced). Returns NULL if none.The returned string becomes invalid if the message is modified, since it points into the wire-marshaled message data. message the message the message interface (should not be freed) or NULL
References _dbus_header_get_field_basic, DBUS_HEADER_FIELD_INTERFACE, DBUS_TYPE_STRING, DBusMessage::header, NULL.
Referenced by _dbus_connection_close_possibly_shared, _dbus_connection_message_sent_unlocked, _dbus_connection_queue_received_message_link, dbus_connection_dispatch, dbus_connection_send_preallocated, dbus_connection_steal_borrowed_message, dbus_message_get_signature, dbus_message_has_interface.
DBUS_EXPORT dbus_bool_t dbus_message_has_interface(DBusMessage *message, const char *iface)
Checks if the message has an interface.
message the message iface the interface name TRUE if the interface field in the header matches
References dbus_message_get_interface, FALSE, NULL, TRUE.
Referenced by dbus_connection_get_dispatch_status.
DBUS_EXPORT dbus_bool_t dbus_message_set_member(DBusMessage *message, const char *member)
Sets the interface member being invoked (DBUS_MESSAGE_TYPE_METHOD_CALL) or emitted (DBUS_MESSAGE_TYPE_SIGNAL).
The member name must contain only valid characters as defined in the D-Bus specification. message the message member the member or NULL to unset FALSE if not enough memory
References DBUS_HEADER_FIELD_MEMBER, DBUS_TYPE_STRING, FALSE, DBusMessage::locked, NULL.
DBUS_EXPORT const char * dbus_message_get_member(DBusMessage *message)
Gets the interface member being invoked (DBUS_MESSAGE_TYPE_METHOD_CALL) or emitted (DBUS_MESSAGE_TYPE_SIGNAL).
Returns NULL if none.The returned string becomes invalid if the message is modified, since it points into the wire-marshaled message data. message the message the member name (should not be freed) or NULL
References _dbus_header_get_field_basic, DBUS_HEADER_FIELD_MEMBER, DBUS_TYPE_STRING, DBusMessage::header, NULL.
Referenced by _dbus_connection_close_possibly_shared, _dbus_connection_message_sent_unlocked, _dbus_connection_queue_received_message_link, dbus_connection_dispatch, dbus_connection_send_preallocated, dbus_connection_steal_borrowed_message, dbus_message_get_signature, dbus_message_has_member.
DBUS_EXPORT dbus_bool_t dbus_message_has_member(DBusMessage *message, const char *member)
Checks if the message has an interface member.
message the message member the member name TRUE if there is a member field in the header
References dbus_message_get_member, FALSE, NULL, TRUE.
DBUS_EXPORT dbus_bool_t dbus_message_set_error_name(DBusMessage *message, const char *error_name)
Sets the name of the error (DBUS_MESSAGE_TYPE_ERROR).
The name is fully-qualified (namespaced).The error name must contain only valid characters as defined in the D-Bus specification. message the message error_name the name or NULL to unset FALSE if not enough memory
References DBUS_HEADER_FIELD_ERROR_NAME, DBUS_TYPE_STRING, FALSE, DBusMessage::locked, NULL.
Referenced by _dbus_connection_close_if_only_one_ref.
DBUS_EXPORT const char * dbus_message_get_error_name(DBusMessage *message)
Gets the error name (DBUS_MESSAGE_TYPE_ERROR only) or NULL if none.
The returned string becomes invalid if the message is modified, since it points into the wire-marshaled message data. message the message the error name (should not be freed) or NULL
References _dbus_header_get_field_basic, DBUS_HEADER_FIELD_ERROR_NAME, DBUS_TYPE_STRING, DBusMessage::header, NULL.
Referenced by dbus_message_is_error, dbus_set_error_from_message.
DBUS_EXPORT dbus_bool_t dbus_message_set_destination(DBusMessage *message, const char *destination)
Sets the message's destination.
The destination is the name of another connection on the bus and may be either the unique name assigned by the bus to each connection, or a well-known name specified in advance.The destination name must contain only valid characters as defined in the D-Bus specification. message the message destination the destination name or NULL to unset FALSE if not enough memory
References DBUS_HEADER_FIELD_DESTINATION, DBUS_TYPE_STRING, FALSE, DBusMessage::locked, NULL.
DBUS_EXPORT const char * dbus_message_get_destination(DBusMessage *message)
Gets the destination of a message or NULL if there is none set.
The returned string becomes invalid if the message is modified, since it points into the wire-marshaled message data. message the message the message destination (should not be freed) or NULL
References _dbus_header_get_field_basic, DBUS_HEADER_FIELD_DESTINATION, DBUS_TYPE_STRING, DBusMessage::header, NULL.
Referenced by _dbus_connection_close_possibly_shared, dbus_connection_get_dispatch_status, dbus_message_has_destination.
DBUS_EXPORT dbus_bool_t dbus_message_set_sender(DBusMessage *message, const char *sender)
Sets the message sender.
The sender must be a valid bus name as defined in the D-Bus specification.Usually you don't want to call this. The message bus daemon will call it to set the origin of each message. If you aren't implementing a message bus daemon you shouldn't need to set the sender. message the message sender the sender or NULL to unset FALSE if not enough memory
References DBUS_HEADER_FIELD_SENDER, DBUS_TYPE_STRING, FALSE, DBusMessage::locked, NULL.
DBUS_EXPORT const char * dbus_message_get_sender(DBusMessage *message)
Gets the unique name of the connection which originated this message, or NULL if unknown or inapplicable.
The sender is filled in by the message bus.Note, the returned sender is always the unique bus name. Connections may own multiple other bus names, but those are not found in the sender field.The returned string becomes invalid if the message is modified, since it points into the wire-marshaled message data. message the message the unique name of the sender or NULL
References _dbus_header_get_field_basic, DBUS_HEADER_FIELD_SENDER, DBUS_TYPE_STRING, DBusMessage::header, NULL.
Referenced by dbus_message_has_sender, dbus_message_new_error, dbus_message_new_method_return.
DBUS_EXPORT const char * dbus_message_get_signature(DBusMessage *message)
Gets the type signature of the message, i.e.
the arguments in the message payload. The signature includes only "in" arguments for DBUS_MESSAGE_TYPE_METHOD_CALL and only "out" arguments for DBUS_MESSAGE_TYPE_METHOD_RETURN, so is slightly different from what you might expect (that is, it does not include the signature of the entire C++-style method).The signature is a string made up of type codes such as DBUS_TYPE_INT32. The string is terminated with nul (nul is also the value of DBUS_TYPE_INVALID).The returned string becomes invalid if the message is modified, since it points into the wire-marshaled message data. message the message the type signature
References _dbus_assert, dbus_message_get_interface, dbus_message_get_member, dbus_message_get_type, FALSE, DBusMessage::header, NULL, TRUE.
Referenced by _dbus_connection_close_possibly_shared, _dbus_connection_message_sent_unlocked, _dbus_connection_queue_received_message_link, dbus_connection_dispatch, dbus_connection_steal_borrowed_message, dbus_message_has_signature, dbus_message_lock.
static dbus_bool_t _dbus_message_has_type_interface_member(DBusMessage *message, int type, const char *iface, const char *member)
DBUS_EXPORT dbus_bool_t dbus_message_is_method_call(DBusMessage *message, const char *iface, const char *method)
Checks whether the message is a method call with the given interface and member fields.
If the message is not DBUS_MESSAGE_TYPE_METHOD_CALL, or has a different interface or member field, returns FALSE. If the interface field is missing, then it will be assumed equal to the provided interface. The D-Bus protocol allows method callers to leave out the interface name. message the message iface the name to check (must not be NULL) method the name to check (must not be NULL) TRUE if the message is the specified method call
References DBUS_MESSAGE_TYPE_METHOD_CALL, FALSE, NULL.
Referenced by _dbus_object_tree_free_all_unlocked, dbus_connection_get_dispatch_status.
DBUS_EXPORT dbus_bool_t dbus_message_is_signal(DBusMessage *message, const char *iface, const char *signal_name)
Checks whether the message is a signal with the given interface and member fields.
If the message is not DBUS_MESSAGE_TYPE_SIGNAL, or has a different interface or member field, returns FALSE. message the message iface the name to check (must not be NULL) signal_name the name to check (must not be NULL) TRUE if the message is the specified signal
References DBUS_MESSAGE_TYPE_SIGNAL, FALSE, NULL.
Referenced by dbus_connection_read_write.
DBUS_EXPORT dbus_bool_t dbus_message_is_error(DBusMessage *message, const char *error_name)
Checks whether the message is an error reply with the given error name.
If the message is not DBUS_MESSAGE_TYPE_ERROR, or has a different name, returns FALSE. message the message error_name the name to check (must not be NULL) TRUE if the message is the specified error
References dbus_message_get_error_name, dbus_message_get_type, DBUS_MESSAGE_TYPE_ERROR, FALSE, NULL, TRUE.
DBUS_EXPORT dbus_bool_t dbus_message_has_destination(DBusMessage *message, const char *name)
Checks whether the message was sent to the given name.
If the message has no destination specified or has a different destination, returns FALSE. message the message name the name to check (must not be NULL) TRUE if the message has the given destination name
References dbus_message_get_destination, FALSE, NULL, TRUE.
DBUS_EXPORT dbus_bool_t dbus_message_has_sender(DBusMessage *message, const char *name)
Checks whether the message has the given unique name as its sender.
If the message has no sender specified or has a different sender, returns FALSE. Note that a peer application will always have the unique name of the connection as the sender. So you can't use this function to see whether a sender owned a well-known name.Messages from the bus itself will have DBUS_SERVICE_DBUS as the sender. message the message name the name to check (must not be NULL) TRUE if the message has the given sender
References dbus_message_get_sender, FALSE, NULL, TRUE.
DBUS_EXPORT dbus_bool_t dbus_message_has_signature(DBusMessage *message, const char *signature)
Checks whether the message has the given signature; see dbus_message_get_signature() for more details on what the signature looks like.
message the message signature typecode array TRUE if message has the given signature
References dbus_message_get_signature, FALSE, NULL, TRUE.
DBUS_EXPORT dbus_bool_t dbus_set_error_from_message(DBusError *error, DBusMessage *message)
Sets a DBusError based on the contents of the given message.
The error is only set if the message is an error message, as in DBUS_MESSAGE_TYPE_ERROR. The name of the error is set to the name of the message, and the error message is set to the first argument if the argument exists and is a string.The return value indicates whether the error was set (the error is set if and only if the message is an error message). So you can check for an error reply and convert it to DBusError in one go: if(dbus_set_error_from_message(error,reply)) returnerror; else processreply; error the error to set message the message to set it from TRUE if the message had type DBUS_MESSAGE_TYPE_ERROR
References dbus_message_get_args, dbus_message_get_error_name, dbus_message_get_type, DBUS_MESSAGE_TYPE_ERROR, dbus_set_error, DBUS_TYPE_INVALID, DBUS_TYPE_STRING, FALSE, NULL, TRUE.
Referenced by dbus_bus_get_id, dbus_bus_get_unix_user, dbus_bus_register, dbus_bus_release_name, dbus_bus_request_name, dbus_bus_start_service_by_name, dbus_connection_send_with_reply_and_block.
DBUS_EXPORT dbus_bool_t dbus_message_contains_unix_fds(DBusMessage *message)
Checks whether a message contains unix fds.
message the message TRUE if the message contains unix fds
References _dbus_assert, FALSE.
DBusMessageLoader* _dbus_message_loader_new(void)
Creates a new message loader.
Returns NULL if memory can't be allocated.new loader, or NULL.
References _dbus_string_init, _dbus_string_set_length, DBusMessageLoader::corrupted, DBusMessageLoader::corruption_reason, DBusMessageLoader::data, dbus_free, DBUS_MAXIMUM_MESSAGE_LENGTH, dbus_new0, DBUS_VALID, FALSE, INITIAL_LOADER_DATA_LEN, DBusMessageLoader::max_message_size, DBusMessageLoader::max_message_unix_fds, NULL, DBusMessageLoader::refcount.
Referenced by _dbus_transport_init_base, dbus_message_demarshal.
DBusMessageLoader* _dbus_message_loader_ref(DBusMessageLoader *loader)
Increments the reference count of the loader.
loader the loader. the loader
References DBusMessageLoader::refcount.
void _dbus_message_loader_unref(DBusMessageLoader *loader)
Decrements the reference count of the loader and finalizes the loader when the count reaches zero.
loader the loader.
References _dbus_list_clear, _dbus_list_foreach, _dbus_string_free, DBusMessageLoader::data, dbus_free, dbus_message_unref, DBusMessageLoader::messages, NULL, DBusMessageLoader::refcount.
Referenced by _dbus_transport_finalize_base, _dbus_transport_init_base, dbus_message_demarshal.
void _dbus_message_loader_get_buffer(DBusMessageLoader *loader, DBusString **buffer)
Gets the buffer to use for reading data from the network.
Network data is read directly into an allocated buffer, which is then used in the DBusMessage, to avoid as many extra memcpy's as possible. The buffer must always be returned immediately using _dbus_message_loader_return_buffer(), even if no bytes are successfully read.Todothis function can be a lot more clever. For example it can probably always return a buffer size to read exactly the body of the next message, thus avoiding any memory wastage or reallocs.Todowe need to enforce a max length on strings in header fields. loader the message loader. buffer the buffer
References _dbus_assert, DBusMessageLoader::buffer_outstanding, DBusMessageLoader::data, TRUE.
Referenced by _dbus_transport_do_iteration, dbus_message_demarshal.
void _dbus_message_loader_return_buffer(DBusMessageLoader *loader, DBusString *buffer)
Returns a buffer obtained from _dbus_message_loader_get_buffer(), indicating to the loader how many bytes of the buffer were filled in.
This function must always be called, even if no bytes were successfully read. loader the loader. buffer the buffer.
References _dbus_assert, DBusMessageLoader::buffer_outstanding, DBusMessageLoader::data, FALSE.
Referenced by _dbus_transport_do_iteration, dbus_message_demarshal.
dbus_bool_t _dbus_message_loader_get_unix_fds(DBusMessageLoader *loader, int **fds, unsigned *max_n_fds)
Gets the buffer to use for reading unix fds from the network.
This works similar to _dbus_message_loader_get_buffer() loader the message loader. fds the array to read fds into max_n_fds how many fds to read at most TRUE on success, FALSE on OOM
References _dbus_assert, _dbus_assert_not_reached, dbus_realloc, FALSE, DBusMessageLoader::max_message_unix_fds, TRUE.
void _dbus_message_loader_return_unix_fds(DBusMessageLoader *loader, int *fds, unsigned n_fds)
Returns a buffer obtained from _dbus_message_loader_get_unix_fds().
This works similar to _dbus_message_loader_return_buffer() loader the message loader. fds the array fds were read into n_fds how many fds were read
References _dbus_assert, _dbus_assert_not_reached, _dbus_header_get_field_basic, _dbus_header_load, _dbus_list_append, _dbus_list_find_last, _dbus_list_remove_last, _dbus_memdup, _dbus_string_compact, _dbus_string_copy_len, _dbus_string_delete, _dbus_validate_body_with_reason, _dbus_verbose_bytes_of_string, DBusMessage::body, DBusMessageLoader::corrupted, DBusMessageLoader::corruption_reason, DBusHeader::data, DBusMessageLoader::data, dbus_free, DBUS_HEADER_FIELD_UNIX_FDS, DBUS_TYPE_UINT32, DBUS_VALID, DBUS_VALIDITY_UNKNOWN_OOM_ERROR, FALSE, DBusMessage::header, DBusMessageLoader::messages, NULL, TRUE.
static dbus_bool_t load_message(DBusMessageLoader *loader, DBusMessage *message, int byte_order, int fields_array_len, int header_len, int body_len)
dbus_bool_t _dbus_message_loader_queue_messages(DBusMessageLoader *loader)
Converts buffered data into messages, if we have enough data.
If we don't have enough data, does nothing.Todowe need to check that the proper named header fields exist for each message type.TodoIf a message has unknown type, we should probably eat it right here rather than passing it out to applications. However it's not an error to see messages of unknown type. loader the loader. TRUE if we had enough memory to finish.
References _dbus_assert, _dbus_header_have_message_untrusted, _dbus_list_find_last, DBusMessageLoader::corrupted, DBusMessageLoader::corruption_reason, DBusMessageLoader::data, dbus_message_unref, DBUS_MINIMUM_HEADER_SIZE, DBUS_VALID, FALSE, DBusMessageLoader::max_message_size, DBusMessageRealIter::message, DBusMessageLoader::messages, NULL, TRUE.
Referenced by _dbus_transport_get_dispatch_status, dbus_message_demarshal.
DBusMessage* _dbus_message_loader_peek_message(DBusMessageLoader *loader)
Peeks at first loaded message, returns NULL if no messages have been queued.
loader the loader. the next message, or NULL if none.
References DBusList::data, DBusMessageLoader::messages, NULL.
Referenced by _dbus_transport_get_dispatch_status.
DBusMessage* _dbus_message_loader_pop_message(DBusMessageLoader *loader)
Pops a loaded message (passing ownership of the message to the caller).
Returns NULL if no messages have been queued. loader the loader. the next message, or NULL if none.
References _dbus_list_pop_first, DBusMessageLoader::messages.
Referenced by dbus_message_demarshal.
DBusList* _dbus_message_loader_pop_message_link(DBusMessageLoader *loader)
Pops a loaded message inside a list link (passing ownership of the message and link to the caller).
Returns NULL if no messages have been loaded. loader the loader. the next message link, or NULL if none.
References _dbus_list_pop_first_link, DBusMessageLoader::messages.
Referenced by _dbus_transport_queue_messages.
void _dbus_message_loader_putback_message_link(DBusMessageLoader *loader, DBusList *link)
Returns a popped message link, used to undo a pop.
loader the loader link the link with a message in it
References _dbus_list_prepend_link, DBusMessageLoader::messages.
Referenced by _dbus_transport_queue_messages.
dbus_bool_t _dbus_message_loader_get_is_corrupted(DBusMessageLoader *loader)
Checks whether the loader is confused due to bad data.
If messages are received that are invalid, the loader gets confused and gives up permanently. This state is called "corrupted." loader the loader TRUE if the loader is hosed.
References _dbus_assert, DBusMessageLoader::corrupted, DBusMessageLoader::corruption_reason, DBUS_VALID.
Referenced by _dbus_transport_queue_messages, dbus_message_demarshal.
DBusValidity _dbus_message_loader_get_corruption_reason(DBusMessageLoader *loader)
Checks what kind of bad data confused the loader.
loader the loader why the loader is hosed, or DBUS_VALID if it isn't.
References _dbus_assert, DBusMessageLoader::corrupted, DBusMessageLoader::corruption_reason, DBUS_VALID.
void _dbus_message_loader_set_max_message_size(DBusMessageLoader *loader, long size)
Sets the maximum size message we allow.
loader the loader size the max message size in bytes
References DBUS_MAXIMUM_MESSAGE_LENGTH, DBusMessageLoader::max_message_size.
Referenced by _dbus_transport_set_max_message_size.
long _dbus_message_loader_get_max_message_size(DBusMessageLoader *loader)
Gets the maximum allowed message size in bytes.
loader the loader max size in bytes
References DBusMessageLoader::max_message_size.
Referenced by _dbus_transport_get_max_message_size.
void _dbus_message_loader_set_max_message_unix_fds(DBusMessageLoader *loader, long n)
Sets the maximum unix fds per message we allow.
loader the loader n the max number of unix fds in a message
References DBUS_MAXIMUM_MESSAGE_UNIX_FDS, DBusMessageLoader::max_message_unix_fds.
Referenced by _dbus_transport_set_max_message_unix_fds.
long _dbus_message_loader_get_max_message_unix_fds(DBusMessageLoader *loader)
Gets the maximum allowed number of unix fds per message.
loader the loader max unix fds
References DBusMessageLoader::max_message_unix_fds.
Referenced by _dbus_transport_get_max_message_unix_fds.
int _dbus_message_loader_get_pending_fds_count(DBusMessageLoader *loader)
Return how many file descriptors are pending in the loader.
loader the loader
Referenced by _dbus_transport_get_pending_fds_count.
void _dbus_message_loader_set_pending_fds_function(DBusMessageLoader *loader, void(*callback)(void *), void *data)
Register a function to be called whenever the number of pending file descriptors in the loader change.
loader the loader callback the callback data the data for the callback
References _DBUS_LOCK_NAME.
Referenced by _dbus_transport_set_pending_fds_function.
dbus_bool_t dbus_message_allocate_data_slot(dbus_int32_t *slot_p)
Allocates an integer ID to be used for storing application-specific data on any DBusMessage.
The allocated ID may then be used with dbus_message_set_data() and dbus_message_get_data(). The passed-in slot must be initialized to -1, and is filled in with the slot ID. If the passed-in slot is not -1, it's assumed to be already allocated, and its refcount is incremented.The allocated slot is global, i.e. all DBusMessage objects will have a slot with the given integer ID reserved. slot_p address of a global variable storing the slot FALSE on failure (no memory)
References _dbus_data_slot_allocator_alloc.
void dbus_message_free_data_slot(dbus_int32_t *slot_p)
Deallocates a global ID for message data slots.
dbus_message_get_data() and dbus_message_set_data() may no longer be used with this slot. Existing data stored on existing DBusMessage objects will be freed when the message is finalized, but may not be retrieved (and may only be replaced if someone else reallocates the slot). When the refcount on the passed-in slot reaches 0, it is set to -1. slot_p address storing the slot to deallocate
References _dbus_data_slot_allocator_free.
dbus_bool_t dbus_message_set_data(DBusMessage *message, dbus_int32_t slot, void *data, DBusFreeFunction free_data_func)
Stores a pointer on a DBusMessage, along with an optional function to be used for freeing the data when the data is set again, or when the message is finalized.
The slot number must have been allocated with dbus_message_allocate_data_slot(). message the message slot the slot number data the data to store free_data_func finalizer function for the data TRUE if there was enough memory to store the data
References _dbus_data_slot_list_set, FALSE, NULL, DBusMessage::slot_list.
void* dbus_message_get_data(DBusMessage *message, dbus_int32_t slot)
Retrieves data previously set with dbus_message_set_data().
The slot must still be allocated (must not have been freed). message the message slot the slot to get data from the data, or NULL if not found
References _dbus_data_slot_list_get, NULL, DBusMessage::slot_list.
int dbus_message_type_from_string(const char *type_str)
Utility function to convert a machine-readable (not translated) string into a D-Bus message type.
"method_call"->DBUS_MESSAGE_TYPE_METHOD_CALL "method_return"->DBUS_MESSAGE_TYPE_METHOD_RETURN "signal"->DBUS_MESSAGE_TYPE_SIGNAL "error"->DBUS_MESSAGE_TYPE_ERROR anythingelse->DBUS_MESSAGE_TYPE_INVALID
References DBUS_MESSAGE_TYPE_ERROR, DBUS_MESSAGE_TYPE_INVALID, DBUS_MESSAGE_TYPE_METHOD_CALL, DBUS_MESSAGE_TYPE_METHOD_RETURN, DBUS_MESSAGE_TYPE_SIGNAL.
const char* dbus_message_type_to_string(int type)
Utility function to convert a D-Bus message type into a machine-readable string (not translated).
DBUS_MESSAGE_TYPE_METHOD_CALL->"method_call" DBUS_MESSAGE_TYPE_METHOD_RETURN->"method_return" DBUS_MESSAGE_TYPE_SIGNAL->"signal" DBUS_MESSAGE_TYPE_ERROR->"error" DBUS_MESSAGE_TYPE_INVALID->"invalid"
References DBUS_MESSAGE_TYPE_ERROR, DBUS_MESSAGE_TYPE_METHOD_CALL, DBUS_MESSAGE_TYPE_METHOD_RETURN, DBUS_MESSAGE_TYPE_SIGNAL.
Referenced by _dbus_connection_close_possibly_shared, _dbus_connection_message_sent_unlocked, _dbus_connection_queue_received_message_link, dbus_connection_dispatch, dbus_connection_steal_borrowed_message.
dbus_bool_t dbus_message_marshal(DBusMessage *msg, char **marshalled_data_p, int *len_p)
Turn a DBusMessage into the marshalled form as described in the D-Bus specification.
Generally, this function is only useful for encapsulating D-Bus messages in a different protocol. msg the DBusMessage marshalled_data_p the location to save the marshalled form to len_p the location to save the length of the marshalled form to FALSE if there was not enough memory
References _dbus_string_copy, _dbus_string_free, _dbus_string_init, _dbus_string_steal_data, DBusMessage::body, DBusHeader::data, dbus_message_lock, FALSE, DBusMessage::header, DBusMessage::locked, NULL, TRUE.
DBusMessage* dbus_message_demarshal(const char *str, int len, DBusError *error)
Demarshal a D-Bus message from the format described in the D-Bus specification.
Generally, this function is only useful for encapsulating D-Bus messages in a different protocol. str the marshalled DBusMessage len the length of str error the location to save errors to NULL if there was an error
References _dbus_message_loader_get_buffer, _dbus_message_loader_get_is_corrupted, _dbus_message_loader_new, _dbus_message_loader_pop_message, _dbus_message_loader_queue_messages, _dbus_message_loader_return_buffer, _dbus_message_loader_unref, _dbus_string_append_len, DBusMessageLoader::corruption_reason, DBUS_ERROR_INVALID_ARGS, dbus_set_error, NULL.
int dbus_message_demarshal_bytes_needed(const char *buf, int len)
Returns the number of bytes required to be in the buffer to demarshal a D-Bus message.
Generally, this function is only useful for encapsulating D-Bus messages in a different protocol. buf data to be marshalled len the length of buf -1 if there was no valid data to be demarshalled, 0 if there wasn't enough data to determine how much should be demarshalled. Otherwise returns the number of bytes to be demarshalled
References _dbus_assert, _dbus_header_have_message_untrusted, _dbus_string_free, _dbus_string_init_const_len, DBUS_MAXIMUM_MESSAGE_LENGTH, DBUS_MINIMUM_HEADER_SIZE, DBUS_VALID.
void dbus_message_set_allow_interactive_authorization(DBusMessage *message, dbus_bool_t allow)
Sets a flag indicating that the caller of the method is prepared to wait for interactive authorization to take place (for instance via Polkit) before the actual method is processed.
The flag is FALSE by default; that is, by default the other end is expected to make any authorization decisions non-interactively and promptly. It may use the error DBUS_ERROR_INTERACTIVE_AUTHORIZATION_REQUIRED to signal that authorization failed, but could have succeeded if this flag had been used.For messages whose type is not DBUS_MESSAGE_TYPE_METHOD_CALL, this flag is meaningless and should not be set.On the protocol level this toggles DBUS_HEADER_FLAG_ALLOW_INTERACTIVE_AUTHORIZATION. message the message allow TRUE if interactive authorization is acceptable
References _dbus_header_toggle_flag, DBUS_HEADER_FLAG_ALLOW_INTERACTIVE_AUTHORIZATION, DBusMessage::header, DBusMessage::locked, NULL.
dbus_bool_t dbus_message_get_allow_interactive_authorization(DBusMessage *message)
Returns whether the flag controlled by dbus_message_set_allow_interactive_authorization() has been set.
message the message
References _dbus_header_get_flag, DBUS_HEADER_FLAG_ALLOW_INTERACTIVE_AUTHORIZATION, FALSE, DBusMessage::header, NULL.