dbus-server-protected.h
_dbus_server_trace_ref
TOOK_LOCK_CHECK
RELEASING_LOCK_CHECK
HAVE_LOCK_CHECK
TRACE_LOCKS
SERVER_LOCK
SERVER_UNLOCK
DBusServerListenResult
we aren't in charge of this address type
typedef struct DBusServerVTable DBusServerVTable
dbus_bool_t _dbus_server_init_base(DBusServer *server, const DBusServerVTable *vtable, const DBusString *address)
Initializes the members of the DBusServer base class.
Chained up to by subclass constructors. server the server. vtable the vtable for the subclass. address the server's address TRUE on success.
References DBusServer::vtable, _dbus_atomic_inc, DBusServer::refcount, _dbus_assert, DBusServer::address, NULL, DBusServer::watches, DBusServer::timeouts, DBusServer::published_address, FALSE, _dbus_string_init, DBusServer::guid_hex, _dbus_generate_uuid, DBusServer::guid, _dbus_uuid_encode, _dbus_rmutex_new_at_location, DBusServer::mutex, _dbus_watch_list_new, _dbus_timeout_list_new, _dbus_data_slot_list_init, DBusServer::slot_list, TRUE, _dbus_rmutex_free_at_location, _dbus_watch_list_free, _dbus_timeout_list_free, dbus_free, _dbus_string_free.
Referenced by _dbus_server_new_for_socket.
void _dbus_server_finalize_base(DBusServer *server)
Finalizes the members of the DBusServer base class.
Chained up to by subclass finalizers. server the server.
References _dbus_assert, DBusServer::have_server_lock, DBusServer::disconnected, _dbus_data_slot_list_free, DBusServer::slot_list, dbus_server_set_new_connection_function, NULL, _dbus_watch_list_free, DBusServer::watches, _dbus_timeout_list_free, DBusServer::timeouts, _dbus_rmutex_free_at_location, DBusServer::mutex, dbus_free, DBusServer::address, dbus_free_string_array, DBusServer::auth_mechanisms, _dbus_string_free, DBusServer::guid_hex.
Referenced by _dbus_server_new_for_socket.
dbus_bool_t _dbus_server_add_watch(DBusServer *server, DBusWatch *watch)
Adds a watch for this server, chaining out to application-provided watch handlers.
server the server. watch the watch to add.
References _dbus_watch_list_add_watch, NULL, FALSE.
Referenced by _dbus_server_new_for_socket.
void _dbus_server_remove_watch(DBusServer *server, DBusWatch *watch)
Removes a watch previously added with _dbus_server_remove_watch().
server the server. watch the watch to remove.
References NULL, _dbus_watch_list_remove_watch, FALSE.
Referenced by _dbus_server_new_for_socket.
void _dbus_server_toggle_all_watches(DBusServer *server, dbus_bool_t enabled)
Toggles all watch and notifies app via server's DBusWatchToggledFunction if available.
server the server. enabled whether to enable or disable
References _dbus_watch_list_toggle_all_watches, DBusServer::watches.
dbus_bool_t _dbus_server_add_timeout(DBusServer *server, DBusTimeout *timeout)
Adds a timeout for this server, chaining out to application-provided timeout handlers.
The timeout should be repeatedly handled with dbus_timeout_handle() at its given interval until it is removed. server the server. timeout the timeout to add.
References _dbus_timeout_list_add_timeout, NULL, FALSE.
void _dbus_server_remove_timeout(DBusServer *server, DBusTimeout *timeout)
Removes a timeout previously added with _dbus_server_add_timeout().
server the server. timeout the timeout to remove.
References NULL, _dbus_timeout_list_remove_timeout, FALSE.
void _dbus_server_toggle_timeout(DBusServer *server, DBusTimeout *timeout, dbus_bool_t enabled)
Toggles a timeout and notifies app via server's DBusTimeoutToggledFunction if available.
It's an error to call this function on a timeout that was not previously added. server the server. timeout the timeout to toggle. enabled whether to enable or disable
References NULL, _dbus_timeout_list_toggle_timeout.
void _dbus_server_ref_unlocked(DBusServer *server)
Like dbus_server_ref() but does not acquire the lock (must already be held)
server the server.
References _dbus_assert, NULL, _dbus_atomic_inc, DBusServer::refcount.
void _dbus_server_unref_unlocked(DBusServer *server)
Like dbus_server_unref() but does not acquire the lock (must already be held)
server the server.
References _dbus_assert, NULL, _dbus_atomic_dec, DBusServer::refcount, DBusServer::disconnected, DBusServer::vtable, DBusServerVTable::finalize, _dbus_server_listen_socket, _dbus_server_listen_platform_specific.
DBusServerListenResult _dbus_server_listen_platform_specific(DBusAddressEntry *entry, DBusServer **server_p, DBusError *error)
Tries to interpret the address entry in a platform-specific way, creating a platform-specific server type if appropriate.
Sets error if the result is not OK. entry an address entry server_p location to store a new DBusServer, or NULL on failure. error location to store rationale for failure on bad address the outcome
References NULL, dbus_address_entry_get_method, dbus_address_entry_get_value, _dbus_set_bad_address, _dbus_string_init, dbus_set_error, DBUS_ERROR_NO_MEMORY, _dbus_string_free, _dbus_string_append, _dbus_generate_random_ascii, _dbus_concat_dir_and_file, _dbus_server_new_for_domain_socket, TRUE, FALSE, _dbus_listen_systemd_sockets, _dbus_append_address_from_socket, _dbus_server_new_for_socket, dbus_free, _dbus_close_socket, _dbus_server_new_for_launchd, _dbus_server_new_for_tcp_socket.
Referenced by _dbus_server_unref_unlocked.