dbus-errors.c
_DBUS_STATIC_ASSERT(sizeof(DBusRealError)==sizeof(DBusError))
static const char* message_from_error(const char *error)
Returns a longer message describing an error name.
If the error name is unknown, returns the name itself. error the error to describe a constant string describing the error.
DBUS_EXPORT void dbus_error_init(DBusError *error)
Initializes a DBusError structure.
Does not allocate any memory; the error only needs to be freed if it is set at some point. error the DBusError.
References DBusRealError::const_message, DBusRealError::message, DBusRealError::name, NULL, TRUE.
Referenced by _dbus_file_exists, _dbus_groups_from_uid, _dbus_keyring_get_hex_key, _dbus_keyring_new_for_credentials, _dbus_spawn_async_with_babysitter, _dbus_transport_open_platform_specific, dbus_error_free, dbus_move_error.
DBUS_EXPORT void dbus_error_free(DBusError *error)
Frees an error that's been set (or just initialized), then reinitializes the error as in dbus_error_init().
error memory where the error is stored.
References DBusRealError::const_message, dbus_error_init, dbus_free, DBusRealError::message, DBusRealError::name, NULL.
Referenced by _dbus_babysitter_unref, _dbus_connection_handle_watch, _dbus_file_exists, _dbus_get_local_machine_uuid_encoded, _dbus_groups_from_uid, _dbus_keyring_get_hex_key, _dbus_keyring_new_for_credentials, _dbus_read_local_machine_uuid, _dbus_read_uuid_file, _dbus_sha_compute, _dbus_spawn_async_with_babysitter, _dbus_transport_open_platform_specific, _dbus_user_database_lookup, dbus_address_unescape_value, dbus_connection_register_fallback, dbus_connection_register_object_path, dbus_move_error, dbus_server_get_data, dbus_server_listen.
DBUS_EXPORT void dbus_set_error_const(DBusError *error, const char *name, const char *message)
Assigns an error name and message to a DBusError.
Does nothing if error is NULL. The message may be NULL, which means a default message will be deduced from the name. The default message will be totally useless, though, so using a NULL message is not recommended.Because this function does not copy the error name or message, you must ensure the name and message are global data that won't be freed. You probably want dbus_set_error() instead, in most cases. error the error or NULL name the error name (not copied!!!) message the error message (not copied!!!)
References _dbus_assert, DBusRealError::const_message, DBusError::message, DBusRealError::message, DBusError::name, DBusRealError::name, NULL, TRUE.
Referenced by _dbus_get_autolaunch_address, _dbus_keyring_get_best_key, _dbus_keyring_new_for_credentials, _dbus_listen_systemd_sockets, _dbus_lookup_launchd_socket, _dbus_printf_string_upper_bound, _dbus_spawn_async_with_babysitter.
DBUS_EXPORT void dbus_move_error(DBusError *src, DBusError *dest)
Moves an error src into dest, freeing src and overwriting dest.
Both src and dest must be initialized. src is reinitialized to an empty error. dest may not contain an existing error. If the destination is NULL, just frees and reinits the source error. src the source error dest the destination error or NULL
References dbus_error_free, dbus_error_init.
Referenced by _dbus_connection_handle_watch, _dbus_read_uuid_file, _dbus_transport_open, _dbus_transport_open_platform_specific, dbus_server_listen.
DBUS_EXPORT dbus_bool_t dbus_error_has_name(const DBusError *error, const char *name)
Checks whether the error is set and has the given name.
error the error name the name TRUE if the given named error occurred
References _dbus_assert, _dbus_string_equal, _dbus_string_init_const, FALSE, DBusError::message, DBusError::name, NULL.
Referenced by _dbus_read_uuid_file, _dbus_spawn_async_with_babysitter, _dbus_user_database_lookup, dbus_connection_register_fallback, dbus_connection_register_object_path.
DBUS_EXPORT dbus_bool_t dbus_error_is_set(const DBusError *error)
Checks whether an error occurred (the error is set).
error the error object TRUE if an error occurred
References _dbus_assert, FALSE, DBusError::message, DBusError::name, NULL.
Referenced by _dbus_lookup_launchd_socket, _dbus_spawn_async_with_babysitter, _dbus_transport_open, _dbus_transport_open_platform_specific, _dbus_write_pid_to_file_and_pipe, dbus_address_entry_get_value, dbus_address_unescape_value, dbus_parse_address, dbus_server_listen.
DBUS_EXPORT void dbus_set_error(DBusError *error, const char *name, const char *format,...)
Assigns an error name and message to a DBusError.
Does nothing if error is NULL.The format may be NULL, which means a (pretty much useless) default message will be deduced from the name. This is not a good idea, just go ahead and provide a useful error message. It won't hurt you.If no memory can be allocated for the error message, an out-of-memory error message will be set instead. error the error.or NULL name the error name format printf-style format string.
References _dbus_assert, _dbus_strdup, _dbus_string_append, _dbus_string_append_printf_valist, _dbus_string_free, _dbus_string_init, _dbus_string_steal_data, DBusRealError::const_message, dbus_free, FALSE, DBusError::message, DBusRealError::message, DBusError::name, DBusRealError::name, NULL.
Referenced by _dbus_append_address_from_socket, _dbus_babysitter_set_child_exit_error, _dbus_become_daemon, _dbus_bus_notify_shared_connection_disconnected_unlocked, _dbus_change_to_daemon_user, _dbus_check_dir_is_private_to_user, _dbus_close, _dbus_close_socket, _dbus_command_for_pid, _dbus_connect_exec, _dbus_connect_tcp_socket, _dbus_connect_unix_socket, _dbus_create_directory, _dbus_create_file_exclusively, _dbus_delete_directory, _dbus_delete_file, _dbus_directory_close, _dbus_directory_get_next_file, _dbus_directory_open, _dbus_dup, _dbus_file_exists, _dbus_file_get_contents, _dbus_full_duplex_pipe, _dbus_get_tmpdir, _dbus_is_console_user, _dbus_keyring_new_for_credentials, _dbus_listen_systemd_sockets, _dbus_listen_tcp_socket, _dbus_listen_unix_socket, _dbus_lookup_launchd_socket, _dbus_make_file_world_readable, _dbus_message_iter_get_args_valist, _dbus_object_tree_register, _dbus_read_credentials_socket, _dbus_read_local_machine_uuid, _dbus_send_credentials_socket, _dbus_server_listen_platform_specific, _dbus_server_new_for_domain_socket, _dbus_server_new_for_launchd, _dbus_server_new_for_tcp_socket, _dbus_set_bad_address, _dbus_spawn_async_with_babysitter, _dbus_stat, _dbus_string_save_to_file, _dbus_transport_finalize_base, _dbus_transport_new_for_domain_socket, _dbus_transport_new_for_tcp_socket, _dbus_transport_open_platform_specific, _dbus_unix_user_is_at_console, _dbus_user_database_lookup, _dbus_user_database_lookup_group, _dbus_uuid_encode, _dbus_write_pid_to_file_and_pipe, dbus_address_entry_get_value, dbus_connection_send_with_reply_and_block, dbus_message_demarshal, dbus_parse_address, dbus_server_listen, dbus_set_error_from_message, dbus_signature_validate, dbus_signature_validate_single, dbus_validate_bus_name, dbus_validate_error_name, dbus_validate_interface, dbus_validate_member, dbus_validate_path, dbus_validate_utf8.