dbus-address.c
_DBUS_ADDRESS_OPTIONALLY_ESCAPED_BYTE
TRUE if the byte need not be escaped when found in a dbus address.
All other bytes are required to be escaped in a valid address.
Referenced by _dbus_address_append_escaped, dbus_address_entry_get_value.
void _dbus_set_bad_address(DBusError *error, const char *address_problem_type, const char *address_problem_field, const char *address_problem_other)
Sets DBUS_ERROR_BAD_ADDRESS.
If address_problem_type and address_problem_field are not NULL, sets an error message about how the field is no good. Otherwise, sets address_problem_other as the error message. error the error to set address_problem_type the address type of the bad address or NULL address_problem_field the missing field of the bad address or NULL address_problem_other any other error message or NULL
References DBUS_ERROR_BAD_ADDRESS, dbus_set_error, NULL.
Referenced by _dbus_server_listen_platform_specific, _dbus_transport_open, _dbus_transport_open_platform_specific, _dbus_transport_open_socket.
dbus_bool_t _dbus_address_append_escaped(DBusString *escaped, const DBusString *unescaped)
Appends an escaped version of one string to another string, using the D-Bus address escaping mechanism.
escaped the string to append to unescaped the string to escape FALSE if no memory
References _DBUS_ADDRESS_OPTIONALLY_ESCAPED_BYTE, _dbus_list_clear, _dbus_list_get_first_link, _dbus_list_get_next_link, _dbus_string_append_byte, _dbus_string_append_byte_as_hex, _dbus_string_free, _dbus_string_set_length, DBusList::data, dbus_free, FALSE, DBusAddressEntry::keys, DBusAddressEntry::method, NULL, TRUE, DBusAddressEntry::values.
Referenced by _dbus_append_address_from_socket, _dbus_server_new_for_domain_socket, _dbus_server_new_for_tcp_socket, dbus_address_escape_value.
static void dbus_address_entry_free(DBusAddressEntry *entry)
DBUS_EXPORT void dbus_address_entries_free(DBusAddressEntry **entries)
Frees a NULL-terminated array of address entries.
entries the array.
References _dbus_string_init, dbus_free, dbus_new0, DBusAddressEntry::method, NULL.
Referenced by _dbus_connection_handle_watch, _dbus_transport_finalize_base, dbus_address_unescape_value, dbus_server_listen.
static DBusAddressEntry* create_entry(void)
DBUS_EXPORT const char * dbus_address_entry_get_method(DBusAddressEntry *entry)
Returns the method string of an address entry.
For example, given the address entry "tcp:host=example.com" it would return the string "tcp" entry the entry. a string describing the method. This string must not be freed.
References DBusAddressEntry::method.
Referenced by _dbus_server_listen_platform_specific, _dbus_server_listen_socket, _dbus_transport_finalize_base, _dbus_transport_open_platform_specific, _dbus_transport_open_socket, dbus_server_listen.
DBUS_EXPORT const char * dbus_address_entry_get_value(DBusAddressEntry *entry, const char *key)
Returns a value from a key of an entry.
For example, given the address "tcp:host=example.com,port=8073" if you asked for the key "host" you would get the value "example.com"The returned value is already unescaped. entry the entry. key the key. the key value. This string must not be freed.
References _DBUS_ADDRESS_OPTIONALLY_ESCAPED_BYTE, _dbus_assert, _dbus_list_get_first_link, _dbus_list_get_next_link, _dbus_string_append_byte, _dbus_string_equal_c_str, _dbus_string_hex_decode, _dbus_string_init_const, DBusList::data, DBUS_ERROR_BAD_ADDRESS, dbus_error_is_set, dbus_set_error, FALSE, DBusAddressEntry::keys, NULL, TRUE, DBusAddressEntry::values.
Referenced by _dbus_connection_handle_watch, _dbus_server_listen_platform_specific, _dbus_server_listen_socket, _dbus_transport_finalize_base, _dbus_transport_open, _dbus_transport_open_platform_specific, _dbus_transport_open_socket, dbus_address_unescape_value.
static dbus_bool_t append_unescaped_value(DBusString *unescaped, const DBusString *escaped, int escaped_start, int escaped_len, DBusError *error)
DBUS_EXPORT dbus_bool_t dbus_parse_address(const char *address, DBusAddressEntry ***entry, int *array_len, DBusError *error)
Parses an address string of the form:
method:key=value,key=value;method:key=valueSee the D-Bus specification for complete docs on the format.When connecting to an address, the first address entries in the semicolon-separated list should be tried first. address the address. entry return location to an array of entries. array_len return location for array length. error address where an error can be returned. TRUE on success, FALSE otherwise.
References _dbus_assert, _dbus_list_append, _dbus_list_clear, _dbus_list_get_first_link, _dbus_list_get_length, _dbus_list_get_next_link, _dbus_string_copy_len, _dbus_string_find, _dbus_string_find_to, _dbus_string_free, _dbus_string_init, _dbus_string_init_const, DBusList::data, DBUS_ERROR_BAD_ADDRESS, dbus_error_is_set, DBUS_ERROR_NO_MEMORY, dbus_free, dbus_new, dbus_new0, dbus_set_error, FALSE, DBusAddressEntry::keys, DBusAddressEntry::method, NULL, TRUE, DBusAddressEntry::values.
Referenced by _dbus_connection_handle_watch, _dbus_transport_finalize_base, dbus_address_unescape_value, dbus_server_listen.
DBUS_EXPORT char * dbus_address_escape_value(const char *value)
Escapes the given string as a value in a key=value pair for a D-Bus address.
value the unescaped value newly-allocated escaped value or NULL if no memory
References _dbus_address_append_escaped, _dbus_string_free, _dbus_string_init, _dbus_string_init_const, _dbus_string_steal_data, NULL.
Referenced by _dbus_transport_new_for_domain_socket, dbus_address_unescape_value.
DBUS_EXPORT char * dbus_address_unescape_value(const char *value, DBusError *error)
Unescapes the given string as a value in a key=value pair for a D-Bus address.
Note that dbus_address_entry_get_value() returns an already-unescaped value. value the escaped value error error to set if the unescaping fails newly-allocated unescaped value or NULL if no memory
References _dbus_assert, _dbus_assert_not_reached, _DBUS_N_ELEMENTS, _dbus_string_free, _dbus_string_init, _dbus_string_init_const, _dbus_string_steal_data, _dbus_warn, dbus_address_entries_free, dbus_address_entry_get_value, dbus_address_escape_value, dbus_error_free, DBUS_ERROR_INIT, dbus_error_is_set, dbus_free, dbus_parse_address, DBusError::message, NULL, TRUE.