dbus-memory.c
typedef struct ShutdownClosure ShutdownClosure
Represents a function to be called on shutdown.
int _dbus_current_generation
_dbus_current_generation is used to track each time that dbus_shutdown() is called, so we can reinit things after it's been called.
It is simply incremented each time we shut down.
Referenced by _dbus_condvar_wake_one, _dbus_connection_close_possibly_shared, _dbus_connection_new_for_transport, _dbus_connection_ref_unlocked, _dbus_get_local_machine_uuid_encoded, dbus_connection_close, dbus_connection_ref, dbus_connection_unref, dbus_message_get_reply_serial, dbus_message_ref, dbus_message_unref, dbus_threads_init.
ShutdownClosure* registered_globals
DBUS_EXPORT DBUS_MALLOC void * dbus_malloc(size_t bytes)
Allocates the given number of bytes, as with standard malloc().
Guaranteed to return NULL if bytes is zero on all platforms. Returns NULL if the allocation fails. The memory must be released with dbus_free().dbus_malloc() memory is NOT safe to free with regular free() from the C library. Free it with dbus_free() only. bytes number of bytes to allocate allocated memory, or NULL if the allocation fails.
References _dbus_abort, _dbus_atomic_inc, _dbus_warn, NULL.
Referenced by _dbus_babysitter_set_watch_functions, _dbus_check_dir_is_private_to_user, _dbus_directory_close, _dbus_file_exists, _dbus_hash_table_get_n_entries, _dbus_mem_pool_alloc, _dbus_mem_pool_dealloc, _dbus_memdup, _dbus_printf_string_upper_bound, _dbus_strdup, _dbus_string_copy_data, _dbus_string_init_preallocated, dbus_shutdown.
DBUS_EXPORT DBUS_MALLOC void * dbus_malloc0(size_t bytes)
Allocates the given number of bytes, as with standard malloc(), but all bytes are initialized to zero as with calloc().
Guaranteed to return NULL if bytes is zero on all platforms. Returns NULL if the allocation fails. The memory must be released with dbus_free().dbus_malloc0() memory is NOT safe to free with regular free() from the C library. Free it with dbus_free() only. bytes number of bytes to allocate allocated memory, or NULL if the allocation fails.
References _dbus_abort, _dbus_atomic_inc, _dbus_warn, NULL.
Referenced by _dbus_mem_pool_alloc, _dbus_mem_pool_dealloc, _dbus_object_tree_get_user_data_unlocked.
DBUS_EXPORT DBUS_MALLOC void * dbus_realloc(void *memory, size_t bytes)
Resizes a block of memory previously allocated by dbus_malloc() or dbus_malloc0().
Guaranteed to free the memory and return NULL if bytes is zero on all platforms. Returns NULL if the resize fails. If the resize fails, the memory is not freed. memory block to be resized bytes new size of the memory block allocated memory, or NULL if the resize fails.
References _dbus_abort, _dbus_atomic_inc, _dbus_warn, dbus_free, FALSE, NULL.
Referenced by _dbus_check_dir_is_private_to_user, _dbus_data_slot_allocator_alloc, _dbus_data_slot_list_set, _dbus_listen_tcp_socket, _dbus_message_loader_get_unix_fds, _dbus_string_free, dbus_message_iter_init_append, dbus_shutdown.
DBUS_EXPORT void dbus_free(void *memory)
Frees a block of memory previously allocated by dbus_malloc() or dbus_malloc0().
If passed NULL, does nothing. memory block to be freed
References _dbus_assert, _dbus_atomic_dec, TRUE.
Referenced by _dbus_address_append_escaped, _dbus_auth_unref, _dbus_babysitter_unref, _dbus_change_to_daemon_user, _dbus_check_dir_is_private_to_user, _dbus_connection_close_possibly_shared, _dbus_connection_handle_watch, _dbus_connection_new_for_transport, _dbus_counter_unref, _dbus_credentials_add_adt_audit_data, _dbus_credentials_add_windows_sid, _dbus_credentials_clear, _dbus_credentials_unref, _dbus_data_slot_allocator_free, _dbus_data_slot_list_free, _dbus_decompose_path, _dbus_directory_close, _dbus_directory_open, _dbus_group_info_free, _dbus_group_info_free_allocated, _dbus_groups_from_uid, _dbus_hash_table_get_n_entries, _dbus_hash_table_new, _dbus_hash_table_unref, _dbus_keyring_unref, _dbus_listen_systemd_sockets, _dbus_listen_tcp_socket, _dbus_mem_pool_dealloc, _dbus_mem_pool_free, _dbus_message_loader_new, _dbus_message_loader_return_unix_fds, _dbus_message_loader_unref, _dbus_object_tree_get_user_data_unlocked, _dbus_object_tree_new, _dbus_object_tree_register, _dbus_object_tree_unref, _dbus_pending_call_new_unlocked, _dbus_pending_call_ref_unlocked, _dbus_printf_string_upper_bound, _dbus_server_finalize_base, _dbus_server_init_base, _dbus_server_listen_platform_specific, _dbus_server_new_for_domain_socket, _dbus_server_new_for_socket, _dbus_server_new_for_tcp_socket, _dbus_split_paths_and_append, _dbus_string_find_byte_backward, _dbus_string_free, _dbus_timeout_list_free, _dbus_timeout_unref, _dbus_transport_finalize_base, _dbus_transport_new_for_domain_socket, _dbus_transport_new_for_socket, _dbus_transport_open, _dbus_type_writer_write_fixed_multi, _dbus_user_database_unref, _dbus_user_info_free, _dbus_user_info_free_allocated, _dbus_watch_list_free, _dbus_watch_unref, dbus_address_entries_free, dbus_address_unescape_value, dbus_connection_free_preallocated_send, dbus_connection_ref, dbus_error_free, dbus_free_string_array, dbus_message_copy, dbus_message_get_reply_serial, dbus_message_iter_init_append, dbus_parse_address, dbus_realloc, dbus_server_get_data, dbus_set_error, dbus_shutdown.
DBUS_EXPORT void dbus_free_string_array(char **str_array)
Frees a NULL-terminated array of strings.
If passed NULL, does nothing. str_array the array to be freed
References dbus_free.
Referenced by _dbus_auth_set_mechanisms, _dbus_auth_unref, _dbus_decompose_path, _dbus_dup_string_array, _dbus_get_environment, _dbus_message_iter_get_args_valist, _dbus_object_tree_dispatch_and_unlock, _dbus_object_tree_free_all_unlocked, _dbus_server_finalize_base, _dbus_spawn_async_with_babysitter, _dbus_transport_open_platform_specific, dbus_connection_get_object_path_data, dbus_connection_list_registered, dbus_connection_remove_filter, dbus_connection_unregister_object_path, dbus_server_set_auth_mechanisms.
dbus_bool_t _dbus_register_shutdown_func(DBusShutdownFunction func, void *data)
Register a cleanup function to be called exactly once the next time dbus_shutdown() is called.
func the function data data to pass to the function FALSE on not enough memory
References _DBUS_LOCK, _DBUS_UNLOCK, ShutdownClosure::data, dbus_new, FALSE, ShutdownClosure::func, ShutdownClosure::next, NULL, TRUE.
Referenced by _dbus_connection_handle_watch, _dbus_user_database_lookup.
dbus_bool_t _dbus_register_shutdown_func_unlocked(DBusShutdownFunction func, void *data)
DBUS_EXPORT void dbus_shutdown(void)
Frees all memory allocated internally by libdbus and reverses the effects of dbus_threads_init().
libdbus keeps internal global variables, for example caches and thread locks, and it can be useful to free these internal data structures.dbus_shutdown() does NOT free memory that was returned to the application. It only frees libdbus-internal data structures.You MUST free all memory and release all reference counts returned to you by libdbus prior to calling dbus_shutdown().If a shared connection is open, calling dbus_shutdown() will drain its queue of messages and disconnect it. In particular, this will result in processing of the special Disconnected signal, which may result in a call to _exit(), unless you have used dbus_connection_set_exit_on_disconnect() to disable that behaviour.You can't continue to use any D-Bus objects, such as connections, that were allocated prior to dbus_shutdown(). You can, however, start over; call dbus_threads_init() again, create new connections, and so forth.WARNING: dbus_shutdown() is NOT thread safe, it must be called while NO other threads are using D-Bus. (Remember, you have to free all D-Bus objects and memory before you call dbus_shutdown(), so no thread can be using libdbus.)The purpose of dbus_shutdown() is to allow applications to get clean output from memory leak checkers. dbus_shutdown() may also be useful if you want to dlopen() libdbus instead of linking to it, and want to be able to unload the library again.There is absolutely no requirement to call dbus_shutdown() - in fact, most applications won't bother and should not feel guilty.You have to know that nobody is using libdbus in your application's process before you can call dbus_shutdown(). One implication of this is that calling dbus_shutdown() from a library is almost certainly wrong, since you don't know what the rest of the app is up to.
References _dbus_assert_not_reached, _dbus_threads_lock_platform_specific, _dbus_threads_unlock_platform_specific, ShutdownClosure::data, dbus_free, dbus_malloc, dbus_realloc, ShutdownClosure::func, ShutdownClosure::next, NULL, TRUE.