dbus-dataslot.h
_DBUS_DATA_SLOT_ALLOCATOR_INIT
typedef struct DBusDataSlotAllocator DBusDataSlotAllocator
typedef struct DBusDataSlotList DBusDataSlotList
typedef struct DBusDataSlot DBusDataSlot
Opaque typedef for DBusDataSlot.
typedef struct DBusAllocatedSlot DBusAllocatedSlot
dbus_bool_t _dbus_data_slot_allocator_init(DBusDataSlotAllocator *allocator, DBusGlobalLock lock)
Initializes a data slot allocator object, used to assign integer IDs for data slots.
allocator the allocator to initialize
References DBusDataSlotAllocator::allocated_slots, NULL, DBusDataSlotAllocator::n_allocated_slots, DBusDataSlotAllocator::n_used_slots, DBusDataSlotAllocator::lock, TRUE.
Referenced by _dbus_data_slot_list_free.
dbus_bool_t _dbus_data_slot_allocator_alloc(DBusDataSlotAllocator *allocator, int *slot_id_p)
Allocates an integer ID to be used for storing data in a DBusDataSlotList.
If the value at *slot_id_p is not -1, this function just increments the refcount for the existing slot ID. If the value is -1, a new slot ID is allocated and stored at *slot_id_p. allocator the allocator slot_id_p address to fill with the slot ID TRUE on success
References DBusDataSlotAllocator::lock, FALSE, _dbus_assert, DBusDataSlotAllocator::allocated_slots, DBusAllocatedSlot::slot_id, DBusAllocatedSlot::refcount, DBusDataSlotAllocator::n_used_slots, DBusDataSlotAllocator::n_allocated_slots, dbus_realloc, NULL.
Referenced by dbus_connection_allocate_data_slot, _dbus_data_slot_list_free, dbus_message_allocate_data_slot, dbus_pending_call_allocate_data_slot, dbus_server_allocate_data_slot.
void _dbus_data_slot_allocator_free(DBusDataSlotAllocator *allocator, int *slot_id_p)
Deallocates an ID previously allocated with _dbus_data_slot_allocator_alloc().
Existing data stored on existing DBusDataSlotList objects with this ID will be freed when the data list is finalized, but may not be retrieved (and may only be replaced if someone else reallocates the slot). The slot value is reset to -1 if this is the last unref. allocator the allocator slot_id_p address where we store the slot
References DBusDataSlotAllocator::lock, _dbus_assert_not_reached, _dbus_assert, DBusDataSlotAllocator::allocated_slots, DBusAllocatedSlot::slot_id, DBusAllocatedSlot::refcount, DBusDataSlotAllocator::n_allocated_slots, DBusDataSlotAllocator::n_used_slots, dbus_free, NULL.
Referenced by dbus_connection_free_data_slot, _dbus_data_slot_list_free, dbus_message_free_data_slot, dbus_pending_call_free_data_slot, dbus_server_free_data_slot.
void _dbus_data_slot_list_init(DBusDataSlotList *list)
Initializes a slot list.
list the list to initialize.
References DBusDataSlotList::slots, NULL, DBusDataSlotList::n_slots.
Referenced by _dbus_connection_new_for_transport, _dbus_data_slot_list_free, dbus_message_get_reply_serial, _dbus_pending_call_new_unlocked, _dbus_server_init_base.
dbus_bool_t _dbus_data_slot_list_set(DBusDataSlotAllocator *allocator, DBusDataSlotList *list, int slot, void *data, DBusFreeFunction free_data_func, DBusFreeFunction *old_free_func, void **old_data)
Stores a pointer in the data slot list, along with an optional function to be used for freeing the data when the data is set again, or when the slot list is finalized.
The slot number must have been allocated with _dbus_data_slot_allocator_alloc() for the same allocator passed in here. The same allocator has to be used with the slot list every time. allocator the allocator to use list the data slot list slot the slot number data the data to store free_data_func finalizer function for the data old_free_func free function for any previously-existing data old_data previously-existing data, should be freed with old_free_func TRUE if there was enough memory to store the data
References DBusDataSlotAllocator::lock, _dbus_assert_not_reached, _dbus_assert, DBusDataSlotAllocator::allocated_slots, DBusAllocatedSlot::slot_id, DBusDataSlotList::n_slots, dbus_realloc, DBusDataSlotList::slots, NULL, FALSE, DBusDataSlot::data, DBusDataSlot::free_data_func, TRUE.
Referenced by dbus_connection_set_data, _dbus_data_slot_list_free, dbus_message_set_data, _dbus_pending_call_set_data_unlocked, dbus_server_set_data.
void* _dbus_data_slot_list_get(DBusDataSlotAllocator *allocator, DBusDataSlotList *list, int slot)
Retrieves data previously set with _dbus_data_slot_list_set_data().
The slot must still be allocated (must not have been freed). allocator the allocator slot was allocated from list the data slot list slot the slot to get data from the data, or NULL if not found
References DBusDataSlotAllocator::lock, _dbus_assert_not_reached, _dbus_assert, DBusDataSlotAllocator::allocated_slots, DBusAllocatedSlot::slot_id, DBusDataSlotList::n_slots, NULL, DBusDataSlotList::slots, DBusDataSlot::data.
Referenced by dbus_connection_get_data, _dbus_data_slot_list_free, dbus_message_get_data, dbus_pending_call_get_data, dbus_server_get_data.
void _dbus_data_slot_list_clear(DBusDataSlotList *list)
Frees all data slots contained in the list, calling application-provided free functions if they exist.
list the list to clear
References DBusDataSlotList::slots, DBusDataSlot::free_data_func, DBusDataSlot::data, NULL.
Referenced by _dbus_data_slot_list_free.
void _dbus_data_slot_list_free(DBusDataSlotList *list)
Frees the data slot list and all data slots contained in it, calling application-provided free functions if they exist.
list the list to free
References _dbus_data_slot_list_clear, dbus_free, DBusDataSlotList::slots, NULL, DBusDataSlotList::n_slots, _DBUS_POINTER_TO_INT, _dbus_assert, _dbus_data_slot_allocator_init, _dbus_assert_not_reached, _dbus_data_slot_list_init, _dbus_data_slot_allocator_alloc, _dbus_data_slot_list_set, _DBUS_INT_TO_POINTER, _dbus_data_slot_list_get, _dbus_data_slot_list_free, _dbus_data_slot_allocator_free, TRUE.
Referenced by dbus_connection_ref, _dbus_data_slot_list_free, dbus_message_get_reply_serial, _dbus_pending_call_ref_unlocked, _dbus_server_finalize_base.