dbus-sysdeps-unix.h
typedef struct DBusUserInfo DBusUserInfo
Information about a UNIX user.
typedef struct DBusGroupInfo DBusGroupInfo
Information about a UNIX group.
dbus_bool_t _dbus_close(int fd, DBusError *error)
Closes a file descriptor.
fd the file descriptor error error object FALSE if error set
References _dbus_error_from_errno, dbus_set_error, FALSE, TRUE.
Referenced by _dbus_become_daemon, _dbus_close_socket, _dbus_command_for_pid, _dbus_connect_tcp_socket, _dbus_connect_unix_socket, _dbus_create_file_exclusively, _dbus_file_get_contents, _dbus_full_duplex_pipe, _dbus_generate_random_bytes, _dbus_listen_systemd_sockets, _dbus_listen_tcp_socket, _dbus_listen_unix_socket, _dbus_message_iter_get_args_valist, _dbus_string_save_to_file, dbus_message_iter_append_basic.
int _dbus_dup(int fd, DBusError *error)
Duplicates a file descriptor.
Makes sure the fd returned is >= 3 (i.e. avoids stdin/stdout/stderr). Sets O_CLOEXEC. fd the file descriptor to duplicate error address of error location. duplicated file descriptor
References _dbus_error_from_errno, _dbus_fd_set_close_on_exec, dbus_set_error, FALSE, TRUE.
Referenced by _dbus_message_iter_get_args_valist, dbus_message_copy, dbus_message_iter_append_basic, dbus_message_iter_get_basic.
int _dbus_read(int fd, DBusString *buffer, int count)
Thin wrapper around the read() system call that appends the data it reads to the DBusString buffer.
It appends up to the given count, and returns the same value and same errno as read(). The only exception is that _dbus_read() handles EINTR for you. Also, _dbus_read() can return ENOMEM, even though regular UNIX read doesn't.Unlike _dbus_read_socket(), _dbus_read() is not available on Windows. fd the file descriptor to read from buffer the buffer to append data to count the amount of data to read the number of bytes read or -1
References _dbus_assert, _dbus_string_get_data_len, _dbus_string_lengthen, _dbus_string_set_length, _dbus_verbose_bytes_of_string.
Referenced by _dbus_command_for_pid, _dbus_file_get_contents, _dbus_generate_random_bytes, _dbus_get_tmpdir, _dbus_read_socket.
int _dbus_write(int fd, const DBusString *buffer, int start, int len)
Thin wrapper around the write() system call that writes a part of a DBusString and handles EINTR for you.
fd the file descriptor to write buffer the buffer to write data from start the first byte in the buffer to write len the number of bytes to try to write the number of bytes written or -1 on error
References _dbus_verbose_bytes_of_string.
Referenced by _dbus_string_save_to_file, _dbus_write_socket, _dbus_write_two.
int _dbus_write_two(int fd, const DBusString *buffer1, int start1, int len1, const DBusString *buffer2, int start2, int len2)
Like _dbus_write() but will use writev() if possible to write both buffers in sequence.
The return value is the number of bytes written in the first buffer, plus the number written in the second. If the first buffer is written successfully and an error occurs writing the second, the number of bytes in the first is returned (i.e. the error is ignored), on systems that don't have writev. Handles EINTR for you. The second buffer may be NULL. fd the file descriptor buffer1 first buffer start1 first byte to write in first buffer len1 number of bytes to write from first buffer buffer2 second buffer, or NULL start2 first byte to write in second buffer len2 number of bytes to write in second buffer total bytes written from both buffers, or -1 on error
References _dbus_assert, _dbus_write, NULL.
Referenced by _dbus_write_socket_two.
int _dbus_connect_unix_socket(const char *path, dbus_bool_t abstract, DBusError *error)
Creates a socket and connects it to the UNIX domain socket at the given path.
The connection fd is returned, and is set up as nonblocking.Uses abstract sockets instead of filesystem-linked sockets if requested (it's possible only on Linux; see "man 7 unix" on Linux). On non-Linux abstract socket usage always fails.This will set FD_CLOEXEC for the socket returned. path the path to UNIX domain socket abstract TRUE to use abstract namespace error return location for error code connection file descriptor or -1 on error
References _dbus_close, _dbus_error_from_errno, _DBUS_ZERO, DBUS_ERROR_BAD_ADDRESS, DBUS_ERROR_NOT_SUPPORTED, dbus_set_error, NULL.
Referenced by _dbus_transport_new_for_domain_socket.
int _dbus_listen_unix_socket(const char *path, dbus_bool_t abstract, DBusError *error)
Creates a socket and binds it to the given path, then listens on the socket.
The socket is set to be nonblocking.Uses abstract sockets instead of filesystem-linked sockets if requested (it's possible only on Linux; see "man 7 unix" on Linux). On non-Linux abstract socket usage always fails.This will set FD_CLOEXEC for the socket returned path the socket name abstract TRUE to use abstract namespace error return location for errors the listening file descriptor or -1 on error
References _dbus_close, _dbus_error_from_errno, _dbus_warn, _DBUS_ZERO, DBUS_ERROR_BAD_ADDRESS, DBUS_ERROR_NOT_SUPPORTED, dbus_set_error, NULL.
Referenced by _dbus_server_new_for_domain_socket.
int _dbus_connect_exec(const char *path, char *const argv[], DBusError *error)
Creates a UNIX domain socket and connects it to the specified process to execute.
This will set FD_CLOEXEC for the socket returned. path the path to the executable argv the argument list for the process to execute. argv[0] typically is identical to the path of the executable error return location for error code connection file descriptor or -1 on error
References _dbus_close_all, _dbus_error_from_errno, _dbus_fd_set_close_on_exec, dbus_set_error.
Referenced by _dbus_transport_new_for_domain_socket.
int _dbus_listen_systemd_sockets(int **fd, DBusError *error)
Acquires one or more sockets passed in from systemd.
The sockets are set to be nonblocking.This will set FD_CLOEXEC for the sockets returned. fds the file descriptors error return location for errors the number of file descriptors
References _dbus_close, _dbus_error_from_errno, DBUS_ERROR_BAD_ADDRESS, DBUS_ERROR_NO_MEMORY, DBUS_ERROR_NOT_SUPPORTED, dbus_free, dbus_new, dbus_set_error, dbus_set_error_const, NULL, TRUE.
Referenced by _dbus_server_listen_platform_specific.
dbus_bool_t _dbus_read_credentials(int client_fd, DBusCredentials *credentials, DBusError *error)
dbus_bool_t _dbus_send_credentials(int server_fd, DBusError *error)
dbus_bool_t _dbus_lookup_launchd_socket(DBusString *socket_path, const char *launchd_env_var, DBusError *error)
quries launchd for a specific env var which holds the socket path.
socket_path append the socket path to this DBusString launchd_env_var the env var to look up error a DBusError to store the error in case of failure the value of the env var
References _dbus_assert, _dbus_check_setuid, _dbus_lookup_launchd_socket, _DBUS_N_ELEMENTS, _dbus_string_append, _dbus_string_copy, _dbus_string_free, _dbus_string_init, _dbus_string_shorten, dbus_error_is_set, DBUS_ERROR_NOT_SUPPORTED, dbus_set_error, dbus_set_error_const, FALSE, NULL, TRUE.
Referenced by _dbus_lookup_launchd_socket, _dbus_transport_open_platform_specific.
dbus_bool_t _dbus_user_info_fill(DBusUserInfo *info, const DBusString *username, DBusError *error)
Gets user info for the given username.
info user info object to initialize username the username error error return TRUE on success
References DBUS_UID_UNSET.
Referenced by _dbus_user_database_lookup.
dbus_bool_t _dbus_user_info_fill_uid(DBusUserInfo *info, dbus_uid_t uid, DBusError *error)
Gets user info for the given user ID.
info user info object to initialize uid the user ID error error return TRUE on success
References NULL.
Referenced by _dbus_user_database_lookup.
void _dbus_user_info_free(DBusUserInfo *info)
Frees the members of info (but not info itself)
info the user info struct
References dbus_free, DBusUserInfo::group_ids, DBusUserInfo::homedir, DBusUserInfo::username.
Referenced by _dbus_user_info_free_allocated.
dbus_bool_t _dbus_group_info_fill(DBusGroupInfo *info, const DBusString *groupname, DBusError *error)
Initializes the given DBusGroupInfo struct with information about the given group name.
info the group info struct groupname name of group error the error return FALSE if error is set
References DBUS_GID_UNSET.
Referenced by _dbus_user_database_lookup_group.
dbus_bool_t _dbus_group_info_fill_gid(DBusGroupInfo *info, dbus_gid_t gid, DBusError *error)
Initializes the given DBusGroupInfo struct with information about the given group ID.
info the group info struct gid group ID error the error return FALSE if error is set
References NULL.
Referenced by _dbus_user_database_lookup_group.
void _dbus_group_info_free(DBusGroupInfo *info)
Frees the members of info (but not info itself).
info the group info
References dbus_free, DBusGroupInfo::groupname.
Referenced by _dbus_group_info_free_allocated.
dbus_uid_t _dbus_getuid(void)
Gets our UID.
process UID
Referenced by _dbus_user_database_lookup.
dbus_uid_t _dbus_geteuid(void)
Gets our effective UID.
process effective UID
Referenced by _dbus_append_user_from_current_process, _dbus_credentials_add_from_current_process, _dbus_unix_user_is_process_owner.
dbus_bool_t _dbus_parse_uid(const DBusString *uid_str, dbus_uid_t *uid)
Gets a UID from a UID string.
uid_str the UID in string form uid UID to fill in TRUE if successfully filled in UID
References _dbus_string_parse_int, FALSE, TRUE.
void _dbus_close_all(void)
Closes all file descriptors except the first three (i.e.
stdin, stdout, stderr).
References NULL.
Referenced by _dbus_connect_exec, _dbus_get_tmpdir.
dbus_bool_t _dbus_append_address_from_socket(int fd, DBusString *address, DBusError *error)
Read the address from the socket and append it to the string.
fd the socket address error return location for error code
References _dbus_address_append_escaped, _dbus_error_from_errno, _dbus_string_append, _dbus_string_append_printf, _dbus_string_init_const, dbus_set_error, FALSE, TRUE.
Referenced by _dbus_server_listen_platform_specific.
void _dbus_fd_set_close_on_exec(int fd)
Sets the file descriptor to be close on exec.
Should be called for all file descriptors in D-Bus code. fd the file descriptor
Referenced by _dbus_accept, _dbus_connect_exec, _dbus_dup, _dbus_full_duplex_pipe, _dbus_read_socket_with_unix_fds, _dbus_server_new_for_launchd.