dbus-sha.c
static void SHATransform(dbus_uint32_t *digest, dbus_uint32_t *data)
static void swap_words(dbus_uint32_t *buffer, int byte_count)
static void sha_init(DBusSHAContext *context)
static void sha_append(DBusSHAContext *context, const unsigned char *buffer, unsigned int count)
static void sha_finish(DBusSHAContext *context, unsigned char digest[20])
void _dbus_sha_init(DBusSHAContext *context)
Initializes the SHA context.
context an uninitialized context, typically on the stack.
Referenced by _dbus_sha_compute.
void _dbus_sha_update(DBusSHAContext *context, const DBusString *data)
Feeds more data into an existing shasum computation.
context the SHA context data the additional data to hash
Referenced by _dbus_sha_compute.
dbus_bool_t _dbus_sha_final(DBusSHAContext *context, DBusString *results)
SHA finalization.
Ends an SHA message-digest operation, writing the the message digest and zeroing the context. The results are returned as a raw 20-byte digest, not as the ascii-hex-digits string form of the digest. context the SHA context results string to append the 20-byte SHA digest to FALSE if not enough memory to append the digest
References _dbus_string_append_len, _DBUS_ZERO, FALSE, TRUE.
Referenced by _dbus_sha_compute.
dbus_bool_t _dbus_sha_compute(const DBusString *data, DBusString *ascii_output)
Computes the ASCII hex-encoded shasum of the given data and appends it to the output string.
data input data to be hashed ascii_output string to append ASCII shasum to FALSE if not enough memory
References _dbus_assert_not_reached, _dbus_concat_dir_and_file, _dbus_file_get_contents, _dbus_sha_compute, _dbus_sha_final, _dbus_sha_init, _dbus_sha_update, _dbus_string_append, _dbus_string_append_byte, _dbus_string_delete, _dbus_string_equal, _dbus_string_find, _dbus_string_free, _dbus_string_hex_encode, _dbus_string_init, _dbus_string_init_const, _dbus_string_init_const_len, _dbus_string_move, _dbus_string_parse_int, _dbus_string_pop_line, _dbus_string_set_length, _dbus_string_skip_blank, _dbus_string_starts_with_c_str, _dbus_warn, dbus_error_free, DBUS_ERROR_INIT, FALSE, DBusError::message, NULL, TRUE.
Referenced by _dbus_read_local_machine_uuid, _dbus_sha_compute.