dbus-auth.h
DBusAuthState
typedef struct DBusAuth DBusAuth
DBusAuth* _dbus_auth_server_new(const DBusString *guid)
Creates a new auth conversation object for the server side.
See http://dbus.freedesktop.org/doc/dbus-specification.html#auth-protocol for full details on what this object does.the new object or NULL if no memory
References _dbus_string_init, NULL, _dbus_string_copy, _dbus_string_free, DBusAuth::side, DBusAuth::state, DBUS_AUTH_SERVER, DBusAuthServer::guid, DBusAuthServer::failures, DBusAuthServer::max_failures.
Referenced by _dbus_transport_init_base.
DBusAuth* _dbus_auth_client_new(void)
Creates a new auth conversation object for the client side.
See http://dbus.freedesktop.org/doc/dbus-specification.html#auth-protocol for full details on what this object does.the new object or NULL if no memory
References _dbus_string_init, NULL, _dbus_string_free, DBUS_AUTH_CLIENT, DBusAuth::side, DBusAuth::state, _dbus_auth_unref.
Referenced by _dbus_transport_init_base.
DBusAuth* _dbus_auth_ref(DBusAuth *auth)
Increments the refcount of an auth object.
auth the auth conversation the auth conversation
References _dbus_assert, NULL, DBusAuth::refcount.
void _dbus_auth_unref(DBusAuth *auth)
Decrements the refcount of an auth object.
auth the auth conversation
References _dbus_assert, NULL, DBusAuth::refcount, DBUS_AUTH_IS_CLIENT, _dbus_string_free, DBUS_AUTH_CLIENT, _dbus_list_clear, DBUS_AUTH_IS_SERVER, DBUS_AUTH_SERVER, DBusAuth::keyring, _dbus_keyring_unref, DBusAuth::context, DBusAuth::challenge, DBusAuth::identity, DBusAuth::incoming, DBusAuth::outgoing, dbus_free_string_array, DBusAuth::allowed_mechs, _dbus_credentials_unref, DBusAuth::credentials, DBusAuth::authorized_identity, DBusAuth::desired_identity, dbus_free.
Referenced by _dbus_auth_client_new, _dbus_transport_init_base, _dbus_transport_finalize_base.
dbus_bool_t _dbus_auth_set_mechanisms(DBusAuth *auth, const char **mechanisms)
Sets an array of authentication mechanism names that we are willing to use.
auth the auth conversation mechanisms NULL-terminated array of mechanism names FALSE if no memory
References NULL, _dbus_dup_string_array, FALSE, dbus_free_string_array, DBusAuth::allowed_mechs, TRUE.
Referenced by _dbus_transport_set_auth_mechanisms.
DBusAuthState _dbus_auth_do_work(DBusAuth *auth)
Analyzes buffered input and moves the auth conversation forward, returning the new state of the auth conversation.
auth the auth conversation the new state
References DBusAuth::needed_memory, FALSE, DBUS_AUTH_IN_END_STATE, DBusAuth::incoming, DBusAuth::outgoing, DBUS_AUTH_NAME, DBusAuth::state.
Referenced by _dbus_transport_try_to_authenticate, _dbus_transport_get_dispatch_status.
dbus_bool_t _dbus_auth_get_bytes_to_send(DBusAuth *auth, const DBusString **str)
Gets bytes that need to be sent to the peer we're conversing with.
After writing some bytes, _dbus_auth_bytes_sent() must be called to notify the auth object that they were written. auth the auth conversation str return location for a ref to the buffer to send FALSE if nothing to send
References _dbus_assert, NULL, DBusAuth::outgoing, FALSE, TRUE.
void _dbus_auth_bytes_sent(DBusAuth *auth, int bytes_sent)
Notifies the auth conversation object that the given number of bytes of the outgoing buffer have been written out.
auth the auth conversation bytes_sent number of bytes written out
References DBUS_AUTH_NAME, DBusAuth::outgoing, _dbus_string_delete.
void _dbus_auth_get_buffer(DBusAuth *auth, DBusString **buffer)
Get a buffer to be used for reading bytes from the peer we're conversing with.
Bytes should be appended to this buffer. auth the auth conversation buffer return location for buffer to append bytes to
References _dbus_assert, NULL, DBusAuth::buffer_outstanding, DBusAuth::incoming, TRUE.
void _dbus_auth_return_buffer(DBusAuth *auth, DBusString *buffer)
Returns a buffer with new data read into it.
auth the auth conversation buffer the buffer being returned
References _dbus_assert, DBusAuth::incoming, DBusAuth::buffer_outstanding, FALSE.
void _dbus_auth_get_unused_bytes(DBusAuth *auth, const DBusString **str)
Returns leftover bytes that were not used as part of the auth conversation.
These bytes will be part of the message stream instead. This function may not be called until authentication has succeeded. auth the auth conversation str return location for pointer to string of unused bytes
References DBUS_AUTH_IN_END_STATE, DBusAuth::incoming.
Referenced by _dbus_transport_do_iteration.
void _dbus_auth_delete_unused_bytes(DBusAuth *auth)
Gets rid of unused bytes returned by _dbus_auth_get_unused_bytes() after we've gotten them and successfully moved them elsewhere.
auth the auth conversation
References DBUS_AUTH_IN_END_STATE, _dbus_string_set_length, DBusAuth::incoming.
Referenced by _dbus_transport_do_iteration.
dbus_bool_t _dbus_auth_needs_encoding(DBusAuth *auth)
Called post-authentication, indicates whether we need to encode the message stream with _dbus_auth_encode_data() prior to sending it to the peer.
auth the auth conversation TRUE if we need to encode the stream
References DBusAuth::state, FALSE, DBusAuth::mech, NULL, DBUS_AUTH_IS_CLIENT, DBusAuthMechanismHandler::client_encode_func, DBusAuthMechanismHandler::server_encode_func.
Referenced by _dbus_auth_encode_data.
dbus_bool_t _dbus_auth_encode_data(DBusAuth *auth, const DBusString *plaintext, DBusString *encoded)
Called post-authentication, encodes a block of bytes for sending to the peer.
If no encoding was negotiated, just copies the bytes (you can avoid this by checking _dbus_auth_needs_encoding()). auth the auth conversation plaintext the plain text data encoded initialized string to where encoded data is appended TRUE if we had enough memory and successfully encoded
References _dbus_assert, DBusAuth::state, FALSE, _dbus_auth_needs_encoding, DBUS_AUTH_IS_CLIENT, DBusAuth::mech, DBusAuthMechanismHandler::client_encode_func, DBusAuthMechanismHandler::server_encode_func, _dbus_string_copy.
dbus_bool_t _dbus_auth_needs_decoding(DBusAuth *auth)
Called post-authentication, indicates whether we need to decode the message stream with _dbus_auth_decode_data() after receiving it from the peer.
auth the auth conversation TRUE if we need to encode the stream
References DBusAuth::state, FALSE, DBusAuth::mech, NULL, DBUS_AUTH_IS_CLIENT, DBusAuthMechanismHandler::client_decode_func, DBusAuthMechanismHandler::server_decode_func.
Referenced by _dbus_auth_decode_data, _dbus_transport_do_iteration.
dbus_bool_t _dbus_auth_decode_data(DBusAuth *auth, const DBusString *encoded, DBusString *plaintext)
Called post-authentication, decodes a block of bytes received from the peer.
If no encoding was negotiated, just copies the bytes (you can avoid this by checking _dbus_auth_needs_decoding()).Todo1.0? We need to be able to distinguish "out of memory" error from "the data is hosed" error. auth the auth conversation encoded the encoded data plaintext initialized string where decoded data is appended TRUE if we had enough memory and successfully decoded
References _dbus_assert, DBusAuth::state, FALSE, _dbus_auth_needs_decoding, DBUS_AUTH_IS_CLIENT, DBusAuth::mech, DBusAuthMechanismHandler::client_decode_func, DBusAuthMechanismHandler::server_decode_func, _dbus_string_copy.
Referenced by _dbus_transport_do_iteration.
dbus_bool_t _dbus_auth_set_credentials(DBusAuth *auth, DBusCredentials *credentials)
Sets credentials received via reliable means from the operating system.
auth the auth conversation credentials the credentials received FALSE on OOM
References _dbus_credentials_clear, DBusAuth::credentials, _dbus_credentials_add_credentials.
DBusCredentials* _dbus_auth_get_identity(DBusAuth *auth)
Gets the identity we authorized the client as.
Apps may have different policies as to what identities they allow.Returned credentials are not a copy and should not be modified auth the auth conversation the credentials we've authorized BY REFERENCE do not modify
References DBusAuth::state, DBusAuth::authorized_identity, _dbus_assert, _dbus_credentials_are_empty.
Referenced by _dbus_transport_get_is_connected, _dbus_transport_try_to_authenticate, _dbus_transport_get_is_anonymous, _dbus_transport_get_unix_user, _dbus_transport_get_unix_process_id, _dbus_transport_get_adt_audit_session_data, _dbus_transport_get_windows_user.
dbus_bool_t _dbus_auth_set_context(DBusAuth *auth, const DBusString *context)
Sets the "authentication context" which scopes cookies with the DBUS_COOKIE_SHA1 auth mechanism for example.
auth the auth conversation context the context FALSE if no memory
References _dbus_string_replace_len, DBusAuth::context.
const char* _dbus_auth_get_guid_from_server(DBusAuth *auth)
Gets the GUID from the server if we've authenticated; gets NULL otherwise.
auth the auth object the GUID in ASCII hex format
References _dbus_assert, DBUS_AUTH_IS_CLIENT, DBusAuth::state, DBUS_AUTH_CLIENT, NULL.
Referenced by _dbus_transport_try_to_authenticate, _dbus_transport_get_server_id.
void _dbus_auth_set_unix_fd_possible(DBusAuth *auth, dbus_bool_t b)
Sets whether unix fd passing is potentially on the transport and hence shall be negotiated.
auth the auth conversation b TRUE when unix fd passing shall be negotiated, otherwise FALSE
References DBusAuth::unix_fd_possible.
Referenced by _dbus_transport_new_for_socket.
dbus_bool_t _dbus_auth_get_unix_fd_negotiated(DBusAuth *auth)
Queries whether unix fd passing was successfully negotiated.
auth the auth conversion TRUE when unix fd passing was negotiated.
References DBusAuth::unix_fd_negotiated.