dbus-string-util.c
DBUS_CAN_USE_DBUS_STRING_PRIVATE
dbus_bool_t _dbus_string_ends_with_c_str(const DBusString *a, const char *c_str)
Returns whether a string ends with the given suffix.
Todomemcmp might make this faster. a the string c_str the C-style string TRUE if the string ends with the suffix
References _dbus_assert, DBUS_GENERIC_STRING_PREAMBLE, FALSE, DBusRealString::len, NULL, DBusRealString::str, TRUE.
Referenced by _dbus_directory_open.
dbus_bool_t _dbus_string_find_byte_backward(const DBusString *str, int start, unsigned char byte, int *found)
Find the given byte scanning backward from the given start.
Sets *found to -1 if the byte is not found. str the string start the place to start scanning (will not find the byte at this point) byte the byte to find found return location for where it was found TRUE if found
References _dbus_assert, _dbus_assert_not_reached, _DBUS_N_ELEMENTS, _dbus_string_append, _dbus_string_append_byte, _dbus_string_append_int, _dbus_string_append_len, _dbus_string_compact, _dbus_string_copy, _dbus_string_equal, _dbus_string_equal_c_str, _dbus_string_equal_substring, _dbus_string_find, _dbus_string_find_byte_backward, _dbus_string_find_eol, _dbus_string_find_to, _dbus_string_free, _dbus_string_hex_decode, _dbus_string_hex_encode, _dbus_string_init, _dbus_string_init_const, _dbus_string_insert_bytes, _dbus_string_move, _dbus_string_parse_int, _dbus_string_pop_line, _dbus_string_replace_len, _dbus_string_set_length, _dbus_string_shorten, _dbus_string_split_on_byte, _dbus_string_steal_data, _dbus_string_tolower_ascii, _dbus_string_toupper_ascii, DBUS_CONST_STRING_PREAMBLE, dbus_free, NULL, TRUE.
Referenced by _dbus_directory_close, _dbus_string_find_byte_backward, _dbus_string_get_dirname.