dbus-marshal-validate.c
VALID_INITIAL_NAME_CHARACTER
Determine wether the given character is valid as the first character in a name.
Referenced by _dbus_validate_interface, _dbus_validate_member.
VALID_NAME_CHARACTER
Determine wether the given character is valid as a second or later character in a name.
Referenced by _dbus_validate_interface, _dbus_validate_member, _dbus_validate_path.
VALID_INITIAL_BUS_NAME_CHARACTER
Determine wether the given character is valid as the first character in a bus name.
VALID_BUS_NAME_CHARACTER
Determine wether the given character is valid as a second or later character in a bus name.
DBusValidity _dbus_validate_signature_with_reason(const DBusString *type_str, int type_pos, int len)
Verifies that the range of type_str from type_pos to type_end is a valid signature.
If this function returns TRUE, it will be safe to iterate over the signature with a types-only DBusTypeReader. The range passed in should NOT include the terminating nul/DBUS_TYPE_INVALID. type_str the string type_pos where the typecodes start len length of typecodes DBUS_VALID if valid, reason why invalid otherwise
References _dbus_assert, _dbus_assert_not_reached, _dbus_first_type_in_signature, _DBUS_INT32_MAX, _DBUS_INT_TO_POINTER, _dbus_list_append, _dbus_list_clear, _dbus_list_pop_last, _DBUS_POINTER_TO_INT, _dbus_string_init_const_len, _dbus_string_validate_utf8, _dbus_type_get_alignment, _dbus_type_reader_get_current_type, _dbus_type_reader_get_element_type, _dbus_type_reader_init_types_only, _dbus_type_reader_next, _dbus_type_reader_recurse, _dbus_type_to_string, _dbus_unpack_uint32, _dbus_validate_path, DBUS_DICT_ENTRY_BEGIN_CHAR, DBUS_DICT_ENTRY_END_CHAR, DBUS_MAXIMUM_ARRAY_LENGTH, DBUS_MAXIMUM_SIGNATURE_LENGTH, DBUS_MAXIMUM_TYPE_RECURSION_DEPTH, DBUS_STRUCT_BEGIN_CHAR, DBUS_STRUCT_END_CHAR, DBUS_TYPE_ARRAY, DBUS_TYPE_BOOLEAN, DBUS_TYPE_BYTE, DBUS_TYPE_DICT_ENTRY, DBUS_TYPE_DOUBLE, DBUS_TYPE_INT16, DBUS_TYPE_INT32, DBUS_TYPE_INT64, DBUS_TYPE_INVALID, dbus_type_is_basic, dbus_type_is_fixed, dbus_type_is_valid, DBUS_TYPE_OBJECT_PATH, DBUS_TYPE_SIGNATURE, DBUS_TYPE_STRING, DBUS_TYPE_STRUCT, DBUS_TYPE_UINT16, DBUS_TYPE_UINT32, DBUS_TYPE_UINT64, DBUS_TYPE_UNIX_FD, DBUS_TYPE_VARIANT, DBUS_VALID, DBUS_VALIDITY_UNKNOWN_OOM_ERROR, FALSE, NULL, TRUE, DBusTypeReader::type_pos.
Referenced by _dbus_validate_signature, dbus_signature_validate.
static DBusValidity validate_body_helper(DBusTypeReader *reader, int byte_order, dbus_bool_t walk_reader_to_end, int total_depth, const unsigned char *p, const unsigned char *end, const unsigned char **new_p)
DBusValidity _dbus_validate_body_with_reason(const DBusString *expected_signature, int expected_signature_start, int byte_order, int *bytes_remaining, const DBusString *value_str, int value_pos, int len)
Verifies that the range of value_str from value_pos to value_end is a legitimate value of type expected_signature.
If this function returns TRUE, it will be safe to iterate over the values with DBusTypeReader. The signature is assumed to be already valid.If bytes_remaining is not NULL, then leftover bytes will be stored there and DBUS_VALID returned. If it is NULL, then DBUS_INVALID_TOO_MUCH_DATA will be returned if bytes are left over. expected_signature the expected types in the value_str expected_signature_start where in expected_signature is the signature byte_order the byte order bytes_remaining place to store leftover bytes value_str the string containing the body value_pos where the values start len length of values after value_pos DBUS_VALID if valid, reason why invalid otherwise
References _dbus_assert, _dbus_type_reader_init_types_only, DBUS_INVALID_TOO_MUCH_DATA, DBUS_VALID, TRUE.
Referenced by _dbus_header_load, _dbus_message_loader_return_unix_fds.
dbus_bool_t _dbus_validate_path(const DBusString *str, int start, int len)
Checks that the given range of the string is a valid object path name in the D-Bus protocol.
Part of the validation ensures that the object path contains only ASCII.Todothis is inconsistent with most of DBusString in that it allows a start,len range that extends past the string end.Todochange spec to disallow more things, such as spaces in the path name str the string start first byte index to check len number of bytes to check TRUE if the byte range exists and is a valid name
References _dbus_assert, DBUS_INVALID_TOO_MUCH_DATA, DBUS_VALID, DBUS_VALIDITY_UNKNOWN_OOM_ERROR, FALSE, TRUE, VALID_NAME_CHARACTER.
Referenced by _dbus_validate_signature_with_reason, dbus_validate_path.
const char * _dbus_validity_to_error_message(DBusValidity validity)
dbus_bool_t _dbus_validate_interface(const DBusString *str, int start, int len)
Checks that the given range of the string is a valid interface name in the D-Bus protocol.
This includes a length restriction and an ASCII subset, see the specification.Todothis is inconsistent with most of DBusString in that it allows a start,len range that extends past the string end. str the string start first byte index to check len number of bytes to check TRUE if the byte range exists and is a valid name
References _dbus_assert, DBUS_MAXIMUM_NAME_LENGTH, FALSE, NULL, TRUE, VALID_INITIAL_NAME_CHARACTER, VALID_NAME_CHARACTER.
Referenced by _dbus_header_have_message_untrusted, _dbus_validate_error_name, dbus_validate_interface.
dbus_bool_t _dbus_validate_member(const DBusString *str, int start, int len)
Checks that the given range of the string is a valid member name in the D-Bus protocol.
This includes a length restriction, etc., see the specification.Todothis is inconsistent with most of DBusString in that it allows a start,len range that extends past the string end. str the string start first byte index to check len number of bytes to check TRUE if the byte range exists and is a valid name
References _dbus_assert, DBUS_MAXIMUM_NAME_LENGTH, FALSE, TRUE, VALID_INITIAL_NAME_CHARACTER, VALID_NAME_CHARACTER.
Referenced by _dbus_header_have_message_untrusted, dbus_validate_member.
dbus_bool_t _dbus_validate_error_name(const DBusString *str, int start, int len)
Checks that the given range of the string is a valid error name in the D-Bus protocol.
This includes a length restriction, etc., see the specification.Todothis is inconsistent with most of DBusString in that it allows a start,len range that extends past the string end. str the string start first byte index to check len number of bytes to check TRUE if the byte range exists and is a valid name
References _dbus_validate_interface.
Referenced by _dbus_header_have_message_untrusted, dbus_validate_error_name.
static dbus_bool_t _dbus_validate_bus_name_full(const DBusString *str, int start, int len, dbus_bool_t is_namespace)
dbus_bool_t _dbus_validate_bus_name(const DBusString *str, int start, int len)
Checks that the given range of the string is a valid bus name in the D-Bus protocol.
This includes a length restriction, etc., see the specification.Todothis is inconsistent with most of DBusString in that it allows a start,len range that extends past the string end. str the string start first byte index to check len number of bytes to check TRUE if the byte range exists and is a valid name
References FALSE.
Referenced by _dbus_header_have_message_untrusted, dbus_validate_bus_name.
dbus_bool_t _dbus_validate_bus_namespace(const DBusString *str, int start, int len)
Checks that the given range of the string is a prefix of a valid bus name in the D-Bus protocol.
Unlike _dbus_validate_bus_name(), this accepts strings with only one period-separated component.Todothis is inconsistent with most of DBusString in that it allows a start,len range that extends past the string end. str the string start first byte index to check len number of bytes to check TRUE if the byte range exists and is a valid name
References TRUE.
dbus_bool_t _dbus_validate_signature(const DBusString *str, int start, int len)
Checks that the given range of the string is a valid message type signature in the D-Bus protocol.
Todothis is inconsistent with most of DBusString in that it allows a start,len range that extends past the string end. str the string start first byte index to check len number of bytes to check TRUE if the byte range exists and is a valid signature
References _dbus_assert, _dbus_validate_signature_with_reason, DBUS_VALID, DEFINE_DBUS_NAME_CHECK, FALSE.