dbus-pending-call-internal.h
dbus_bool_t _dbus_pending_call_is_timeout_added_unlocked(DBusPendingCall *pending)
Checks to see if a timeout has been added.
pending the pending_call TRUE if there is a timeout or FALSE if not
References _dbus_assert, NULL, DBusPendingCall::timeout_added.
Referenced by _dbus_connection_queue_received_message_link, _dbus_connection_toggle_timeout_unlocked, _dbus_connection_close_if_only_one_ref.
void _dbus_pending_call_set_timeout_added_unlocked(DBusPendingCall *pending, dbus_bool_t is_added)
Sets wether the timeout has been added.
pending the pending_call is_added whether or not a timeout is added
References _dbus_assert, NULL, DBusPendingCall::timeout_added.
Referenced by _dbus_connection_queue_received_message_link, _dbus_connection_toggle_timeout_unlocked, _dbus_connection_close_if_only_one_ref, dbus_connection_send.
DBusTimeout* _dbus_pending_call_get_timeout_unlocked(DBusPendingCall *pending)
Retrives the timeout.
pending the pending_call a timeout object or NULL if call has no timeout
References _dbus_assert, NULL, DBusPendingCall::timeout.
Referenced by _dbus_connection_queue_received_message_link, _dbus_connection_toggle_timeout_unlocked, _dbus_connection_close_if_only_one_ref, _dbus_connection_block_pending_call, dbus_connection_send.
dbus_uint32_t _dbus_pending_call_get_reply_serial_unlocked(DBusPendingCall *pending)
Gets the reply's serial number.
pending the pending_call a serial number for the reply or 0
References _dbus_assert, NULL, DBusPendingCall::reply_serial.
Referenced by _dbus_connection_toggle_timeout_unlocked, _dbus_connection_do_iteration_unlocked, _dbus_connection_close_if_only_one_ref, _dbus_connection_block_pending_call.
void _dbus_pending_call_set_reply_serial_unlocked(DBusPendingCall *pending, dbus_uint32_t serial)
Sets the reply's serial number.
pending the pending_call serial the serial number
References _dbus_assert, NULL, DBusPendingCall::reply_serial.
Referenced by _dbus_pending_call_set_timeout_error_unlocked.
DBusConnection* _dbus_pending_call_get_connection_and_lock(DBusPendingCall *pending)
Gets the connection associated with this pending call.
pending the pending_call the connection associated with the pending call
References _dbus_assert, NULL, CONNECTION_LOCK, DBusPendingCall::connection.
Referenced by _dbus_connection_block_pending_call, dbus_connection_send.
DBusConnection* _dbus_pending_call_get_connection_unlocked(DBusPendingCall *pending)
Gets the connection associated with this pending call.
pending the pending_call the connection associated with the pending call
References _dbus_assert, NULL, DBusPendingCall::connection.
Referenced by _dbus_connection_toggle_timeout_unlocked.
dbus_bool_t _dbus_pending_call_get_completed_unlocked(DBusPendingCall *pending)
Checks whether the pending call has received a reply yet, or not.
Assumes connection lock is held. pending the pending call TRUE if a reply has been received
References DBusPendingCall::completed, _DBUS_LOCK_NAME.
Referenced by _dbus_connection_do_iteration_unlocked, _dbus_connection_block_pending_call.
void _dbus_pending_call_complete(DBusPendingCall *pending)
Calls notifier function for the pending call and sets the call to completed.
pending the pending call
References _dbus_assert, DBusPendingCall::completed, TRUE, DBusPendingCall::function, dbus_pending_call_get_data.
Referenced by _dbus_connection_close_if_only_one_ref.
void _dbus_pending_call_set_reply_unlocked(DBusPendingCall *pending, DBusMessage *message)
Sets the reply of a pending call with the given message, or if the message is NULL, by timing out the pending call.
pending the pending call message the message to complete the call with, or NULL to time out the call
References NULL, DBusPendingCall::timeout_link, DBusList::data, _dbus_list_clear, dbus_message_ref, dbus_message_get_type, DBUS_MESSAGE_TYPE_METHOD_RETURN, DBUS_MESSAGE_TYPE_ERROR, DBusPendingCall::reply_serial, _dbus_assert, DBusPendingCall::reply, dbus_message_get_reply_serial.
Referenced by _dbus_connection_close_if_only_one_ref.
void _dbus_pending_call_queue_timeout_error_unlocked(DBusPendingCall *pending, DBusConnection *connection)
If the pending call hasn't been timed out, add its timeout error reply to the connection's incoming message queue.
pending the pending call connection the connection the call was sent to
References _dbus_assert, DBusPendingCall::connection, DBusPendingCall::timeout_link, _dbus_connection_queue_synthesized_message_link, NULL.
Referenced by _dbus_connection_close_if_only_one_ref, dbus_connection_send.
dbus_bool_t _dbus_pending_call_set_timeout_error_unlocked(DBusPendingCall *pending, DBusMessage *message, dbus_uint32_t serial)
Sets the reply message associated with the pending call to a timeout error.
pending the pending_call message the message we are sending the error reply to serial serial number for the reply FALSE on OOM
References DBusPendingCall::reply, dbus_message_new_error, DBUS_ERROR_NO_REPLY, NULL, FALSE, _dbus_list_alloc_link, dbus_message_unref, DBusPendingCall::timeout_link, _dbus_pending_call_set_reply_serial_unlocked, TRUE.
Referenced by dbus_connection_send_with_reply.
DBusPendingCall* _dbus_pending_call_new_unlocked(DBusConnection *connection, int timeout_milliseconds, DBusTimeoutHandler timeout_handler)
Creates a new pending reply object.
connection connection where reply will arrive timeout_milliseconds length of timeout, -1 (or DBUS_TIMEOUT_USE_DEFAULT) for default, DBUS_TIMEOUT_INFINITE for no timeout timeout_handler timeout handler, takes pending call as data a new DBusPendingCall or NULL if no memory.
References DBusPendingCall::timeout, _dbus_assert, dbus_pending_call_allocate_data_slot, NULL, dbus_new0, dbus_pending_call_free_data_slot, DBUS_TIMEOUT_INFINITE, _dbus_timeout_new, dbus_free, _dbus_atomic_inc, DBusPendingCall::refcount, DBusPendingCall::connection, _dbus_connection_ref_unlocked, _dbus_data_slot_list_init, DBusPendingCall::slot_list.
Referenced by dbus_connection_send_with_reply.
DBusPendingCall* _dbus_pending_call_ref_unlocked(DBusPendingCall *pending)
Increments the reference count on a pending call, while the lock on its connection is already held.
pending the pending call object the pending call object
References _dbus_atomic_inc, DBusPendingCall::refcount, DBusPendingCall::connection, _dbus_assert, DBusPendingCall::timeout_added, _dbus_data_slot_list_free, DBusPendingCall::slot_list, DBusPendingCall::timeout, NULL, _dbus_timeout_unref, DBusPendingCall::timeout_link, dbus_message_unref, DBusList::data, _dbus_list_free_link, DBusPendingCall::reply, dbus_free, dbus_pending_call_free_data_slot, dbus_connection_unref.
Referenced by _dbus_connection_toggle_timeout_unlocked, _dbus_connection_close_if_only_one_ref.
void _dbus_pending_call_unref_and_unlock(DBusPendingCall *pending)
Decrements the reference count on a pending call, freeing it if the count reaches 0.
Assumes connection lock is already held. pending the pending call object
References _dbus_atomic_dec, DBusPendingCall::refcount, _dbus_assert, CONNECTION_UNLOCK, DBusPendingCall::connection.
Referenced by _dbus_connection_toggle_timeout_unlocked, _dbus_connection_close_if_only_one_ref.
dbus_bool_t _dbus_pending_call_set_data_unlocked(DBusPendingCall *pending, dbus_int32_t slot, void *data, DBusFreeFunction free_data_func)
Stores a pointer on a DBusPendingCall, along with an optional function to be used for freeing the data when the data is set again, or when the pending call is finalized.
The slot number must have been allocated with dbus_pending_call_allocate_data_slot(). pending the pending_call slot the slot number data the data to store free_data_func finalizer function for the data TRUE if there was enough memory to store the data
References _dbus_data_slot_list_set, DBusPendingCall::slot_list, CONNECTION_UNLOCK, DBusPendingCall::connection, CONNECTION_LOCK.
Referenced by dbus_pending_call_set_notify, dbus_pending_call_set_data.