dbus-list.c
DBusMemPool* list_pool
static DBusList* alloc_link(void *data)
static void free_link(DBusList *link)
static void link_before(DBusList **list, DBusList *before_this_link, DBusList *link)
static void link_after(DBusList **list, DBusList *after_this_link, DBusList *link)
DBusList* _dbus_list_alloc_link(void *data)
Allocates a linked list node.
Useful for preallocating nodes and using _dbus_list_append_link() to avoid allocations. data the value to store in the link. a newly allocated link.
Referenced by _dbus_connection_close_possibly_shared, _dbus_connection_new_for_transport, _dbus_message_add_counter, _dbus_pending_call_set_timeout_error_unlocked, dbus_connection_dispatch, dbus_connection_get_dispatch_status.
void _dbus_list_free_link(DBusList *link)
Frees a linked list node allocated with _dbus_list_alloc_link.
Does not free the data in the node. link the list node
Referenced by _dbus_connection_close_possibly_shared, _dbus_connection_new_for_transport, _dbus_connection_unlock, _dbus_list_length_is_one, _dbus_pending_call_ref_unlocked, dbus_connection_dispatch, dbus_connection_free_preallocated_send, dbus_connection_get_dispatch_status, dbus_connection_ref, dbus_connection_steal_borrowed_message.
dbus_bool_t _dbus_list_append(DBusList **list, void *data)
Appends a value to the list.
May return FALSE if insufficient memory exists to add a list link. This is a constant-time operation. list address of the list head. data the value to append. TRUE on success.
References _dbus_list_prepend, FALSE, DBusList::next, TRUE.
Referenced by _dbus_list_copy, _dbus_list_length_is_one, _dbus_message_loader_return_unix_fds, _dbus_object_tree_dispatch_and_unlock, _dbus_split_paths_and_append, _dbus_timeout_list_add_timeout, _dbus_type_writer_write_fixed_multi, _dbus_validate_signature_with_reason, _dbus_watch_list_add_watch, dbus_connection_add_filter, dbus_parse_address.
dbus_bool_t _dbus_list_prepend(DBusList **list, void *data)
Prepends a value to the list.
May return FALSE if insufficient memory exists to add a list link. This is a constant-time operation. list address of the list head. data the value to prepend. TRUE on success.
References FALSE, NULL, TRUE.
Referenced by _dbus_connection_handle_watch, _dbus_list_append, _dbus_list_insert_after, _dbus_list_length_is_one.
void _dbus_list_append_link(DBusList **list, DBusList *link)
Appends a link to the list.
Cannot fail due to out of memory. This is a constant-time operation. list address of the list head. link the link to append.
References _dbus_list_prepend_link, DBusList::next.
Referenced by _dbus_connection_queue_received_message_link, _dbus_connection_queue_synthesized_message_link, _dbus_list_insert_before_link, _dbus_message_add_counter_link.
void _dbus_list_prepend_link(DBusList **list, DBusList *link)
Prepends a link to the list.
Cannot fail due to out of memory. This is a constant-time operation. list address of the list head. link the link to prepend.
Referenced by _dbus_connection_close_possibly_shared, _dbus_connection_message_sent_unlocked, _dbus_list_append_link, _dbus_list_insert_after_link, _dbus_message_loader_putback_message_link, dbus_connection_dispatch, dbus_connection_get_dispatch_status, dbus_connection_pop_message, dbus_connection_steal_borrowed_message.
dbus_bool_t _dbus_list_insert_after(DBusList **list, DBusList *after_this_link, void *data)
Inserts data into the list after the given existing link.
list the list to modify after_this_link existing link to insert after, or NULL to prepend data the value to insert TRUE on success, FALSE if memory allocation fails
References _dbus_list_prepend, FALSE, NULL, TRUE.
Referenced by _dbus_list_length_is_one.
void _dbus_list_insert_before_link(DBusList **list, DBusList *before_this_link, DBusList *link)
Inserts a link into the list before the given existing link.
list the list to modify before_this_link existing link to insert before, or NULL to append link the link to insert
References _dbus_list_append_link, NULL.
void _dbus_list_insert_after_link(DBusList **list, DBusList *after_this_link, DBusList *link)
Inserts a link into the list after the given existing link.
list the list to modify after_this_link existing link to insert after, or NULL to prepend link the link to insert
References _dbus_list_prepend_link, NULL.
dbus_bool_t _dbus_list_remove(DBusList **list, void *data)
Removes a value from the list.
Only removes the first value equal to the given data pointer, even if multiple values exist which match. This is a linear-time operation. list address of the list head. data the value to remove. TRUE if a value was found to remove.
References _dbus_list_get_next_link, _dbus_list_remove_link, DBusList::data, FALSE, NULL, TRUE.
Referenced by _dbus_connection_handle_watch, _dbus_list_length_is_one, _dbus_timeout_list_remove_timeout, _dbus_watch_list_remove_watch.
dbus_bool_t _dbus_list_remove_last(DBusList **list, void *data)
Removes a value from the list.
Only removes the last value equal to the given data pointer, even if multiple values exist which match. This is a linear-time operation. list address of the list head. data the value to remove. TRUE if a value was found to remove.
References _dbus_list_find_last, _dbus_list_remove_link, FALSE, TRUE.
Referenced by _dbus_list_length_is_one, _dbus_message_loader_return_unix_fds, _dbus_timeout_list_add_timeout, _dbus_watch_list_add_watch.
DBusList* _dbus_list_find_last(DBusList **list, void *data)
Finds a value in the list.
Returns the last link with value equal to the given data pointer. This is a linear-time operation. Returns NULL if no value found that matches. list address of the list head. data the value to find. the link if found
References _dbus_list_get_last_link, _dbus_list_get_prev_link, DBusList::data, NULL.
Referenced by _dbus_list_remove_last, _dbus_message_loader_queue_messages, _dbus_message_loader_return_unix_fds, _dbus_message_remove_counter.
void _dbus_list_unlink(DBusList **list, DBusList *link)
Removes the given link from the list, but doesn't free it.
_dbus_list_remove_link() both removes the link and also frees it. list the list link the link in the list
References DBusList::next, NULL, DBusList::prev.
Referenced by _dbus_connection_message_sent_unlocked, _dbus_list_pop_first_link, _dbus_list_remove_link.
void _dbus_list_remove_link(DBusList **list, DBusList *link)
Removes a link from the list.
This is a constant-time operation. list address of the list head. link the list link to remove.
References _dbus_list_unlink.
Referenced by _dbus_connection_close_if_only_one_ref, _dbus_list_length_is_one, _dbus_list_pop_first, _dbus_list_pop_last, _dbus_list_remove, _dbus_list_remove_last, _dbus_message_remove_counter, _dbus_object_tree_dispatch_and_unlock, dbus_connection_remove_filter.
void _dbus_list_clear(DBusList **list)
Frees all links in the list and sets the list head to NULL.
Does not free the data in each link, for obvious reasons. This is a linear-time operation. list address of the list head.
References _dbus_list_get_next_link, NULL.
Referenced by _dbus_address_append_escaped, _dbus_auth_unref, _dbus_list_copy, _dbus_list_length_is_one, _dbus_message_loader_unref, _dbus_pending_call_set_reply_unlocked, _dbus_split_paths_and_append, _dbus_timeout_list_free, _dbus_validate_signature_with_reason, _dbus_watch_list_free, dbus_connection_dispatch, dbus_connection_ref, dbus_message_get_reply_serial, dbus_parse_address.
DBusList* _dbus_list_get_first_link(DBusList **list)
Gets the first link in the list.
This is a constant-time operation. list address of the list head. the first link, or NULL for an empty list.
Referenced by _dbus_address_append_escaped, _dbus_connection_close_if_only_one_ref, _dbus_list_length_is_one, _dbus_list_pop_first, _dbus_list_pop_first_link, _dbus_object_tree_dispatch_and_unlock, _dbus_timeout_list_set_functions, _dbus_watch_list_set_functions, _dbus_watch_list_toggle_all_watches, dbus_address_entry_get_value, dbus_connection_dispatch, dbus_connection_ref, dbus_parse_address.
DBusList* _dbus_list_get_last_link(DBusList **list)
Gets the last link in the list.
This is a constant-time operation. list address of the list head. the last link, or NULL for an empty list.
References NULL.
Referenced by _dbus_connection_message_sent_unlocked, _dbus_list_find_last, _dbus_list_length_is_one, _dbus_list_pop_last, dbus_connection_pop_message, dbus_connection_remove_filter.
void* _dbus_list_get_last(DBusList **list)
Gets the last data in the list.
This is a constant-time operation. list address of the list head. the last data in the list, or NULL for an empty list.
References NULL.
Referenced by _dbus_connection_get_message_to_send, _dbus_list_length_is_one.
void* _dbus_list_get_first(DBusList **list)
Gets the first data in the list.
This is a constant-time operation. list address of the list head. the first data in the list, or NULL for an empty list.
References NULL.
Referenced by _dbus_list_length_is_one, dbus_connection_borrow_message.
DBusList* _dbus_list_pop_first_link(DBusList **list)
Removes the first link in the list and returns it.
This is a constant-time operation. list address of the list head. the first link in the list, or NULL for an empty list.
References _dbus_list_get_first_link, _dbus_list_unlink, NULL.
Referenced by _dbus_connection_unlock, _dbus_list_length_is_one, _dbus_message_loader_pop_message_link, dbus_connection_steal_borrowed_message.
void* _dbus_list_pop_first(DBusList **list)
Removes the first value in the list and returns it.
This is a constant-time operation. list address of the list head. the first data in the list, or NULL for an empty list.
References _dbus_list_get_first_link, _dbus_list_remove_link, DBusList::data, NULL.
Referenced by _dbus_connection_handle_watch, _dbus_list_length_is_one, _dbus_message_loader_pop_message, dbus_connection_steal_borrowed_message.
void* _dbus_list_pop_last(DBusList **list)
Removes the last value in the list and returns it.
This is a constant-time operation. list address of the list head. the last data in the list, or NULL for an empty list.
References _dbus_list_get_last_link, _dbus_list_remove_link, DBusList::data, NULL.
Referenced by _dbus_list_length_is_one, _dbus_validate_signature_with_reason.
dbus_bool_t _dbus_list_copy(DBusList **list, DBusList **dest)
Copies a list.
This is a linear-time operation. If there isn't enough memory to copy the entire list, the destination list will be set to NULL. list address of the head of the list to copy. dest address where the copied list should be placed. TRUE on success, FALSE if not enough memory.
References _dbus_assert, _dbus_list_append, _dbus_list_clear, _dbus_list_get_next_link, DBusList::data, FALSE, NULL, TRUE.
Referenced by _dbus_list_length_is_one, dbus_connection_dispatch.
int _dbus_list_get_length(DBusList **list)
Gets the length of a list.
This is a linear-time operation. list address of the head of the list number of elements in the list.
References _dbus_list_get_next_link, NULL.
Referenced by _dbus_list_length_is_one, _dbus_object_tree_dispatch_and_unlock, dbus_parse_address.
void _dbus_list_foreach(DBusList **list, DBusForeachFunction function, void *data)
Calls the given function for each element in the list.
The function is passed the list element as its first argument, and the given data as its second argument. list address of the head of the list. function function to call for each element. data extra data for the function.
References _dbus_list_get_next_link, DBusList::data, NULL.
Referenced by _dbus_message_loader_unref, _dbus_split_paths_and_append, _dbus_timeout_list_free, _dbus_timeout_list_set_functions, _dbus_watch_list_free, _dbus_watch_list_set_functions, dbus_connection_dispatch, dbus_connection_ref, dbus_message_get_reply_serial.
dbus_bool_t _dbus_list_length_is_one(DBusList **list)
Check whether length is exactly one.
list the list TRUE if length is exactly one
References _dbus_assert, _dbus_assert_not_reached, _DBUS_INT_MAX, _DBUS_INT_MIN, _DBUS_INT_TO_POINTER, _dbus_list_append, _dbus_list_clear, _dbus_list_copy, _dbus_list_free_link, _dbus_list_get_first, _dbus_list_get_first_link, _dbus_list_get_last, _dbus_list_get_last_link, _dbus_list_get_length, _dbus_list_get_next_link, _dbus_list_get_prev_link, _dbus_list_insert_after, _dbus_list_length_is_one, _dbus_list_pop_first, _dbus_list_pop_first_link, _dbus_list_pop_last, _dbus_list_prepend, _dbus_list_remove, _dbus_list_remove_last, _dbus_list_remove_link, _DBUS_POINTER_TO_INT, DBusList::data, FALSE, DBusList::next, NULL, DBusList::prev, TRUE.
Referenced by _dbus_list_length_is_one.