dbus-threads-internal.h
typedef struct DBusRMutex DBusRMutex
A mutex which is recursive if possible, else non-recursive.
This is typically recursive, but that cannot be relied upon.
typedef struct DBusCMutex DBusCMutex
A mutex suitable for use with condition variables.
This is typically non-recursive.
void _dbus_rmutex_lock(DBusRMutex *mutex)
Locks a mutex.
Does nothing if passed a NULL pointer. Locks may be recursive if threading implementation initialized recursive locks.
References NULL.
void _dbus_rmutex_unlock(DBusRMutex *mutex)
Unlocks a mutex.
Does nothing if passed a NULL pointer.TRUE on success
References NULL.
Referenced by _dbus_connection_unlock.
void _dbus_rmutex_new_at_location(DBusRMutex **location_p)
Creates a new mutex or creates a no-op mutex if threads are not initialized.
May return NULL even if threads are initialized, indicating out-of-memory.If possible, the mutex returned by this function is recursive, to avoid deadlocks. However, that cannot be relied on. location_p the location of the new mutex, can return NULL on OOM
References _dbus_assert, NULL, dbus_threads_init_default.
Referenced by _dbus_connection_new_for_transport, _dbus_server_init_base.
void _dbus_rmutex_free_at_location(DBusRMutex **location_p)
Frees a DBusRMutex; does nothing if passed a NULL pointer.
References NULL.
Referenced by _dbus_connection_new_for_transport, dbus_connection_ref, _dbus_server_init_base, _dbus_server_finalize_base.
void _dbus_cmutex_lock(DBusCMutex *mutex)
Locks a mutex.
Does nothing if passed a NULL pointer. Locks may be recursive if threading implementation initialized recursive locks.
References NULL.
Referenced by _dbus_connection_remove_pending_call, dbus_connection_pop_message.
void _dbus_cmutex_unlock(DBusCMutex *mutex)
Unlocks a mutex.
Does nothing if passed a NULL pointer.TRUE on success
References NULL.
Referenced by _dbus_connection_remove_pending_call, dbus_connection_pop_message.
void _dbus_cmutex_new_at_location(DBusCMutex **location_p)
Creates a new mutex or creates a no-op mutex if threads are not initialized.
May return NULL even if threads are initialized, indicating out-of-memory.The returned mutex is suitable for use with condition variables. location_p the location of the new mutex, can return NULL on OOM
References _dbus_assert, NULL, dbus_threads_init_default.
Referenced by _dbus_connection_new_for_transport.
void _dbus_cmutex_free_at_location(DBusCMutex **location_p)
Frees a DBusCMutex; does nothing if passed a NULL pointer.
References NULL.
Referenced by _dbus_connection_new_for_transport, dbus_connection_ref.
DBusCondVar* _dbus_condvar_new(void)
Creates a new condition variable using the function supplied to dbus_threads_init(), or creates a no-op condition variable if threads are not initialized.
May return NULL even if threads are initialized, indicating out-of-memory.new mutex or NULL
References dbus_threads_init_default, NULL.
Referenced by _dbus_condvar_new_at_location.
void _dbus_condvar_free(DBusCondVar *cond)
Frees a conditional variable created with dbus_condvar_new(); does nothing if passed a NULL pointer.
References NULL.
void _dbus_condvar_wait(DBusCondVar *cond, DBusCMutex *mutex)
Atomically unlocks the mutex and waits for the conditions variable to be signalled.
Locks the mutex again before returning. Does nothing if passed a NULL pointer.
References NULL.
Referenced by _dbus_connection_remove_pending_call, dbus_connection_pop_message.
dbus_bool_t _dbus_condvar_wait_timeout(DBusCondVar *cond, DBusCMutex *mutex, int timeout_milliseconds)
Atomically unlocks the mutex and waits for the conditions variable to be signalled, or for a timeout.
Locks the mutex again before returning. Does nothing if passed a NULL pointer. Return value is FALSE if we timed out, TRUE otherwise. cond the condition variable mutex the mutex timeout_milliseconds the maximum time to wait FALSE if the timeout occurred, TRUE if not
References NULL, TRUE.
Referenced by _dbus_connection_remove_pending_call.
void _dbus_condvar_wake_one(DBusCondVar *cond)
If there are threads waiting on the condition variable, wake up exactly one.
Does nothing if passed a NULL pointer.
References NULL, _dbus_assert, TRUE, FALSE, DBusCMutex::lock, _dbus_current_generation, dbus_threads_init_default.
Referenced by _dbus_connection_remove_pending_call, dbus_connection_pop_message.
void _dbus_condvar_new_at_location(DBusCondVar **location_p)
This does the same thing as _dbus_condvar_new.
It however gives another level of indirection by allocating a pointer to point to the condvar location; this used to be useful.the location of a new condvar or NULL on OOM
References _dbus_assert, NULL, _dbus_condvar_new.
Referenced by _dbus_connection_new_for_transport.
void _dbus_condvar_free_at_location(DBusCondVar **location_p)
Frees a condition variable; does nothing if passed a NULL pointer.
References NULL.
Referenced by _dbus_connection_new_for_transport, dbus_connection_ref.
DBusRMutex* _dbus_platform_rmutex_new(void)
void _dbus_platform_rmutex_free(DBusRMutex *mutex)
void _dbus_platform_rmutex_lock(DBusRMutex *mutex)
void _dbus_platform_rmutex_unlock(DBusRMutex *mutex)
DBusCMutex* _dbus_platform_cmutex_new(void)
void _dbus_platform_cmutex_free(DBusCMutex *mutex)
void _dbus_platform_cmutex_lock(DBusCMutex *mutex)
void _dbus_platform_cmutex_unlock(DBusCMutex *mutex)
DBusCondVar* _dbus_platform_condvar_new(void)
void _dbus_platform_condvar_free(DBusCondVar *cond)
void _dbus_platform_condvar_wait(DBusCondVar *cond, DBusCMutex *mutex)
dbus_bool_t _dbus_platform_condvar_wait_timeout(DBusCondVar *cond, DBusCMutex *mutex, int timeout_milliseconds)
void _dbus_platform_condvar_wake_one(DBusCondVar *cond)