dbus-server.c
typedef dbus_bool_t(* DBusWatchAddFunction) (DBusWatchList *list, DBusWatch *watch))(DBusWatchList *list, DBusWatch *watch)
Function to be called in protected_change_watch() with refcount held.
typedef void(* DBusWatchRemoveFunction) (DBusWatchList *list, DBusWatch *watch))(DBusWatchList *list, DBusWatch *watch)
Function to be called in protected_change_watch() with refcount held.
typedef void(* DBusWatchToggleFunction) (DBusWatchList *list, DBusWatch *watch, dbus_bool_t enabled))(DBusWatchList *list, DBusWatch *watch, dbus_bool_t enabled)
Function to be called in protected_change_watch() with refcount held.
typedef dbus_bool_t(* DBusTimeoutAddFunction) (DBusTimeoutList *list, DBusTimeout *timeout))(DBusTimeoutList *list, DBusTimeout *timeout)
Function to be called in protected_change_timeout() with refcount held.
typedef void(* DBusTimeoutRemoveFunction) (DBusTimeoutList *list, DBusTimeout *timeout))(DBusTimeoutList *list, DBusTimeout *timeout)
Function to be called in protected_change_timeout() with refcount held.
typedef void(* DBusTimeoutToggleFunction) (DBusTimeoutList *list, DBusTimeout *timeout, dbus_bool_t enabled))(DBusTimeoutList *list, DBusTimeout *timeout, dbus_bool_t enabled)
Function to be called in protected_change_timeout() with refcount held.
DBusServerListenResult(* func) (DBusAddressEntry *entry, DBusServer **server_p, DBusError *error))(DBusAddressEntry *entry, DBusServer **server_p, DBusError *error)
const struct @7 listen_funcs[][]
DBusDataSlotAllocator slot_allocator
void _dbus_server_trace_ref(DBusServer *server, int old_refcount, int new_refcount, const char *why)
static char* copy_address_with_guid_appended(const DBusString *address, const DBusString *guid_hex)
dbus_bool_t _dbus_server_init_base(DBusServer *server, const DBusServerVTable *vtable, const DBusString *address)
Initializes the members of the DBusServer base class.
Chained up to by subclass constructors. server the server. vtable the vtable for the subclass. address the server's address TRUE on success.
References _dbus_assert, _dbus_atomic_inc, _dbus_data_slot_list_init, _dbus_generate_uuid, _dbus_rmutex_free_at_location, _dbus_rmutex_new_at_location, _dbus_string_free, _dbus_string_init, _dbus_timeout_list_free, _dbus_timeout_list_new, _dbus_uuid_encode, _dbus_watch_list_free, _dbus_watch_list_new, DBusServer::address, dbus_free, FALSE, DBusServer::guid, DBusServer::guid_hex, DBusServer::mutex, NULL, DBusServer::published_address, DBusServer::refcount, DBusServer::slot_list, DBusServer::timeouts, TRUE, DBusServer::vtable, DBusServer::watches.
Referenced by _dbus_server_new_for_socket.
void _dbus_server_finalize_base(DBusServer *server)
Finalizes the members of the DBusServer base class.
Chained up to by subclass finalizers. server the server.
References _dbus_assert, _dbus_data_slot_list_free, _dbus_rmutex_free_at_location, _dbus_string_free, _dbus_timeout_list_free, _dbus_watch_list_free, DBusServer::address, DBusServer::auth_mechanisms, dbus_free, dbus_free_string_array, dbus_server_set_new_connection_function, DBusServer::disconnected, DBusServer::guid_hex, DBusServer::have_server_lock, DBusServer::mutex, NULL, DBusServer::slot_list, DBusServer::timeouts, DBusServer::watches.
Referenced by _dbus_server_new_for_socket.
static dbus_bool_t protected_change_watch(DBusServer *server, DBusWatch *watch, DBusWatchAddFunction add_function, DBusWatchRemoveFunction remove_function, DBusWatchToggleFunction toggle_function, dbus_bool_t enabled)
dbus_bool_t _dbus_server_add_watch(DBusServer *server, DBusWatch *watch)
Adds a watch for this server, chaining out to application-provided watch handlers.
server the server. watch the watch to add.
References _dbus_watch_list_add_watch, FALSE, NULL.
Referenced by _dbus_server_new_for_socket.
void _dbus_server_remove_watch(DBusServer *server, DBusWatch *watch)
Removes a watch previously added with _dbus_server_remove_watch().
server the server. watch the watch to remove.
References _dbus_watch_list_remove_watch, FALSE, NULL.
Referenced by _dbus_server_new_for_socket.
void _dbus_server_toggle_all_watches(DBusServer *server, dbus_bool_t enabled)
Toggles all watch and notifies app via server's DBusWatchToggledFunction if available.
server the server. enabled whether to enable or disable
References _dbus_watch_list_toggle_all_watches, DBusServer::watches.
static dbus_bool_t protected_change_timeout(DBusServer *server, DBusTimeout *timeout, DBusTimeoutAddFunction add_function, DBusTimeoutRemoveFunction remove_function, DBusTimeoutToggleFunction toggle_function, dbus_bool_t enabled)
dbus_bool_t _dbus_server_add_timeout(DBusServer *server, DBusTimeout *timeout)
Adds a timeout for this server, chaining out to application-provided timeout handlers.
The timeout should be repeatedly handled with dbus_timeout_handle() at its given interval until it is removed. server the server. timeout the timeout to add.
References _dbus_timeout_list_add_timeout, FALSE, NULL.
void _dbus_server_remove_timeout(DBusServer *server, DBusTimeout *timeout)
Removes a timeout previously added with _dbus_server_add_timeout().
server the server. timeout the timeout to remove.
References _dbus_timeout_list_remove_timeout, FALSE, NULL.
void _dbus_server_toggle_timeout(DBusServer *server, DBusTimeout *timeout, dbus_bool_t enabled)
Toggles a timeout and notifies app via server's DBusTimeoutToggledFunction if available.
It's an error to call this function on a timeout that was not previously added. server the server. timeout the timeout to toggle. enabled whether to enable or disable
References _dbus_timeout_list_toggle_timeout, NULL.
void _dbus_server_ref_unlocked(DBusServer *server)
Like dbus_server_ref() but does not acquire the lock (must already be held)
server the server.
References _dbus_assert, _dbus_atomic_inc, NULL, DBusServer::refcount.
void _dbus_server_unref_unlocked(DBusServer *server)
Like dbus_server_unref() but does not acquire the lock (must already be held)
server the server.
References _dbus_assert, _dbus_atomic_dec, _dbus_server_listen_platform_specific, _dbus_server_listen_socket, DBusServer::disconnected, DBusServerVTable::finalize, NULL, DBusServer::refcount, DBusServer::vtable.
DBUS_EXPORT DBusServer * dbus_server_listen(const char *address, DBusError *error)
Listens for new connections on the given address.
If there are multiple semicolon-separated address entries in the address, tries each one and listens on the first one that works.Returns NULL and sets error if listening fails for any reason. Otherwise returns a new DBusServer. dbus_server_set_new_connection_function(), dbus_server_set_watch_functions(), and dbus_server_set_timeout_functions() should be called immediately to render the server fully functional.To free the server, applications must call first dbus_server_disconnect() and then dbus_server_unref(). address the address of this server. error location to store reason for failure. a new DBusServer, or NULL on failure.
References _dbus_assert, _DBUS_N_ELEMENTS, dbus_address_entries_free, dbus_address_entry_get_method, DBUS_ERROR_ADDRESS_IN_USE, DBUS_ERROR_BAD_ADDRESS, dbus_error_free, DBUS_ERROR_INIT, dbus_error_is_set, dbus_move_error, dbus_parse_address, dbus_set_error, FALSE, NULL, TRUE.
Referenced by dbus_server_get_data.
DBUS_EXPORT DBusServer * dbus_server_ref(DBusServer *server)
Increments the reference count of a DBusServer.
server the server. the server
References _dbus_atomic_dec, _dbus_atomic_inc, _dbus_return_if_fail_warning_format, _dbus_warn_check_failed, NULL, DBusServer::refcount.
Referenced by dbus_server_disconnect.
DBUS_EXPORT void dbus_server_unref(DBusServer *server)
Decrements the reference count of a DBusServer.
Finalizes the server if the reference count reaches zero.The server must be disconnected before the refcount reaches zero. server the server.
References _dbus_assert, _dbus_atomic_dec, _dbus_atomic_inc, _dbus_return_if_fail_warning_format, _dbus_warn_check_failed, DBusServer::disconnected, DBusServerVTable::finalize, NULL, DBusServer::refcount, DBusServer::vtable.
Referenced by dbus_server_disconnect, dbus_server_get_data.
DBUS_EXPORT void dbus_server_disconnect(DBusServer *server)
Releases the server's address and stops listening for new clients.
If called more than once, only the first call has an effect. Does not modify the server's reference count. server the server.
References _dbus_assert, dbus_server_ref, dbus_server_unref, DBusServerVTable::disconnect, DBusServer::disconnected, NULL, TRUE, DBusServer::vtable.
Referenced by dbus_server_get_data.
DBUS_EXPORT dbus_bool_t dbus_server_get_is_connected(DBusServer *server)
Returns TRUE if the server is still listening for new connections.
server the server.
References DBusServer::disconnected, FALSE, NULL.
DBUS_EXPORT char * dbus_server_get_address(DBusServer *server)
Returns the address of the server, as a newly-allocated string which must be freed by the caller.
server the server the address or NULL if no memory
References _dbus_strdup, DBusServer::address, NULL.
Referenced by dbus_server_get_data.
DBUS_EXPORT char * dbus_server_get_id(DBusServer *server)
Returns the unique ID of the server, as a newly-allocated string which must be freed by the caller.
This ID is normally used by clients to tell when two DBusConnection would be equivalent (because the server address passed to dbus_connection_open() will have the same guid in the two cases). dbus_connection_open() can re-use an existing connection with the same ID instead of opening a new connection.This is an ID unique to each DBusServer. Remember that a DBusServer represents only one mode of connecting, so e.g. a bus daemon can listen on multiple addresses which will mean it has multiple DBusServer each with their own ID.The ID is not a UUID in the sense of RFC4122; the details are explained in the D-Bus specification. server the server the id of the server or NULL if no memory
References _dbus_string_copy_data, DBusServer::guid_hex, NULL.
Referenced by dbus_server_get_data.
DBUS_EXPORT void dbus_server_set_new_connection_function(DBusServer *server, DBusNewConnectionFunction function, void *data, DBusFreeFunction free_data_function)
Sets a function to be used for handling new connections.
The given function is passed each new connection as the connection is created. If the new connection function increments the connection's reference count, the connection will stay alive. Otherwise, the connection will be unreferenced and closed. The new connection function may also close the connection itself, which is considered good form if the connection is not wanted.The connection here is private in the sense of dbus_connection_open_private(), so if the new connection function keeps a reference it must arrange for the connection to be closed. i.e. libdbus does not own this connection once the new connection function takes a reference. server the server. function a function to handle new connections. data data to pass to the new connection handler. free_data_function function to free the data.
References DBusServer::new_connection_data, DBusServer::new_connection_free_data_function, DBusServer::new_connection_function, NULL.
Referenced by _dbus_server_finalize_base.
DBUS_EXPORT dbus_bool_t dbus_server_set_watch_functions(DBusServer *server, DBusAddWatchFunction add_function, DBusRemoveWatchFunction remove_function, DBusWatchToggledFunction toggled_function, void *data, DBusFreeFunction free_data_function)
Sets the watch functions for the server.
These functions are responsible for making the application's main loop aware of file descriptors that need to be monitored for events.This function behaves exactly like dbus_connection_set_watch_functions(); see the documentation for that routine. server the server. add_function function to begin monitoring a new descriptor. remove_function function to stop monitoring a descriptor. toggled_function function to notify when the watch is enabled/disabled data data to pass to add_function and remove_function. free_data_function function to be called to free the data. FALSE on failure (no memory)
References _dbus_warn_check_failed, _dbus_watch_list_set_functions, FALSE, NULL, DBusServer::watches.
DBUS_EXPORT dbus_bool_t dbus_server_set_timeout_functions(DBusServer *server, DBusAddTimeoutFunction add_function, DBusRemoveTimeoutFunction remove_function, DBusTimeoutToggledFunction toggled_function, void *data, DBusFreeFunction free_data_function)
Sets the timeout functions for the server.
These functions are responsible for making the application's main loop aware of timeouts.This function behaves exactly like dbus_connection_set_timeout_functions(); see the documentation for that routine. server the server. add_function function to add a timeout. remove_function function to remove a timeout. toggled_function function to notify when the timeout is enabled/disabled data data to pass to add_function and remove_function. free_data_function function to be called to free the data. FALSE on failure (no memory)
References _dbus_timeout_list_set_functions, _dbus_warn_check_failed, FALSE, NULL, DBusServer::timeouts.
DBUS_EXPORT dbus_bool_t dbus_server_set_auth_mechanisms(DBusServer *server, const char **mechanisms)
Sets the authentication mechanisms that this server offers to clients, as a NULL-terminated array of mechanism names.
This function only affects connections created after it is called. Pass NULL instead of an array to use all available mechanisms (this is the default behavior).The D-Bus specification describes some of the supported mechanisms. server the server mechanisms NULL-terminated array of mechanisms FALSE if no memory
References _dbus_dup_string_array, _DBUS_LOCK_NAME, DBusServer::auth_mechanisms, dbus_free_string_array, FALSE, NULL, TRUE.
DBUS_EXPORT dbus_bool_t dbus_server_allocate_data_slot(dbus_int32_t *slot_p)
Allocates an integer ID to be used for storing application-specific data on any DBusServer.
The allocated ID may then be used with dbus_server_set_data() and dbus_server_get_data(). The slot must be initialized with -1. If a nonnegative slot is passed in, the refcount is incremented on that slot, rather than creating a new slot.The allocated slot is global, i.e. all DBusServer objects will have a slot with the given integer ID reserved. slot_p address of global variable storing the slot ID FALSE on no memory
References _dbus_data_slot_allocator_alloc.
DBUS_EXPORT void dbus_server_free_data_slot(dbus_int32_t *slot_p)
Deallocates a global ID for server data slots.
dbus_server_get_data() and dbus_server_set_data() may no longer be used with this slot. Existing data stored on existing DBusServer objects will be freed when the server is finalized, but may not be retrieved (and may only be replaced if someone else reallocates the slot). slot_p address of the slot to deallocate
References _dbus_data_slot_allocator_free.
DBUS_EXPORT dbus_bool_t dbus_server_set_data(DBusServer *server, int slot, void *data, DBusFreeFunction free_data_func)
Stores a pointer on a DBusServer, along with an optional function to be used for freeing the data when the data is set again, or when the server is finalized.
The slot number must have been allocated with dbus_server_allocate_data_slot(). server the server slot the slot number data the data to store free_data_func finalizer function for the data TRUE if there was enough memory to store the data
References _dbus_data_slot_list_set, FALSE, NULL, DBusServer::slot_list.
DBUS_EXPORT void * dbus_server_get_data(DBusServer *server, int slot)
Retrieves data previously set with dbus_server_set_data().
The slot must still be allocated (must not have been freed). server the server slot the slot to get data from the data, or NULL if not found
References _dbus_assert, _dbus_assert_not_reached, _dbus_data_slot_list_get, _DBUS_N_ELEMENTS, _dbus_warn, dbus_error_free, DBUS_ERROR_INIT, dbus_free, dbus_server_disconnect, dbus_server_get_address, dbus_server_get_id, dbus_server_listen, dbus_server_unref, DBusError::message, DBusError::name, NULL, DBusServer::slot_list, TRUE.