dbus-marshal-basic.h
DBUS_COMPILER_BYTE_ORDER
DBUS_UINT16_SWAP_LE_BE_CONSTANT
DBUS_UINT32_SWAP_LE_BE_CONSTANT
DBUS_UINT64_SWAP_LE_BE_CONSTANT
DBUS_UINT16_SWAP_LE_BE
DBUS_INT16_SWAP_LE_BE
DBUS_UINT32_SWAP_LE_BE
DBUS_INT32_SWAP_LE_BE
DBUS_UINT64_SWAP_LE_BE
DBUS_INT64_SWAP_LE_BE
DBUS_INT16_TO_LE
DBUS_UINT16_TO_LE
DBUS_INT16_TO_BE
DBUS_UINT16_TO_BE
DBUS_INT32_TO_LE
DBUS_UINT32_TO_LE
DBUS_INT32_TO_BE
DBUS_UINT32_TO_BE
DBUS_INT64_TO_LE
DBUS_UINT64_TO_LE
DBUS_INT64_TO_BE
DBUS_UINT64_TO_BE
DBUS_INT16_FROM_LE
DBUS_UINT16_FROM_LE
DBUS_INT16_FROM_BE
DBUS_UINT16_FROM_BE
DBUS_INT32_FROM_LE
DBUS_UINT32_FROM_LE
DBUS_INT32_FROM_BE
DBUS_UINT32_FROM_BE
DBUS_INT64_FROM_LE
DBUS_UINT64_FROM_LE
DBUS_INT64_FROM_BE
DBUS_UINT64_FROM_BE
dbus_uint16_t _dbus_unpack_uint16(int byte_order, const unsigned char *data)
Unpacks a 16 bit unsigned integer from a data pointer.
byte_order The byte order to use data the data pointer the integer
References _dbus_assert, DBUS_LITTLE_ENDIAN.
void _dbus_pack_uint32(dbus_uint32_t value, int byte_order, unsigned char *data)
Packs a 32 bit unsigned integer into a data pointer.
value the value byte_order the byte order to use data the data pointer
References DBusBasicValue::u64.
Referenced by _dbus_first_type_in_signature_c_str.
dbus_uint32_t _dbus_unpack_uint32(int byte_order, const unsigned char *data)
Unpacks a 32 bit unsigned integer from a data pointer.
byte_order The byte order to use data the data pointer the integer
References _dbus_assert, DBUS_LITTLE_ENDIAN, DBUS_BIG_ENDIAN, _dbus_string_get_data_len.
Referenced by _dbus_marshal_set_uint32, _dbus_marshal_read_uint32, _dbus_verbose_bytes, _dbus_first_type_in_signature_c_str, _dbus_type_writer_init_values_only, _dbus_type_writer_write_fixed_multi, _dbus_validate_signature_with_reason.
dbus_bool_t _dbus_marshal_set_basic(DBusString *str, int pos, int type, const void *value, int byte_order, int *old_end_pos, int *new_end_pos)
Sets an existing basic type value to a new value.
Arguments work the same way as _dbus_marshal_basic_type(). str the string pos location of the current value type the type of the current and new values value the address of the new value byte_order byte order for marshaling old_end_pos location to store end position of the old value, or NULL new_end_pos location to store end position of the new value, or NULL FALSE if no memory
References DBUS_TYPE_BYTE, DBusBasicValue::byt, TRUE, DBUS_TYPE_INT16, DBUS_TYPE_UINT16, DBusBasicValue::u16, DBUS_TYPE_BOOLEAN, DBUS_TYPE_INT32, DBUS_TYPE_UINT32, DBUS_TYPE_UNIX_FD, DBusBasicValue::u32, DBUS_TYPE_INT64, DBUS_TYPE_UINT64, DBUS_TYPE_DOUBLE, DBUS_TYPE_STRING, DBUS_TYPE_OBJECT_PATH, _dbus_assert, DBusBasicValue::str, NULL, DBUS_TYPE_SIGNATURE, _dbus_assert_not_reached, FALSE.
Referenced by _dbus_first_type_in_signature_c_str.
dbus_bool_t _dbus_marshal_write_basic(DBusString *str, int insert_at, int type, const void *value, int byte_order, int *pos_after)
Marshals a basic-typed value.
The "value" pointer is always the address of a variable containing the basic type value. So for example for int32 it will be dbus_int32_t*, and for string it will be const char**. This is for symmetry with _dbus_marshal_read_basic() and to have a simple consistent rule. str string to marshal to insert_at where to insert the value type type of value value pointer to a variable containing the value byte_order byte order pos_after NULL or the position after the type TRUE on success
References _dbus_assert, dbus_type_is_basic, DBUS_TYPE_BYTE, _dbus_string_insert_byte, DBusBasicValue::byt, FALSE, TRUE, DBUS_TYPE_INT16, DBUS_TYPE_UINT16, DBusBasicValue::u16, DBUS_TYPE_BOOLEAN, DBusBasicValue::u32, DBUS_TYPE_INT32, DBUS_TYPE_UINT32, DBUS_TYPE_UNIX_FD, DBUS_TYPE_INT64, DBUS_TYPE_UINT64, DBUS_TYPE_DOUBLE, DBUS_TYPE_STRING, DBUS_TYPE_OBJECT_PATH, DBusBasicValue::str, NULL, DBUS_TYPE_SIGNATURE, _dbus_assert_not_reached, _dbus_string_init_const_len, _dbus_string_copy_len.
Referenced by _dbus_type_writer_init_values_only.
dbus_bool_t _dbus_marshal_write_fixed_multi(DBusString *str, int insert_at, int element_type, const void *value, int n_elements, int byte_order, int *pos_after)
Marshals a block of values of fixed-length type all at once, as an optimization.
dbus_type_is_fixed() returns TRUE for fixed-length types, which are the basic types minus the string-like types.The value argument should be the adddress of an array, so e.g. "const dbus_uint32_t**" str string to marshal to insert_at where to insert the value element_type type of array elements value address of an array to marshal n_elements number of elements in the array byte_order byte order pos_after NULL or the position after the type TRUE on success
References _dbus_assert, dbus_type_is_fixed, _dbus_type_to_string, DBUS_TYPE_BYTE, DBUS_TYPE_INT16, DBUS_TYPE_UINT16, DBUS_TYPE_BOOLEAN, DBUS_TYPE_INT32, DBUS_TYPE_UINT32, DBUS_TYPE_UNIX_FD, DBUS_TYPE_INT64, DBUS_TYPE_UINT64, DBUS_TYPE_DOUBLE, _dbus_assert_not_reached, FALSE.
Referenced by _dbus_type_writer_write_fixed_multi.
void _dbus_marshal_read_basic(const DBusString *str, int pos, int type, void *value, int byte_order, int *new_pos)
Demarshals a basic-typed value.
The "value" pointer is always the address of a variable of the basic type. So e.g. if the basic type is "double" then the pointer is a double*, and if it's "char*" then the pointer is a "char**".A value of type DBusBasicValue is guaranteed to be large enough to hold any of the types that may be returned, which is handy if you are trying to do things generically. For example you can pass a DBusBasicValue* in to this function, and then pass the same DBusBasicValue* in to _dbus_marshal_basic_type() in order to move a value from one place to another. str the string containing the data pos position in the string type type of value to demarshal value pointer to return value data byte_order the byte order new_pos pointer to update with new position, or NULL
References _dbus_assert, dbus_type_is_basic, DBUS_TYPE_BYTE, DBUS_TYPE_INT16, DBUS_TYPE_UINT16, DBUS_TYPE_INT32, DBUS_TYPE_UINT32, DBUS_TYPE_BOOLEAN, DBUS_TYPE_UNIX_FD, DBUS_TYPE_INT64, DBUS_TYPE_UINT64, DBUS_TYPE_DOUBLE, dbus_uint64_t, DBUS_TYPE_STRING, DBUS_TYPE_OBJECT_PATH, _dbus_marshal_read_uint32, DBUS_TYPE_SIGNATURE, _dbus_warn_check_failed, _dbus_type_to_string, _dbus_assert_not_reached, _dbus_string_insert_2_aligned, _dbus_string_insert_4_aligned, _dbus_string_insert_8_aligned, DBUS_LITTLE_ENDIAN, DBUS_BIG_ENDIAN, _dbus_warn, _dbus_string_init_const_len, DBUS_MAXIMUM_SIGNATURE_LENGTH, _dbus_string_insert_byte, _dbus_string_copy_len, _dbus_string_equal_substring, _dbus_verbose_bytes_of_string, TRUE, _dbus_string_delete, FALSE.
Referenced by _dbus_first_type_in_signature_c_str, _dbus_header_get_field_basic, _dbus_type_reader_read_basic.
void _dbus_marshal_read_fixed_multi(const DBusString *str, int pos, int element_type, void *value, int n_elements, int byte_order, int *new_pos)
void _dbus_marshal_skip_basic(const DBusString *str, int type, int byte_order, int *pos)
Skips over a basic-typed value, reporting the following position.
str the string containing the data type type of value to read byte_order the byte order pos pointer to position in the string, updated on return to new position
References _dbus_assert, DBUS_LITTLE_ENDIAN, DBUS_BIG_ENDIAN, DBUS_TYPE_BYTE, DBUS_TYPE_INT16, DBUS_TYPE_UINT16, DBUS_TYPE_BOOLEAN, DBUS_TYPE_INT32, DBUS_TYPE_UINT32, DBUS_TYPE_UNIX_FD, DBUS_TYPE_INT64, DBUS_TYPE_UINT64, DBUS_TYPE_DOUBLE, DBUS_TYPE_STRING, DBUS_TYPE_OBJECT_PATH, _dbus_marshal_read_uint32, DBUS_TYPE_SIGNATURE, _dbus_warn, _dbus_type_to_string, _dbus_assert_not_reached.
Referenced by _dbus_type_signature_next.
void _dbus_marshal_skip_array(const DBusString *str, int element_type, int byte_order, int *pos)
Skips an array, returning the next position.
str the string containing the data element_type the type of array elements byte_order the byte order pos pointer to position in the string, updated on return to new position
References _dbus_marshal_read_uint32, _dbus_type_get_alignment.
Referenced by _dbus_type_signature_next.
void _dbus_marshal_set_uint32(DBusString *str, int pos, dbus_uint32_t value, int byte_order)
Sets the 4 bytes at the given offset to a marshaled unsigned integer, replacing anything found there previously.
str the string to write the marshalled int to pos the byte offset where int should be written value the value byte_order the byte order to use
References _dbus_string_init_const, _dbus_assert, _dbus_unpack_uint32, _dbus_string_replace_len, FALSE, _dbus_marshal_set_uint32, TRUE.
Referenced by _dbus_marshal_set_uint32, _dbus_first_type_in_signature_c_str, _dbus_header_set_serial, _dbus_header_update_lengths, _dbus_type_writer_unrecurse.
dbus_uint32_t _dbus_marshal_read_uint32(const DBusString *str, int pos, int byte_order, int *new_pos)
Convenience function to demarshal a 32 bit unsigned integer.
str the string containing the data byte_order the byte order pos the position in the string new_pos the new position of the string the demarshaled integer.
References _dbus_assert, _dbus_unpack_uint32.
Referenced by _dbus_marshal_read_basic, _dbus_marshal_skip_basic, _dbus_marshal_skip_array, _dbus_header_get_serial, _dbus_header_have_message_untrusted.
int _dbus_type_get_alignment(int typecode)
Gets the alignment requirement for the given type; will be 1, 4, or 8.
typecode the type alignment of 1, 4, or 8
References DBUS_TYPE_BYTE, DBUS_TYPE_VARIANT, DBUS_TYPE_SIGNATURE, DBUS_TYPE_INT16, DBUS_TYPE_UINT16, DBUS_TYPE_BOOLEAN, DBUS_TYPE_INT32, DBUS_TYPE_UINT32, DBUS_TYPE_UNIX_FD, DBUS_TYPE_STRING, DBUS_TYPE_OBJECT_PATH, DBUS_TYPE_ARRAY, DBUS_TYPE_INT64, DBUS_TYPE_UINT64, DBUS_TYPE_DOUBLE, DBUS_TYPE_STRUCT, DBUS_TYPE_DICT_ENTRY, _dbus_assert_not_reached.
Referenced by _dbus_marshal_skip_array, _dbus_first_type_in_signature_c_str, _dbus_type_reader_read_fixed_multi, _dbus_type_writer_init_values_only, _dbus_validate_signature_with_reason, dbus_message_iter_append_fixed_array.
const char* _dbus_type_to_string(int typecode)
Returns a string describing the given type.
typecode the type to describe a constant string describing the type
References DBUS_TYPE_INVALID, DBUS_TYPE_BOOLEAN, DBUS_TYPE_BYTE, DBUS_TYPE_INT16, DBUS_TYPE_UINT16, DBUS_TYPE_INT32, DBUS_TYPE_UINT32, DBUS_TYPE_INT64, DBUS_TYPE_UINT64, DBUS_TYPE_DOUBLE, DBUS_TYPE_STRING, DBUS_TYPE_OBJECT_PATH, DBUS_TYPE_SIGNATURE, DBUS_TYPE_STRUCT, DBUS_TYPE_DICT_ENTRY, DBUS_TYPE_ARRAY, DBUS_TYPE_VARIANT, DBUS_STRUCT_BEGIN_CHAR, DBUS_STRUCT_END_CHAR, DBUS_DICT_ENTRY_BEGIN_CHAR, DBUS_DICT_ENTRY_END_CHAR, DBUS_TYPE_UNIX_FD.
Referenced by _dbus_marshal_read_basic, _dbus_marshal_write_fixed_multi, _dbus_marshal_skip_basic, _dbus_first_type_in_signature_c_str, _dbus_type_signature_next, _dbus_type_reader_get_current_type, _dbus_type_reader_recurse, _dbus_type_reader_next, _dbus_type_reader_set_basic, _dbus_type_writer_init_values_only, _dbus_type_writer_unrecurse, _dbus_type_writer_write_fixed_multi, _dbus_validate_signature_with_reason, _dbus_message_iter_get_args_valist, dbus_message_append_args_valist.
int _dbus_first_type_in_signature(const DBusString *str, int pos)
Get the first type in the signature.
The difference between this and just getting the first byte of the signature is that you won't get DBUS_STRUCT_BEGIN_CHAR, you'll get DBUS_TYPE_STRUCT instead. str string containing signature pos where the signature starts the first type in the signature
Referenced by _dbus_type_signature_next, _dbus_type_reader_get_current_type, _dbus_type_reader_get_element_type, _dbus_type_reader_read_fixed_multi, _dbus_type_reader_recurse, _dbus_type_writer_init_values_only, _dbus_validate_signature_with_reason.
int _dbus_first_type_in_signature_c_str(const char *str, int pos)
Similar to _dbus_first_type_in_signature, but operates on a C string buffer.
str a C string buffer pos where the signature starts the first type in the signature
References _dbus_assert, dbus_type_is_fixed, dbus_type_is_basic, _dbus_type_to_string, _dbus_type_get_alignment, _dbus_string_init_const_len, dbus_int64_t, DBUS_INT64_CONSTANT, dbus_uint64_t, _dbus_string_init, _dbus_assert_not_reached, DBUS_BIG_ENDIAN, _DBUS_DOUBLES_BITWISE_EQUAL, DBUS_LITTLE_ENDIAN, DBUS_UINT64_CONSTANT, FALSE, TRUE, _dbus_string_set_length, _dbus_marshal_set_uint32, _dbus_unpack_uint32, _dbus_pack_uint32, _dbus_string_init_const, _dbus_marshal_set_basic, DBUS_TYPE_STRING, NULL, _dbus_marshal_read_basic, _dbus_string_free.
Referenced by dbus_signature_iter_get_current_type, dbus_signature_iter_get_element_type.
void _dbus_swap_array(unsigned char *data, int n_elements, int alignment)
Swaps the elements of an array to the opposite byte order.
data start of array n_elements number of elements alignment size of each element
References _dbus_assert, dbus_uint64_t, _dbus_swap_array, DBUS_MAXIMUM_ARRAY_LENGTH, _dbus_string_insert_alignment, _dbus_string_init_const_len, _dbus_string_copy, TRUE, _dbus_string_delete, FALSE.
Referenced by _dbus_swap_array.