dbus-mempool.h
DBusMemPool
Opaque object representing a memory pool.
Memory pools allow avoiding per-malloc-block memory overhead when allocating a lot of small objects that are all the same size. They are slightly faster than calling malloc() also.
DBusMemPool* _dbus_mem_pool_new(int element_size, dbus_bool_t zero_elements)
Creates a new memory pool, or returns NULL on failure.
Objects in the pool must be at least sizeof(void*) bytes each, due to the way memory pools work. To avoid creating 64 bit problems, this means at least 8 bytes on all platforms, unless you are 4 bytes on 32-bit and 8 bytes on 64-bit. element_size size of an element allocated from the pool. zero_elements whether to zero-initialize elements the new pool or NULL
References dbus_new0, NULL, _dbus_assert, DBusMemPool::element_size, DBusMemPool::zero_elements, FALSE, DBusMemPool::allocated_elements, DBusMemPool::block_size.
Referenced by _dbus_hash_table_new, _dbus_mem_pool_dealloc.
void _dbus_mem_pool_free(DBusMemPool *pool)
Frees a memory pool (and all elements allocated from it).
pool the memory pool.
References DBusMemPool::blocks, NULL, DBusFreedElement::next, DBusMemBlock::next, dbus_free.
Referenced by _dbus_hash_table_unref, _dbus_mem_pool_dealloc.
void* _dbus_mem_pool_alloc(DBusMemPool *pool)
Allocates an object from the memory pool.
The object must be freed with _dbus_mem_pool_dealloc(). pool the memory pool the allocated object or NULL if no memory.
References ELEMENT_PADDING, DBusMemPool::element_size, DBusMemPool::zero_elements, dbus_malloc0, dbus_malloc, NULL, DBusMemBlock::next, DBusMemPool::blocks, DBusMemPool::allocated_elements, DBusMemBlock::elements, DBusMemPool::free_elements, DBusFreedElement::next, DBusMemBlock::used_so_far, DBusMemPool::block_size, _DBUS_INT_MAX, _dbus_assert.
Referenced by _dbus_hash_table_remove_all, _dbus_mem_pool_dealloc.
dbus_bool_t _dbus_mem_pool_dealloc(DBusMemPool *pool, void *element)
Deallocates an object previously created with _dbus_mem_pool_alloc().
The previous object must have come from this same pool. pool the memory pool element the element earlier allocated. TRUE if there are no remaining allocated elements
References NULL, DBusMemPool::blocks, DBusMemBlock::elements, DBusMemBlock::next, dbus_free, _dbus_assert, DBusMemPool::allocated_elements, _dbus_assert_not_reached, FALSE, DBusFreedElement::next, DBusMemPool::free_elements, DBusMemPool::element_size, DBusMemPool::block_size, DBusMemBlock::used_so_far, dbus_malloc, _dbus_mem_pool_new, _dbus_mem_pool_alloc, _dbus_mem_pool_dealloc, _dbus_mem_pool_free, dbus_malloc0, TRUE, _DBUS_N_ELEMENTS.
Referenced by _dbus_hash_table_remove_all, _dbus_hash_table_free_preallocated_entry, _dbus_mem_pool_dealloc.
void _dbus_mem_pool_get_stats(DBusMemPool *pool, dbus_uint32_t *in_use_p, dbus_uint32_t *in_free_list_p, dbus_uint32_t *allocated_p)