dbus-transport.c
DBusTransportOpenResult(* func) (DBusAddressEntry *entry, DBusTransport **transport_p, DBusError *error))(DBusAddressEntry *entry, DBusTransport **transport_p, DBusError *error)
const struct @9 open_funcs[][]
static void live_messages_notify(DBusCounter *counter, void *user_data)
dbus_bool_t _dbus_transport_init_base(DBusTransport *transport, const DBusTransportVTable *vtable, const DBusString *server_guid, const DBusString *address)
Initializes the base class members of DBusTransport.
Chained up to by subclasses in their constructor. The server GUID is the globally unique ID for the server creating this connection and will be NULL for the client side of a connection. The GUID is in hex format. transport the transport being created. vtable the subclass vtable. server_guid non-NULL if this transport is on the server side of a connection address the address of the transport TRUE on success.
References _dbus_assert, _dbus_auth_client_new, _dbus_auth_server_new, _dbus_auth_unref, _dbus_counter_new, _dbus_counter_set_notify, _dbus_counter_unref, _dbus_credentials_new, _dbus_credentials_unref, _dbus_message_loader_new, _dbus_message_loader_unref, _dbus_string_copy_data, DBusTransport::address, DBusTransport::auth, DBusTransport::authenticated, DBusTransport::credentials, DBusTransport::disconnected, DBusTransport::expected_guid, FALSE, DBusTransport::free_unix_user_data, DBusTransport::free_windows_user_data, DBusTransport::is_server, DBusTransport::live_messages, DBusTransport::loader, DBusTransport::max_live_messages_size, DBusTransport::max_live_messages_unix_fds, NULL, DBusTransport::receive_credentials_pending, DBusTransport::refcount, DBusTransport::send_credentials_pending, TRUE, DBusTransport::unix_user_data, DBusTransport::unix_user_function, DBusTransport::vtable, DBusTransport::windows_user_data, DBusTransport::windows_user_function.
Referenced by _dbus_transport_new_for_socket.
void _dbus_transport_finalize_base(DBusTransport *transport)
Finalizes base class members of DBusTransport.
Chained up to from subclass finalizers. transport the transport.
References _dbus_assert, _dbus_auth_unref, _dbus_counter_set_notify, _dbus_counter_unref, _dbus_credentials_unref, _dbus_get_autolaunch_address, _dbus_message_loader_unref, _dbus_string_free, _dbus_string_init, _dbus_transport_disconnect, _dbus_transport_open, _dbus_transport_open_platform_specific, _dbus_transport_open_socket, DBusTransport::address, DBusTransport::auth, DBusTransport::credentials, dbus_address_entries_free, dbus_address_entry_get_method, dbus_address_entry_get_value, DBUS_ERROR_NO_MEMORY, dbus_free, dbus_parse_address, dbus_set_error, DBusTransport::disconnected, DBusTransport::expected_guid, DBusTransport::free_unix_user_data, DBusTransport::free_windows_user_data, DBusTransport::live_messages, DBusTransport::loader, NULL, DBusTransport::unix_user_data, DBusTransport::windows_user_data.
static DBusTransport* check_address(const char *address, DBusError *error)
Verifies if a given D-Bus address is a valid address by attempting to connect to it.
If it is, returns the opened DBusTransport object. If it isn't, returns NULL and sets error. address the address to be checked. error address where an error can be returned. a new transport, or NULL on failure.
static DBusTransport* _dbus_transport_new_for_autolaunch(const char *scope, DBusError *error)
Creates a new transport for the "autostart" method.
This creates a client-side of a transport. scope scope of autolaunch (Windows only) error address where an error can be returned. a new transport, or NULL on failure.
static DBusTransportOpenResult _dbus_transport_open_autolaunch(DBusAddressEntry *entry, DBusTransport **transport_p, DBusError *error)
DBusTransport* _dbus_transport_open(DBusAddressEntry *entry, DBusError *error)
Try to open a new transport for the given address entry.
(This opens a client-side-of-the-connection transport.) entry the address entry error location to store reason for failure. new transport of NULL on failure.
References _DBUS_N_ELEMENTS, _dbus_set_bad_address, _dbus_strdup, dbus_address_entry_get_value, DBUS_ERROR_INIT, dbus_error_is_set, dbus_free, dbus_move_error, DBusTransport::expected_guid, NULL.
Referenced by _dbus_connection_handle_watch, _dbus_transport_finalize_base.
DBusTransport* _dbus_transport_ref(DBusTransport *transport)
Increments the reference count for the transport.
transport the transport. the transport.
References _dbus_assert, DBusTransport::refcount.
Referenced by _dbus_connection_new_for_transport, _dbus_transport_do_iteration, _dbus_transport_get_socket_fd, _dbus_transport_handle_watch, _dbus_transport_set_connection.
void _dbus_transport_unref(DBusTransport *transport)
Decrements the reference count for the transport.
Disconnects and finalizes the transport if the reference count reaches zero. transport the transport.
References _dbus_assert, DBusTransportVTable::finalize, NULL, DBusTransport::refcount, DBusTransport::vtable.
Referenced by _dbus_connection_handle_watch, _dbus_transport_do_iteration, _dbus_transport_get_socket_fd, _dbus_transport_handle_watch, _dbus_transport_set_connection, dbus_connection_ref.
void _dbus_transport_disconnect(DBusTransport *transport)
Closes our end of the connection to a remote application.
Further attempts to use this transport will fail. Only the first call to _dbus_transport_disconnect() will have an effect. transport the transport.
References _dbus_assert, DBusTransportVTable::disconnect, DBusTransport::disconnected, NULL, TRUE, DBusTransport::vtable.
Referenced by _dbus_transport_finalize_base, _dbus_transport_get_is_connected, _dbus_transport_queue_messages, _dbus_transport_try_to_authenticate, dbus_connection_unref.
dbus_bool_t _dbus_transport_get_is_connected(DBusTransport *transport)
Returns TRUE if the transport has not been disconnected.
Disconnection can result from _dbus_transport_disconnect() or because the server drops its end of the connection. transport the transport. whether we're connected
References _dbus_assert, _dbus_auth_get_identity, _dbus_connection_lock, _dbus_connection_unlock, _dbus_credentials_get_unix_uid, _dbus_credentials_get_windows_sid, _dbus_credentials_include, _dbus_credentials_new_from_current_process, _dbus_credentials_same_user, _dbus_credentials_unref, _dbus_strdup, _dbus_transport_disconnect, DBusTransport::allow_anonymous, DBusTransport::auth, DBusTransport::connection, DBUS_UID_FORMAT, DBusTransport::disconnected, FALSE, NULL, TRUE, DBusTransport::unix_user_data, DBusTransport::unix_user_function, DBusTransport::windows_user_function.
Referenced by dbus_connection_close, dbus_connection_pop_message, dbus_connection_ref, dbus_connection_unref.
static dbus_bool_t auth_via_unix_user_function(DBusTransport *transport)
static dbus_bool_t auth_via_windows_user_function(DBusTransport *transport)
static dbus_bool_t auth_via_default_rules(DBusTransport *transport)
dbus_bool_t _dbus_transport_peek_is_authenticated(DBusTransport *transport)
Returns TRUE if we have been authenticated.
It will return TRUE even if the transport is now disconnected, but was ever authenticated before disconnecting.This replaces the older _dbus_transport_get_is_authenticated() which had side-effects. transport the transport whether we're authenticated
References DBusTransport::authenticated.
Referenced by _dbus_connection_queue_received_message_link.
dbus_bool_t _dbus_transport_try_to_authenticate(DBusTransport *transport)
Returns TRUE if we have been authenticated.
It will return TRUE even if the transport is now disconnected, but was ever authenticated before disconnecting.If we have not finished authenticating, but we have enough buffered input to finish the job, then this function will do so before it returns.This used to be called _dbus_transport_get_is_authenticated(), but that name seems inappropriate for a function with side-effects.Todowe drop connection->mutex when calling the unix_user_function, and windows_user_function, which may not be safe really. transport the transport whether we're authenticated
References _dbus_assert, _dbus_auth_do_work, _dbus_auth_get_guid_from_server, _dbus_auth_get_identity, _dbus_connection_ref_unlocked, _dbus_connection_unref_unlocked, _dbus_credentials_include, _dbus_transport_disconnect, DBusTransport::auth, DBusTransport::authenticated, DBusTransport::connection, DBusTransport::disconnected, DBusTransport::expected_guid, FALSE, DBusTransport::is_server, NULL, DBusTransport::receive_credentials_pending, DBusTransport::send_credentials_pending, TRUE, DBusTransport::unix_user_function, DBusTransport::windows_user_function.
Referenced by _dbus_transport_get_dispatch_status, dbus_connection_get_adt_audit_session_data, dbus_connection_get_is_authenticated, dbus_connection_get_unix_process_id, dbus_connection_get_unix_user, dbus_connection_get_windows_user.
dbus_bool_t _dbus_transport_get_is_anonymous(DBusTransport *transport)
See dbus_connection_get_is_anonymous().
transport the transport TRUE if not authenticated or authenticated as anonymous
References _dbus_auth_get_identity, _dbus_credentials_are_anonymous, DBusTransport::auth, DBusTransport::authenticated, FALSE, TRUE.
Referenced by dbus_connection_get_is_anonymous.
dbus_bool_t _dbus_transport_can_pass_unix_fd(DBusTransport *transport)
Returns TRUE if the transport supports sending unix fds.
transport the transport TRUE if TRUE it is possible to send unix fds across the transport.
Referenced by dbus_connection_can_send_type, dbus_connection_send, dbus_connection_send_preallocated, dbus_connection_send_with_reply, dbus_connection_send_with_reply_and_block.
const char* _dbus_transport_get_address(DBusTransport *transport)
Gets the address of a transport.
It will be NULL for a server-side transport. transport the transport transport's address
References DBusTransport::address.
Referenced by dbus_connection_get_outgoing_unix_fds.
const char* _dbus_transport_get_server_id(DBusTransport *transport)
Gets the id of the server we are connected to (see dbus_server_get_id()).
Only works on client side. transport the transport transport's server's id or NULL if we are the server side
References _dbus_auth_get_guid_from_server, DBusTransport::auth, DBusTransport::authenticated, DBusTransport::expected_guid, DBusTransport::is_server, NULL.
Referenced by dbus_connection_get_server_id.
dbus_bool_t _dbus_transport_handle_watch(DBusTransport *transport, DBusWatch *watch, unsigned int condition)
Handles a watch by reading data, writing data, or disconnecting the transport, as appropriate for the given condition.
transport the transport. watch the watch. condition the current state of the watched file descriptor. FALSE if not enough memory to fully handle the watch
References _dbus_assert, _dbus_transport_ref, _dbus_transport_unref, _dbus_warn_check_failed, _dbus_watch_ref, _dbus_watch_sanitize_condition, _dbus_watch_unref, dbus_watch_get_socket, DBusTransport::disconnected, DBusTransportVTable::handle_watch, NULL, TRUE, DBusTransport::vtable.
Referenced by _dbus_connection_handle_watch.
dbus_bool_t _dbus_transport_set_connection(DBusTransport *transport, DBusConnection *connection)
Sets the connection using this transport.
Allows the transport to add watches to the connection, queue incoming messages, and pull outgoing messages. transport the transport. connection the connection. FALSE if not enough memory
References _dbus_assert, _dbus_transport_ref, _dbus_transport_unref, DBusTransport::connection, DBusTransportVTable::connection_set, NULL, DBusTransport::vtable.
Referenced by _dbus_connection_new_for_transport.
dbus_bool_t _dbus_transport_get_socket_fd(DBusTransport *transport, int *fd_p)
Get the socket file descriptor, if any.
transport the transport fd_p pointer to fill in with the descriptor TRUE if a descriptor was available
References _dbus_transport_ref, _dbus_transport_unref, DBusTransport::disconnected, FALSE, DBusTransportVTable::get_socket_fd, NULL, DBusTransport::vtable.
Referenced by dbus_connection_get_socket.
void _dbus_transport_do_iteration(DBusTransport *transport, unsigned int flags, int timeout_milliseconds)
Performs a single poll()/select() on the transport's file descriptors and then reads/writes data as appropriate, queueing incoming messages and sending outgoing messages.
This is the backend for _dbus_connection_do_iteration(). See _dbus_connection_do_iteration() for full details. transport the transport. flags indicates whether to read or write, and whether to block. timeout_milliseconds if blocking, timeout or -1 for no timeout.
References _dbus_assert, _dbus_auth_decode_data, _dbus_auth_delete_unused_bytes, _dbus_auth_get_unused_bytes, _dbus_auth_needs_decoding, _dbus_message_loader_get_buffer, _dbus_message_loader_return_buffer, _dbus_string_copy, _dbus_string_free, _dbus_string_init, _dbus_string_move, _dbus_transport_ref, _dbus_transport_unref, DBusTransport::auth, DBusTransport::disconnected, DBusTransportVTable::do_iteration, FALSE, DBusTransport::loader, NULL, TRUE, DBusTransport::vtable.
Referenced by _dbus_connection_do_iteration_unlocked.
static dbus_bool_t recover_unused_bytes(DBusTransport *transport)
DBusDispatchStatus _dbus_transport_get_dispatch_status(DBusTransport *transport)
Reports our current dispatch status (whether there's buffered data to be queued as messages, or not, or we need memory).
transport the transport current status
References _dbus_auth_do_work, _dbus_counter_get_size_value, _dbus_counter_get_unix_fd_value, _dbus_message_loader_peek_message, _dbus_message_loader_queue_messages, _dbus_transport_try_to_authenticate, DBusTransport::auth, DBUS_DISPATCH_COMPLETE, DBUS_DISPATCH_DATA_REMAINS, DBUS_DISPATCH_NEED_MEMORY, DBusTransport::live_messages, DBusTransport::loader, DBusTransport::max_live_messages_size, DBusTransport::max_live_messages_unix_fds, NULL, TRUE, DBusTransport::unused_bytes_recovered.
Referenced by _dbus_transport_queue_messages, dbus_connection_pop_message.
dbus_bool_t _dbus_transport_queue_messages(DBusTransport *transport)
Processes data we've read while handling a watch, potentially converting some of it to messages and queueing those messages on the connection.
transport the transport TRUE if we had enough memory to queue all messages
References _dbus_assert, _dbus_connection_queue_received_message_link, _dbus_message_add_counter, _dbus_message_loader_get_is_corrupted, _dbus_message_loader_pop_message_link, _dbus_message_loader_putback_message_link, _dbus_transport_disconnect, _dbus_transport_get_dispatch_status, DBusTransport::connection, DBusList::data, DBUS_DISPATCH_DATA_REMAINS, DBUS_DISPATCH_NEED_MEMORY, DBusTransport::live_messages, DBusTransportVTable::live_messages_changed, DBusTransport::loader, NULL, DBusTransport::vtable.
Referenced by dbus_connection_pop_message.
void _dbus_transport_set_max_message_size(DBusTransport *transport, long size)
See dbus_connection_set_max_message_size().
transport the transport size the max size of a single message
References _dbus_message_loader_set_max_message_size, DBusTransport::loader.
Referenced by dbus_connection_set_max_message_size.
void _dbus_transport_set_max_message_unix_fds(DBusTransport *transport, long n)
See dbus_connection_set_max_message_unix_fds().
transport the transport n the max number of unix fds of a single message
References _dbus_message_loader_set_max_message_unix_fds, DBusTransport::loader.
Referenced by dbus_connection_set_max_message_unix_fds.
long _dbus_transport_get_max_message_size(DBusTransport *transport)
See dbus_connection_get_max_message_size().
transport the transport max message size
References _dbus_message_loader_get_max_message_size, DBusTransport::loader.
Referenced by dbus_connection_get_max_message_size.
long _dbus_transport_get_max_message_unix_fds(DBusTransport *transport)
See dbus_connection_get_max_message_unix_fds().
transport the transport max message unix fds
References _dbus_message_loader_get_max_message_unix_fds, DBusTransport::loader.
Referenced by dbus_connection_get_max_message_unix_fds.
void _dbus_transport_set_max_received_size(DBusTransport *transport, long size)
See dbus_connection_set_max_received_size().
transport the transport size the max size of all incoming messages
References _dbus_counter_set_notify, DBusTransport::live_messages, DBusTransport::max_live_messages_size, DBusTransport::max_live_messages_unix_fds.
Referenced by dbus_connection_set_max_received_size.
void _dbus_transport_set_max_received_unix_fds(DBusTransport *transport, long n)
See dbus_connection_set_max_received_unix_fds().
transport the transport n the max unix fds of all incoming messages
References _dbus_counter_set_notify, DBusTransport::live_messages, DBusTransport::max_live_messages_size, DBusTransport::max_live_messages_unix_fds.
Referenced by dbus_connection_set_max_received_unix_fds.
long _dbus_transport_get_max_received_size(DBusTransport *transport)
See dbus_connection_get_max_received_size().
transport the transport max bytes for all live messages
References DBusTransport::max_live_messages_size.
Referenced by dbus_connection_get_max_received_size.
long _dbus_transport_get_max_received_unix_fds(DBusTransport *transport)
See dbus_connection_set_max_received_unix_fds().
transport the transport max unix fds for all live messages
References DBusTransport::max_live_messages_unix_fds.
Referenced by dbus_connection_get_max_received_unix_fds.
dbus_bool_t _dbus_transport_get_unix_user(DBusTransport *transport, unsigned long *uid)
See dbus_connection_get_unix_user().
transport the transport uid return location for the user ID TRUE if uid is filled in with a valid user ID
References _dbus_auth_get_identity, _dbus_credentials_get_unix_uid, _dbus_credentials_include, _DBUS_INT32_MAX, DBusTransport::auth, DBusTransport::authenticated, FALSE, TRUE.
Referenced by dbus_connection_get_unix_user.
dbus_bool_t _dbus_transport_get_unix_process_id(DBusTransport *transport, unsigned long *pid)
See dbus_connection_get_unix_process_id().
transport the transport pid return location for the process ID TRUE if uid is filled in with a valid process ID
References _dbus_auth_get_identity, _dbus_credentials_get_pid, _dbus_credentials_include, DBusTransport::auth, DBusTransport::authenticated, DBUS_PID_UNSET, FALSE, TRUE.
Referenced by dbus_connection_get_unix_process_id.
dbus_bool_t _dbus_transport_get_adt_audit_session_data(DBusTransport *transport, void **data, int *data_size)
See dbus_connection_get_adt_audit_session_data().
transport the transport data return location for the ADT audit data data_size return length of audit data TRUE if audit data is filled in with a valid ucred
References _dbus_auth_get_identity, _dbus_credentials_get_adt_audit_data, _dbus_credentials_get_adt_audit_data_size, _dbus_credentials_include, DBusTransport::auth, DBusTransport::authenticated, FALSE, NULL, TRUE.
Referenced by dbus_connection_get_adt_audit_session_data.
void _dbus_transport_set_unix_user_function(DBusTransport *transport, DBusAllowUnixUserFunction function, void *data, DBusFreeFunction free_data_function, void **old_data, DBusFreeFunction *old_free_data_function)
See dbus_connection_set_unix_user_function().
transport the transport function the predicate data data to pass to the predicate free_data_function function to free the data old_data the old user data to be freed old_free_data_function old free data function to free it with
References DBusTransport::free_unix_user_data, DBusTransport::unix_user_data, DBusTransport::unix_user_function.
Referenced by dbus_connection_set_unix_user_function.
dbus_bool_t _dbus_transport_get_windows_user(DBusTransport *transport, char **windows_sid_p)
See dbus_connection_get_windows_user().
transport the transport windows_sid_p return location for the user ID TRUE if user is available; the returned value may still be NULL if no memory to copy it
References _dbus_auth_get_identity, _dbus_credentials_get_windows_sid, _dbus_credentials_include, _dbus_strdup, DBusTransport::auth, DBusTransport::authenticated, FALSE, NULL, TRUE.
Referenced by dbus_connection_get_windows_user.
void _dbus_transport_set_windows_user_function(DBusTransport *transport, DBusAllowWindowsUserFunction function, void *data, DBusFreeFunction free_data_function, void **old_data, DBusFreeFunction *old_free_data_function)
See dbus_connection_set_windows_user_function().
transport the transport function the predicate data data to pass to the predicate free_data_function function to free the data old_data the old user data to be freed old_free_data_function old free data function to free it with
References DBusTransport::free_windows_user_data, DBusTransport::windows_user_data, DBusTransport::windows_user_function.
Referenced by dbus_connection_set_windows_user_function.
dbus_bool_t _dbus_transport_set_auth_mechanisms(DBusTransport *transport, const char **mechanisms)
Sets the SASL authentication mechanisms supported by this transport.
transport the transport mechanisms the NULL-terminated array of mechanisms FALSE if no memory
References _dbus_auth_set_mechanisms, DBusTransport::auth.
void _dbus_transport_set_allow_anonymous(DBusTransport *transport, dbus_bool_t value)
See dbus_connection_set_allow_anonymous()
transport the transport value TRUE to allow anonymous connection
References DBusTransport::allow_anonymous, FALSE.
Referenced by dbus_connection_set_allow_anonymous.
int _dbus_transport_get_pending_fds_count(DBusTransport *transport)
Return how many file descriptors are pending in the loader.
transport the transport
References _dbus_message_loader_get_pending_fds_count, DBusTransport::loader.
Referenced by _dbus_connection_get_pending_fds_count.
void _dbus_transport_set_pending_fds_function(DBusTransport *transport, void(*callback)(void *), void *data)
Register a function to be called whenever the number of pending file descriptors in the loader change.
transport the transport callback the callback
References _dbus_counter_get_size_value, _dbus_counter_get_unix_fd_value, _dbus_message_loader_set_pending_fds_function, DBusTransport::live_messages, DBusTransport::loader, NULL.
Referenced by _dbus_connection_set_pending_fds_function.