DBusHashTable
DBusHashType
Hash keys are strings.
typedef int(* KeyCompareFunc) (const void *key_a, const void *key_b))(const void *key_a, const void *key_b)
Key comparison function.
DBusHashTable
Public opaque hash table object.
DBusHashIter
Public opaque hash table iterator object.
typedef struct DBusPreallocatedHash DBusPreallocatedHash
A preallocated hash entry.
DBusHashTable * _dbus_hash_table_new(DBusHashType type, DBusFreeFunction key_free_function, DBusFreeFunction value_free_function)
Constructs a new hash table.
Should be freed with _dbus_hash_table_unref(). If memory cannot be allocated for the hash table, returns NULL. type the type of hash key to use. key_free_function function to free hash keys. value_free_function function to free hash values. a new DBusHashTable or NULL if no memory.
References _dbus_assert, _dbus_assert_not_reached, _dbus_mem_pool_new, _DBUS_N_ELEMENTS, buckets, dbus_free, DBUS_HASH_INT, DBUS_HASH_STRING, DBUS_HASH_UINTPTR, dbus_new0, DBUS_SMALL_HASH_TABLE, down_shift, entry_pool, find_function, free_key_function, free_value_function, hi_rebuild_size, key_type, lo_rebuild_size, mask, n_buckets, n_entries, NULL, REBUILD_MULTIPLIER, refcount, static_buckets, TRUE.
Referenced by _dbus_connection_handle_watch, _dbus_connection_new_for_transport, _dbus_hash_table_get_n_entries, _dbus_user_database_new.
DBusHashTable * _dbus_hash_table_ref(DBusHashTable *table)
Increments the reference count for a hash table.
table the hash table to add a reference to. the hash table.
References refcount.
Referenced by _dbus_hash_table_get_n_entries.
void _dbus_hash_table_unref(DBusHashTable *table)
Decrements the reference count for a hash table, freeing the hash table if the count reaches zero.
table the hash table to remove a reference from.
References _dbus_mem_pool_free, buckets, dbus_free, entry_pool, n_buckets, DBusHashEntry::next, NULL, refcount, static_buckets.
Referenced by _dbus_connection_handle_watch, _dbus_connection_new_for_transport, _dbus_hash_table_get_n_entries, _dbus_user_database_unref, dbus_connection_ref.
void _dbus_hash_table_remove_all(DBusHashTable *table)
Removed all entries from a hash table.
table the hash table to remove all entries from.
References _dbus_assert, _dbus_hash_iter_init, _dbus_hash_iter_next, _dbus_hash_iter_remove_entry, _dbus_mem_pool_alloc, _dbus_mem_pool_dealloc, entry_pool, free_key_function, free_value_function, DBusHashEntry::key, n_entries, DBusHashEntry::next, NULL, DBusHashEntry::value.
Referenced by _dbus_user_database_flush.
void _dbus_hash_iter_init(DBusHashTable *table, DBusHashIter *iter)
Initializes a hash table iterator.
To iterate over all entries in a hash table, use the following code (the printf assumes a hash from strings to strings obviously):DBusHashIteriter; _dbus_hash_iter_init(table,&iter); while(_dbus_hash_iter_next(&iter)) { printf("Thefirstkeyis%sandvalueis%s\n", _dbus_hash_iter_get_string_key(&iter), _dbus_hash_iter_get_value(&iter)); } The iterator is initialized pointing "one before" the first hash entry. The first call to _dbus_hash_iter_next() moves it onto the first valid entry or returns FALSE if the hash table is empty. Subsequent calls move to the next valid entry or return FALSE if there are no more entries.Note that it is guaranteed to be safe to remove a hash entry during iteration, but it is not safe to add a hash entry. table the hash table to iterate over. iter the iterator to initialize.
References DBusRealHashIter::bucket, DBusRealHashIter::entry, n_entries, DBusRealHashIter::n_entries_on_init, DBusRealHashIter::next_bucket, DBusRealHashIter::next_entry, NULL, DBusRealHashIter::table.
Referenced by _dbus_connection_close_if_only_one_ref, _dbus_connection_handle_watch, _dbus_hash_table_get_n_entries, _dbus_hash_table_remove_all.
dbus_bool_t _dbus_hash_iter_next(DBusHashIter *iter)
Move the hash iterator forward one step, to the next hash entry.
The documentation for _dbus_hash_iter_init() explains in more detail. iter the iterator to move forward. FALSE if there are no more entries to move to.
References _dbus_assert, DBusRealHashIter::bucket, buckets, DBusRealHashIter::entry, FALSE, n_buckets, n_entries, DBusRealHashIter::n_entries_on_init, DBusHashEntry::next, DBusRealHashIter::next_bucket, DBusRealHashIter::next_entry, NULL, DBusRealHashIter::table, TRUE.
Referenced by _dbus_connection_close_if_only_one_ref, _dbus_connection_handle_watch, _dbus_hash_table_get_n_entries, _dbus_hash_table_remove_all.
void _dbus_hash_iter_remove_entry(DBusHashIter *iter)
Removes the current entry from the hash table.
If a key_free_function or value_free_function was provided to _dbus_hash_table_new(), frees the key and/or value for this entry. iter the hash table iterator.
References _dbus_assert, DBusRealHashIter::bucket, DBusRealHashIter::entry, NULL, DBusRealHashIter::table.
Referenced by _dbus_connection_close_if_only_one_ref, _dbus_hash_table_get_n_entries, _dbus_hash_table_remove_all.
void * _dbus_hash_iter_get_value(DBusHashIter *iter)
Gets the value of the current entry.
iter the hash table iterator.
References _dbus_assert, DBusRealHashIter::entry, NULL, DBusRealHashIter::table, DBusHashEntry::value.
Referenced by _dbus_connection_close_if_only_one_ref, _dbus_connection_handle_watch, _dbus_hash_table_get_n_entries.
void _dbus_hash_iter_set_value(DBusHashIter *iter, void *value)
Sets the value of the current entry.
If the hash table has a value_free_function it will be used to free the previous value. The hash table will own the passed-in value (it will not be copied). iter the hash table iterator. value the new value.
References _dbus_assert, DBusRealHashIter::entry, free_value_function, NULL, DBusRealHashIter::table, DBusHashEntry::value.
Referenced by _dbus_hash_table_get_n_entries.
int _dbus_hash_iter_get_int_key(DBusHashIter *iter)
Gets the key for the current entry.
Only works for hash tables of type DBUS_HASH_INT. iter the hash table iterator.
References _dbus_assert, _DBUS_POINTER_TO_INT, DBusRealHashIter::entry, DBusHashEntry::key, NULL, DBusRealHashIter::table.
Referenced by _dbus_hash_table_get_n_entries.
uintptr_t _dbus_hash_iter_get_uintptr_key(DBusHashIter *iter)
Gets the key for the current entry.
Only works for hash tables of type DBUS_HASH_UINTPTR. iter the hash table iterator.
References _dbus_assert, DBusRealHashIter::entry, DBusHashEntry::key, NULL, DBusRealHashIter::table.
const char * _dbus_hash_iter_get_string_key(DBusHashIter *iter)
Gets the key for the current entry.
Only works for hash tables of type DBUS_HASH_STRING iter the hash table iterator.
References _dbus_assert, DBusRealHashIter::entry, DBusHashEntry::key, NULL, DBusRealHashIter::table.
Referenced by _dbus_hash_table_get_n_entries.
dbus_bool_t _dbus_hash_iter_lookup(DBusHashTable *table, void *key, dbus_bool_t create_if_not_found, DBusHashIter *iter)
A low-level but efficient interface for manipulating the hash table.
It's efficient because you can get, set, and optionally create the hash entry while only running the hash function one time.Note that while calling _dbus_hash_iter_next() on the iterator filled in by this function may work, it's completely undefined which entries are after this iter and which are before it. So it would be silly to iterate using this iterator.If the hash entry is created, its value will be initialized to all bits zero.FALSE may be returned due to memory allocation failure, or because create_if_not_found was FALSE and the entry did not exist.If create_if_not_found is TRUE and the entry is created, the hash table takes ownership of the key that's passed in.For a hash table of type DBUS_HASH_INT, cast the int key to the key parameter using _DBUS_INT_TO_POINTER(). table the hash table. key the hash key. create_if_not_found if TRUE, create the entry if it didn't exist. iter the iterator to initialize. TRUE if the hash entry now exists (and the iterator is thus valid).
References _dbus_assert, DBusRealHashIter::bucket, buckets, DBusRealHashIter::entry, FALSE, find_function, hi_rebuild_size, DBusHashEntry::key, lo_rebuild_size, n_entries, DBusRealHashIter::n_entries_on_init, DBusHashEntry::next, DBusRealHashIter::next_bucket, DBusRealHashIter::next_entry, NULL, DBusRealHashIter::table, TRUE.
Referenced by _dbus_hash_table_get_n_entries.
static void add_allocated_entry(DBusHashTable *table, DBusHashEntry *entry, unsigned int idx, void *key, DBusHashEntry ***bucket)
static DBusHashEntry* add_entry(DBusHashTable *table, unsigned int idx, void *key, DBusHashEntry ***bucket, DBusPreallocatedHash *preallocated)
static DBusHashEntry* find_generic_function(DBusHashTable *table, void *key, unsigned int idx, KeyCompareFunc compare_func, dbus_bool_t create_if_not_found, DBusHashEntry ***bucket, DBusPreallocatedHash *preallocated)
void * _dbus_hash_table_lookup_string(DBusHashTable *table, const char *key)
Looks up the value for a given string in a hash table of type DBUS_HASH_STRING.
Returns NULL if the value is not present. (A not-present entry is indistinguishable from an entry with a value of NULL.) table the hash table. key the string to look up. the value of the hash entry.
References _dbus_assert, DBUS_HASH_STRING, FALSE, find_function, DBusHashEntry::key, key_type, NULL, DBusHashEntry::value.
Referenced by _dbus_connection_handle_watch, _dbus_hash_table_get_n_entries, _dbus_user_database_lookup, _dbus_user_database_lookup_group.
void * _dbus_hash_table_lookup_int(DBusHashTable *table, int key)
Looks up the value for a given integer in a hash table of type DBUS_HASH_INT.
Returns NULL if the value is not present. (A not-present entry is indistinguishable from an entry with a value of NULL.) table the hash table. key the integer to look up. the value of the hash entry.
References _dbus_assert, _DBUS_INT_TO_POINTER, DBUS_HASH_INT, FALSE, find_function, key_type, NULL, DBusHashEntry::value.
Referenced by _dbus_connection_queue_received_message_link, _dbus_hash_table_get_n_entries, dbus_connection_dispatch.
void * _dbus_hash_table_lookup_uintptr(DBusHashTable *table, uintptr_t key)
Looks up the value for a given integer in a hash table of type DBUS_HASH_UINTPTR.
Returns NULL if the value is not present. (A not-present entry is indistinguishable from an entry with a value of NULL.) table the hash table. key the integer to look up. the value of the hash entry.
References _dbus_assert, DBUS_HASH_UINTPTR, FALSE, find_function, DBusHashEntry::key, key_type, NULL, DBusHashEntry::value.
Referenced by _dbus_hash_table_get_n_entries, _dbus_user_database_lookup, _dbus_user_database_lookup_group.
dbus_bool_t _dbus_hash_table_remove_string(DBusHashTable *table, const char *key)
Removes the hash entry for the given key.
If no hash entry for the key exists, does nothing. table the hash table. key the hash key. TRUE if the entry existed
References _dbus_assert, DBUS_HASH_STRING, FALSE, find_function, DBusHashEntry::key, key_type, NULL, TRUE.
Referenced by _dbus_connection_handle_watch, _dbus_hash_table_get_n_entries.
dbus_bool_t _dbus_hash_table_remove_int(DBusHashTable *table, int key)
Removes the hash entry for the given key.
If no hash entry for the key exists, does nothing. table the hash table. key the hash key. TRUE if the entry existed
References _dbus_assert, _DBUS_INT_TO_POINTER, DBUS_HASH_INT, FALSE, find_function, key_type, NULL, TRUE.
Referenced by _dbus_connection_toggle_timeout_unlocked, _dbus_hash_table_get_n_entries.
dbus_bool_t _dbus_hash_table_remove_uintptr(DBusHashTable *table, uintptr_t key)
Removes the hash entry for the given key.
If no hash entry for the key exists, does nothing. table the hash table. key the hash key. TRUE if the entry existed
References _dbus_assert, DBUS_HASH_UINTPTR, FALSE, find_function, DBusHashEntry::key, key_type, NULL, TRUE.
Referenced by _dbus_hash_table_get_n_entries, _dbus_user_database_lookup, _dbus_user_database_lookup_group.
dbus_bool_t _dbus_hash_table_insert_string(DBusHashTable *table, char *key, void *value)
Creates a hash entry with the given key and value.
The key and value are not copied; they are stored in the hash table by reference. If an entry with the given key already exists, the previous key and value are overwritten (and freed if the hash table has a key_free_function and/or value_free_function).Returns FALSE if memory for the new hash entry can't be allocated. table the hash table. key the hash entry key. value the hash entry value.
References _dbus_assert, _dbus_hash_table_insert_string_preallocated, _dbus_hash_table_preallocate_entry, DBUS_HASH_STRING, FALSE, key_type, NULL, TRUE.
Referenced by _dbus_connection_handle_watch, _dbus_hash_table_get_n_entries, _dbus_user_database_lookup, _dbus_user_database_lookup_group.
dbus_bool_t _dbus_hash_table_insert_int(DBusHashTable *table, int key, void *value)
Creates a hash entry with the given key and value.
The key and value are not copied; they are stored in the hash table by reference. If an entry with the given key already exists, the previous key and value are overwritten (and freed if the hash table has a key_free_function and/or value_free_function).Returns FALSE if memory for the new hash entry can't be allocated. table the hash table. key the hash entry key. value the hash entry value.
References _dbus_assert, _DBUS_INT_TO_POINTER, DBUS_HASH_INT, FALSE, find_function, free_key_function, free_value_function, DBusHashEntry::key, key_type, NULL, TRUE, DBusHashEntry::value.
Referenced by _dbus_connection_toggle_timeout_unlocked, _dbus_hash_table_get_n_entries.
dbus_bool_t _dbus_hash_table_insert_uintptr(DBusHashTable *table, uintptr_t key, void *value)
Creates a hash entry with the given key and value.
The key and value are not copied; they are stored in the hash table by reference. If an entry with the given key already exists, the previous key and value are overwritten (and freed if the hash table has a key_free_function and/or value_free_function).Returns FALSE if memory for the new hash entry can't be allocated. table the hash table. key the hash entry key. value the hash entry value.
References _dbus_assert, DBUS_HASH_UINTPTR, FALSE, find_function, free_key_function, free_value_function, DBusHashEntry::key, key_type, NULL, TRUE, DBusHashEntry::value.
Referenced by _dbus_hash_table_get_n_entries, _dbus_user_database_lookup, _dbus_user_database_lookup_group.
DBusPreallocatedHash * _dbus_hash_table_preallocate_entry(DBusHashTable *table)
Preallocate an opaque data blob that allows us to insert into the hash table at a later time without allocating any memory.
table the hash table the preallocated data, or NULL if no memory
Referenced by _dbus_hash_table_insert_string.
void _dbus_hash_table_free_preallocated_entry(DBusHashTable *table, DBusPreallocatedHash *preallocated)
Frees an opaque DBusPreallocatedHash that was not used in order to insert into the hash table.
table the hash table preallocated the preallocated data
References _dbus_assert, _dbus_mem_pool_dealloc, entry_pool, NULL.
void _dbus_hash_table_insert_string_preallocated(DBusHashTable *table, DBusPreallocatedHash *preallocated, char *key, void *value)
Inserts a string-keyed entry into the hash table, using a preallocated data block from _dbus_hash_table_preallocate_entry().
This function cannot fail due to lack of memory. The DBusPreallocatedHash object is consumed and should not be reused or freed. Otherwise this function works just like _dbus_hash_table_insert_string(). table the hash table preallocated the preallocated data key the hash key value the value
References _dbus_assert, DBUS_HASH_STRING, find_function, free_key_function, free_value_function, DBusHashEntry::key, key_type, NULL, TRUE, DBusHashEntry::value.
Referenced by _dbus_hash_table_insert_string.
int _dbus_hash_table_get_n_entries(DBusHashTable *table)
Gets the number of hash entries in a hash table.
table the hash table. the number of entries in the table.
References _dbus_assert, _dbus_assert_not_reached, _dbus_hash_iter_get_int_key, _dbus_hash_iter_get_string_key, _dbus_hash_iter_get_value, _dbus_hash_iter_init, _dbus_hash_iter_lookup, _dbus_hash_iter_next, _dbus_hash_iter_remove_entry, _dbus_hash_iter_set_value, _dbus_hash_table_insert_int, _dbus_hash_table_insert_string, _dbus_hash_table_insert_uintptr, _dbus_hash_table_lookup_int, _dbus_hash_table_lookup_string, _dbus_hash_table_lookup_uintptr, _dbus_hash_table_new, _dbus_hash_table_ref, _dbus_hash_table_remove_int, _dbus_hash_table_remove_string, _dbus_hash_table_remove_uintptr, _dbus_hash_table_unref, _DBUS_INT_TO_POINTER, _dbus_strdup, dbus_free, DBUS_HASH_INT, DBUS_HASH_STRING, DBUS_HASH_UINTPTR, dbus_malloc, dbus_new, FALSE, DBusHashEntry::key, n_entries, NULL, TRUE, DBusHashEntry::value.
Referenced by _dbus_connection_close_if_only_one_ref, _dbus_connection_handle_watch.