DBusTransportSocket
typedef struct DBusTransportSocket DBusTransportSocket
Opaque object representing a socket file descriptor transport.
const DBusTransportVTable socket_vtable
static void free_watches(DBusTransport *transport)
static void socket_finalize(DBusTransport *transport)
static void check_write_watch(DBusTransport *transport)
static void check_read_watch(DBusTransport *transport)
static void do_io_error(DBusTransport *transport)
static dbus_bool_t read_data_into_auth(DBusTransport *transport, dbus_bool_t *oom)
static dbus_bool_t write_data_from_auth(DBusTransport *transport)
static dbus_bool_t exchange_credentials(DBusTransport *transport, dbus_bool_t do_reading, dbus_bool_t do_writing)
static dbus_bool_t do_authentication(DBusTransport *transport, dbus_bool_t do_reading, dbus_bool_t do_writing, dbus_bool_t *auth_completed)
static dbus_bool_t do_writing(DBusTransport *transport)
static dbus_bool_t do_reading(DBusTransport *transport)
static dbus_bool_t unix_error_with_read_to_come(DBusTransport *itransport, DBusWatch *watch, unsigned int flags)
static dbus_bool_t socket_handle_watch(DBusTransport *transport, DBusWatch *watch, unsigned int flags)
static void socket_disconnect(DBusTransport *transport)
static dbus_bool_t socket_connection_set(DBusTransport *transport)
static void socket_do_iteration(DBusTransport *transport, unsigned int flags, int timeout_milliseconds)
TodoWe need to have a way to wake up the select sleep if a new iteration request comes in with a flag (read/write) that we're not currently serving.Otherwise a call that just reads could block a write call forever (if there are no incoming messages).
static void socket_live_messages_changed(DBusTransport *transport)
static dbus_bool_t socket_get_socket_fd(DBusTransport *transport, int *fd_p)
DBusTransport* _dbus_transport_new_for_socket(int fd, const DBusString *server_guid, const DBusString *address)
Creates a new transport for the given socket file descriptor.
The file descriptor must be nonblocking (use _dbus_set_fd_nonblocking() to make it so). This function is shared by various transports that boil down to a full duplex file descriptor. fd the file descriptor. server_guid non-NULL if this transport is on the server side of a connection address the transport's address the new transport, or NULL if no memory.
References _dbus_auth_set_unix_fd_possible, _dbus_socket_can_pass_unix_fd, _dbus_string_free, _dbus_string_init, _dbus_transport_init_base, _dbus_watch_invalidate, _dbus_watch_new, _dbus_watch_unref, DBusTransport::auth, base, dbus_free, dbus_new0, DBUS_WATCH_READABLE, DBUS_WATCH_WRITABLE, encoded_incoming, encoded_outgoing, FALSE, fd, max_bytes_read_per_iteration, max_bytes_written_per_iteration, message_bytes_written, NULL, read_watch, write_watch.
Referenced by _dbus_transport_new_for_domain_socket, _dbus_transport_new_for_tcp_socket.
DBusTransport* _dbus_transport_new_for_tcp_socket(const char *host, const char *port, const char *family, const char *noncefile, DBusError *error)
Creates a new transport for the given hostname and port.
If host is NULL, it will default to localhost host the host to connect to port the port to connect to family the address family to connect to noncefile path to nonce file error location to store reason for failure. a new transport, or NULL on failure.
References _dbus_close_socket, _dbus_string_append, _dbus_string_free, _dbus_string_init, _dbus_transport_new_for_socket, DBUS_ERROR_NO_MEMORY, dbus_set_error, fd, NULL.
Referenced by _dbus_transport_open_socket.
DBusTransportOpenResult _dbus_transport_open_socket(DBusAddressEntry *entry, DBusTransport **transport_p, DBusError *error)
Opens a TCP socket transport.
entry the address entry to try opening as a tcp transport. transport_p return location for the opened transport error error to be set result of the attempt
References _dbus_assert, _dbus_set_bad_address, _dbus_transport_new_for_tcp_socket, dbus_address_entry_get_method, dbus_address_entry_get_value, NULL, TRUE.
Referenced by _dbus_transport_finalize_base.