DBusConnectionInternals
typedef struct DBusMessageFilter DBusMessageFilter
Internal struct representing a message filter function.
typedef dbus_bool_t(* DBusWatchAddFunction) (DBusWatchList *list, DBusWatch *watch))(DBusWatchList *list, DBusWatch *watch)
Function to be called in protected_change_watch() with refcount held.
typedef void(* DBusWatchRemoveFunction) (DBusWatchList *list, DBusWatch *watch))(DBusWatchList *list, DBusWatch *watch)
Function to be called in protected_change_watch() with refcount held.
typedef void(* DBusWatchToggleFunction) (DBusWatchList *list, DBusWatch *watch, dbus_bool_t enabled))(DBusWatchList *list, DBusWatch *watch, dbus_bool_t enabled)
Function to be called in protected_change_watch() with refcount held.
typedef dbus_bool_t(* DBusTimeoutAddFunction) (DBusTimeoutList *list, DBusTimeout *timeout))(DBusTimeoutList *list, DBusTimeout *timeout)
Function to be called in protected_change_timeout() with refcount held.
typedef void(* DBusTimeoutRemoveFunction) (DBusTimeoutList *list, DBusTimeout *timeout))(DBusTimeoutList *list, DBusTimeout *timeout)
Function to be called in protected_change_timeout() with refcount held.
typedef void(* DBusTimeoutToggleFunction) (DBusTimeoutList *list, DBusTimeout *timeout, dbus_bool_t enabled))(DBusTimeoutList *list, DBusTimeout *timeout, dbus_bool_t enabled)
Function to be called in protected_change_timeout() with refcount held.
dbus_bool_t _dbus_modify_sigpipe
DBusHashTable* shared_connections
DBusList* shared_connections_no_guid
static void _dbus_connection_trace_ref(DBusConnection *connection, int old_refcount, int new_refcount, const char *why)
static DBusDispatchStatus _dbus_connection_get_dispatch_status_unlocked(DBusConnection *connection)
static void _dbus_connection_update_dispatch_status_and_unlock(DBusConnection *connection, DBusDispatchStatus new_status)
static void _dbus_connection_last_unref(DBusConnection *connection)
static void _dbus_connection_acquire_dispatch(DBusConnection *connection)
Acquire the dispatcher.
This is a separate lock so the main connection lock can be dropped to call out to application dispatch handlers. connection the connection.
static void _dbus_connection_release_dispatch(DBusConnection *connection)
Release the dispatcher when you're done with it.
Only call after you've acquired the dispatcher. Wakes up at most one thread currently waiting to acquire the dispatcher. connection the connection.
static DBusDispatchStatus _dbus_connection_flush_unlocked(DBusConnection *connection)
Blocks until the outgoing message queue is empty.
Assumes connection lock already held.If you call this, you MUST call update_dispatch_status afterword... connection the connection.
static void _dbus_connection_close_possibly_shared_and_unlock(DBusConnection *connection)
static dbus_bool_t _dbus_connection_get_is_connected_unlocked(DBusConnection *connection)
static dbus_bool_t _dbus_connection_peek_for_reply_unlocked(DBusConnection *connection, dbus_uint32_t client_serial)
static DBusMessageFilter* _dbus_message_filter_ref(DBusMessageFilter *filter)
static void _dbus_message_filter_unref(DBusMessageFilter *filter)
void _dbus_connection_lock(DBusConnection *connection)
Acquires the connection lock.
connection the connection.
References CONNECTION_LOCK.
Referenced by _dbus_object_tree_dispatch_and_unlock, _dbus_transport_get_is_connected.
void _dbus_connection_unlock(DBusConnection *connection)
Releases the connection lock.
connection the connection.
References _dbus_list_free_link, _dbus_list_pop_first_link, _dbus_rmutex_unlock, DBusList::data, dbus_message_unref, DBusConnection::dispatch_cond, DBusConnection::dispatch_mutex, DBusConnection::expired_messages, DBusConnection::io_path_cond, DBusConnection::io_path_mutex, DBusConnection::mutex, NULL, DBusConnection::wakeup_main_data, DBusConnection::wakeup_main_function.
Referenced by _dbus_object_tree_dispatch_and_unlock, _dbus_object_tree_free_all_unlocked, _dbus_object_tree_list_registered_and_unlock, _dbus_object_tree_unregister_and_unlock, _dbus_transport_get_is_connected.
static void _dbus_connection_wakeup_mainloop(DBusConnection *connection)
Wakes up the main loop if it is sleeping Needed if we're e.g.
queueing outgoing messages on a thread while the mainloop sleeps. connection the connection.
void _dbus_connection_queue_received_message_link(DBusConnection *connection, DBusList *link)
Adds a message-containing list link to the incoming message queue, taking ownership of the link and the message's current refcount.
Cannot fail due to lack of memory. connection the connection. link the message link to queue.
References _dbus_assert, _dbus_connection_remove_timeout_unlocked, _dbus_hash_table_lookup_int, _dbus_list_append_link, _dbus_pending_call_get_timeout_unlocked, _dbus_pending_call_is_timeout_added_unlocked, _dbus_pending_call_set_timeout_added_unlocked, _dbus_transport_peek_is_authenticated, DBusList::data, dbus_message_get_interface, dbus_message_get_member, dbus_message_get_path, dbus_message_get_reply_serial, dbus_message_get_signature, dbus_message_get_type, dbus_message_type_to_string, FALSE, DBusConnection::incoming_messages, DBusConnection::n_incoming, NULL, DBusConnection::pending_replies, DBusConnection::transport.
Referenced by _dbus_transport_queue_messages.
void _dbus_connection_queue_synthesized_message_link(DBusConnection *connection, DBusList *link)
Adds a link + message to the incoming message queue.
Can't fail. Takes ownership of both link and message. connection the connection. link the list node and message to queue.
References _dbus_list_append_link, DBusList::data, DBusConnection::incoming_messages, DBusConnection::n_incoming.
Referenced by _dbus_pending_call_queue_timeout_error_unlocked, dbus_connection_pop_message.
dbus_bool_t _dbus_connection_has_messages_to_send_unlocked(DBusConnection *connection)
Checks whether there are messages in the outgoing message queue.
Called with connection lock held. connection the connection. TRUE if the outgoing queue is non-empty.
References NULL, DBusConnection::outgoing_messages.
Referenced by dbus_connection_has_messages_to_send.
dbus_bool_t dbus_connection_has_messages_to_send(DBusConnection *connection)
Checks whether there are messages in the outgoing message queue.
Use dbus_connection_flush() to block until all outgoing messages have been written to the underlying transport (such as a socket). connection the connection. TRUE if the outgoing queue is non-empty.
References _dbus_connection_has_messages_to_send_unlocked, CONNECTION_LOCK, CONNECTION_UNLOCK, FALSE, NULL.
DBusMessage* _dbus_connection_get_message_to_send(DBusConnection *connection)
Gets the next outgoing message.
The message remains in the queue, and the caller does not own a reference to it. connection the connection. the message to be sent.
References _dbus_list_get_last, DBusConnection::outgoing_messages.
void _dbus_connection_message_sent_unlocked(DBusConnection *connection, DBusMessage *message)
Notifies the connection that a message has been sent, so the message can be removed from the outgoing queue.
Called with the connection lock held. connection the connection. message the message that was sent.
References _dbus_assert, _dbus_list_get_last_link, _dbus_list_prepend_link, _dbus_list_unlink, _dbus_message_remove_counter, DBusList::data, dbus_message_get_interface, dbus_message_get_member, dbus_message_get_path, dbus_message_get_signature, dbus_message_get_type, dbus_message_type_to_string, DBusConnection::expired_messages, DBusConnection::n_outgoing, NULL, DBusConnection::outgoing_counter, DBusConnection::outgoing_messages.
Referenced by dbus_connection_pop_message.
static dbus_bool_t protected_change_watch(DBusConnection *connection, DBusWatch *watch, DBusWatchAddFunction add_function, DBusWatchRemoveFunction remove_function, DBusWatchToggleFunction toggle_function, dbus_bool_t enabled)
dbus_bool_t _dbus_connection_add_watch_unlocked(DBusConnection *connection, DBusWatch *watch)
Adds a watch using the connection's DBusAddWatchFunction if available.
Otherwise records the watch to be added when said function is available. Also re-adds the watch if the DBusAddWatchFunction changes. May fail due to lack of memory. Connection lock should be held when calling this. connection the connection. watch the watch to add. TRUE on success.
References _dbus_watch_list_add_watch, FALSE, NULL.
void _dbus_connection_remove_watch_unlocked(DBusConnection *connection, DBusWatch *watch)
Removes a watch using the connection's DBusRemoveWatchFunction if available.
It's an error to call this function on a watch that was not previously added. Connection lock should be held when calling this. connection the connection. watch the watch to remove.
References _dbus_watch_list_remove_watch, FALSE, NULL.
void _dbus_connection_toggle_watch_unlocked(DBusConnection *connection, DBusWatch *watch, dbus_bool_t enabled)
Toggles a watch and notifies app via connection's DBusWatchToggledFunction if available.
It's an error to call this function on a watch that was not previously added. Connection lock should be held when calling this. connection the connection. watch the watch to toggle. enabled whether to enable or disable
References _dbus_assert, _dbus_watch_list_toggle_watch, NULL.
static dbus_bool_t protected_change_timeout(DBusConnection *connection, DBusTimeout *timeout, DBusTimeoutAddFunction add_function, DBusTimeoutRemoveFunction remove_function, DBusTimeoutToggleFunction toggle_function, dbus_bool_t enabled)
dbus_bool_t _dbus_connection_add_timeout_unlocked(DBusConnection *connection, DBusTimeout *timeout)
Adds a timeout using the connection's DBusAddTimeoutFunction if available.
Otherwise records the timeout to be added when said function is available. Also re-adds the timeout if the DBusAddTimeoutFunction changes. May fail due to lack of memory. The timeout will fire repeatedly until removed. Connection lock should be held when calling this. connection the connection. timeout the timeout to add. TRUE on success.
References _dbus_timeout_list_add_timeout, FALSE, NULL.
Referenced by _dbus_connection_toggle_timeout_unlocked.
void _dbus_connection_remove_timeout_unlocked(DBusConnection *connection, DBusTimeout *timeout)
Removes a timeout using the connection's DBusRemoveTimeoutFunction if available.
It's an error to call this function on a timeout that was not previously added. Connection lock should be held when calling this. connection the connection. timeout the timeout to remove.
References _dbus_timeout_list_remove_timeout, FALSE, NULL.
Referenced by _dbus_connection_close_if_only_one_ref, _dbus_connection_queue_received_message_link, _dbus_connection_toggle_timeout_unlocked, dbus_connection_send.
void _dbus_connection_toggle_timeout_unlocked(DBusConnection *connection, DBusTimeout *timeout, dbus_bool_t enabled)
Toggles a timeout and notifies app via connection's DBusTimeoutToggledFunction if available.
It's an error to call this function on a timeout that was not previously added. Connection lock should be held when calling this. connection the connection. timeout the timeout to toggle. enabled whether to enable or disable
References _dbus_assert, _dbus_connection_add_timeout_unlocked, _dbus_connection_ref_unlocked, _dbus_connection_remove_timeout_unlocked, _dbus_connection_unref_unlocked, _dbus_hash_table_insert_int, _dbus_hash_table_remove_int, _dbus_pending_call_get_connection_unlocked, _dbus_pending_call_get_reply_serial_unlocked, _dbus_pending_call_get_timeout_unlocked, _dbus_pending_call_is_timeout_added_unlocked, _dbus_pending_call_ref_unlocked, _dbus_pending_call_set_timeout_added_unlocked, _dbus_pending_call_unref_and_unlock, _dbus_timeout_list_toggle_timeout, CONNECTION_LOCK, FALSE, NULL, DBusConnection::pending_replies, TRUE.
static dbus_bool_t _dbus_connection_attach_pending_call_unlocked(DBusConnection *connection, DBusPendingCall *pending)
static void free_pending_call_on_hash_removal(void *data)
static void _dbus_connection_detach_pending_call_unlocked(DBusConnection *connection, DBusPendingCall *pending)
static void _dbus_connection_detach_pending_call_and_unlock(DBusConnection *connection, DBusPendingCall *pending)
void _dbus_connection_remove_pending_call(DBusConnection *connection, DBusPendingCall *pending)
Removes a pending call from the connection, such that the pending reply will be ignored.
May drop the last reference to the pending call. connection the connection pending the pending call
References _dbus_assert, _dbus_cmutex_lock, _dbus_cmutex_unlock, _dbus_condvar_wait, _dbus_condvar_wait_timeout, _dbus_condvar_wake_one, _dbus_connection_ref_unlocked, _dbus_connection_unref_unlocked, CONNECTION_LOCK, CONNECTION_UNLOCK, FALSE, DBusConnection::io_path_acquired, DBusConnection::io_path_cond, DBusConnection::io_path_mutex, TRUE.
Referenced by dbus_pending_call_cancel.
static dbus_bool_t _dbus_connection_acquire_io_path(DBusConnection *connection, int timeout_milliseconds)
Acquire the transporter I/O path.
This must be done before doing any I/O in the transporter. May sleep and drop the IO path mutex while waiting for the I/O path. connection the connection. timeout_milliseconds maximum blocking time, or -1 for no limit. TRUE if the I/O path was acquired.
static void _dbus_connection_release_io_path(DBusConnection *connection)
Release the I/O path when you're done with it.
Only call after you've acquired the I/O. Wakes up at most one thread currently waiting to acquire the I/O path. connection the connection.
void _dbus_connection_do_iteration_unlocked(DBusConnection *connection, DBusPendingCall *pending, unsigned int flags, int timeout_milliseconds)
Queues incoming messages and sends outgoing messages for this connection, optionally blocking in the process.
Each call to _dbus_connection_do_iteration_unlocked() will call select() or poll() one time and then read or write data if possible.The purpose of this function is to be able to flush outgoing messages or queue up incoming messages without returning control to the application and causing reentrancy weirdness.The flags parameter allows you to specify whether to read incoming messages, write outgoing messages, or both, and whether to block if no immediate action is possible.The timeout_milliseconds parameter does nothing unless the iteration is blocking.If there are no outgoing messages and DBUS_ITERATION_DO_READING wasn't specified, then it's impossible to block, even if you specify DBUS_ITERATION_BLOCK; in that case the function returns immediately.If pending is not NULL then a check is made if the pending call is completed after the io path has been required. If the call has been completed nothing is done. This must be done since the _dbus_connection_acquire_io_path releases the connection lock for a while.Called with connection lock held. connection the connection. pending the pending call that should be checked or NULL flags iteration flags. timeout_milliseconds maximum blocking time, or -1 for no limit.
References _dbus_pending_call_get_completed_unlocked, _dbus_pending_call_get_reply_serial_unlocked, _dbus_transport_do_iteration, DBusConnection::n_outgoing, NULL, DBusConnection::transport.
Referenced by _dbus_connection_block_pending_call, _dbus_connection_close_possibly_shared, dbus_connection_flush, dbus_connection_send_with_reply_and_block.
DBusConnection* _dbus_connection_new_for_transport(DBusTransport *transport)
Creates a new connection for the given transport.
A transport represents a message stream that uses some concrete mechanism, such as UNIX domain sockets. May return NULL if insufficient memory exists to create the connection. transport the transport. the new connection, or NULL on failure.
References _dbus_atomic_inc, _dbus_cmutex_free_at_location, _dbus_cmutex_new_at_location, _dbus_condvar_free_at_location, _dbus_condvar_new_at_location, _dbus_counter_new, _dbus_counter_unref, _dbus_current_generation, _dbus_data_slot_list_init, _dbus_disable_sigpipe, _dbus_hash_table_new, _dbus_hash_table_unref, _dbus_list_alloc_link, _dbus_list_free_link, _dbus_object_tree_new, _dbus_object_tree_unref, _dbus_rmutex_free_at_location, _dbus_rmutex_new_at_location, _dbus_timeout_list_free, _dbus_timeout_list_new, _dbus_transport_ref, _dbus_transport_set_connection, _dbus_watch_list_free, _dbus_watch_list_new, DBusConnection::client_serial, CONNECTION_LOCK, CONNECTION_UNLOCK, DBUS_DISPATCH_COMPLETE, dbus_free, DBUS_HASH_INT, DBUS_INTERFACE_LOCAL, dbus_message_new_signal, dbus_message_unref, dbus_new0, DBUS_PATH_LOCAL, DBusConnection::disconnect_message_link, DBusConnection::disconnected_message_arrived, DBusConnection::disconnected_message_processed, DBusConnection::dispatch_cond, DBusConnection::dispatch_mutex, DBusConnection::exit_on_disconnect, FALSE, DBusConnection::filter_list, DBusConnection::io_path_cond, DBusConnection::io_path_mutex, DBusConnection::last_dispatch_status, DBusConnection::mutex, NULL, DBusConnection::objects, DBusConnection::outgoing_counter, DBusConnection::pending_replies, DBusConnection::refcount, DBusConnection::route_peer_messages, DBusConnection::shareable, DBusConnection::slot_list, DBusConnection::slot_mutex, DBusConnection::timeouts, DBusConnection::transport, DBusConnection::watches.
Referenced by _dbus_connection_handle_watch.
DBusConnection* _dbus_connection_ref_unlocked(DBusConnection *connection)
Increments the reference count of a DBusConnection.
Requires that the caller already holds the connection lock. connection the connection. the connection.
References _dbus_assert, _dbus_atomic_inc, _dbus_current_generation, NULL, DBusConnection::refcount.
Referenced by _dbus_connection_handle_watch, _dbus_connection_remove_pending_call, _dbus_connection_toggle_timeout_unlocked, _dbus_object_tree_unregister_and_unlock, _dbus_pending_call_new_unlocked, _dbus_transport_try_to_authenticate, dbus_connection_dispatch, dbus_connection_pop_message, dbus_connection_send, dbus_connection_unref.
void _dbus_connection_unref_unlocked(DBusConnection *connection)
Decrements the reference count of a DBusConnection.
Requires that the caller already holds the connection lock. connection the connection.
References _dbus_assert, _dbus_atomic_dec, DBusConnection::client_serial, NULL, DBusConnection::refcount.
Referenced by _dbus_connection_handle_watch, _dbus_connection_remove_pending_call, _dbus_connection_toggle_timeout_unlocked, _dbus_transport_try_to_authenticate, dbus_connection_pop_message.
static dbus_uint32_t _dbus_connection_get_next_client_serial(DBusConnection *connection)
dbus_bool_t _dbus_connection_handle_watch(DBusWatch *watch, unsigned int condition, void *data)
A callback for use with dbus_watch_new() to create a DBusWatch.
TodoThis is basically a hack - we could delete _dbus_transport_handle_watch() and the virtual handle_watch in DBusTransport if we got rid of it. The reason this is some work is threading, see the _dbus_connection_handle_watch() implementation. watch the watch. condition the current condition of the file descriptors being watched. data must be a pointer to a DBusConnection FALSE if the IO condition may not have been fully handled due to lack of memory
References _dbus_assert, _dbus_assert_not_reached, _dbus_connection_close_possibly_shared, _dbus_connection_new_for_transport, _dbus_connection_ref_unlocked, _dbus_connection_unref_unlocked, _dbus_hash_iter_get_value, _dbus_hash_iter_init, _dbus_hash_iter_next, _dbus_hash_table_get_n_entries, _dbus_hash_table_insert_string, _dbus_hash_table_lookup_string, _dbus_hash_table_new, _dbus_hash_table_remove_string, _dbus_hash_table_unref, _dbus_list_pop_first, _dbus_list_prepend, _dbus_list_remove, _DBUS_LOCK, _dbus_register_shutdown_func, _dbus_strdup, _dbus_transport_handle_watch, _dbus_transport_open, _dbus_transport_unref, _DBUS_UNLOCK, CONNECTION_LOCK, CONNECTION_UNLOCK, dbus_address_entries_free, dbus_address_entry_get_value, dbus_connection_pop_message, dbus_connection_ref, dbus_connection_unref, dbus_error_free, DBUS_ERROR_INIT, dbus_free, DBUS_HASH_STRING, dbus_message_unref, dbus_move_error, dbus_parse_address, FALSE, DBusConnection::have_connection_lock, NULL, DBusConnection::server_guid, DBusConnection::shareable, DBusConnection::transport, TRUE.
static void close_connection_on_shutdown(DBusConnection *connection)
static void shared_connections_shutdown(void *data)
static dbus_bool_t connection_lookup_shared(DBusAddressEntry *entry, DBusConnection **result)
static dbus_bool_t connection_record_shared_unlocked(DBusConnection *connection, const char *guid)
static void connection_forget_shared_unlocked(DBusConnection *connection)
static DBusConnection* connection_try_from_address_entry(DBusAddressEntry *entry, DBusError *error)
static DBusConnection* _dbus_connection_open_internal(const char *address, dbus_bool_t shared, DBusError *error)
void _dbus_connection_close_possibly_shared(DBusConnection *connection)
Closes a shared OR private connection, while dbus_connection_close() can only be used on private connections.
Should only be called by the dbus code that owns the connection - an owner must be known, the open/close state is like malloc/free, not like ref/unref. connection the connection
References _dbus_assert, _dbus_connection_do_iteration_unlocked, _dbus_counter_ref, _dbus_current_generation, _dbus_list_alloc_link, _dbus_list_free_link, _dbus_list_prepend_link, _dbus_message_add_counter_link, DBusPreallocatedSend::connection, CONNECTION_LOCK, DBusPreallocatedSend::counter_link, DBusList::data, dbus_free, dbus_message_get_destination, dbus_message_get_interface, dbus_message_get_member, dbus_message_get_path, dbus_message_get_serial, dbus_message_get_signature, dbus_message_get_type, dbus_message_lock, dbus_message_ref, dbus_message_set_serial, dbus_message_type_to_string, dbus_new, DBusConnection::n_outgoing, NULL, DBusConnection::outgoing_counter, DBusConnection::outgoing_messages, DBusPreallocatedSend::queue_link.
Referenced by _dbus_bus_notify_shared_connection_disconnected_unlocked, _dbus_connection_handle_watch.
static DBusPreallocatedSend* _dbus_connection_preallocate_send_unlocked(DBusConnection *connection)
static void _dbus_connection_send_preallocated_unlocked_no_update(DBusConnection *connection, DBusPreallocatedSend *preallocated, DBusMessage *message, dbus_uint32_t *client_serial)
static void _dbus_connection_send_preallocated_and_unlock(DBusConnection *connection, DBusPreallocatedSend *preallocated, DBusMessage *message, dbus_uint32_t *client_serial)
dbus_bool_t _dbus_connection_send_and_unlock(DBusConnection *connection, DBusMessage *message, dbus_uint32_t *client_serial)
Like dbus_connection_send(), but assumes the connection is already locked on function entry, and unlocks before returning.
connection the connection message the message to send client_serial return location for client serial of sent message FALSE on out-of-memory
References _dbus_assert, CONNECTION_UNLOCK, FALSE, NULL, TRUE.
Referenced by _dbus_object_tree_free_all_unlocked, dbus_connection_send.
void _dbus_connection_close_if_only_one_ref(DBusConnection *connection)
Used internally to handle the semantics of dbus_server_set_new_connection_function().
If the new connection function does not ref the connection, we want to close it.A bit of a hack, probably the new connection function should have returned a value for whether to close, or should have had to close the connection itself if it didn't want it.But, this works OK as long as the new connection function doesn't do anything crazy like keep the connection around without ref'ing it.We have to lock the connection across refcount check and close in case the new connection function spawns a thread that closes and unrefs. In that case, if the app thread closes and unrefs first, we'll harmlessly close again; if the app thread still has the ref, we'll close and then the app will close harmlessly. If the app unrefs without closing, the app is broken since if the app refs from the new connection function it is supposed to also close.If we didn't atomically check the refcount and close with the lock held though, we could screw this up. connection the connection
References _dbus_assert, _dbus_atomic_get, _dbus_connection_remove_timeout_unlocked, _dbus_hash_iter_get_value, _dbus_hash_iter_init, _dbus_hash_iter_next, _dbus_hash_iter_remove_entry, _dbus_hash_table_get_n_entries, _dbus_list_get_first_link, _dbus_list_get_next_link, _dbus_list_remove_link, _dbus_pending_call_complete, _dbus_pending_call_get_reply_serial_unlocked, _dbus_pending_call_get_timeout_unlocked, _dbus_pending_call_is_timeout_added_unlocked, _dbus_pending_call_queue_timeout_error_unlocked, _dbus_pending_call_ref_unlocked, _dbus_pending_call_set_reply_unlocked, _dbus_pending_call_set_timeout_added_unlocked, _dbus_pending_call_unref_and_unlock, _dbus_sleep_milliseconds, CONNECTION_LOCK, CONNECTION_UNLOCK, DBusList::data, dbus_message_get_reply_serial, dbus_message_iter_append_basic, dbus_message_iter_init_append, dbus_message_new, dbus_message_set_error_name, dbus_message_set_no_reply, dbus_message_set_reply_serial, DBUS_MESSAGE_TYPE_ERROR, dbus_message_unref, dbus_pending_call_unref, DBUS_TYPE_STRING, FALSE, DBusConnection::incoming_messages, DBusConnection::n_incoming, NULL, DBusConnection::pending_replies, DBusMessageFilter::refcount, DBusConnection::refcount, TRUE.
static void _dbus_memory_pause_based_on_timeout(int timeout_milliseconds)
When a function that blocks has been called with a timeout, and we run out of memory, the time to wait for memory is based on the timeout.
If the caller was willing to block a long time we wait a relatively long time for memory, if they were only willing to block briefly then we retry for memory at a rapid rate. timeout_milliseconds the timeout requested for blocking
static DBusMessage* generate_local_error_message(dbus_uint32_t serial, char *error_name, char *error_msg)
static DBusMessage* check_for_reply_unlocked(DBusConnection *connection, dbus_uint32_t client_serial)
static void connection_timeout_and_complete_all_pending_calls_unlocked(DBusConnection *connection)
static void complete_pending_call_and_unlock(DBusConnection *connection, DBusPendingCall *pending, DBusMessage *message)
static dbus_bool_t check_for_reply_and_update_dispatch_unlocked(DBusConnection *connection, DBusPendingCall *pending)
void _dbus_connection_block_pending_call(DBusPendingCall *pending)
Blocks until a pending call times out or gets a reply.
Does not re-enter the main loop or run filter/path-registered callbacks. The reply to the message will not be seen by filter callbacks.Returns immediately if pending call already got a reply.Todocould use performance improvements (it keeps scanning the whole message queue for example) pending the pending call we block for a reply on
References _dbus_assert, _dbus_connection_do_iteration_unlocked, _dbus_get_monotonic_time, _dbus_pending_call_get_completed_unlocked, _dbus_pending_call_get_connection_and_lock, _dbus_pending_call_get_reply_serial_unlocked, _dbus_pending_call_get_timeout_unlocked, CONNECTION_LOCK, DBUS_DISPATCH_DATA_REMAINS, DBUS_DISPATCH_NEED_MEMORY, DBUS_ERROR_DISCONNECTED, dbus_pending_call_get_completed, dbus_pending_call_ref, dbus_pending_call_unref, dbus_timeout_get_interval, DBusConnection::disconnect_message_link, NULL.
Referenced by dbus_pending_call_block.
int _dbus_connection_get_pending_fds_count(DBusConnection *connection)
Return how many file descriptors are pending in the loader.
connection the connection
References _dbus_transport_get_pending_fds_count, DBusConnection::transport.
void _dbus_connection_set_pending_fds_function(DBusConnection *connection, DBusPendingFdsChangeFunction callback, void *data)
Register a function to be called whenever the number of pending file descriptors in the loader change.
connection the connection callback the callback
References _dbus_transport_set_pending_fds_function, DBusConnection::transport.