DBusObjectTree
typedef struct DBusObjectSubtree DBusObjectSubtree
Subnode of the object hierarchy.
static DBusObjectSubtree * _dbus_object_subtree_new(const char *name, const DBusObjectPathVTable *vtable, void *user_data)
static DBusObjectSubtree * _dbus_object_subtree_ref(DBusObjectSubtree *subtree)
static void _dbus_object_subtree_unref(DBusObjectSubtree *subtree)
DBusObjectTree* _dbus_object_tree_new(DBusConnection *connection)
Creates a new object tree, representing a mapping from paths to handler vtables.
connection the connection this tree belongs to the new tree or NULL if no memory
References connection, dbus_free, dbus_new0, DBusObjectSubtree::invoke_as_fallback, NULL, refcount, root, TRUE.
Referenced by _dbus_connection_new_for_transport, _dbus_decompose_path.
DBusObjectTree* _dbus_object_tree_ref(DBusObjectTree *tree)
Increment the reference count.
tree the object tree the object tree
References _dbus_assert, refcount.
Referenced by _dbus_decompose_path.
void _dbus_object_tree_unref(DBusObjectTree *tree)
Decrement the reference count.
tree the object tree
References _dbus_assert, _dbus_object_tree_free_all_unlocked, dbus_free, refcount.
Referenced by _dbus_connection_new_for_transport, _dbus_decompose_path, dbus_connection_ref.
static DBusObjectSubtree* find_subtree_recurse(DBusObjectSubtree *subtree, const char **path, dbus_bool_t create_if_not_found, int *index_in_parent, dbus_bool_t *exact_match)
static DBusObjectSubtree* find_subtree(DBusObjectTree *tree, const char **path, int *index_in_parent)
static DBusObjectSubtree* lookup_subtree(DBusObjectTree *tree, const char **path)
static DBusObjectSubtree* find_handler(DBusObjectTree *tree, const char **path, dbus_bool_t *exact_match)
static DBusObjectSubtree* ensure_subtree(DBusObjectTree *tree, const char **path)
static char * flatten_path(const char **path)
dbus_bool_t _dbus_object_tree_register(DBusObjectTree *tree, dbus_bool_t fallback, const char **path, const DBusObjectPathVTable *vtable, void *user_data, DBusError *error)
Registers a new subtree in the global object tree.
tree the global object tree fallback TRUE to handle messages to children of this path path NULL-terminated array of path elements giving path to subtree vtable the vtable used to traverse this subtree user_data user data to pass to methods in the vtable error address where an error can be returned FALSE if an error (DBUS_ERROR_NO_MEMORY or DBUS_ERROR_OBJECT_PATH_IN_USE) is reported
References _dbus_assert, DBUS_ERROR_OBJECT_PATH_IN_USE, dbus_free, dbus_set_error, FALSE, DBusObjectSubtree::invoke_as_fallback, DBusObjectSubtree::message_function, DBusObjectPathVTable::message_function, DBusObjectSubtree::n_subtrees, DBusObjectSubtree::name, NULL, DBusObjectSubtree::parent, DBusObjectSubtree::subtrees, TRUE, DBusObjectSubtree::unregister_function, DBusObjectPathVTable::unregister_function, DBusObjectSubtree::user_data.
Referenced by _dbus_decompose_path, dbus_connection_remove_filter.
static dbus_bool_t unregister_subtree(DBusObjectSubtree *subtree, DBusObjectPathUnregisterFunction *unregister_function_out, void **user_data_out)
Attempts to unregister the given subtree.
If the subtree is registered, stores its unregister function and user data for later use and returns TRUE. If subtree is not registered, simply returns FALSE. Does not free subtree or remove it from the object tree. subtree the subtree to unregister unregister_function_out stores subtree's unregister_function user_data_out stores subtree's user_data FALSE if the subtree was not registered, TRUE on success
static dbus_bool_t attempt_child_removal(DBusObjectSubtree *parent, int child_index)
Attempts to remove a child subtree from its parent.
If removal is successful, also frees the child. Returns TRUE on success, FALSE otherwise. A FALSE return value tells unregister_and_free_path_recurse to stop attempting to remove ancestors, i.e., that no ancestors of the specified child are eligible for removal. parent parent from which to remove child child_index parent->subtrees index of child to remove TRUE if removal and free succeed, FALSE otherwise
static dbus_bool_t unregister_and_free_path_recurse(DBusObjectSubtree *subtree, const char **path, dbus_bool_t *continue_removal_attempts, DBusObjectPathUnregisterFunction *unregister_function_out, void **user_data_out)
Searches the object tree for a registered subtree node at the given path.
If a registered node is found, it is removed from the tree and freed, and TRUE is returned. If a registered subtree node is not found at the given path, the tree is not modified and FALSE is returned.The found node's unregister_function and user_data are returned in the corresponding _out arguments. The caller should define these variables and pass their addresses as arguments.Likewise, the caller should define and set to TRUE a boolean variable, then pass its address as the continue_removal_attempts argument.Once a matching registered node is found, removed and freed, the recursive return path is traversed. Along the way, eligible ancestor nodes are removed and freed. An ancestor node is eligible for removal if and only if 1) it has no children, i.e., it has become childless and 2) it is not itself a registered handler.For example, suppose /A/B and /A/C are registered paths, and that these are the only paths in the tree. If B is removed and freed, C is still reachable through A, so A cannot be removed and freed. If C is subsequently removed and freed, then A becomes a childless node and it becomes eligible for removal, and will be removed and freed.Similarly, suppose /A is a registered path, and /A/B is also a registered path, and that these are the only paths in the tree. If B is removed and freed, then even though A has become childless, it can't be freed because it refers to a path that is still registered. subtree subtree from which to start the search, root for initial call path path to subtree (same as _dbus_object_tree_unregister_and_unlock) continue_removal_attempts pointer to a bool, TRUE for initial call unregister_function_out returns the found node's unregister_function user_data_out returns the found node's user_data TRUE if a registered node was found at path, FALSE otherwise
void _dbus_object_tree_unregister_and_unlock(DBusObjectTree *tree, const char **path)
Unregisters an object subtree that was registered with the same path.
tree the global object tree path path to the subtree (same as the one passed to _dbus_object_tree_register())
References _dbus_assert, _dbus_connection_ref_unlocked, _dbus_connection_unlock, _dbus_warn, connection, dbus_connection_unref, FALSE, DBusObjectSubtree::message_function, DBusObjectSubtree::n_subtrees, NULL, DBusObjectSubtree::parent, root, DBusObjectSubtree::subtrees, TRUE, DBusObjectSubtree::unregister_function, DBusObjectSubtree::user_data.
Referenced by _dbus_decompose_path, dbus_connection_unregister_object_path.
static void free_subtree_recurse(DBusConnection *connection, DBusObjectSubtree *subtree)
void _dbus_object_tree_free_all_unlocked(DBusObjectTree *tree)
Free all the handlers in the tree.
Lock on tree's connection must not be held. tree the object tree
References _dbus_assert, _dbus_connection_send_and_unlock, _dbus_connection_unlock, _dbus_strdup, _dbus_string_append, _dbus_string_append_printf, _dbus_string_free, _dbus_string_init, connection, dbus_free_string_array, DBUS_HANDLER_RESULT_HANDLED, DBUS_HANDLER_RESULT_NEED_MEMORY, DBUS_HANDLER_RESULT_NOT_YET_HANDLED, DBUS_INTERFACE_INTROSPECTABLE, DBUS_INTROSPECT_1_0_XML_DOCTYPE_DECL_NODE, dbus_message_is_method_call, dbus_message_iter_append_basic, dbus_message_iter_init_append, dbus_message_new_method_return, dbus_message_unref, dbus_new0, DBUS_TYPE_STRING, FALSE, DBusObjectSubtree::n_subtrees, DBusObjectSubtree::name, NULL, root, DBusObjectSubtree::subtrees, TRUE.
Referenced by _dbus_object_tree_unref, dbus_connection_ref.
static dbus_bool_t _dbus_object_tree_list_registered_unlocked(DBusObjectTree *tree, const char **parent_path, char ***child_entries)
static DBusHandlerResult handle_default_introspect_and_unlock(DBusObjectTree *tree, DBusMessage *message, const char **path)
DBusHandlerResult _dbus_object_tree_dispatch_and_unlock(DBusObjectTree *tree, DBusMessage *message, dbus_bool_t *found_object)
Tries to dispatch a message by directing it to handler for the object path listed in the message header, if any.
Messages are dispatched first to the registered handler that matches the largest number of path elements; that is, message to /foo/bar/baz would go to the handler for /foo/bar before the one for /foo.Todothread problems tree the global object tree message the message to dispatch found_object return location for the object whether message was handled successfully
References _dbus_connection_lock, _dbus_connection_unlock, _dbus_list_append, _dbus_list_get_first_link, _dbus_list_get_length, _dbus_list_get_next_link, _dbus_list_remove_link, connection, DBusList::data, dbus_free_string_array, DBUS_HANDLER_RESULT_NEED_MEMORY, DBUS_HANDLER_RESULT_NOT_YET_HANDLED, dbus_message_get_path_decomposed, FALSE, DBusObjectSubtree::invoke_as_fallback, DBusObjectSubtree::message_function, NULL, DBusObjectSubtree::parent, DBusObjectSubtree::user_data.
Referenced by _dbus_decompose_path, dbus_connection_dispatch.
void* _dbus_object_tree_get_user_data_unlocked(DBusObjectTree *tree, const char **path)
Looks up the data passed to _dbus_object_tree_register() for a handler at the given path.
tree the global object tree path NULL-terminated array of path elements giving path to subtree the object's user_data or NULL if none found
References _dbus_assert, _dbus_atomic_dec, _dbus_atomic_inc, dbus_free, dbus_malloc0, FALSE, DBusObjectSubtree::invoke_as_fallback, DBusObjectSubtree::max_subtrees, DBusObjectSubtree::message_function, DBusObjectPathVTable::message_function, DBusObjectSubtree::n_subtrees, DBusObjectSubtree::name, NULL, DBusObjectSubtree::parent, DBusObjectSubtree::refcount, DBusObjectSubtree::subtrees, DBusObjectSubtree::unregister_function, DBusObjectPathVTable::unregister_function, DBusObjectSubtree::user_data.
Referenced by _dbus_decompose_path, dbus_connection_get_object_path_data.
static DBusObjectSubtree* allocate_subtree_object(const char *name)
Allocates a subtree object.
name name to duplicate. newly-allocated subtree
dbus_bool_t _dbus_object_tree_list_registered_and_unlock(DBusObjectTree *tree, const char **parent_path, char ***child_entries)
Lists the registered fallback handlers and object path handlers at the given parent_path.
The returned array should be freed with dbus_free_string_array(). tree the object tree parent_path the path to list the child handlers of child_entries returns NULL-terminated array of children FALSE if no memory to allocate the child entries
References _dbus_connection_unlock, connection.
Referenced by dbus_connection_list_registered.
dbus_bool_t _dbus_decompose_path(const char *data, int len, char ***path, int *path_len)
Decompose an object path.
A path of just "/" is represented as an empty vector of strings. The path need not be nul terminated. data the path data len the length of the path string path address to store new object path path_len length of stored path
References _dbus_assert, _dbus_assert_not_reached, _dbus_decompose_path, _dbus_memdup, _DBUS_N_ELEMENTS, _dbus_object_tree_dispatch_and_unlock, _dbus_object_tree_get_user_data_unlocked, _dbus_object_tree_new, _dbus_object_tree_ref, _dbus_object_tree_register, _dbus_object_tree_unref, _dbus_object_tree_unregister_and_unlock, _dbus_string_append, _dbus_string_append_byte, _dbus_string_free, _dbus_string_init, _dbus_string_steal_data, _dbus_warn, dbus_free, dbus_free_string_array, DBUS_HANDLER_RESULT_NEED_MEMORY, DBUS_HANDLER_RESULT_NOT_YET_HANDLED, dbus_message_new_method_call, dbus_message_unref, dbus_new0, FALSE, DBusObjectSubtree::n_subtrees, DBusObjectSubtree::name, NULL, root, DBusObjectSubtree::subtrees, TRUE.
Referenced by _dbus_decompose_path, dbus_connection_get_object_path_data, dbus_connection_list_registered, dbus_connection_remove_filter, dbus_connection_unregister_object_path, dbus_message_get_path_decomposed.
VERBOSE_FIND
Set to 1 to get a bunch of debug spew about finding the subtree nodes.
VERBOSE_DECOMPOSE
Set to 1 to get a bunch of spew about disassembling the path string.